import { Logo } from './Logo';
import { 
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from './ui/dialog';
import { Button } from './ui/button';

export function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-gray-50 border-t mt-auto">
      <div className="container mx-auto px-4 py-12">
        <div className="grid md:grid-cols-4 gap-8 mb-8">
          {/* Brand */}
          <div>
            <Logo className="mb-4" />
            <p className="text-sm text-muted-foreground">
              Empowering retirees with intelligent tools and guidance for their retirement village journey.
            </p>
          </div>

          {/* Quick Links */}
          <div>
            <h4 className="mb-4">Quick Links</h4>
            <ul className="space-y-2 text-sm">
              <li>
                <a href="#" className="text-muted-foreground hover:text-foreground transition-colors">
                  Village Directory
                </a>
              </li>
              <li>
                <a href="#list-village" className="text-muted-foreground hover:text-foreground transition-colors">
                  List Your Village
                </a>
              </li>
              <li>
                <a href="#" className="text-muted-foreground hover:text-foreground transition-colors">
                  Resources
                </a>
              </li>
              <li>
                <a href="#" className="text-muted-foreground hover:text-foreground transition-colors">
                  Pricing
                </a>
              </li>
            </ul>
          </div>

          {/* Legal */}
          <div>
            <h4 className="mb-4">Legal</h4>
            <ul className="space-y-2 text-sm">
              <li>
                <Dialog>
                  <DialogTrigger asChild>
                    <button className="text-muted-foreground hover:text-foreground transition-colors text-left">
                      Terms of Service
                    </button>
                  </DialogTrigger>
                  <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
                    <DialogHeader>
                      <DialogTitle>Terms of Service</DialogTitle>
                      <DialogDescription>
                        Last updated: January 28, 2026
                      </DialogDescription>
                    </DialogHeader>
                    <div className="space-y-4 text-sm">
                      <section>
                        <h3 className="mb-2">1. Acceptance of Terms</h3>
                        <p className="text-muted-foreground">
                          By accessing and using RetirePath, you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to these terms, please do not use our services.
                        </p>
                      </section>
                      
                      <section>
                        <h3 className="mb-2">2. Service Description</h3>
                        <p className="text-muted-foreground">
                          RetirePath provides information, tools, and resources to assist individuals researching retirement villages in Australia. Our services include village directories, contract analysis tools, home valuation estimates, and educational resources.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">3. No Professional Advice</h3>
                        <p className="text-muted-foreground mb-2">
                          RetirePath does not provide legal, financial, tax, or professional advice. All information, analysis, and estimates provided through our platform are for general informational purposes only. You should not rely on this information as a substitute for professional advice.
                        </p>
                        <p className="text-muted-foreground">
                          We strongly recommend consulting with qualified professionals including solicitors, financial advisors, and real estate agents before making any retirement village or property decisions.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">4. Information Accuracy</h3>
                        <p className="text-muted-foreground">
                          While we strive to maintain accurate and up-to-date information, RetirePath makes no warranties or representations about the accuracy, completeness, or timeliness of information displayed in our village directory or generated by our tools. Retirement village details, pricing, and availability are subject to change without notice.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">5. AI-Generated Content</h3>
                        <p className="text-muted-foreground">
                          Our platform uses artificial intelligence to analyze contracts, estimate home values, and provide recommendations. AI-generated analysis may contain errors or omissions. Users are solely responsible for verifying all information and seeking professional advice before making decisions.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">6. Limitation of Liability</h3>
                        <p className="text-muted-foreground">
                          To the fullest extent permitted by law, RetirePath, its officers, directors, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of our services.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">7. User Responsibilities</h3>
                        <p className="text-muted-foreground">
                          Users are responsible for conducting their own due diligence, verifying all information with retirement villages directly, and making informed decisions. You agree not to hold RetirePath responsible for any decisions you make based on information provided through our platform.
                        </p>
                      </section>

                      <section className="mb-6">
                        <h3 className="mb-2">8. Membership and Payments</h3>
                        <p className="text-muted-foreground">
                          Paid membership plans grant access to premium features for a specified period (1, 3, or 6 months). Subscriptions are one-time payments and do not automatically renew. Your subscription will expire at the end of the selected period unless you purchase a new subscription. Refunds are provided in accordance with our refund policy. We reserve the right to modify pricing and features with reasonable notice.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">9. Changes to Terms</h3>
                        <p className="text-muted-foreground">
                          We reserve the right to modify these terms at any time. Continued use of RetirePath after changes constitutes acceptance of the modified terms.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">10. Governing Law</h3>
                        <p className="text-muted-foreground">
                          These terms are governed by the laws of Australia. Any disputes shall be subject to the exclusive jurisdiction of the courts of Australia.
                        </p>
                      </section>
                    </div>
                  </DialogContent>
                </Dialog>
              </li>
              <li>
                <Dialog>
                  <DialogTrigger asChild>
                    <button className="text-muted-foreground hover:text-foreground transition-colors text-left">
                      Privacy Policy
                    </button>
                  </DialogTrigger>
                  <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
                    <DialogHeader>
                      <DialogTitle>Privacy Policy</DialogTitle>
                      <DialogDescription>
                        Last updated: January 28, 2026
                      </DialogDescription>
                    </DialogHeader>
                    <div className="space-y-4 text-sm">
                      <section>
                        <h3 className="mb-2">1. Information We Collect</h3>
                        <p className="text-muted-foreground mb-2">
                          We collect information you provide directly to us, including:
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li>Name, email address, and contact information</li>
                          <li>Payment and billing information</li>
                          <li>Property and personal details entered into our tools</li>
                          <li>Usage data and preferences</li>
                        </ul>
                      </section>

                      <section>
                        <h3 className="mb-2">2. How We Use Your Information</h3>
                        <p className="text-muted-foreground mb-2">
                          We use your information to:
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li>Provide and improve our services</li>
                          <li>Process payments and manage subscriptions</li>
                          <li>Send important updates and notifications</li>
                          <li>Generate personalized recommendations and analysis</li>
                          <li>Comply with legal obligations</li>
                        </ul>
                      </section>

                      <section>
                        <h3 className="mb-2">3. Data Security</h3>
                        <p className="text-muted-foreground">
                          We implement appropriate technical and organizational measures to protect your personal information. However, no method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">4. Information Sharing</h3>
                        <p className="text-muted-foreground">
                          We do not sell your personal information. We may share information with service providers who assist in operating our platform, payment processors, and as required by law.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">5. Your Rights</h3>
                        <p className="text-muted-foreground">
                          You have the right to access, correct, or delete your personal information. You may also object to processing or request data portability. Contact us to exercise these rights.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">6. Cookies</h3>
                        <p className="text-muted-foreground">
                          We use cookies and similar technologies to enhance user experience, analyze usage patterns, and remember your preferences.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">7. Contact Us</h3>
                        <p className="text-muted-foreground">
                          For privacy-related questions or requests, please contact us at privacy@retirepath.com.au
                        </p>
                      </section>
                    </div>
                  </DialogContent>
                </Dialog>
              </li>
              <li>
                <Dialog>
                  <DialogTrigger asChild>
                    <button className="text-muted-foreground hover:text-foreground transition-colors text-left">
                      Disclaimer
                    </button>
                  </DialogTrigger>
                  <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
                    <DialogHeader>
                      <DialogTitle>General Disclaimer</DialogTitle>
                      <DialogDescription>
                        Important information about using RetirePath
                      </DialogDescription>
                    </DialogHeader>
                    <div className="space-y-4 text-sm">
                      <section>
                        <h3 className="mb-2">No Professional Advice</h3>
                        <p className="text-muted-foreground">
                          RetirePath provides general information and tools only. We do not provide legal, financial, tax, real estate, or other professional advice. All information, analysis, recommendations, and estimates are for informational purposes only and should not be relied upon as professional advice.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Seek Professional Guidance</h3>
                        <p className="text-muted-foreground mb-2">
                          We strongly recommend consulting qualified professionals before making any decisions, including:
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li>Solicitors experienced in retirement village law for contract review</li>
                          <li>Licensed financial advisors for financial planning and advice</li>
                          <li>Real estate agents for property valuations and sales advice</li>
                          <li>Tax professionals for tax implications</li>
                          <li>Healthcare providers for care needs assessment</li>
                        </ul>
                      </section>

                      <section>
                        <h3 className="mb-2">AI-Generated Content</h3>
                        <p className="text-muted-foreground">
                          Our platform uses artificial intelligence to analyze data and generate recommendations. AI technology, while powerful, can make errors or produce incomplete analysis. All AI-generated content should be verified independently and not relied upon as the sole basis for important decisions.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Information Accuracy</h3>
                        <p className="text-muted-foreground">
                          While we make reasonable efforts to ensure information accuracy, we do not guarantee the completeness, accuracy, or timeliness of any information on our platform. Retirement village details, pricing, fees, and availability change frequently. Always verify current information directly with villages and operators.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Third-Party Information</h3>
                        <p className="text-muted-foreground">
                          Our village directory includes information provided by retirement village operators and third-party sources. RetirePath is not responsible for the accuracy of operator-submitted information. We recommend conducting thorough independent research and inspections.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Limitation of Liability</h3>
                        <p className="text-muted-foreground">
                          To the maximum extent permitted by law, RetirePath accepts no liability for any loss, damage, or adverse outcome resulting from use of our platform, reliance on information provided, or decisions made based on our tools and resources. Users assume all risks associated with their use of RetirePath.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Your Responsibility</h3>
                        <p className="text-muted-foreground">
                          You are solely responsible for conducting thorough due diligence, verifying all information, seeking professional advice, and making informed decisions that are appropriate for your individual circumstances.
                        </p>
                      </section>
                    </div>
                  </DialogContent>
                </Dialog>
              </li>
              
              {/* NEW: Refund Policy */}
              <li>
                <Dialog>
                  <DialogTrigger asChild>
                    <button className="text-muted-foreground hover:text-foreground transition-colors text-left">
                      Refund Policy
                    </button>
                  </DialogTrigger>
                  <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
                    <DialogHeader>
                      <DialogTitle>Refund Policy</DialogTitle>
                      <DialogDescription>
                        Last updated: January 28, 2026
                      </DialogDescription>
                    </DialogHeader>
                    <div className="space-y-4 text-sm">
                      <section>
                        <h3 className="mb-2">7-Day Money-Back Guarantee</h3>
                        <p className="text-muted-foreground mb-2">
                          We stand behind the quality of our services. If you're not satisfied with RetirePath within 7 days of your purchase, we'll provide a full refund—no questions asked.
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li>Full refund available within 7 days of purchase date</li>
                          <li>No questions asked for refunds within the cooling-off period</li>
                          <li>Refunds are processed to your original payment method</li>
                          <li>Processing time: 5-10 business days after approval</li>
                        </ul>
                      </section>

                      <section>
                        <h3 className="mb-2">After the 7-Day Period</h3>
                        <p className="text-muted-foreground mb-2">
                          After the 7-day cooling-off period, refunds are generally not available. However:
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li>Your subscription is a one-time payment (no recurring charges)</li>
                          <li>Your access continues until your subscription expiry date</li>
                          <li>You will not be charged again unless you purchase a new subscription</li>
                        </ul>
                        <p className="text-muted-foreground mt-2">
                          If you experience technical issues or service problems after the 7-day period, please contact us. We'll work with you to resolve the issue and may offer a partial refund or subscription extension at our discretion.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">How to Request a Refund</h3>
                        <p className="text-muted-foreground mb-2">
                          To request a refund within the 7-day cooling-off period:
                        </p>
                        <ol className="list-decimal pl-5 text-muted-foreground space-y-1">
                          <li>Email us at: <strong>support@retirepath.com.au</strong></li>
                          <li>Subject line: "Refund Request"</li>
                          <li>Include: Your registered email address and purchase date</li>
                          <li>Reason for refund (optional but helpful for improving our service)</li>
                        </ol>
                        <p className="text-muted-foreground mt-2">
                          We'll process your refund request within 2 business days and notify you via email.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Australian Consumer Law Rights</h3>
                        <p className="text-muted-foreground">
                          This refund policy is in addition to your rights under Australian Consumer Law. If our services have a major problem or don't match the description we provided, you have additional consumer guarantee rights that cannot be excluded. These rights include the right to a refund, replacement, or compensation for any reasonably foreseeable loss or damage. Contact us if you believe you have a consumer guarantee claim.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Exceptional Circumstances</h3>
                        <p className="text-muted-foreground">
                          In exceptional circumstances (such as serious illness, bereavement, or unforeseen financial hardship), we may consider refund requests outside the 7-day period. Please contact us to discuss your situation. While we cannot guarantee a refund, we'll consider each case individually and work with you where possible.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Processing Time</h3>
                        <p className="text-muted-foreground">
                          Once your refund is approved, please allow 5-10 business days for the funds to appear in your account. Processing times may vary depending on your financial institution.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Questions</h3>
                        <p className="text-muted-foreground">
                          For questions about our refund policy or to request a refund, please contact: <strong>support@retirepath.com.au</strong>
                        </p>
                      </section>
                    </div>
                  </DialogContent>
                </Dialog>
              </li>

              {/* NEW: Cookie Policy */}
              <li>
                <Dialog>
                  <DialogTrigger asChild>
                    <button className="text-muted-foreground hover:text-foreground transition-colors text-left">
                      Cookie Policy
                    </button>
                  </DialogTrigger>
                  <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
                    <DialogHeader>
                      <DialogTitle>Cookie Policy</DialogTitle>
                      <DialogDescription>
                        Last updated: January 28, 2026
                      </DialogDescription>
                    </DialogHeader>
                    <div className="space-y-4 text-sm">
                      <section>
                        <h3 className="mb-2">What Are Cookies?</h3>
                        <p className="text-muted-foreground">
                          Cookies are small text files that are placed on your device (computer, smartphone, or tablet) when you visit websites. They help websites remember your preferences, improve your experience, and provide important functionality.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Cookies We Use</h3>
                        <p className="text-muted-foreground mb-2">
                          RetirePath uses the following types of cookies:
                        </p>

                        <div className="space-y-3">
                          <div>
                            <h4 className="font-semibold text-foreground">Essential Cookies (Required)</h4>
                            <p className="text-muted-foreground">
                              These cookies are necessary for the website to function properly. They enable core functionality such as:
                            </p>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1 mt-1">
                              <li>User authentication and login sessions</li>
                              <li>Security and fraud prevention</li>
                              <li>Remembering your membership status</li>
                              <li>Shopping cart functionality</li>
                            </ul>
                            <p className="text-muted-foreground mt-1 italic">
                              Essential cookies cannot be disabled as they are required for the platform to work.
                            </p>
                          </div>

                          <div>
                            <h4 className="font-semibold text-foreground">Preference Cookies</h4>
                            <p className="text-muted-foreground">
                              These cookies remember your settings and preferences, such as:
                            </p>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1 mt-1">
                              <li>Your saved village searches and filters</li>
                              <li>Display preferences and layout choices</li>
                              <li>Language and regional settings</li>
                            </ul>
                          </div>

                          <div>
                            <h4 className="font-semibold text-foreground">Analytics Cookies</h4>
                            <p className="text-muted-foreground">
                              These cookies help us understand how visitors use our website, allowing us to improve the user experience. They collect information such as:
                            </p>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1 mt-1">
                              <li>Pages visited and time spent on pages</li>
                              <li>How you arrived at our website</li>
                              <li>Which features and tools you use most</li>
                              <li>Error messages and technical issues</li>
                            </ul>
                            <p className="text-muted-foreground mt-1 italic">
                              Analytics data is anonymized and cannot be used to identify you personally.
                            </p>
                          </div>
                        </div>
                      </section>

                      <section>
                        <h3 className="mb-2">Third-Party Cookies</h3>
                        <p className="text-muted-foreground mb-2">
                          Some cookies are set by third-party services we use:
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li><strong>Stripe:</strong> Payment processing and fraud prevention (essential)</li>
                          <li><strong>Supabase:</strong> User authentication and secure data storage (essential)</li>
                        </ul>
                        <p className="text-muted-foreground mt-2">
                          These third parties have their own privacy policies and cookie policies. We recommend reviewing their policies for more information.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Managing Cookies</h3>
                        <p className="text-muted-foreground mb-2">
                          You can control and manage cookies through your browser settings:
                        </p>

                        <div className="space-y-2">
                          <div>
                            <h4 className="font-semibold text-foreground">Browser Controls</h4>
                            <p className="text-muted-foreground">
                              Most browsers allow you to:
                            </p>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                              <li>View and delete cookies</li>
                              <li>Block third-party cookies</li>
                              <li>Block cookies from specific websites</li>
                              <li>Block all cookies</li>
                              <li>Delete all cookies when closing the browser</li>
                            </ul>
                          </div>

                          <div className="bg-amber-50 border border-amber-200 rounded p-3 mt-2">
                            <p className="text-amber-900 font-semibold">⚠️ Important Notice</p>
                            <p className="text-amber-800 text-sm mt-1">
                              Disabling essential cookies will prevent you from logging in and using core features of RetirePath. You will still be able to browse public areas of the website.
                            </p>
                          </div>
                        </div>
                      </section>

                      <section>
                        <h3 className="mb-2">How to Disable Cookies in Popular Browsers</h3>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li><strong>Chrome:</strong> Settings → Privacy and security → Cookies and other site data</li>
                          <li><strong>Firefox:</strong> Settings → Privacy & Security → Cookies and Site Data</li>
                          <li><strong>Safari:</strong> Preferences → Privacy → Manage Website Data</li>
                          <li><strong>Edge:</strong> Settings → Cookies and site permissions → Cookies and site data</li>
                        </ul>
                        <p className="text-muted-foreground mt-2">
                          For more detailed instructions, search for "disable cookies" along with your browser name and version.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Changes to This Cookie Policy</h3>
                        <p className="text-muted-foreground">
                          We may update this Cookie Policy from time to time to reflect changes in technology, legislation, or our business practices. We encourage you to review this policy periodically.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Questions</h3>
                        <p className="text-muted-foreground">
                          For questions about our use of cookies, please contact: <strong>privacy@retirepath.com.au</strong>
                        </p>
                      </section>
                    </div>
                  </DialogContent>
                </Dialog>
              </li>

              {/* NEW: Acceptable Use Policy */}
              <li>
                <Dialog>
                  <DialogTrigger asChild>
                    <button className="text-muted-foreground hover:text-foreground transition-colors text-left">
                      Acceptable Use
                    </button>
                  </DialogTrigger>
                  <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
                    <DialogHeader>
                      <DialogTitle>Acceptable Use Policy</DialogTitle>
                      <DialogDescription>
                        Guidelines for using RetirePath responsibly
                      </DialogDescription>
                    </DialogHeader>
                    <div className="space-y-4 text-sm">
                      <section>
                        <h3 className="mb-2">Purpose</h3>
                        <p className="text-muted-foreground">
                          This Acceptable Use Policy outlines the rules and guidelines for using RetirePath. By accessing our platform, you agree to use it responsibly and in accordance with these guidelines. This policy protects all users and ensures RetirePath remains a trusted resource for retirees.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Prohibited Activities</h3>
                        <p className="text-muted-foreground mb-2">
                          You must not use RetirePath to:
                        </p>

                        <div className="space-y-3">
                          <div>
                            <h4 className="font-semibold text-foreground">Account Misuse</h4>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                              <li>Provide false, inaccurate, or misleading information during registration</li>
                              <li>Share your account credentials with others</li>
                              <li>Create multiple accounts to abuse free trials or promotions</li>
                              <li>Use another person's account without permission</li>
                              <li>Impersonate any person or entity</li>
                            </ul>
                          </div>

                          <div>
                            <h4 className="font-semibold text-foreground">Security & Technical Abuse</h4>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                              <li>Attempt to breach or circumvent security measures</li>
                              <li>Use automated tools, bots, or scrapers to extract data</li>
                              <li>Introduce viruses, malware, or malicious code</li>
                              <li>Attempt unauthorized access to our systems or databases</li>
                              <li>Interfere with or disrupt the platform's operation</li>
                              <li>Reverse engineer or decompile any part of the platform</li>
                            </ul>
                          </div>

                          <div>
                            <h4 className="font-semibold text-foreground">Inappropriate Content</h4>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                              <li>Post defamatory, abusive, or harassing content</li>
                              <li>Submit false or misleading reviews about retirement villages</li>
                              <li>Include offensive, discriminatory, or hateful language</li>
                              <li>Share sexually explicit or inappropriate content</li>
                              <li>Post spam, advertising, or promotional content</li>
                            </ul>
                          </div>

                          <div>
                            <h4 className="font-semibold text-foreground">Illegal Activities</h4>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                              <li>Use the platform for any unlawful purpose</li>
                              <li>Violate any local, state, national, or international law</li>
                              <li>Engage in fraud or financial crimes</li>
                              <li>Infringe on intellectual property rights</li>
                              <li>Violate privacy laws or misuse personal information</li>
                            </ul>
                          </div>

                          <div>
                            <h4 className="font-semibold text-foreground">Commercial Misuse</h4>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                              <li>Resell or redistribute access to RetirePath</li>
                              <li>Use data from RetirePath for commercial purposes without permission</li>
                              <li>Systematically download or copy content for external use</li>
                              <li>Create derivative products using our data or tools</li>
                            </ul>
                          </div>
                        </div>
                      </section>

                      <section>
                        <h3 className="mb-2">Village Reviews & Feedback Guidelines</h3>
                        <p className="text-muted-foreground mb-2">
                          When submitting reviews or feedback about retirement villages:
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li>Reviews must be based on genuine personal experience</li>
                          <li>Be honest, fair, and constructive in your feedback</li>
                          <li>Focus on facts rather than unverified claims</li>
                          <li>Do not include personal information about staff or residents</li>
                          <li>Avoid defamatory statements or unsubstantiated allegations</li>
                          <li>Do not submit fake reviews or reviews for compensation</li>
                        </ul>
                        <p className="text-muted-foreground mt-2">
                          We reserve the right to moderate, edit, or remove reviews that violate these guidelines.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Data Usage & Privacy</h3>
                        <p className="text-muted-foreground">
                          You agree to respect the privacy of other users and retirement village operators. Do not collect, store, or misuse personal information accessed through RetirePath. All data collected by our platform is governed by our Privacy Policy.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Consequences of Violations</h3>
                        <p className="text-muted-foreground mb-2">
                          Violations of this Acceptable Use Policy may result in:
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li><strong>Warning:</strong> First-time minor violations may receive a warning</li>
                          <li><strong>Temporary Suspension:</strong> Your account may be suspended for serious or repeated violations</li>
                          <li><strong>Permanent Ban:</strong> Severe violations will result in permanent account termination without refund</li>
                          <li><strong>Legal Action:</strong> We reserve the right to pursue legal action for serious violations, including reporting illegal activity to authorities</li>
                        </ul>
                        <p className="text-muted-foreground mt-2">
                          We may terminate accounts at our discretion for violations of this policy.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Reporting Violations</h3>
                        <p className="text-muted-foreground">
                          If you become aware of any violations of this Acceptable Use Policy, please report them to us immediately at: <strong>support@retirepath.com.au</strong>
                        </p>
                        <p className="text-muted-foreground mt-2">
                          Include as much detail as possible, such as:
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li>Description of the violation</li>
                          <li>Date and time (if applicable)</li>
                          <li>Screenshots or evidence (if available)</li>
                          <li>Your contact information for follow-up</li>
                        </ul>
                      </section>

                      <section>
                        <h3 className="mb-2">Changes to This Policy</h3>
                        <p className="text-muted-foreground">
                          We may update this Acceptable Use Policy from time to time. Continued use of RetirePath after changes constitutes acceptance of the updated policy. We encourage you to review this policy periodically.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Questions</h3>
                        <p className="text-muted-foreground">
                          For questions about this policy or to report violations, please contact: <strong>support@retirepath.com.au</strong>
                        </p>
                      </section>
                    </div>
                  </DialogContent>
                </Dialog>
              </li>

              {/* NEW: Accessibility Statement */}
              <li>
                <Dialog>
                  <DialogTrigger asChild>
                    <button className="text-muted-foreground hover:text-foreground transition-colors text-left">
                      Accessibility
                    </button>
                  </DialogTrigger>
                  <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
                    <DialogHeader>
                      <DialogTitle>Accessibility Statement</DialogTitle>
                      <DialogDescription>
                        Our commitment to digital accessibility
                      </DialogDescription>
                    </DialogHeader>
                    <div className="space-y-4 text-sm">
                      <section>
                        <h3 className="mb-2">Our Commitment</h3>
                        <p className="text-muted-foreground">
                          RetirePath is committed to ensuring digital accessibility for people with disabilities. We continuously work to improve the accessibility and usability of our platform and ensure it provides a positive experience for all users, regardless of ability or technology.
                        </p>
                        <p className="text-muted-foreground mt-2">
                          We believe that everyone, including retirees with disabilities, should have equal access to information and tools for making informed retirement village decisions.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Accessibility Standards</h3>
                        <p className="text-muted-foreground">
                          RetirePath aims to conform to the Web Content Accessibility Guidelines (WCAG) 2.1, Level AA standards. These guidelines explain how to make web content more accessible for people with disabilities and improve the user experience for everyone.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Current Accessibility Features</h3>
                        <p className="text-muted-foreground mb-2">
                          Our platform includes the following accessibility features:
                        </p>

                        <div className="space-y-2">
                          <div>
                            <h4 className="font-semibold text-foreground">Keyboard Navigation</h4>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                              <li>Full keyboard navigation support for all interactive elements</li>
                              <li>Logical tab order throughout the platform</li>
                              <li>Skip navigation links to bypass repetitive content</li>
                              <li>Visible focus indicators on all focusable elements</li>
                            </ul>
                          </div>

                          <div>
                            <h4 className="font-semibold text-foreground">Screen Reader Compatibility</h4>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                              <li>Semantic HTML markup for proper content structure</li>
                              <li>ARIA labels and descriptions for interactive elements</li>
                              <li>Alternative text descriptions for images and icons</li>
                              <li>Descriptive link text and button labels</li>
                            </ul>
                          </div>

                          <div>
                            <h4 className="font-semibold text-foreground">Visual Design</h4>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                              <li>Sufficient color contrast ratios for text and backgrounds</li>
                              <li>Clear visual hierarchy and consistent navigation</li>
                              <li>Responsive design that adapts to different screen sizes</li>
                              <li>Text resizing support up to 200% without loss of functionality</li>
                              <li>No reliance on color alone to convey information</li>
                            </ul>
                          </div>

                          <div>
                            <h4 className="font-semibold text-foreground">Content & Language</h4>
                            <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                              <li>Clear, simple language appropriate for our audience</li>
                              <li>Descriptive headings and labels</li>
                              <li>Meaningful error messages and instructions</li>
                              <li>Consistent navigation and interface patterns</li>
                            </ul>
                          </div>
                        </div>
                      </section>

                      <section>
                        <h3 className="mb-2">Known Limitations</h3>
                        <p className="text-muted-foreground mb-2">
                          Despite our best efforts, some areas of RetirePath may not yet be fully accessible:
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li>Some PDF documents may not be fully accessible to screen readers</li>
                          <li>Third-party content (such as embedded videos or maps) may have accessibility limitations</li>
                          <li>Some complex data visualizations may require alternative formats</li>
                        </ul>
                        <p className="text-muted-foreground mt-2">
                          We are actively working to address these limitations and improve accessibility across the entire platform.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Assistive Technologies</h3>
                        <p className="text-muted-foreground mb-2">
                          RetirePath has been tested with the following assistive technologies:
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li>Screen readers (NVDA, JAWS, VoiceOver)</li>
                          <li>Keyboard-only navigation</li>
                          <li>Voice recognition software</li>
                          <li>Screen magnification software</li>
                        </ul>
                        <p className="text-muted-foreground mt-2">
                          We continually test with various assistive technologies to ensure compatibility.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Accessibility Feedback</h3>
                        <p className="text-muted-foreground mb-2">
                          We welcome your feedback on the accessibility of RetirePath. If you encounter accessibility barriers, please let us know:
                        </p>
                        <ul className="list-disc pl-5 text-muted-foreground space-y-1">
                          <li><strong>Email:</strong> accessibility@retirepath.com.au</li>
                          <li><strong>Subject:</strong> "Accessibility Feedback"</li>
                          <li><strong>Include:</strong> Page URL, description of the issue, assistive technology used (if applicable)</li>
                        </ul>
                        <p className="text-muted-foreground mt-2">
                          We aim to respond to accessibility feedback within 5 business days and work with you to provide an accessible alternative if needed.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Alternative Formats</h3>
                        <p className="text-muted-foreground">
                          If you require information from RetirePath in an alternative format (such as large print, audio, or braille), please contact us at <strong>accessibility@retirepath.com.au</strong>. We'll work with you to provide the information in a format that meets your needs.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Third-Party Content</h3>
                        <p className="text-muted-foreground">
                          RetirePath may contain links to external websites and third-party content that we do not control. We cannot guarantee the accessibility of external content, but we strive to select partners who share our commitment to accessibility.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Ongoing Improvements</h3>
                        <p className="text-muted-foreground">
                          Accessibility is an ongoing effort. We regularly review our platform and implement improvements to enhance accessibility. Our development team receives accessibility training, and we conduct regular accessibility audits to identify and address issues.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Compliance Status</h3>
                        <p className="text-muted-foreground">
                          We are committed to meeting WCAG 2.1 Level AA standards and complying with the Disability Discrimination Act 1992 (Australia). While we strive for full compliance, we acknowledge that achieving complete accessibility is an ongoing process.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Assessment & Testing</h3>
                        <p className="text-muted-foreground">
                          This accessibility statement was last reviewed on January 28, 2026. We conduct regular accessibility assessments using a combination of automated testing tools and manual testing with assistive technologies.
                        </p>
                      </section>

                      <section>
                        <h3 className="mb-2">Contact Us</h3>
                        <p className="text-muted-foreground">
                          For questions, feedback, or concerns about accessibility, please contact:
                        </p>
                        <p className="text-muted-foreground mt-2">
                          <strong>Email:</strong> accessibility@retirepath.com.au<br />
                          <strong>Alternative:</strong> support@retirepath.com.au
                        </p>
                      </section>

                      <section>
                        <p className="text-muted-foreground italic">
                          Last updated: January 28, 2026
                        </p>
                      </section>
                    </div>
                  </DialogContent>
                </Dialog>
              </li>
            </ul>
          </div>

          {/* Support */}
          <div>
            <h4 className="mb-4">Support</h4>
            <ul className="space-y-2 text-sm">
              <li>
                <a href="mailto:support@retirepath.com.au" className="text-muted-foreground hover:text-foreground transition-colors">
                  Contact Support
                </a>
              </li>
              <li>
                <a href="#" className="text-muted-foreground hover:text-foreground transition-colors">
                  Help Center
                </a>
              </li>
            </ul>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="pt-8 border-t text-center text-sm text-muted-foreground">
          <p>© {currentYear} RetirePath. All rights reserved.</p>
          <p className="mt-2">
            RetirePath is an independent information platform. We are not affiliated with any retirement village operator or real estate agency.
          </p>
        </div>
      </div>
    </footer>
  );
}