import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from './dialog';
import { Button } from './button';
import { Checkbox } from './checkbox';
import { Label } from './label';
import { AlertCircle } from 'lucide-react';

interface LegalAcknowledgmentDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onAccept: () => void;
  title: string;
  type: 'contract' | 'valuation' | 'matcher';
}

export function LegalAcknowledgmentDialog({
  open,
  onOpenChange,
  onAccept,
  title,
  type
}: LegalAcknowledgmentDialogProps) {
  const [acknowledged, setAcknowledged] = useState(false);

  const handleAccept = () => {
    if (acknowledged) {
      onAccept();
      setAcknowledged(false); // Reset for next time
    }
  };

  const getContent = () => {
    switch (type) {
      case 'contract':
        return {
          description: 'Please read and acknowledge the following before proceeding:',
          points: [
            'This analysis is for general information only and is NOT legal advice',
            'RetirePath is not a law firm and does not provide legal advice',
            'This tool uses AI technology which may contain errors or omissions',
            'We do not verify the accuracy of contract terms you enter',
            'We cannot assess your specific legal situation'
          ],
          warning: 'You MUST consult a qualified solicitor experienced in retirement village law before making any decisions based on this analysis.',
          liability: 'RetirePath accepts no liability for any decisions made based on the information provided. The accuracy of analysis depends on the accuracy and completeness of information you provide.'
        };
      
      case 'valuation':
        return {
          description: 'Please read and acknowledge the following before proceeding:',
          points: [
            'This is an automated estimate only and is NOT a professional property valuation',
            'This estimate is generated by AI and may be significantly inaccurate',
            'This should not be used for financial decisions or setting sale prices',
            'This does not constitute financial advice',
            'This is not a substitute for a licensed property valuer'
          ],
          warning: 'You MUST consult licensed property valuers and financial advisors before making property or financial decisions.',
          liability: 'RetirePath accepts no liability for any decisions made based on these estimates. Actual sale prices may vary significantly from estimated values.'
        };

      case 'matcher':
        return {
          description: 'Please understand the following about this tool:',
          points: [
            'This tool provides suggestions based on your preferences only',
            'It does not provide personalized advice',
            'We do not verify village information accuracy',
            'Matches do not guarantee suitability for your needs',
            'This does not replace your own research and due diligence'
          ],
          warning: 'Always visit villages in person, verify all information directly with operators, and consult with professionals before making decisions.',
          liability: 'RetirePath is an independent information platform and accepts no liability for decisions made based on village matches or recommendations.'
        };
    }
  };

  const content = getContent();

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <AlertCircle className="size-6 text-orange-600" />
            {title}
          </DialogTitle>
          <DialogDescription className="text-base pt-2">
            {content.description}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* Key Points */}
          <div className="bg-orange-50 border border-orange-200 rounded-lg p-4">
            <ul className="space-y-2">
              {content.points.map((point, index) => (
                <li key={index} className="flex items-start gap-2">
                  <span className="text-orange-600 mt-1">•</span>
                  <span className="text-sm">{point}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Warning Box */}
          <div className="bg-red-50 border-2 border-red-300 rounded-lg p-4">
            <p className="text-red-900">
              <strong className="block mb-2">⚠️ IMPORTANT:</strong>
              {content.warning}
            </p>
          </div>

          {/* Liability */}
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
            <p className="text-sm text-muted-foreground">
              <strong>Limitation of Liability:</strong> {content.liability}
            </p>
          </div>

          {/* Acknowledgment Checkbox */}
          <div className="flex items-start gap-3 p-4 bg-white border-2 border-gray-300 rounded-lg">
            <Checkbox
              id="acknowledge"
              checked={acknowledged}
              onCheckedChange={(checked) => setAcknowledged(checked as boolean)}
              className="mt-1"
            />
            <Label
              htmlFor="acknowledge"
              className="text-sm cursor-pointer leading-relaxed"
            >
              <strong>I understand and agree:</strong> I have read and understood the above disclaimers. 
              I acknowledge that this tool does not provide professional advice and I will consult 
              with qualified professionals before making any decisions.
            </Label>
          </div>
        </div>

        <DialogFooter className="gap-2">
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
          >
            Cancel
          </Button>
          <Button
            onClick={handleAccept}
            disabled={!acknowledged}
            className="bg-blue-600 hover:bg-blue-700"
          >
            I Understand - Continue
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
