-- NSW Batch 11: 25 NSW Far North Coast & Northern Rivers Retirement Villages
-- Geographic Focus: Byron Bay, Ballina, Lismore, Coffs Harbour, Port Macquarie
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Stockland Halcyon Greens Port Macquarie', 'Stockland', 'Premium Mid North Coast retirement resort near beaches. Modern villas with championship golf course access. Pool, gym, cinema, bowling green and clubhouse. Minutes to Port Macquarie beaches and town centre.', '1 Lakewood Drive', 'Port Macquarie', 'NSW', '2444', 'Independent Living', 380000, 580000, 160, 250, 214, 16, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Golf Course', 'Clubhouse', 'Gardens'], '1800 550 550', 'portmacquarie@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Palm Lake Resort Ballina Beach', 'Palm Lake Resort', 'North Coast over-50s resort community near beaches. Contemporary manufactured homes with resort facilities. Pool, tennis, bowling green, gym and community hub. Walk to Ballina beaches and shops.', '1 Beach Avenue', 'Ballina', 'NSW', '2478', 'Independent Living', 320000, 480000, 120, 190, 186, 14, ARRAY['Pool', 'Tennis Courts', 'Bowling Green', 'Gym', 'Clubhouse', 'Beach Access'], '02 6686 9300', 'ballinabeach@palmlakeresort.com.au', 'https://www.palmlakeresort.com.au', 'Active'),

('Aveo Freedom Coffs Harbour', 'Aveo Group', 'Coastal retirement village near pristine Coffs beaches. Modern villas and apartments with ocean breezes. Pool, gym, bowling green and community centre. Enjoy year-round mild climate and banana capital lifestyle.', '88 Ocean Parade', 'Coffs Harbour', 'NSW', '2450', 'Independent Living', 340000, 520000, 150, 230, 156, 12, ARRAY['Pool', 'Gym', 'Bowling Green', 'Community Centre', 'Gardens', 'Workshop'], '1300 283 000', 'coffsharbour@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Anglicare Greenview Gardens Lismore', 'Anglicare', 'Northern Rivers retirement village in regional Lismore. Spacious villas with tropical gardens and mountain views. Chapel, community centre and bowling green. Close to Base Hospital and shopping. Warm subtropical climate.', '42 Ballina Road', 'Lismore', 'NSW', '2480', 'Independent Living, Aged Care', 260000, 400000, 110, 180, 94, 8, ARRAY['Chapel', 'Bowling Green', 'Gardens', 'Mountain Views', 'Community Centre', 'Aged Care'], '02 6621 3100', 'lismore@anglicare.org.au', 'https://www.anglicare.org.au', 'Active'),

('IRT The Palms Ballina', 'IRT Group', 'North Coast retirement community near beaches and river. Comfortable villas with subtropical gardens. Pool, bowling green and community facilities. Short drive to Byron Bay, Ballina beaches and Richmond Valley.', '88 River Street', 'Ballina', 'NSW', '2478', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 118, 10, ARRAY['Pool', 'Bowling Green', 'Gardens', 'River Views', 'Community Centre', 'Aged Care'], '1300 157 677', 'ballina@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Uniting Wauchope', 'Uniting', 'Hastings region retirement village near Port Macquarie. Affordable villas with community centre and gardens. Close to Wauchope town centre and Timbertown. Easy access to beaches and Hastings River.', '22 High Street', 'Wauchope', 'NSW', '2446', 'Independent Living', 240000, 380000, 100, 170, 86, 7, ARRAY['Community Centre', 'Gardens', 'Bowling Green', 'Library', 'BBQ Areas'], '1300 864 846', 'wauchope@uniting.org', 'https://www.uniting.org', 'Active'),

('Opal Aged Care Byron Bay', 'Opal Aged Care', 'Premium Northern Rivers retirement near iconic Byron Bay. Modern apartments with hinterland views. Pool, gym and wellness centre. Walk to beaches, cafes and bohemian village. Ultimate coastal lifestyle.', '88 Bangalow Road', 'Byron Bay', 'NSW', '2481', 'Independent Living, Aged Care', 520000, 780000, 200, 300, 72, 4, ARRAY['Pool', 'Gym', 'Wellness Centre', 'Hinterland Views', 'Beach Access', 'Aged Care'], '1300 672 524', 'byronbay@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('Presbyterian Aged Care Kempsey', 'Presbyterian Aged Care NSW & ACT', 'Mid North Coast retirement village in Kempsey. Comfortable villas with chapel and community facilities. Close to Macleay River and medical services. Affordable regional living with coastal access.', '42 Sea Street', 'Kempsey', 'NSW', '2440', 'Independent Living, Aged Care', 220000, 360000, 95, 165, 78, 6, ARRAY['Chapel', 'Community Centre', 'Gardens', 'River Views', 'Aged Care'], '02 6562 3100', 'kempsey@pac.org.au', 'https://www.pac.org.au', 'Active'),

('Baptistcare Macleay Valley', 'BaptistCare', 'Kempsey region retirement community with river views. Spacious villas surrounded by tropical gardens. Chapel, bowling green and community centre. Enjoy mild coastal climate and river lifestyle.', '88 Pacific Highway', 'Kempsey', 'NSW', '2440', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 92, 7, ARRAY['Chapel', 'Bowling Green', 'River Views', 'Gardens', 'Community Centre', 'Aged Care'], '02 6562 4200', 'kempsey@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Regis Aged Care Coffs Harbour', 'Regis Aged Care', 'Mid North Coast retirement village near beaches. Quality villas with ocean breezes and tropical gardens. Pool, bowling green and community facilities. Walk to Coffs Jetty, beaches and shopping plaza.', '22 Park Beach Road', 'Coffs Harbour', 'NSW', '2450', 'Independent Living, Aged Care', 320000, 480000, 140, 220, 104, 9, ARRAY['Pool', 'Bowling Green', 'Gardens', 'Ocean Breeze', 'Community Centre', 'Aged Care'], '02 6652 4100', 'coffs@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Grafton', 'Respect', 'Clarence Valley retirement village with jacaranda-lined streets. Comfortable villas near Clarence River. Community centre, gardens and bowling green. Historic town centre and medical facilities nearby.', '88 Prince Street', 'Grafton', 'NSW', '2460', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 86, 7, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'River Views', 'Aged Care'], '02 6642 3100', 'grafton@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Southern Cross Care Macksville', 'Southern Cross Care', 'Nambucca Valley retirement community near beaches. Spacious villas with tropical setting. Bowling green, community hall and gardens. Close to Nambucca Heads beaches and Scotts Head. Relaxed coastal living.', '42 River Street', 'Macksville', 'NSW', '2447', 'Independent Living, Aged Care', 260000, 400000, 115, 185, 74, 6, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Coastal Setting', 'Aged Care'], '02 6568 3100', 'macksville@sccliving.org.au', 'https://www.sccliving.org.au', 'Active'),

('Adventist Retirement Plus Goonellabah', 'Adventist Retirement Plus', 'Lismore hinterland retirement village with rainforest views. Health-focused community surrounded by nature. Pool, wellness centre and walking trails. Close to Southern Cross University and Lismore.', '88 Loftus Drive', 'Goonellabah', 'NSW', '2480', 'Independent Living', 260000, 400000, 115, 185, 96, 8, ARRAY['Pool', 'Wellness Centre', 'Rainforest Views', 'Walking Trails', 'Gardens'], '02 6625 4200', 'goonellabah@adventistretirementplus.org.au', 'https://www.retirementplus.com.au', 'Active'),

('Estia Health Nambucca Heads', 'Estia Health', 'Mid North Coast beachside retirement village. Modern villas near pristine beaches and Nambucca River. Pool, community centre and coastal walks. Perfect fishing and beach lifestyle destination.', '22 Wellington Drive', 'Nambucca Heads', 'NSW', '2448', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 68, 5, ARRAY['Pool', 'Beach Access', 'River Views', 'Community Centre', 'Aged Care'], '02 6569 3100', 'nambucca@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Bupa Aged Care Tweed Heads', 'Bupa', 'Far North Coast retirement village on Queensland border. Modern villas near Gold Coast beaches. Pool, gym and community facilities. Access to Tweed and Gold Coast amenities. Warm subtropical climate.', '88 Tweed Coast Road', 'Tweed Heads', 'NSW', '2485', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 112, 10, ARRAY['Pool', 'Gym', 'Community Centre', 'Gardens', 'Beach Access', 'Aged Care'], '1300 280 334', 'tweedheads@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Port Macquarie Central', 'Allity', 'Town centre retirement community near Settlement City. Contemporary apartments with rooftop terrace. Walk to shops, restaurants, cinema and waterfront. Perfect urban coastal retirement location.', '42 Horton Street', 'Port Macquarie', 'NSW', '2444', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 96, 7, ARRAY['Rooftop Terrace', 'Urban Location', 'Community Centre', 'Library', 'Aged Care'], '02 6584 3100', 'portmac@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Casino', 'Bolton Clarke', 'Richmond Valley retirement village in Casino. Comfortable villas with community centre and gardens. Close to regional services and Northern Rivers attractions. Affordable country living with subtropical climate.', '88 Canterbury Street', 'Casino', 'NSW', '2470', 'Independent Living, Aged Care', 210000, 350000, 90, 160, 72, 6, ARRAY['Community Centre', 'Gardens', 'Bowling Green', 'Library', 'Aged Care'], '1300 228 655', 'casino@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Villa Maria Catholic Homes Murwillumbah', 'Villa Maria Catholic Homes', 'Tweed Valley retirement village with mountain views. Catholic community with chapel and pastoral care. Gardens, community centre and bowling green. Explore Mount Warning and hinterland waterfalls.', '42 Murwillumbah Street', 'Murwillumbah', 'NSW', '2484', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 68, 5, ARRAY['Chapel', 'Mountain Views', 'Gardens', 'Bowling Green', 'Aged Care'], '02 6672 3100', 'murwillumbah@vmch.com.au', 'https://www.vmch.com.au', 'Active'),

('Japara Lennox Head', 'Japara', 'Premium North Coast beachside retirement near Byron Bay. Modern villas with ocean views. Pool, community facilities and beach access. Walk to Lennox Head village, surf breaks and coastal walks. Iconic location.', '88 Ballina Street', 'Lennox Head', 'NSW', '2478', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 62, 3, ARRAY['Pool', 'Ocean Views', 'Beach Access', 'Community Centre', 'Aged Care'], '1800 52 72 72', 'lennoxhead@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Sawtell', 'Tricare', 'Coffs Coast beachside retirement village. Modern villas near beautiful Sawtell Beach. Pool, bowling green and community centre. Walk to Sawtell village cafes, shops and First Avenue beachfront. Premium coastal position.', '22 Boronia Street', 'Sawtell', 'NSW', '2452', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 84, 6, ARRAY['Pool', 'Bowling Green', 'Beach Access', 'Community Centre', 'Aged Care'], '02 6653 3100', 'sawtell@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Yamba', 'Mayflower', 'Clarence River mouth retirement village with ocean and river views. Spacious villas near pristine beaches. Community centre, gardens and fishing access. Perfect fishing paradise and coastal lifestyle.', '88 Yamba Road', 'Yamba', 'NSW', '2464', 'Independent Living', 320000, 490000, 140, 220, 72, 5, ARRAY['Ocean Views', 'River Views', 'Fishing Access', 'Community Centre', 'Gardens'], '02 6646 1234', 'yamba@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL LifeCare Ocean Shores', 'RSL LifeCare', 'Brunswick Heads hinterland retirement community. Peaceful villas surrounded by nature. Community centre, gardens and walking trails. Close to Byron Bay, Brunswick beaches and village cafes. Veterans services available.', '88 Shara Boulevard', 'Ocean Shores', 'NSW', '2483', 'Independent Living', 300000, 460000, 130, 210, 94, 8, ARRAY['Gardens', 'Walking Trails', 'Community Centre', 'Nature Setting', 'RSL Services'], '02 6680 3100', 'oceanshores@rsllifecare.org.au', 'https://www.rsllifecare.org.au', 'Active'),

('Ingenia Lifestyle Lake Cathie', 'Ingenia Communities', 'Port Macquarie beaches over-50s resort. Modern manufactured homes near pristine Lake Cathie beaches. Pool, bowling green and clubhouse. Perfect surfing, fishing and coastal lifestyle. Affordable beach living.', '1 Beach Drive', 'Lake Cathie', 'NSW', '2445', 'Independent Living', 240000, 400000, 95, 165, 178, 15, ARRAY['Pool', 'Bowling Green', 'Beach Access', 'Lake Access', 'Clubhouse'], '02 6585 1234', 'lakecathie@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Active'),

('NewDirection Care Woolgoolga', 'NewDirection Care', 'Coffs Coast Indian village retirement community. Multicultural friendly with community centre and gardens. Near beautiful Woolgoolga beaches and curry restaurants. Unique cultural diversity and coastal lifestyle.', '22 Beach Street', 'Woolgoolga', 'NSW', '2456', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 76, 6, ARRAY['Community Centre', 'Gardens', 'Beach Access', 'Cultural Centre', 'Aged Care'], '02 6654 3100', 'woolgoolga@newdirection.com.au', 'https://www.newdirection.com.au', 'Active'),

('Arcare Armidale', 'Arcare', 'New England Tablelands retirement village with cool climate. Heritage city villas with four seasons. Community centre, gardens and bowling green. Close to Armidale Hospital, university and Cathedral. Country city lifestyle.', '88 Marsh Street', 'Armidale', 'NSW', '2350', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 82, 7, ARRAY['Bowling Green', 'Gardens', 'Community Centre', 'Heritage Setting', 'Aged Care'], '1300 272 273', 'armidale@arcare.com.au', 'https://www.arcare.com.au', 'Active');
