-- NSW Batch 08: 25 Western Sydney & Blue Mountains Retirement Villages
-- Geographic Focus: Parramatta, Blacktown, Penrith, Blue Mountains
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Stockland Willowdale Gardens', 'Stockland', 'Premium Western Sydney retirement community in Leppington. Contemporary villas and apartments with resort pool, gym, cinema and community hub. Minutes to Leppington station and growing South-West precinct.', '1 Willowdale Boulevard', 'Leppington', 'NSW', '2179', 'Independent Living', 420000, 620000, 170, 250, 196, 13, ARRAY['Pool', 'Gym', 'Cinema', 'Community Centre', 'Gardens', 'Workshop', 'BBQ Areas'], '1800 550 550', 'willowdalegardens@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Lendlease Retirement Living Penrith', 'Lendlease', 'Modern Penrith retirement community near Nepean Hospital. Spacious apartments with mountain views, pool, gym and community facilities. Walk to Penrith CBD and Panthers precinct. Excellent healthcare access.', '45 Parker Street', 'Penrith', 'NSW', '2750', 'Independent Living', 380000, 560000, 160, 240, 138, 9, ARRAY['Pool', 'Gym', 'Mountain Views', 'Community Centre', 'Gardens', 'Library'], '1300 326 033', 'penrith@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Aveo Newmarket Randwick', 'Aveo Group', 'Eastern suburbs retirement living near Prince of Wales Hospital. Contemporary apartments with rooftop terrace, gym and cinema. Walk to Randwick shops, cafes and racecourse. Premium healthcare precinct location.', '22 Belmore Road', 'Randwick', 'NSW', '2031', 'Independent Living', 620000, 880000, 240, 340, 112, 6, ARRAY['Rooftop Terrace', 'Gym', 'Cinema', 'Library', 'Gardens', 'Concierge'], '1300 283 000', 'randwick@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Anglicare Weeroona', 'Anglicare', 'Established Lakemba retirement village with strong community spirit. Independent villas with bowling green, chapel and community hall. Multicultural friendly atmosphere. Close to Lakemba station and Haldon Street shops.', '88 Canterbury Road', 'Lakemba', 'NSW', '2195', 'Independent Living, Aged Care', 340000, 490000, 140, 210, 84, 5, ARRAY['Bowling Green', 'Chapel', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 9740 6100', 'weeroona@anglicare.org.au', 'https://www.anglicare.org.au', 'Active'),

('Opal Aged Care Parramatta', 'Opal Aged Care', 'Central Parramatta retirement community near Westfield. Modern apartments with city views, pool, gym and rooftop terrace. Walk to Parramatta station, restaurants and entertainment. Urban retirement living.', '88 George Street', 'Parramatta', 'NSW', '2150', 'Independent Living, Aged Care', 520000, 740000, 200, 290, 126, 8, ARRAY['Pool', 'Gym', 'Rooftop Terrace', 'City Views', 'Library', 'Aged Care'], '1300 672 524', 'parramatta@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Peakhurst', 'IRT Group', 'South Sydney retirement village in leafy Peakhurst. Spacious villas with community centre, bowling green and gardens. Friendly atmosphere with active social program. Close to Riverwood Plaza and medical facilities.', '1 Boundary Road', 'Peakhurst', 'NSW', '2210', 'Independent Living', 360000, 520000, 150, 230, 98, 7, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Library', 'BBQ Areas'], '1300 157 677', 'peakhurst@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Presbyterian Aged Care Thornleigh', 'Presbyterian Aged Care NSW & ACT', 'Upper North Shore retirement village near Thornleigh station. Independent units with chapel, community centre and gardens. Established community with pastoral care services. Easy train access to city.', '14 Chilvers Road', 'Thornleigh', 'NSW', '2120', 'Independent Living, Aged Care', 420000, 580000, 170, 250, 76, 4, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 9484 2200', 'thornleigh@pac.org.au', 'https://www.pac.org.au', 'Active'),

('Uniting Turramurra', 'Uniting', 'Premium Upper North Shore retirement living in Turramurra. Spacious apartments with quality finishes, pool, gym and community facilities. Beautiful gardens and walking distance to Turramurra village shops and station.', '88 Kissing Point Road', 'Turramurra', 'NSW', '2074', 'Independent Living', 680000, 920000, 260, 360, 94, 5, ARRAY['Pool', 'Gym', 'Gardens', 'Community Centre', 'Library', 'Cinema'], '1300 864 846', 'turramurra@uniting.org', 'https://www.uniting.org', 'Active'),

('Ingenia Lifestyle Chain Valley Bay', 'Ingenia Communities', 'Lake Macquarie over-50s resort community. Modern manufactured homes with lake access. Pool, bowling green, tennis courts and marina. Perfect for boating and fishing enthusiasts. Affordable waterfront living.', '1 Fishing Point Road', 'Chain Valley Bay', 'NSW', '2259', 'Independent Living', 200000, 360000, 85, 145, 216, 18, ARRAY['Pool', 'Bowling Green', 'Tennis Courts', 'Marina', 'Lake Access', 'Community Centre'], '02 4393 1234', 'chainvalley@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Active'),

('Baptistcare Morven Gardens', 'BaptistCare', 'Carlingford retirement village near Carlingford Court. Comfortable villas with chapel, community centre and gardens. Strong Baptist community with regular services. Close to all amenities and medical facilities.', '14 Pennant Hills Road', 'Carlingford', 'NSW', '2118', 'Independent Living', 400000, 560000, 160, 240, 102, 8, ARRAY['Chapel', 'Gardens', 'Community Centre', 'Library', 'BBQ Areas'], '02 9872 3100', 'morvengardens@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Arcare Epping', 'Arcare', 'North-West Sydney retirement community near Epping station. Modern apartments with contemporary design, gym, cinema and cafe. Walk to Epping shops and trains. Metro access to city and Macquarie Park.', '88 Beecroft Road', 'Epping', 'NSW', '2121', 'Independent Living, Aged Care', 540000, 760000, 210, 300, 118, 7, ARRAY['Gym', 'Cinema', 'Cafe', 'Library', 'Gardens', 'Aged Care'], '1300 272 273', 'epping@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Regis Aged Care Roseville', 'Regis Aged Care', 'North Shore retirement village near Roseville station. Quality independent villas and aged care facility. Community centre, gardens and bowling green. Quiet leafy location with excellent transport links.', '12 Hill Street', 'Roseville', 'NSW', '2069', 'Independent Living, Aged Care', 580000, 780000, 230, 320, 86, 4, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 9416 4100', 'roseville@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Eastwood', 'Respect', 'Inner-West retirement community near Eastwood station. Modern apartments with multicultural-friendly environment. Pool, gym and community facilities. Walk to Eastwood Plaza, restaurants and shops.', '42 Rowe Street', 'Eastwood', 'NSW', '2122', 'Independent Living, Aged Care', 480000, 680000, 190, 270, 96, 6, ARRAY['Pool', 'Gym', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 9858 3200', 'eastwood@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Southern Cross Care St Hedwig Village', 'Southern Cross Care', 'Blacktown retirement community with strong Polish heritage. Independent villas with chapel, community hall and bowling green. Cultural activities and Polish services available. Close to Westpoint shopping.', '24 Sunnyholt Road', 'Blacktown', 'NSW', '2148', 'Independent Living, Aged Care', 320000, 470000, 140, 210, 112, 9, ARRAY['Chapel', 'Bowling Green', 'Community Centre', 'Gardens', 'Cultural Centre', 'Aged Care'], '02 9831 6100', 'blacktown@sccliving.org.au', 'https://www.sccliving.org.au', 'Active'),

('Adventist Retirement Plus Wahroonga', 'Adventist Retirement Plus', 'Upper North Shore retirement village near Wahroonga. Health-focused community with villas and units. Pool, gardens and wellness programs. Walk to Wahroonga village and San Adventist Hospital.', '8 Coonanbarra Road', 'Wahroonga', 'NSW', '2076', 'Independent Living', 520000, 720000, 200, 280, 84, 5, ARRAY['Pool', 'Gardens', 'Wellness Centre', 'Community Centre', 'Walking Trails'], '02 9473 8200', 'wahroonga@adventistretirementplus.org.au', 'https://www.retirementplus.com.au', 'Active'),

('Estia Health Katoomba', 'Estia Health', 'Blue Mountains retirement village with stunning mountain views. Cosy villas perfect for cool climate living. Community centre, gardens and fireplace lounge. Enjoy crisp mountain air and village charm.', '88 Lurline Street', 'Katoomba', 'NSW', '2780', 'Independent Living, Aged Care', 280000, 420000, 120, 190, 68, 6, ARRAY['Mountain Views', 'Community Centre', 'Gardens', 'Fireplace Lounge', 'Library', 'Aged Care'], '02 4782 5100', 'katoomba@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Bupa Aged Care Camden', 'Bupa', 'Macarthur region retirement community in growing Camden. Modern villas and apartments with resort amenities. Pool, gym, cinema and community hub. Near new Camden Hospital and shopping precinct.', '1 Argyle Street', 'Camden', 'NSW', '2570', 'Independent Living, Aged Care', 380000, 560000, 160, 240, 142, 11, ARRAY['Pool', 'Gym', 'Cinema', 'Community Centre', 'Gardens', 'Aged Care'], '1300 280 334', 'camden@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Ryde', 'Allity', 'Inner-West retirement living near Top Ryde Shopping Centre. Contemporary apartments with pool, gym and rooftop terrace. Walk to shops, library and medical facilities. Excellent bus and train connections.', '88 Devlin Street', 'Ryde', 'NSW', '2112', 'Independent Living, Aged Care', 520000, 720000, 200, 290, 108, 7, ARRAY['Pool', 'Gym', 'Rooftop Terrace', 'Library', 'Gardens', 'Aged Care'], '02 9807 3100', 'ryde@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Hornsby', 'Bolton Clarke', 'Upper North Shore retirement village near Hornsby Hospital. Quality villas and apartments with community facilities. Pool, bowling green and gardens. Close to Westfield Hornsby and train station.', '12 Peats Ferry Road', 'Hornsby', 'NSW', '2077', 'Independent Living, Aged Care', 480000, 680000, 190, 270, 124, 8, ARRAY['Pool', 'Bowling Green', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '1300 228 655', 'hornsby@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Villa Maria Catholic Homes Westmead', 'Villa Maria Catholic Homes', 'Parramatta region retirement community near Westmead Hospital precinct. Independent villas with chapel and Catholic services. Gardens, community centre and pastoral care. Excellent medical facilities nearby.', '88 Hawkesbury Road', 'Westmead', 'NSW', '2145', 'Independent Living, Aged Care', 420000, 600000, 170, 250, 92, 6, ARRAY['Chapel', 'Gardens', 'Community Centre', 'Library', 'Aged Care'], '02 9891 4200', 'westmead@vmch.com.au', 'https://www.vmch.com.au', 'Active'),

('Japara Roslyn Park', 'Japara', 'Bankstown retirement community with multicultural atmosphere. Modern villas and aged care. Community centre, gardens and cultural programs. Close to Bankstown Central and medical facilities.', '88 Chapel Road', 'Bankstown', 'NSW', '2200', 'Independent Living, Aged Care', 360000, 530000, 150, 230, 104, 8, ARRAY['Community Centre', 'Gardens', 'Cultural Centre', 'Library', 'Aged Care'], '1800 52 72 72', 'bankstown@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare West Pennant Hills', 'Tricare', 'Hills District retirement village in peaceful West Pennant Hills. Spacious villas surrounded by native bushland. Community centre, bowling green and gardens. Close to Cherrybrook Village and Castle Hill.', '88 Coonara Avenue', 'West Pennant Hills', 'NSW', '2125', 'Independent Living, Aged Care', 480000, 680000, 190, 270, 86, 5, ARRAY['Bowling Green', 'Bushland Setting', 'Community Centre', 'Gardens', 'Aged Care'], '02 9484 6100', 'westpennant@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Hunters Hill', 'Mayflower', 'Exclusive harbourside retirement village in prestigious Hunters Hill. Luxury villas with harbour glimpses. Beautiful gardens, community facilities and village atmosphere. Walk to harbour foreshore and boutique shops.', '14 Woolwich Road', 'Hunters Hill', 'NSW', '2110', 'Independent Living', 780000, 1080000, 280, 390, 52, 2, ARRAY['Harbour Views', 'Gardens', 'Community Centre', 'Library', 'Village Atmosphere'], '02 9817 4200', 'huntershil@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL LifeCare Narrabeen', 'RSL LifeCare', 'Northern Beaches retirement living near Narrabeen Lake. Villas and apartments with lake views. Community centre, bowling green and gardens. Short walk to beaches and Narrabeen Sports Centre. Veterans services available.', '88 Ocean Street', 'Narrabeen', 'NSW', '2101', 'Independent Living, Aged Care', 580000, 820000, 220, 310, 116, 7, ARRAY['Lake Views', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '02 9913 4100', 'narrabeen@rsllifecare.org.au', 'https://www.rsllifecare.org.au', 'Active'),

('NewDirection Care Concord', 'NewDirection Care', 'Inner-West retirement community near Concord Hospital. Modern apartments with community facilities and aged care. Pool, gardens and activity programs. Walk to shops, restaurants and Parramatta River.', '22 Wellbank Street', 'Concord', 'NSW', '2137', 'Independent Living, Aged Care', 520000, 720000, 200, 290, 98, 6, ARRAY['Pool', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 9743 3100', 'concord@newdirection.com.au', 'https://www.newdirection.com.au', 'Active');
