-- NSW Batch 09: 25 Southern Highlands & South Coast Retirement Villages
-- Geographic Focus: Wollongong, Shellharbour, Kiama, Southern Highlands, Shoalhaven
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Stockland Halcyon Lakeside', 'Stockland', 'Premium Shellharbour retirement resort near Lake Illawarra. Contemporary villas with waterfront location. Pool, gym, cinema, bowling green and marina access. Minutes to Stockland Shellharbour shopping.', '1 Lakeside Boulevard', 'Shell Cove', 'NSW', '2529', 'Independent Living', 420000, 640000, 170, 260, 186, 12, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Marina', 'Lake Views', 'Community Centre'], '1800 550 550', 'lakeside@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Lendlease Retirement Wollongong', 'Lendlease', 'Coastal retirement community with ocean views. Modern apartments overlooking Wollongong beaches. Pool, gym, cinema and dining facilities. Walk to beach, cafes and Wollongong CBD.', '88 Crown Street', 'Wollongong', 'NSW', '2500', 'Independent Living', 480000, 720000, 190, 280, 132, 8, ARRAY['Pool', 'Gym', 'Cinema', 'Ocean Views', 'Dining Room', 'Gardens', 'Library'], '1300 326 033', 'wollongong@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Aveo Bowral', 'Aveo Group', 'Southern Highlands retirement village in charming Bowral. Heritage-style villas with cool climate gardens. Community centre, library and bowling green. Walk to Bowral village shops, galleries and restaurants.', '22 Bong Bong Street', 'Bowral', 'NSW', '2576', 'Independent Living', 420000, 620000, 170, 250, 94, 6, ARRAY['Bowling Green', 'Gardens', 'Community Centre', 'Library', 'Heritage Style'], '1300 283 000', 'bowral@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Anglicare Marian Gardens', 'Anglicare', 'Fairy Meadow retirement village near Wollongong University. Independent villas with gardens, chapel and community hall. Close to beaches, shops and Wollongong Hospital. Friendly community atmosphere.', '42 Rothery Street', 'Fairy Meadow', 'NSW', '2519', 'Independent Living, Aged Care', 340000, 510000, 140, 220, 86, 5, ARRAY['Chapel', 'Gardens', 'Community Centre', 'Library', 'Aged Care'], '02 4285 4100', 'mariangardens@anglicare.org.au', 'https://www.anglicare.org.au', 'Active'),

('IRT Moruya', 'IRT Group', 'Far South Coast retirement village in historic Moruya. Comfortable villas near beaches and Moruya River. Community centre, bowling green and gardens. Peaceful coastal town lifestyle with excellent fishing.', '14 Campbell Street', 'Moruya', 'NSW', '2537', 'Independent Living, Aged Care', 260000, 400000, 110, 180, 78, 6, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'River Views', 'Aged Care'], '1300 157 677', 'moruya@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Uniting Figtree', 'Uniting', 'Wollongong region retirement community in leafy Figtree. Modern villas and apartments with pool and community facilities. Close to Wollongong Hospital, Westfield Figtree and University. Easy coastal access.', '88 Princes Highway', 'Figtree', 'NSW', '2525', 'Independent Living', 380000, 560000, 160, 240, 116, 9, ARRAY['Pool', 'Community Centre', 'Gardens', 'Library', 'BBQ Areas'], '1300 864 846', 'figtree@uniting.org', 'https://www.uniting.org', 'Active'),

('Opal Aged Care Thirroul', 'Opal Aged Care', 'Beachside retirement living in charming Thirroul village. Contemporary apartments near Lawrence Hargrave Drive cafes. Ocean views, pool and community facilities. Walk to Thirroul Beach and train station.', '22 The Corso', 'Thirroul', 'NSW', '2515', 'Independent Living, Aged Care', 420000, 620000, 170, 250, 74, 4, ARRAY['Pool', 'Ocean Views', 'Community Centre', 'Gardens', 'Aged Care'], '1300 672 524', 'thirroul@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('Presbyterian Aged Care Mittagong', 'Presbyterian Aged Care NSW & ACT', 'Southern Highlands retirement village with cool climate charm. Comfortable villas with chapel, gardens and community centre. Close to Mittagong shops and medical facilities. Four seasons lifestyle.', '88 Old Hume Highway', 'Mittagong', 'NSW', '2575', 'Independent Living, Aged Care', 320000, 480000, 140, 210, 92, 7, ARRAY['Chapel', 'Gardens', 'Community Centre', 'Library', 'Aged Care'], '02 4872 3100', 'mittagong@pac.org.au', 'https://www.pac.org.au', 'Active'),

('Baptistcare Kiama Shores', 'BaptistCare', 'Coastal retirement village with stunning ocean views. Modern villas overlooking Kiama beaches. Chapel, pool and community facilities. Walk to Kiama blowhole, shops and harbor. Premium coastal lifestyle.', '14 Boanyo Avenue', 'Kiama', 'NSW', '2533', 'Independent Living', 480000, 720000, 190, 280, 68, 3, ARRAY['Pool', 'Chapel', 'Ocean Views', 'Community Centre', 'Gardens'], '02 4232 2100', 'kiama@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Regis Aged Care Ulladulla', 'Regis Aged Care', 'South Coast retirement community near beautiful beaches. Comfortable villas with bowling green, gardens and community hall. On-site aged care facility. Enjoy relaxed coastal town lifestyle and fishing.', '88 Princes Highway', 'Ulladulla', 'NSW', '2539', 'Independent Living, Aged Care', 280000, 430000, 120, 190, 84, 6, ARRAY['Bowling Green', 'Gardens', 'Community Centre', 'Library', 'Aged Care'], '02 4455 4200', 'ulladulla@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Nowra', 'Respect', 'Shoalhaven retirement village in regional Nowra. Modern villas and aged care facility. Community centre, bowling green and gardens. Close to Stockland Nowra shopping and base hospital.', '42 Moss Street', 'Nowra', 'NSW', '2541', 'Independent Living, Aged Care', 260000, 400000, 110, 180, 102, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 4421 3100', 'nowra@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Southern Cross Care Batemans Bay', 'Southern Cross Care', 'Beautiful South Coast retirement living near beaches and Clyde River. Spacious villas with water views. Pool, bowling green and community centre. Perfect retirement haven on sapphire coast.', '1 Beach Road', 'Batemans Bay', 'NSW', '2536', 'Independent Living, Aged Care', 340000, 510000, 150, 230, 96, 7, ARRAY['Pool', 'Bowling Green', 'Water Views', 'Community Centre', 'Gardens', 'Aged Care'], '02 4472 6100', 'bateman@sccliving.org.au', 'https://www.sccliving.org.au', 'Active'),

('Adventist Retirement Plus Corrimal', 'Adventist Retirement Plus', 'Northern Wollongong retirement village near beaches. Health-focused community with villas and wellness programs. Pool, gardens and walking trails. Close to Corrimal Beach and local shops.', '88 Railway Street', 'Corrimal', 'NSW', '2518', 'Independent Living', 320000, 480000, 140, 210, 88, 6, ARRAY['Pool', 'Gardens', 'Wellness Centre', 'Walking Trails', 'Community Centre'], '02 4283 2200', 'corrimal@adventistretirementplus.org.au', 'https://www.retirementplus.com.au', 'Active'),

('Estia Health Wollongong', 'Estia Health', 'Central Wollongong retirement community near hospital precinct. Modern apartments with mountain and ocean views. Pool, gym and community facilities. Walk to WIN Entertainment Centre and beaches.', '88 Keira Street', 'Wollongong', 'NSW', '2500', 'Independent Living, Aged Care', 420000, 620000, 170, 250, 108, 7, ARRAY['Pool', 'Gym', 'Mountain Views', 'Ocean Views', 'Community Centre', 'Aged Care'], '02 4226 3100', 'wollongong@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Bupa Aged Care Port Kembla', 'Bupa', 'Industrial city retirement village with harbor views. Affordable villas and aged care near Port Kembla. Community centre, gardens and bowling green. Close to beaches and Warrawong Plaza shopping.', '22 Wentworth Street', 'Port Kembla', 'NSW', '2505', 'Independent Living, Aged Care', 280000, 420000, 120, 190, 94, 8, ARRAY['Bowling Green', 'Harbour Views', 'Community Centre', 'Gardens', 'Aged Care'], '1300 280 334', 'portkembla@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Dapto', 'Allity', 'Wollongong region retirement community near Lake Illawarra. Spacious villas with lake access and fishing. Community centre, bowling green and gardens. Close to Stockland Shellharbour and beaches.', '88 Bong Bong Road', 'Dapto', 'NSW', '2530', 'Independent Living', 300000, 450000, 130, 200, 112, 9, ARRAY['Bowling Green', 'Lake Access', 'Community Centre', 'Gardens', 'Fishing'], '02 4261 3100', 'dapto@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Berry', 'Bolton Clarke', 'Historic Southern Highlands village retirement community. Heritage-style villas in charming Berry township. Gardens, community centre and village atmosphere. Walk to boutique shops, cafes and berry farms.', '14 Victoria Street', 'Berry', 'NSW', '2535', 'Independent Living', 380000, 560000, 160, 240, 62, 4, ARRAY['Gardens', 'Community Centre', 'Heritage Style', 'Village Atmosphere', 'Library'], '1300 228 655', 'berry@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Villa Maria Catholic Homes Bulli', 'Villa Maria Catholic Homes', 'Coastal escarpment retirement village with ocean views. Catholic community with chapel and pastoral care. Gardens, community centre and aged care. Walk to Bulli Beach and scenic coastal drives.', '88 Park Road', 'Bulli', 'NSW', '2516', 'Independent Living, Aged Care', 360000, 540000, 150, 230, 78, 5, ARRAY['Chapel', 'Ocean Views', 'Gardens', 'Community Centre', 'Aged Care'], '02 4267 3100', 'bulli@vmch.com.au', 'https://www.vmch.com.au', 'Active'),

('Japara Warrawong', 'Japara', 'Wollongong industrial suburb retirement community. Affordable villas and aged care facility. Multicultural friendly with community programs. Close to Warrawong Plaza and medical facilities.', '42 King Street', 'Warrawong', 'NSW', '2502', 'Independent Living, Aged Care', 260000, 400000, 110, 180, 86, 7, ARRAY['Community Centre', 'Gardens', 'Cultural Centre', 'Library', 'Aged Care'], '1800 52 72 72', 'warrawong@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Windang', 'Tricare', 'Lake Illawarra waterfront retirement village. Modern villas with lake views and water access. Pool, community centre and bowling green. Perfect for fishing and water activities. Short drive to beaches.', '1 Lake Entrance Road', 'Windang', 'NSW', '2528', 'Independent Living, Aged Care', 340000, 510000, 150, 230, 92, 6, ARRAY['Pool', 'Bowling Green', 'Lake Views', 'Water Access', 'Community Centre', 'Aged Care'], '02 4296 3100', 'windang@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Robertson', 'Mayflower', 'Southern Highlands country village retirement. Peaceful setting with cool climate gardens. Villas surrounded by farmland and native bushland. Community centre and walking trails. Charming country lifestyle.', '88 Hoddle Street', 'Robertson', 'NSW', '2577', 'Independent Living', 280000, 420000, 120, 190, 54, 5, ARRAY['Gardens', 'Bushland Setting', 'Walking Trails', 'Community Centre', 'Country Views'], '02 4885 1234', 'robertson@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL LifeCare Coniston', 'RSL LifeCare', 'Wollongong retirement village with veterans services. Affordable villas near beaches and University. Bowling green, community hall and RSL club facilities. Strong community spirit with regular activities.', '88 Lake Avenue', 'Coniston', 'NSW', '2500', 'Independent Living, Aged Care', 300000, 450000, 130, 200, 98, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'RSL Club', 'Aged Care'], '02 4229 3100', 'coniston@rsllifecare.org.au', 'https://www.rsllifecare.org.au', 'Active'),

('Ingenia Lifestyle Lake Conjola', 'Ingenia Communities', 'South Coast over-50s resort near pristine Lake Conjola. Modern manufactured homes with lake and beach access. Pool, bowling green and community centre. Perfect fishing and holiday destination.', '1 Lakeside Close', 'Lake Conjola', 'NSW', '2539', 'Independent Living', 220000, 380000, 90, 150, 164, 13, ARRAY['Pool', 'Bowling Green', 'Lake Access', 'Beach Access', 'Community Centre', 'Fishing'], '02 4455 1234', 'conjola@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Active'),

('NewDirection Care Shellharbour', 'NewDirection Care', 'Modern Shellharbour retirement community near marina. Contemporary apartments with pool, gym and community facilities. Walk to Shell Cove Marina, beaches and Stockland shopping. Coastal lifestyle living.', '1 Marina Drive', 'Shellharbour', 'NSW', '2529', 'Independent Living, Aged Care', 380000, 580000, 160, 240, 124, 10, ARRAY['Pool', 'Gym', 'Marina Views', 'Community Centre', 'Gardens', 'Aged Care'], '02 4297 3100', 'shellharbour@newdirection.com.au', 'https://www.newdirection.com.au', 'Active'),

('Arcare Unanderra', 'Arcare', 'Western Wollongong retirement community near escarpment. Modern villas with mountain views. Pool, community centre and gardens. Close to Wollongong Hospital, University and shopping centres.', '88 Princes Highway', 'Unanderra', 'NSW', '2526', 'Independent Living, Aged Care', 320000, 480000, 140, 210, 86, 6, ARRAY['Pool', 'Mountain Views', 'Community Centre', 'Gardens', 'Aged Care'], '1300 272 273', 'unanderra@arcare.com.au', 'https://www.arcare.com.au', 'Active');
