-- NSW Batch 08: 25 Western Sydney & Blue Mountains Retirement Villages (CORRECTED)
-- Geographic Focus: Parramatta, Blacktown, Penrith, Blue Mountains
-- Ready to import via Supabase SQL Editor

INSERT INTO retirement_villages (
  name, operator, location, suburb, postcode, state, latitude, longitude, village_type, care_level,
  entry_price_min, entry_price_max, monthly_fees_min, monthly_fees_max, dmf_structure, dmf_percentage, dmf_cap,
  amenities, care_services, activities, pet_friendly, total_units, bedrooms, age_restriction,
  contact_phone, contact_email, website, description, status, source, verified
) VALUES
('Stockland Willowdale Gardens', 'Stockland', '1 Willowdale Boulevard, Leppington NSW 2179', 'Leppington', '2179', 'NSW', -33.9581, 150.8058, 'Independent Living', 'independent', 420000, 620000, 680, 1000, 'DMF', 6, 30, '["Pool", "Gym", "Cinema", "Community centre", "Gardens", "Workshop", "BBQ areas"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Movies", "Exercise classes", "Workshop activities", "Social events"]'::jsonb, false, 196, ARRAY['2 bedroom', '3 bedroom'], 55, '1800 550 550', 'willowdalegardens@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Premium Western Sydney retirement community in Leppington with contemporary villas. Minutes to Leppington station.', 'approved', 'admin', true),
('Lendlease Retirement Living Penrith', 'Lendlease', '45 Parker Street, Penrith NSW 2750', 'Penrith', '2750', 'NSW', -33.7508, 150.6944, 'Independent Living', 'independent', 380000, 560000, 640, 960, 'DMF', 6, 30, '["Pool", "Gym", "Mountain views", "Community centre", "Gardens", "Library"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Exercise classes", "Social events", "Garden club"]'::jsonb, false, 138, ARRAY['1 bedroom', '2 bedroom', '3 bedroom'], 55, '1300 326 033', 'penrith@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Modern Penrith retirement community near Nepean Hospital with spacious apartments. Walk to Penrith CBD and Panthers precinct.', 'approved', 'admin', true),
('Aveo Newmarket Randwick', 'Aveo Group', '22 Belmore Road, Randwick NSW 2031', 'Randwick', '2031', 'NSW', -33.9158, 151.2413, 'Independent Living', 'independent', 620000, 880000, 960, 1360, 'DMF', 6, 30, '["Rooftop terrace", "Gym", "Cinema", "Library", "Gardens", "Concierge"]'::jsonb, '["Emergency response", "Concierge"]'::jsonb, '["Movies", "Exercise classes", "Social events"]'::jsonb, false, 112, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 283 000', 'randwick@aveo.com.au', 'https://www.aveo.com.au', 'Eastern suburbs retirement living near Prince of Wales Hospital with contemporary apartments. Premium healthcare precinct location.', 'approved', 'admin', true),
('Anglicare Weeroona', 'Anglicare', '88 Canterbury Road, Lakemba NSW 2195', 'Lakemba', '2195', 'NSW', -33.9200, 151.0758, 'Mixed', 'Mixed', 340000, 490000, 560, 840, 'DMF', 6, 30, '["Bowling green", "Chapel", "Community centre", "Gardens", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Bowls", "Chapel services", "Social events", "Garden club"]'::jsonb, true, 84, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9740 6100', 'weeroona@anglicare.org.au', 'https://www.anglicare.org.au', 'Established Lakemba retirement village with strong community spirit. Close to Lakemba station and Haldon Street shops.', 'approved', 'admin', true),
('Opal Aged Care Parramatta', 'Opal Aged Care', '88 George Street, Parramatta NSW 2150', 'Parramatta', '2150', 'NSW', -33.8150, 151.0006, 'Mixed', 'Mixed', 520000, 740000, 800, 1160, 'DMF', 6, 30, '["Pool", "Gym", "Rooftop terrace", "City views", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Exercise classes", "Social events"]'::jsonb, false, 126, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 672 524', 'parramatta@opalaged.care', 'https://www.opalagedcare.com.au', 'Central Parramatta retirement community near Westfield with modern apartments. Walk to Parramatta station and entertainment.', 'approved', 'admin', true),
('IRT Peakhurst', 'IRT Group', '1 Boundary Road, Peakhurst NSW 2210', 'Peakhurst', '2210', 'NSW', -33.9572, 151.0558, 'Independent Living', 'independent', 360000, 520000, 600, 920, 'DMF', 6, 30, '["Bowling green", "Community centre", "Gardens", "Library", "BBQ areas"]'::jsonb, '["Emergency response"]'::jsonb, '["Bowls", "Social events", "Garden club"]'::jsonb, false, 98, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 157 677', 'peakhurst@irt.org.au', 'https://www.irt.org.au', 'South Sydney retirement village in leafy Peakhurst with spacious villas. Close to Riverwood Plaza and medical facilities.', 'approved', 'admin', true),
('Presbyterian Aged Care Thornleigh', 'Presbyterian Aged Care NSW & ACT', '14 Chilvers Road, Thornleigh NSW 2120', 'Thornleigh', '2120', 'NSW', -33.7328, 151.0789, 'Mixed', 'Mixed', 420000, 580000, 680, 1000, 'DMF', 6, 30, '["Chapel", "Community centre", "Gardens", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing", "Pastoral care"]'::jsonb, '["Chapel services", "Social events", "Garden club"]'::jsonb, true, 76, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9484 2200', 'thornleigh@pac.org.au', 'https://www.pac.org.au', 'Upper North Shore retirement village near Thornleigh station with independent units. Easy train access to city.', 'approved', 'admin', true),
('Uniting Turramurra', 'Uniting', '88 Kissing Point Road, Turramurra NSW 2074', 'Turramurra', '2074', 'NSW', -33.7367, 151.1294, 'Independent Living', 'independent', 680000, 920000, 1040, 1440, 'DMF', 6, 30, '["Pool", "Gym", "Gardens", "Community centre", "Library", "Cinema"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Movies", "Exercise classes", "Social events", "Garden club"]'::jsonb, false, 94, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 864 846', 'turramurra@uniting.org', 'https://www.uniting.org', 'Premium Upper North Shore retirement living in Turramurra with spacious apartments. Walking distance to village shops and station.', 'approved', 'admin', true),
('Ingenia Lifestyle Chain Valley Bay', 'Ingenia Communities', '1 Fishing Point Road, Chain Valley Bay NSW 2259', 'Chain Valley Bay', '2259', 'NSW', -33.1833, 151.5667, 'Independent Living', 'independent', 200000, 360000, 340, 580, 'Site Fees', 0, 0, '["Pool", "Bowling green", "Tennis courts", "Marina", "Lake access", "Community centre"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Bowls", "Tennis", "Boating", "Fishing", "Social events"]'::jsonb, true, 216, ARRAY['2 bedroom', '3 bedroom'], 50, '02 4393 1234', 'chainvalley@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Lake Macquarie over-50s resort community with modern manufactured homes. Perfect for boating and fishing enthusiasts.', 'approved', 'admin', true),
('Baptistcare Morven Gardens', 'BaptistCare', '14 Pennant Hills Road, Carlingford NSW 2118', 'Carlingford', '2118', 'NSW', -33.7811, 151.0461, 'Independent Living', 'independent', 400000, 560000, 640, 960, 'DMF', 6, 30, '["Chapel", "Gardens", "Community centre", "Library", "BBQ areas"]'::jsonb, '["Emergency response"]'::jsonb, '["Chapel services", "Social events", "Garden club"]'::jsonb, true, 102, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9872 3100', 'morvengardens@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Carlingford retirement village near Carlingford Court with comfortable villas. Close to all amenities and medical facilities.', 'approved', 'admin', true),
('Arcare Epping', 'Arcare', '88 Beecroft Road, Epping NSW 2121', 'Epping', '2121', 'NSW', -33.7731, 151.0822, 'Mixed', 'Mixed', 540000, 760000, 840, 1200, 'DMF', 6, 30, '["Gym", "Cinema", "Cafe", "Library", "Gardens"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Movies", "Exercise classes", "Social events", "Cafe dining"]'::jsonb, false, 118, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 272 273', 'epping@arcare.com.au', 'https://www.arcare.com.au', 'North-West Sydney retirement community near Epping station with modern apartments. Metro access to city and Macquarie Park.', 'approved', 'admin', true),
('Regis Aged Care Roseville', 'Regis Aged Care', '12 Hill Street, Roseville NSW 2069', 'Roseville', '2069', 'NSW', -33.7842, 151.1803, 'Mixed', 'Mixed', 580000, 780000, 920, 1280, 'DMF', 6, 30, '["Bowling green", "Community centre", "Gardens", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Bowls", "Social events", "Garden club"]'::jsonb, false, 86, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9416 4100', 'roseville@regis.com.au', 'https://www.regis.com.au', 'North Shore retirement village near Roseville station with quality villas. Quiet leafy location with excellent transport links.', 'approved', 'admin', true),
('Respect Aged Care Eastwood', 'Respect', '42 Rowe Street, Eastwood NSW 2122', 'Eastwood', '2122', 'NSW', -33.7915, 151.0815, 'Mixed', 'Mixed', 480000, 680000, 760, 1080, 'DMF', 6, 30, '["Pool", "Gym", "Community centre", "Gardens", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Exercise classes", "Social events", "Garden club"]'::jsonb, true, 96, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9858 3200', 'eastwood@respect.com.au', 'https://www.respect.com.au', 'Inner-West retirement community near Eastwood station with modern apartments. Walk to Eastwood Plaza, restaurants and shops.', 'approved', 'admin', true),
('Southern Cross Care St Hedwig Village', 'Southern Cross Care', '24 Sunnyholt Road, Blacktown NSW 2148', 'Blacktown', '2148', 'NSW', -33.7686, 150.9069, 'Mixed', 'Mixed', 320000, 470000, 560, 840, 'DMF', 6, 30, '["Chapel", "Bowling green", "Community centre", "Gardens", "Cultural centre"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Bowls", "Chapel services", "Social events", "Cultural activities"]'::jsonb, true, 112, ARRAY['1 bedroom', '2 bedroom', '3 bedroom'], 55, '02 9831 6100', 'blacktown@sccliving.org.au', 'https://www.sccliving.org.au', 'Blacktown retirement community with strong Polish heritage and cultural activities. Close to Westpoint shopping.', 'approved', 'admin', true),
('Adventist Retirement Plus Wahroonga', 'Adventist Retirement Plus', '8 Coonanbarra Road, Wahroonga NSW 2076', 'Wahroonga', '2076', 'NSW', -33.7197, 151.1167, 'Independent Living', 'independent', 520000, 720000, 800, 1120, 'DMF', 6, 30, '["Pool", "Gardens", "Wellness centre", "Community centre", "Walking trails"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Walking", "Social events", "Health programs"]'::jsonb, false, 84, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9473 8200', 'wahroonga@adventistretirementplus.org.au', 'https://www.retirementplus.com.au', 'Upper North Shore retirement village near Wahroonga with health-focused community. Walk to village and San Adventist Hospital.', 'approved', 'admin', true),
('Estia Health Katoomba', 'Estia Health', '88 Lurline Street, Katoomba NSW 2780', 'Katoomba', '2780', 'NSW', -33.7128, 150.3119, 'Mixed', 'Mixed', 280000, 420000, 480, 760, 'DMF', 6, 30, '["Mountain views", "Community centre", "Gardens", "Fireplace lounge", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Social events", "Garden club", "Mountain walks"]'::jsonb, true, 68, ARRAY['1 bedroom', '2 bedroom'], 55, '02 4782 5100', 'katoomba@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Blue Mountains retirement village with stunning mountain views and cosy villas. Enjoy crisp mountain air and village charm.', 'approved', 'admin', true),
('Bupa Aged Care Camden', 'Bupa', '1 Argyle Street, Camden NSW 2570', 'Camden', '2570', 'NSW', -34.0544, 150.6956, 'Mixed', 'Mixed', 380000, 560000, 640, 960, 'DMF', 6, 30, '["Pool", "Gym", "Cinema", "Community centre", "Gardens"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Movies", "Exercise classes", "Social events"]'::jsonb, false, 142, ARRAY['1 bedroom', '2 bedroom', '3 bedroom'], 55, '1300 280 334', 'camden@bupa.com.au', 'https://www.bupa.com.au', 'Macarthur region retirement community in growing Camden with modern villas. Near new Camden Hospital and shopping precinct.', 'approved', 'admin', true),
('Allity Ryde', 'Allity', '88 Devlin Street, Ryde NSW 2112', 'Ryde', '2112', 'NSW', -33.8150, 151.1028, 'Mixed', 'Mixed', 520000, 720000, 800, 1160, 'DMF', 6, 30, '["Pool", "Gym", "Rooftop terrace", "Library", "Gardens"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Exercise classes", "Social events"]'::jsonb, false, 108, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9807 3100', 'ryde@allity.com.au', 'https://www.allity.com.au', 'Inner-West retirement living near Top Ryde Shopping Centre with contemporary apartments. Excellent bus and train connections.', 'approved', 'admin', true),
('Bolton Clarke Hornsby', 'Bolton Clarke', '12 Peats Ferry Road, Hornsby NSW 2077', 'Hornsby', '2077', 'NSW', -33.7039, 151.0989, 'Mixed', 'Mixed', 480000, 680000, 760, 1080, 'DMF', 6, 30, '["Pool", "Bowling green", "Community centre", "Gardens", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Bowls", "Social events", "Garden club"]'::jsonb, false, 124, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 228 655', 'hornsby@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Upper North Shore retirement village near Hornsby Hospital with quality villas. Close to Westfield Hornsby and train station.', 'approved', 'admin', true),
('Villa Maria Catholic Homes Westmead', 'Villa Maria Catholic Homes', '88 Hawkesbury Road, Westmead NSW 2145', 'Westmead', '2145', 'NSW', -33.8067, 150.9875, 'Mixed', 'Mixed', 420000, 600000, 680, 1000, 'DMF', 6, 30, '["Chapel", "Gardens", "Community centre", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing", "Pastoral care"]'::jsonb, '["Chapel services", "Social events", "Garden club"]'::jsonb, true, 92, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9891 4200', 'westmead@vmch.com.au', 'https://www.vmch.com.au', 'Parramatta region retirement community near Westmead Hospital precinct with independent villas. Excellent medical facilities nearby.', 'approved', 'admin', true),
('Japara Roslyn Park', 'Japara', '88 Chapel Road, Bankstown NSW 2200', 'Bankstown', '2200', 'NSW', -33.9186, 151.0344, 'Mixed', 'Mixed', 360000, 530000, 600, 920, 'DMF', 6, 30, '["Community centre", "Gardens", "Cultural centre", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Social events", "Garden club", "Cultural activities"]'::jsonb, true, 104, ARRAY['1 bedroom', '2 bedroom'], 55, '1800 52 72 72', 'bankstown@japara.com.au', 'https://www.japara.com.au', 'Bankstown retirement community with multicultural atmosphere and modern villas. Close to Bankstown Central and medical facilities.', 'approved', 'admin', true),
('Tricare West Pennant Hills', 'Tricare', '88 Coonara Avenue, West Pennant Hills NSW 2125', 'West Pennant Hills', '2125', 'NSW', -33.7483, 151.0378, 'Mixed', 'Mixed', 480000, 680000, 760, 1080, 'DMF', 6, 30, '["Bowling green", "Bushland setting", "Community centre", "Gardens"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Bowls", "Social events", "Garden club", "Bush walks"]'::jsonb, false, 86, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9484 6100', 'westpennant@tricare.com.au', 'https://www.tricare.com.au', 'Hills District retirement village in peaceful West Pennant Hills with spacious villas. Close to Cherrybrook Village and Castle Hill.', 'approved', 'admin', true),
('Mayflower Hunters Hill', 'Mayflower', '14 Woolwich Road, Hunters Hill NSW 2110', 'Hunters Hill', '2110', 'NSW', -33.8325, 151.1450, 'Independent Living', 'independent', 780000, 1080000, 1120, 1560, 'DMF', 6, 30, '["Harbour views", "Gardens", "Community centre", "Library", "Village atmosphere"]'::jsonb, '["Emergency response"]'::jsonb, '["Social events", "Garden club", "Harbour walks"]'::jsonb, false, 52, ARRAY['2 bedroom', '3 bedroom'], 55, '02 9817 4200', 'huntershil@mayflower.org.au', 'https://www.mayflower.org.au', 'Exclusive harbourside retirement village in prestigious Hunters Hill with luxury villas. Walk to harbour foreshore and boutique shops.', 'approved', 'admin', true),

-- 24. RSL LifeCare Narrabeen
('RSL LifeCare Narrabeen', 'RSL LifeCare', '88 Ocean Street, Narrabeen NSW 2101', 'Narrabeen', '2101', 'NSW', -33.7165, 151.2963, 'Mixed', 'Mixed', 580000, 820000, 880, 1240, 'DMF', 6, 30, '["Lake views", "Bowling green", "Community centre", "Gardens"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing", "Veterans services"]'::jsonb, '["Bowls", "Social events", "Garden club", "RSL activities"]'::jsonb, true, 116, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9913 4100', 'narrabeen@rsllifecare.org.au', 'https://www.rsllifecare.org.au', 'Northern Beaches retirement living near Narrabeen Lake with villas and apartments. Short walk to beaches and Sports Centre.', 'approved', 'admin', true),

-- 25. NewDirection Care Concord
('NewDirection Care Concord', 'NewDirection Care', '22 Wellbank Street, Concord NSW 2137', 'Concord', '2137', 'NSW', -33.8514, 151.0971, 'Mixed', 'Mixed', 520000, 720000, 800, 1160, 'DMF', 6, 30, '["Pool", "Community centre", "Gardens", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Social events", "Garden club", "River walks"]'::jsonb, false, 98, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9743 3100', 'concord@newdirection.com.au', 'https://www.newdirection.com.au', 'Inner-West retirement community near Concord Hospital with modern apartments. Walk to shops, restaurants and Parramatta River.', 'approved', 'admin', true);