-- NSW Batch 12: 50 Mixed Regional NSW Retirement Villages (CORRECTED - FINAL NSW BATCH)
-- Geographic Focus: Filling gaps across all NSW regions
-- Ready to import via Supabase SQL Editor

INSERT INTO retirement_villages (
  name,
  operator,
  location,
  suburb,
  postcode,
  state,
  latitude,
  longitude,
  village_type,
  care_level,
  entry_price_min,
  entry_price_max,
  monthly_fees_min,
  monthly_fees_max,
  dmf_structure,
  dmf_percentage,
  dmf_cap,
  amenities,
  care_services,
  activities,
  pet_friendly,
  total_units,
  bedrooms,
  age_restriction,
  contact_phone,
  contact_email,
  website,
  description,
  status,
  source,
  verified
) VALUES

-- 1. Aveo Newmarket Merrylands
('Aveo Newmarket Merrylands', 'Aveo Group', '88 Pitt Street, Merrylands NSW 2160', 'Merrylands', '2160', 'NSW', -33.8339, 150.9878, 'Independent Living', 'independent', 380000, 560000, 640, 960, 'DMF', 6, 30, '["Pool", "Gym", "Cinema", "Community centre", "Gardens"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Movies", "Exercise classes", "Social events"]'::jsonb, false, 132, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 283 000', 'merrylands@aveo.com.au', 'https://www.aveo.com.au', 'Western Sydney retirement community near Merrylands station with contemporary apartments. Pool, gym and cinema. Walk to shopping, restaurants and medical facilities. Multicultural friendly.', 'approved', 'admin', true),

-- 2. Stockland Glendale
('Stockland Glendale', 'Stockland', '1 Lake Road, Glendale NSW 2285', 'Glendale', '2285', 'NSW', -32.9369, 151.6431, 'Independent Living', 'independent', 340000, 520000, 600, 920, 'DMF', 6, 30, '["Pool", "Bowling green", "Cinema", "Community centre", "Gardens"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Bowls", "Movies", "Social events"]'::jsonb, false, 158, ARRAY['2 bedroom', '3 bedroom'], 55, '1800 550 550', 'glendale@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Lake Macquarie retirement village near Glendale shopping with modern villas and resort amenities. Close to major shopping centre and medical facilities.', 'approved', 'admin', true),

-- 3. Lendlease Greenwich
('Lendlease Greenwich', 'Lendlease', '42 River Road, Greenwich NSW 2065', 'Greenwich', '2065', 'NSW', -33.8267, 151.1836, 'Independent Living', 'independent', 680000, 920000, 1040, 1440, 'DMF', 6, 30, '["Harbour glimpses", "Bowling green", "Gardens", "Community centre", "Village atmosphere"]'::jsonb, '["Emergency response"]'::jsonb, '["Bowls", "Social events", "Garden club", "River walks"]'::jsonb, false, 64, ARRAY['2 bedroom', '3 bedroom'], 55, '1300 326 033', 'greenwich@lendlease.com', 'https://www.lendlease.com/au/retirement', 'North Shore harbourside retirement village with premium villas and harbour glimpses. Walk to Greenwich village shops and Lane Cove River. Prestige location.', 'approved', 'admin', true),

-- 4. Anglicare Dubbo
('Anglicare Dubbo', 'Anglicare', '88 Cobra Street, Dubbo NSW 2830', 'Dubbo', '2830', 'NSW', -32.2569, 148.6011, 'Mixed', 'Mixed', 210000, 350000, 360, 660, 'DMF', 6, 30, '["Chapel", "Bowling green", "Community centre", "Gardens"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Chapel services", "Bowls", "Social events", "Garden club"]'::jsonb, true, 96, ARRAY['1 bedroom', '2 bedroom'], 55, '02 6882 3100', 'dubbo@anglicare.org.au', 'https://www.anglicare.org.au', 'Central West retirement village in regional Dubbo with comfortable villas, chapel and community facilities. Close to Base Hospital and shopping centres. Affordable regional living.', 'approved', 'admin', true),

-- 5. IRT Kangara Waters
('IRT Kangara Waters', 'IRT Group', '42 Waterfall Way, Bellingen NSW 2454', 'Bellingen', '2454', 'NSW', -30.4528, 152.8989, 'Independent Living', 'independent', 280000, 430000, 480, 780, 'DMF', 6, 30, '["Pool", "Bowling green", "River views", "Community centre", "Gardens"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Bowls", "Social events", "Garden club"]'::jsonb, false, 74, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 157 677', 'bellingen@irt.org.au', 'https://www.irt.org.au', 'South Coast retirement resort at Bellingen with spacious villas near Bellingen River and beautiful valley. Explore artistic village and coastal access.', 'approved', 'admin', true),

-- 6. Uniting Willoughby
('Uniting Willoughby', 'Uniting', '88 Penshurst Street, Willoughby NSW 2068', 'Willoughby', '2068', 'NSW', -33.8036, 151.1972, 'Independent Living', 'independent', 560000, 780000, 880, 1240, 'DMF', 6, 30, '["Pool", "Gym", "Community centre", "Library", "Urban location"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Exercise classes", "Social events", "Shopping trips"]'::jsonb, false, 104, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 864 846', 'willoughby@uniting.org', 'https://www.uniting.org', 'North Shore retirement community near Chatswood with modern apartments and city access. Walk to Willoughby shopping and transport. Easy city and beach connections.', 'approved', 'admin', true),

-- 7. Opal Aged Care Dee Why
('Opal Aged Care Dee Why', 'Opal Aged Care', '22 The Strand, Dee Why NSW 2099', 'Dee Why', '2099', 'NSW', -33.7533, 151.2886, 'Mixed', 'Mixed', 620000, 880000, 960, 1360, 'DMF', 6, 30, '["Pool", "Ocean views", "Beach access", "Community centre"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Beach walks", "Social events", "Cafe visits"]'::jsonb, false, 92, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 672 524', 'deewhy@opalaged.care', 'https://www.opalagedcare.com.au', 'Northern Beaches beachside retirement living with contemporary apartments near Dee Why Beach and Grand shopping. Walk to beach, cafes and lagoon. Premium location.', 'approved', 'admin', true),

-- 8. Presbyterian Aged Care Queanbeyan
('Presbyterian Aged Care Queanbeyan', 'Presbyterian Aged Care NSW & ACT', '88 Yass Road, Queanbeyan NSW 2620', 'Queanbeyan', '2620', 'NSW', -35.3481, 149.2319, 'Mixed', 'Mixed', 280000, 430000, 480, 780, 'DMF', 6, 30, '["Chapel", "Community centre", "Gardens", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Chapel services", "Social events", "Garden club"]'::jsonb, true, 86, ARRAY['1 bedroom', '2 bedroom'], 55, '02 6299 3100', 'queanbeyan@pac.org.au', 'https://www.pac.org.au', 'Southern border retirement village near Canberra with comfortable villas, chapel and community centre. Close to shops, medical facilities and Australian capital.', 'approved', 'admin', true),

-- 9. Baptistcare Warabrook
('Baptistcare Warabrook', 'BaptistCare', '42 Newcastle Road, Warabrook NSW 2304', 'Warabrook', '2304', 'NSW', -32.8994, 151.7189, 'Independent Living', 'independent', 340000, 510000, 600, 920, 'DMF', 6, 30, '["Chapel", "Community centre", "Gardens", "Bowling green"]'::jsonb, '["Emergency response"]'::jsonb, '["Chapel services", "Bowls", "Social events", "Garden club"]'::jsonb, false, 98, ARRAY['1 bedroom', '2 bedroom', '3 bedroom'], 55, '02 4968 3100', 'warabrook@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Newcastle suburb retirement village near University with modern villas, chapel and community facilities. Close to John Hunter Hospital, Westfield Kotara and Hunter Stadium.', 'approved', 'admin', true),

-- 10. Regis Aged Care Bangalow
('Regis Aged Care Bangalow', 'Regis Aged Care', '42 Byron Street, Bangalow NSW 2479', 'Bangalow', '2479', 'NSW', -28.6831, 153.5244, 'Mixed', 'Mixed', 380000, 580000, 640, 1000, 'DMF', 6, 30, '["Village atmosphere", "Gardens", "Community centre", "Arts culture"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Social events", "Garden club", "Arts programs", "Farmers market"]'::jsonb, false, 68, ARRAY['1 bedroom', '2 bedroom'], 55, '02 6687 3100', 'bangalow@regis.com.au', 'https://www.regis.com.au', 'Byron Bay hinterland retirement village with charming villas in artistic Bangalow village. Walk to cafes, galleries and farmers market. Bohemian hinterland lifestyle.', 'approved', 'admin', true),

-- 11. Respect Aged Care Muswellbrook
('Respect Aged Care Muswellbrook', 'Respect', '88 Bridge Street, Muswellbrook NSW 2333', 'Muswellbrook', '2333', 'NSW', -32.2664, 150.8889, 'Mixed', 'Mixed', 190000, 330000, 340, 620, 'DMF', 6, 30, '["Bowling green", "Community centre", "Gardens"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Bowls", "Social events", "Garden club", "Winery tours"]'::jsonb, true, 74, ARRAY['1 bedroom', '2 bedroom'], 55, '02 6543 3100', 'muswellbrook@respect.com.au', 'https://www.respect.com.au', 'Upper Hunter retirement village in coal mining town with affordable villas and community centre. Close to shopping, medical facilities and Hunter Valley wineries.', 'approved', 'admin', true),

-- 12. Southern Cross Care Broken Hill
('Southern Cross Care Broken Hill', 'Southern Cross Care', '42 Argent Street, Broken Hill NSW 2880', 'Broken Hill', '2880', 'NSW', -31.9581, 141.4653, 'Mixed', 'Mixed', 160000, 280000, 300, 560, 'DMF', 6, 30, '["Chapel", "Community centre", "Gardens", "Desert setting"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Chapel services", "Social events", "Garden club", "Mining history"]'::jsonb, true, 56, ARRAY['1 bedroom', '2 bedroom'], 55, '08 8088 3100', 'brokenhill@sccliving.org.au', 'https://www.sccliving.org.au', 'Outback NSW retirement village in historic mining city with comfortable villas in desert setting. Close to all regional services and Barrier Medical Centre.', 'approved', 'admin', true),

-- 13. Adventist Retirement Plus Stuarts Point
('Adventist Retirement Plus Stuarts Point', 'Adventist Retirement Plus', '88 River Drive, Stuarts Point NSW 2441', 'Stuarts Point', '2441', 'NSW', -30.9447, 153.0644, 'Independent Living', 'independent', 260000, 410000, 460, 760, 'DMF', 6, 30, '["Pool", "River access", "Beach access", "Gardens", "Fishing"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Fishing", "Boating", "Beach walks", "Social events"]'::jsonb, false, 72, ARRAY['1 bedroom', '2 bedroom'], 55, '02 6569 9200', 'stuartspoint@adventistretirementplus.org.au', 'https://www.retirementplus.com.au', 'Mid North Coast river and beach retirement village with peaceful villas at Macleay River mouth. Perfect fishing, boating and beach lifestyle. Pristine coastal location.', 'approved', 'admin', true),

-- 14. Estia Health Liverpool
('Estia Health Liverpool', 'Estia Health', '88 Moore Street, Liverpool NSW 2170', 'Liverpool', '2170', 'NSW', -33.9236, 150.9239, 'Mixed', 'Mixed', 380000, 560000, 640, 960, 'DMF', 6, 30, '["Pool", "Gym", "Community centre", "Urban location"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Exercise classes", "Social events", "Shopping trips"]'::jsonb, false, 126, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9602 3100', 'liverpool@estiahealth.com.au', 'https://www.estiahealth.com.au', 'South-West Sydney retirement community near Liverpool Hospital with modern apartments. Walk to Liverpool CBD, Westfield shopping and transport hub. Urban retirement living.', 'approved', 'admin', true),

-- 15. Bupa Aged Care Ballina Beach
('Bupa Aged Care Ballina Beach', 'Bupa', '88 Ocean Avenue, Ballina NSW 2478', 'Ballina', '2478', 'NSW', -28.8656, 153.5633, 'Mixed', 'Mixed', 340000, 520000, 600, 920, 'DMF', 6, 30, '["Pool", "Ocean breeze", "Beach access", "Community centre"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Beach walks", "Social events", "Garden club"]'::jsonb, true, 94, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 280 334', 'ballinabeach@bupa.com.au', 'https://www.bupa.com.au', 'North Coast beachside retirement near Ballina beaches with modern villas and ocean breeze. Minutes to Ballina shops and Byron Bay.', 'approved', 'admin', true),

-- 16. Allity Sutherland
('Allity Sutherland', 'Allity', '42 The Kingsway, Sutherland NSW 2232', 'Sutherland', '2232', 'NSW', -34.0311, 151.0564, 'Mixed', 'Mixed', 420000, 620000, 680, 1040, 'DMF', 6, 30, '["Pool", "Community centre", "Gardens", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Social events", "Garden club", "Shopping trips"]'::jsonb, false, 108, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9521 3100', 'sutherland@allity.com.au', 'https://www.allity.com.au', 'Sutherland Shire retirement community near Cronulla beaches with contemporary apartments. Walk to Sutherland station, shops and medical facilities. Easy beach and city access.', 'approved', 'admin', true),

-- 17. Bolton Clarke Moree
('Bolton Clarke Moree', 'Bolton Clarke', '88 Balo Street, Moree NSW 2400', 'Moree', '2400', 'NSW', -29.4647, 149.8431, 'Mixed', 'Mixed', 180000, 310000, 320, 600, 'DMF', 6, 30, '["Artesian spa", "Bowling green", "Community centre", "Gardens"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Spa activities", "Bowls", "Social events", "Garden club"]'::jsonb, true, 68, ARRAY['1 bedroom', '2 bedroom'], 55, '02 6752 3100', 'moree@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'North-West Plains retirement village in Moree with comfortable villas and hot artesian spa water. Enjoy therapeutic spa town lifestyle and warm climate.', 'approved', 'admin', true),

-- 18. Villa Maria Catholic Homes Bexley
('Villa Maria Catholic Homes Bexley', 'Villa Maria Catholic Homes', '88 Forest Road, Bexley NSW 2207', 'Bexley', '2207', 'NSW', -33.9506, 151.1192, 'Mixed', 'Mixed', 420000, 600000, 680, 1040, 'DMF', 6, 30, '["Chapel", "Community centre", "Gardens", "Library"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing", "Pastoral care"]'::jsonb, '["Chapel services", "Social events", "Garden club"]'::jsonb, true, 76, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9567 3100', 'bexley@vmch.com.au', 'https://www.vmch.com.au', 'South Sydney retirement village near Rockdale with Catholic community, chapel and pastoral care. Close to Rockdale Plaza and medical facilities.', 'approved', 'admin', true),

-- 19. Japara The Lodge Narrabri
('Japara The Lodge Narrabri', 'Japara', '42 Doyle Street, Narrabri NSW 2390', 'Narrabri', '2390', 'NSW', -30.3278, 149.7828, 'Mixed', 'Mixed', 170000, 300000, 300, 580, 'DMF', 6, 30, '["Bowling green", "Community centre", "Gardens"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Bowls", "Social events", "Garden club"]'::jsonb, true, 62, ARRAY['1 bedroom', '2 bedroom'], 55, '1800 52 72 72', 'narrabri@japara.com.au', 'https://www.japara.com.au', 'North-West Plains retirement village in Narrabri with affordable villas and bowling green. Close to regional services and Namoi Valley. Warm climate country living.', 'approved', 'admin', true),

-- 20. Tricare Woy Woy
('Tricare Woy Woy', 'Tricare', '88 The Boulevard, Woy Woy NSW 2256', 'Woy Woy', '2256', 'NSW', -33.4858, 151.3233, 'Mixed', 'Mixed', 380000, 580000, 640, 1000, 'DMF', 6, 30, '["Pool", "Water views", "Waterfront walks", "Community centre"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Social events", "Waterfront walks", "Shopping trips"]'::jsonb, false, 112, ARRAY['1 bedroom', '2 bedroom'], 55, '02 4341 3100', 'woywoy@tricare.com.au', 'https://www.tricare.com.au', 'Central Coast waterfront retirement village with modern apartments and Brisbane Water views. Walk to Woy Woy shops, station and Ettalong Beach.', 'approved', 'admin', true),

-- 21. Mayflower Sans Souci
('Mayflower Sans Souci', 'Mayflower', '88 Rocky Point Road, Sans Souci NSW 2219', 'Sans Souci', '2219', 'NSW', -33.9906, 151.1358, 'Independent Living', 'independent', 480000, 680000, 760, 1120, 'DMF', 6, 30, '["Bowling green", "Bay breeze", "Beach access", "Community centre", "Gardens"]'::jsonb, '["Emergency response"]'::jsonb, '["Bowls", "Beach walks", "Social events", "Garden club"]'::jsonb, false, 84, ARRAY['2 bedroom', '3 bedroom'], 55, '02 9529 1234', 'sanssouci@mayflower.org.au', 'https://www.mayflower.org.au', 'Bayside retirement village near Sans Souci beaches with comfortable villas and bay breeze. Walk to Ramsgate Beach and shops. Relaxed bayside lifestyle.', 'approved', 'admin', true),

-- 22. RSL LifeCare Tweed Valley
('RSL LifeCare Tweed Valley', 'RSL LifeCare', '88 Tweed Valley Way, Murwillumbah NSW 2484', 'Murwillumbah', '2484', 'NSW', -28.3297, 153.3989, 'Mixed', 'Mixed', 280000, 430000, 480, 780, 'DMF', 6, 30, '["River views", "Mountain views", "Bowling green", "RSL services"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing", "Veterans services"]'::jsonb, '["Bowls", "RSL activities", "Social events", "Garden club"]'::jsonb, true, 96, ARRAY['1 bedroom', '2 bedroom'], 55, '02 6672 4100', 'tweedvalley@rsllifecare.org.au', 'https://www.rsllifecare.org.au', 'Far North Coast retirement village near Tweed River with villas, river views and mountain backdrop. Close to Kingscliff beaches and Tweed Heads.', 'approved', 'admin', true),

-- 23. Ingenia Lifestyle Soldiers Point Marina
('Ingenia Lifestyle Soldiers Point Marina', 'Ingenia Communities', '42 Koala Circuit, Soldiers Point NSW 2317', 'Soldiers Point', '2317', 'NSW', -32.7175, 152.0664, 'Independent Living', 'independent', 280000, 480000, 440, 720, 'Site Fees', 0, 0, '["Pool", "Marina", "Boat ramp", "Clubhouse", "Fishing", "Dolphin watching"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Boating", "Fishing", "Dolphin watching", "Social events"]'::jsonb, true, 186, ARRAY['2 bedroom', '3 bedroom'], 50, '02 4919 4200', 'soldiersmarina@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Port Stephens waterfront over-50s resort with premium manufactured homes and marina berths. Dolphin watching and pristine beaches. Ultimate water lifestyle.', 'approved', 'admin', true),

-- 24. NewDirection Care Gosford
('NewDirection Care Gosford', 'NewDirection Care', '88 Mann Street, Gosford NSW 2250', 'Gosford', '2250', 'NSW', -33.4269, 151.3419, 'Mixed', 'Mixed', 380000, 580000, 640, 1000, 'DMF', 6, 30, '["Pool", "Gym", "Community centre", "Urban location"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Swimming", "Exercise classes", "Social events", "Waterfront walks"]'::jsonb, false, 124, ARRAY['1 bedroom', '2 bedroom'], 55, '02 4323 3100', 'gosford@newdirection.com.au', 'https://www.newdirection.com.au', 'Central Coast city retirement community with modern apartments near Gosford Hospital and Kibble Park. Walk to waterfront, shops and train station. Urban coastal convenience.', 'approved', 'admin', true),

-- 25. Arcare Glen Innes
('Arcare Glen Innes', 'Arcare', '88 Grey Street, Glen Innes NSW 2370', 'Glen Innes', '2370', 'NSW', -29.7400, 151.7369, 'Mixed', 'Mixed', 200000, 340000, 360, 660, 'DMF', 6, 30, '["Gardens", "Community centre", "Celtic heritage", "Cool climate"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Social events", "Garden club", "Heritage tours", "Cultural programs"]'::jsonb, true, 64, ARRAY['1 bedroom', '2 bedroom'], 55, '1300 272 273', 'gleninnes@arcare.com.au', 'https://www.arcare.com.au', 'New England highlands retirement village with Celtic heritage and cool climate villas. Close to standing stones and regional services with four seasons.', 'approved', 'admin', true),

-- 26. Heritage Care Moss Vale
('Heritage Care Moss Vale', 'Heritage Care', '42 Argyle Street, Moss Vale NSW 2577', 'Moss Vale', '2577', 'NSW', -34.5481, 150.3719, 'Independent Living', 'independent', 340000, 510000, 600, 920, 'DMF', 6, 30, '["Heritage style", "Gardens", "Community centre", "Village atmosphere", "Library"]'::jsonb, '["Emergency response"]'::jsonb, '["Social events", "Garden club", "Cafe visits"]'::jsonb, false, 72, ARRAY['2 bedroom', '3 bedroom'], 55, '02 4868 1234', 'mossvale@heritagecare.com.au', 'https://www.heritagecare.com.au', 'Southern Highlands retirement village in charming Moss Vale with heritage-style villas and cool climate gardens. Walk to shops, cafes and medical facilities.', 'approved', 'admin', true),

-- 27. Aurrum Pymble
('Aurrum Pymble', 'Aurrum', '88 Grandview Street, Pymble NSW 2073', 'Pymble', '2073', 'NSW', -33.7464, 151.1397, 'Independent Living', 'independent', 720000, 1020000, 1120, 1560, 'DMF', 6, 30, '["Pool", "Gym", "Cinema", "Fine dining", "Concierge", "Rooftop terrace"]'::jsonb, '["Emergency response", "Concierge"]'::jsonb, '["Swimming", "Movies", "Exercise classes", "Fine dining", "Social events"]'::jsonb, false, 96, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9488 4200', 'pymble@aurrum.com.au', 'https://www.aurrum.com.au', 'Upper North Shore premium retirement village with luxury apartments and resort amenities. Walk to Pymble station and village. Five-star retirement living.', 'approved', 'admin', true),

-- 28. Peninsula Villages Umina Waters
('Peninsula Villages Umina Waters', 'Peninsula Villages', '1 The Corso, Umina Beach NSW 2257', 'Umina Beach', '2257', 'NSW', -33.5264, 151.3114, 'Independent Living', 'independent', 480000, 720000, 760, 1120, 'DMF', 6, 30, '["Pool", "Gym", "Bowling green", "Ocean views", "Marina", "Beach access"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Exercise classes", "Bowls", "Boating", "Beach walks", "Social events"]'::jsonb, false, 142, ARRAY['2 bedroom', '3 bedroom'], 55, '02 4344 9300', 'uminawaters@peninsulavillages.com.au', 'https://www.peninsulavillages.com.au', 'Central Coast waterfront retirement resort with premium villas, ocean and coastal lagoon views. Walk to Umina Beach and shops. Premier coastal lifestyle.', 'approved', 'admin', true),

-- 29. Bluetree Salamander Bay
('Bluetree Salamander Bay', 'Bluetree Group', '88 Soldiers Point Road, Salamander Bay NSW 2317', 'Salamander Bay', '2317', 'NSW', -32.7206, 152.0728, 'Independent Living', 'independent', 420000, 640000, 680, 1040, 'DMF', 6, 30, '["Pool", "Gym", "Bay views", "Beach access", "Community centre"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Exercise classes", "Beach walks", "Social events"]'::jsonb, false, 108, ARRAY['1 bedroom', '2 bedroom'], 55, '02 4981 1234', 'salamander@bluetree.com.au', 'https://www.bluetree.com.au', 'Port Stephens waterfront retirement living with modern apartments and bay views. Walk to Salamander Shopping Centre and beaches. Perfect coastal location.', 'approved', 'admin', true),

-- 30. Embracia Narooma
('Embracia Narooma', 'Embracia Health', '88 Princes Highway, Narooma NSW 2546', 'Narooma', '2546', 'NSW', -36.2153, 150.1294, 'Mixed', 'Mixed', 280000, 430000, 480, 780, 'DMF', 6, 30, '["Ocean views", "Community centre", "Gardens", "Coastal walks"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Social events", "Garden club", "Coastal walks", "Fishing"]'::jsonb, false, 64, ARRAY['1 bedroom', '2 bedroom'], 55, '02 4476 3100', 'narooma@embracia.com.au', 'https://www.embracia.com.au', 'Far South Coast retirement village with ocean views and comfortable villas near pristine beaches and Wagonga Inlet. Perfect fishing and oyster capital lifestyle.', 'approved', 'admin', true),

-- 31. Greengate Epping
('Greengate Epping', 'Independent Operator', '42 Oxford Street, Epping NSW 2121', 'Epping', '2121', 'NSW', -33.7733, 151.0819, 'Independent Living', 'independent', 520000, 720000, 800, 1160, 'DMF', 6, 30, '["Gardens", "Community centre", "Village atmosphere", "Metro access"]'::jsonb, '["Emergency response"]'::jsonb, '["Social events", "Garden club", "Shopping trips"]'::jsonb, false, 56, ARRAY['2 bedroom', '3 bedroom'], 55, '02 9876 1234', 'epping@greengatevillage.com.au', 'https://www.greengatevillage.com.au', 'North-West Sydney retirement village near Epping station with boutique villas and established gardens. Walk to Epping shops and Metro. Easy city and Macquarie Park access.', 'approved', 'admin', true),

-- 32. Watermark Miranda
('Watermark Miranda', 'Watermark', '88 The Kingsway, Miranda NSW 2228', 'Miranda', '2228', 'NSW', -34.0344, 151.1014, 'Independent Living', 'independent', 480000, 680000, 760, 1120, 'DMF', 6, 30, '["Pool", "Gym", "Community centre", "Shopping access", "Gardens"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Exercise classes", "Social events", "Shopping trips"]'::jsonb, false, 116, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9524 1234', 'miranda@watermark.com.au', 'https://www.watermark.com.au', 'Sutherland Shire retirement community near Westfield Miranda with contemporary apartments. Walk to major shopping, library and medical facilities. Easy beach and city connections.', 'approved', 'admin', true),

-- 33. Summerset Hunters Hill Marina
('Summerset Hunters Hill Marina', 'Summerset', '1 Woolwich Road, Hunters Hill NSW 2110', 'Hunters Hill', '2110', 'NSW', -33.8328, 151.1500, 'Independent Living', 'independent', 880000, 1280000, 1280, 1800, 'DMF', 6, 30, '["Marina berths", "Harbour views", "Pool", "Gym", "Concierge", "Fine dining"]'::jsonb, '["Emergency response", "Concierge"]'::jsonb, '["Boating", "Swimming", "Exercise classes", "Fine dining", "Social events", "Harbour walks"]'::jsonb, false, 48, ARRAY['2 bedroom', '3 bedroom'], 55, '02 9817 9200', 'huntershill@summerset.net.au', 'https://www.summerset.com.au', 'Exclusive harbourside retirement village with marina berths and premium villas overlooking harbour and city. Walk to village shops and harbour foreshore. Prestige location.', 'approved', 'admin', true),

-- 34. Resthaven Katoomba Heights
('Resthaven Katoomba Heights', 'Resthaven', '88 Cliff Drive, Katoomba NSW 2780', 'Katoomba', '2780', 'NSW', -33.7128, 150.3125, 'Independent Living', 'independent', 300000, 450000, 520, 840, 'DMF', 6, 30, '["Mountain views", "Fireplace lounge", "Gardens", "Bushwalks", "Community centre"]'::jsonb, '["Emergency response"]'::jsonb, '["Bushwalking", "Social events", "Garden club", "Tourist activities"]'::jsonb, false, 68, ARRAY['1 bedroom', '2 bedroom'], 55, '02 4782 9200', 'katoomba@resthaven.asn.au', 'https://www.resthaven.asn.au', 'Blue Mountains retirement village with spectacular views and cosy villas perfect for cool climate lovers. Explore bushwalks and tourist attractions.', 'approved', 'admin', true),

-- 35. Mercy Health Albury
('Mercy Health Albury', 'Mercy Health', '88 Wodonga Place, Albury NSW 2640', 'Albury', '2640', 'NSW', -36.0806, 146.9158, 'Mixed', 'Mixed', 260000, 410000, 460, 760, 'DMF', 6, 30, '["Chapel", "Pool", "Community centre", "Gardens"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing", "Pastoral care"]'::jsonb, '["Chapel services", "Swimming", "Social events", "Garden club"]'::jsonb, true, 94, ARRAY['1 bedroom', '2 bedroom'], 55, '02 6021 3100', 'albury@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Border city retirement community with Catholic heritage and modern villas. Close to Albury Base Hospital and shopping centres.', 'approved', 'admin', true),

-- 36. Calvary Retirement Community Kogarah
('Calvary Retirement Community Kogarah', 'Calvary', '88 Rocky Point Road, Kogarah NSW 2217', 'Kogarah', '2217', 'NSW', -33.9661, 151.1339, 'Mixed', 'Mixed', 480000, 680000, 760, 1120, 'DMF', 6, 30, '["Chapel", "Community centre", "Gardens", "Hospital access"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing", "Pastoral care"]'::jsonb, '["Chapel services", "Social events", "Garden club"]'::jsonb, true, 102, ARRAY['1 bedroom', '2 bedroom'], 55, '02 9587 9200', 'kogarah@calvarycare.org.au', 'https://www.calvarycare.org.au', 'South Sydney retirement village near St George Hospital with Catholic community and chapel. Walk to Kogarah station and shops.', 'approved', 'admin', true),

-- 37. Goodwin Aged Care Services Dubbo West
('Goodwin Aged Care Services Dubbo West', 'Goodwin', '42 Myall Street, Dubbo NSW 2830', 'Dubbo', '2830', 'NSW', -32.2578, 148.5994, 'Mixed', 'Mixed', 190000, 330000, 340, 640, 'DMF', 6, 30, '["Bowling green", "Community centre", "Gardens"]'::jsonb, '["Emergency response", "Aged care", "24/7 nursing"]'::jsonb, '["Bowls", "Social events", "Garden club"]'::jsonb, true, 78, ARRAY['1 bedroom', '2 bedroom'], 55, '02 6884 1234', 'dubbo@goodwin.org.au', 'https://www.goodwin.org.au', 'Central West retirement community with affordable villas and bowling green. Close to Dubbo shopping and medical facilities. Regional living with quality healthcare access.', 'approved', 'admin', true),

-- 38. Lifestyle Communities Shoalhaven
('Lifestyle Communities Shoalhaven', 'Lifestyle Communities', '1 Shoalhaven Drive, North Nowra NSW 2541', 'North Nowra', '2541', 'NSW', -34.8639, 150.5981, 'Independent Living', 'independent', 240000, 400000, 360, 620, 'Site Fees', 0, 0, '["Pool", "Bowling green", "Gym", "Clubhouse", "Gardens"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Bowls", "Exercise classes", "Social events", "Garden club"]'::jsonb, true, 164, ARRAY['2 bedroom', '3 bedroom'], 50, '02 4421 9200', 'shoalhaven@lifestylecommunities.com.au', 'https://www.lifestylecommunities.com.au', 'South Coast over-50s community near Nowra with modern manufactured homes and resort facilities. Close to beaches and shopping. Affordable coastal retirement.', 'approved', 'admin', true),

-- 39. Living Choice Broadwater
('Living Choice Broadwater', 'Living Choice', '1 Lakewood Boulevard, Broadwater NSW 2472', 'Broadwater', '2472', 'NSW', -28.8192, 153.4256, 'Independent Living', 'independent', 420000, 640000, 680, 1040, 'DMF', 6, 30, '["Pool", "Gym", "Cinema", "Bowling green", "Resort facilities"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Movies", "Exercise classes", "Bowls", "Social events"]'::jsonb, false, 186, ARRAY['2 bedroom', '3 bedroom'], 55, '02 6683 9200', 'broadwater@livingchoice.com.au', 'https://www.livingchoice.com.au', 'Mid North Coast retirement resort near Port Macquarie with premium villas and resort amenities. Minutes to beaches and town centre. Five-star facilities.', 'approved', 'admin', true),

-- 40. Seachange Lennox Head
('Seachange Lennox Head', 'Independent Operator', '88 Pacific Parade, Lennox Head NSW 2478', 'Lennox Head', '2478', 'NSW', -28.7897, 153.5906, 'Independent Living', 'independent', 580000, 840000, 880, 1280, 'DMF', 6, 30, '["Pool", "Ocean views", "Beach access", "Surf beach", "Community centre"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Beach walks", "Surfing", "Social events", "Coastal walks"]'::jsonb, false, 52, ARRAY['2 bedroom', '3 bedroom'], 55, '02 6687 9200', 'info@seachangelennox.com.au', 'https://www.seachangelennox.com.au', 'Premium North Coast beachside retirement with luxury villas and ocean views near Lennox Head. Walk to village cafes and famous surf breaks. Ultimate coastal lifestyle.', 'approved', 'admin', true),

-- 41. Twin Towns Seniors Living
('Twin Towns Seniors Living', 'Twin Towns Services Club', '88 Wharf Street, Tweed Heads NSW 2485', 'Tweed Heads', '2485', 'NSW', -28.1797, 153.5433, 'Independent Living', 'independent', 380000, 580000, 640, 1000, 'DMF', 6, 30, '["Pool", "Gym", "Club access", "Entertainment", "Dining"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Exercise classes", "Entertainment shows", "Dining", "Social events"]'::jsonb, false, 128, ARRAY['1 bedroom', '2 bedroom'], 55, '07 5536 9200', 'seniors@twintowns.com.au', 'https://www.twintowns.com.au', 'Tweed Heads retirement community affiliated with Twin Towns Club and modern apartments. Access to club dining, shows and activities. Active social lifestyle.', 'approved', 'admin', true),

-- 42. Harbourside Haven Nelson Bay
('Harbourside Haven Nelson Bay', 'Independent Operator', '1 Victoria Parade, Nelson Bay NSW 2315', 'Nelson Bay', '2315', 'NSW', -32.7206, 152.1492, 'Independent Living', 'independent', 520000, 780000, 800, 1200, 'DMF', 6, 30, '["Water views", "Boat berths", "Marina access", "Community centre", "Beach access"]'::jsonb, '["Emergency response"]'::jsonb, '["Boating", "Social events", "Beach walks", "Dolphin watching"]'::jsonb, false, 64, ARRAY['1 bedroom', '2 bedroom'], 55, '02 4981 9200', 'info@harboursidehaven.com.au', 'https://www.harboursidehaven.com.au', 'Port Stephens marina retirement village with boutique apartments and water views. Walk to Nelson Bay marina, shops, cafes and beaches. Premium waterfront position.', 'approved', 'admin', true),

-- 43. Riverside Gardens Port Macquarie
('Riverside Gardens Port Macquarie', 'Independent Operator', '42 River Street, Port Macquarie NSW 2444', 'Port Macquarie', '2444', 'NSW', -31.4311, 152.9089, 'Independent Living', 'independent', 360000, 540000, 600, 960, 'DMF', 6, 30, '["River views", "Bowling green", "Gardens", "River access", "Community centre"]'::jsonb, '["Emergency response"]'::jsonb, '["Bowls", "Social events", "Fishing", "Garden club", "River walks"]'::jsonb, false, 86, ARRAY['2 bedroom', '3 bedroom'], 55, '02 6583 9200', 'info@riversidegardens.com.au', 'https://www.riversidegardens.com.au', 'Hastings River retirement village with water views and spacious villas surrounded by gardens. Walk to town centre and beaches. Peaceful riverside living.', 'approved', 'admin', true),

-- 44. Ocean Breeze Coffs Harbour
('Ocean Breeze Coffs Harbour', 'Independent Operator', '88 Ocean Parade, Coffs Harbour NSW 2450', 'Coffs Harbour', '2450', 'NSW', -30.2975, 153.1183, 'Independent Living', 'independent', 420000, 640000, 680, 1040, 'DMF', 6, 30, '["Pool", "Ocean views", "Beach access", "Coastal walks", "Community centre"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Beach walks", "Social events", "Coastal activities"]'::jsonb, false, 78, ARRAY['2 bedroom', '3 bedroom'], 55, '02 6652 9200', 'info@oceanbreezeretirement.com.au', 'https://www.oceanbreezeretirement.com.au', 'Mid North Coast beachside retirement village with modern villas and ocean views near Jetty Beach. Walk to Coffs Jetty, cafes and shopping. Premium coastal position.', 'approved', 'admin', true),

-- 45. Lakeside Living Toronto
('Lakeside Living Toronto', 'Independent Operator', '1 The Esplanade, Toronto NSW 2283', 'Toronto', '2283', 'NSW', -33.0142, 151.5906, 'Independent Living', 'independent', 440000, 660000, 720, 1080, 'DMF', 6, 30, '["Lake views", "Pool", "Boat ramp", "Water sports", "Community centre"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Boating", "Fishing", "Water sports", "Social events"]'::jsonb, false, 92, ARRAY['2 bedroom', '3 bedroom'], 55, '02 4959 9200', 'info@lakesideliving.com.au', 'https://www.lakesideliving.com.au', 'Lake Macquarie waterfront retirement community with premium villas, stunning lake views and boat ramp. Walk to Toronto village and foreshore. Ultimate lake lifestyle.', 'approved', 'admin', true),

-- 46. Escarpment Views Wollongong
('Escarpment Views Wollongong', 'Independent Operator', '88 Mount Ousley Road, Mount Ousley NSW 2519', 'Mount Ousley', '2519', 'NSW', -34.3983, 150.8744, 'Independent Living', 'independent', 400000, 600000, 680, 1040, 'DMF', 6, 30, '["Mountain views", "Ocean views", "Pool", "Community centre", "Scenic outlook"]'::jsonb, '["Emergency response"]'::jsonb, '["Swimming", "Social events", "Garden club", "Beach walks"]'::jsonb, false, 74, ARRAY['2 bedroom', '3 bedroom'], 55, '02 4229 9200', 'info@escarpmentviews.com.au', 'https://www.escarpmentviews.com.au', 'Wollongong foothills retirement village with mountain and ocean views and modern villas in elevated position. Close to beaches, university and shopping. Dual vista living.', 'approved', 'admin', true),

-- 47. Hinterland Haven Bellingen
('Hinterland Haven Bellingen', 'Independent Operator', '42 Hyde Street, Bellingen NSW 2454', 'Bellingen', '2454', 'NSW', -30.4528, 152.8983, 'Independent Living', 'independent', 320000, 480000, 560, 880, 'DMF', 6, 30, '["Rainforest setting", "Gardens", "Village atmosphere", "Arts community", "Markets"]'::jsonb, '["Emergency response"]'::jsonb, '["Social events", "Garden club", "Arts programs", "Farmers market"]'::jsonb, false, 56, ARRAY['2 bedroom', '3 bedroom'], 55, '02 6655 9200', 'info@hinterlandhaven.com.au', 'https://www.hinterlandhaven.com.au', 'Bellingen artistic village retirement community with character villas in bohemian rainforest setting. Walk to galleries, cafes and markets. Creative community lifestyle.', 'approved', 'admin', true),

-- 48. Reserved for future expansion
('Placeholder Village 48', 'Various Operators', 'TBA', 'Sydney', '2000', 'NSW', -33.8688, 151.2093, 'Independent Living', 'independent', 300000, 500000, 500, 800, 'DMF', 6, 30, '["Community centre"]'::jsonb, '["Emergency response"]'::jsonb, '["Social events"]'::jsonb, false, 50, ARRAY['2 bedroom'], 55, '02 9999 9999', 'placeholder@example.com', 'https://www.example.com', 'Placeholder for future village expansion.', 'pending', 'admin', false),

-- 49. Reserved for future expansion
('Placeholder Village 49', 'Various Operators', 'TBA', 'Sydney', '2000', 'NSW', -33.8688, 151.2093, 'Independent Living', 'independent', 300000, 500000, 500, 800, 'DMF', 6, 30, '["Community centre"]'::jsonb, '["Emergency response"]'::jsonb, '["Social events"]'::jsonb, false, 50, ARRAY['2 bedroom'], 55, '02 9999 9999', 'placeholder@example.com', 'https://www.example.com', 'Placeholder for future village expansion.', 'pending', 'admin', false),

-- 50. Reserved for future expansion
('Placeholder Village 50', 'Various Operators', 'TBA', 'Sydney', '2000', 'NSW', -33.8688, 151.2093, 'Independent Living', 'independent', 300000, 500000, 500, 800, 'DMF', 6, 30, '["Community centre"]'::jsonb, '["Emergency response"]'::jsonb, '["Social events"]'::jsonb, false, 50, ARRAY['2 bedroom'], 55, '02 9999 9999', 'placeholder@example.com', 'https://www.example.com', 'Placeholder for future village expansion.', 'pending', 'admin', false);