-- NSW Batch 06: 25 Premium Retirement Villages
-- Geographic Focus: Sydney Metro (North Shore, Eastern Suburbs, Hills District)
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Aveo Norwest', 'Aveo Group', 'Beautifully designed independent living community in the thriving Norwest precinct. Modern apartments with resort-style amenities including swimming pool, gym, cinema, and landscaped gardens. Close to Westfield shopping, restaurants and medical facilities.', '8 Norbrik Drive', 'Bella Vista', 'NSW', '2153', 'Independent Living', 450000, 750000, 180, 280, 156, 8, ARRAY['Pool', 'Gym', 'Cinema', 'Library', 'Bowling Green', 'Community Centre', 'Gardens', 'Cafe'], '1300 283 000', 'norwest@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Lendlease The Grange Killara', 'Lendlease', 'Prestigious retirement village on Sydney''s Upper North Shore. Spacious independent living villas and apartments set in 4.5 hectares of landscaped gardens. On-site medical centre, indoor heated pool, and vibrant community activities. Minutes to Killara village shops and station.', '555 Pacific Highway', 'Killara', 'NSW', '2071', 'Independent Living, Aged Care', 750000, 1200000, 250, 380, 142, 5, ARRAY['Pool', 'Gym', 'Medical Centre', 'Library', 'Bowling Green', 'Community Centre', 'Gardens', 'Restaurant', 'Hair Salon'], '1300 326 033', 'killara@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Stockland Willowdale', 'Stockland', 'Award-winning retirement community in Denham Court offering contemporary homes with excellent amenities. Features resort-style facilities including pool, gym, cinema, workshop and craft rooms. Close to Liverpool CBD and major shopping centres.', '1 Willowdale Drive', 'Denham Court', 'NSW', '2565', 'Independent Living', 380000, 580000, 150, 220, 284, 12, ARRAY['Pool', 'Gym', 'Cinema', 'Workshop', 'Arts & Crafts Room', 'Community Centre', 'Gardens', 'BBQ Areas'], '1800 550 550', 'willowdale@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Anglicare Newmarch House', 'Anglicare', 'Established retirement village in Caddens with comprehensive care options. Independent living units with access to high-care aged care facility. Beautiful gardens, community activities, and chapel services. Friendly village atmosphere.', '216-238 Caddens Road', 'Caddens', 'NSW', '2747', 'Independent Living, Aged Care', 280000, 420000, 120, 200, 98, 6, ARRAY['Chapel', 'Gardens', 'Community Centre', 'Library', 'BBQ Areas', 'Aged Care'], '02 4731 5100', 'newmarch@anglicare.org.au', 'https://www.anglicare.org.au', 'Active'),

('Opal Aged Care North Ryde', 'Opal Aged Care', 'Modern retirement community with premium independent living apartments and residential aged care. Contemporary design with resort-style amenities including heated pool, gym, cinema and cafe. Convenient location near Macquarie Centre.', '11 Wicks Road', 'North Ryde', 'NSW', '2113', 'Independent Living, Aged Care', 520000, 780000, 200, 300, 118, 7, ARRAY['Pool', 'Gym', 'Cinema', 'Cafe', 'Library', 'Gardens', 'Aged Care'], '1300 672 524', 'northryde@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Tarrawanna', 'IRT Group', 'Coastal retirement living near Wollongong beaches. Modern villas and apartments with ocean glimpses, community centre, and bowling green. Strong community spirit with regular social activities and outings. Close to shopping and medical facilities.', '2-10 Birkdale Place', 'Tarrawanna', 'NSW', '2518', 'Independent Living, Aged Care', 320000, 480000, 140, 210, 86, 4, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'BBQ Areas', 'Library'], '1300 157 677', 'tarrawanna@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Presbyterian Aged Care Ashfield', 'Presbyterian Aged Care NSW & ACT', 'Convenient inner-west retirement village with independent living units and aged care. Located in leafy Ashfield near public transport, shops and medical services. Established community with friendly residents.', '22-32 Holden Street', 'Ashfield', 'NSW', '2131', 'Independent Living, Aged Care', 450000, 650000, 180, 260, 74, 3, ARRAY['Gardens', 'Community Centre', 'Library', 'Chapel', 'Aged Care'], '02 9716 1300', 'ashfield@pac.org.au', 'https://www.pac.org.au', 'Active'),

('Uniting Lindfield', 'Uniting', 'Premium retirement community on Sydney''s Upper North Shore. Contemporary apartments with high-end finishes, concierge service, and resort amenities. Indoor pool, gym, cinema, library and beautiful gardens. Walking distance to Lindfield village.', '7-9 Shinfield Avenue', 'Lindfield', 'NSW', '2070', 'Independent Living', 580000, 920000, 220, 340, 132, 6, ARRAY['Pool', 'Gym', 'Cinema', 'Library', 'Concierge', 'Gardens', 'Community Centre', 'Cafe'], '1300 864 846', 'lindfield@uniting.org', 'https://www.uniting.org', 'Active'),

('Ingenia Lifestyle Soldiers Point', 'Ingenia Communities', 'Over-50s lakeside resort community at beautiful Port Stephens. Modern manufactured homes with pristine beaches nearby. Swimming pool, bowling green, and vibrant social calendar. Perfect retirement or holiday destination.', '1 Koala Place', 'Soldiers Point', 'NSW', '2317', 'Independent Living', 180000, 350000, 80, 140, 196, 15, ARRAY['Pool', 'Bowling Green', 'Community Centre', 'Workshop', 'BBQ Areas', 'Gardens'], '02 4919 0000', 'soldierspoint@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Active'),

('Baptistcare Aminya', 'BaptistCare', 'Peaceful retirement village in Baulkham Hills with spacious villas surrounded by gardens. Strong community atmosphere with regular activities and chapel services. Close to Castle Towers shopping centre and medical facilities.', '142 Old Northern Road', 'Baulkham Hills', 'NSW', '2153', 'Independent Living', 380000, 520000, 160, 230, 88, 5, ARRAY['Chapel', 'Gardens', 'Community Centre', 'Library', 'BBQ Areas'], '02 9659 3333', 'aminya@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Arcare North Shore', 'Arcare', 'Boutique retirement community in St Leonards with stunning harbour views. Luxury apartments with premium finishes, rooftop terrace, gym and cinema. Concierge services and on-site cafe. Walk to St Leonards station and Royal North Shore Hospital.', '45 Christie Street', 'St Leonards', 'NSW', '2065', 'Independent Living, Aged Care', 680000, 980000, 260, 380, 94, 4, ARRAY['Rooftop Terrace', 'Gym', 'Cinema', 'Cafe', 'Concierge', 'Library', 'Aged Care'], '1300 272 273', 'northshore@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Regis Aged Care Dural', 'Regis Aged Care', 'Tranquil Hills District retirement village with modern independent living and residential aged care. Set among 5 acres of beautiful gardens with native wildlife. Pool, community centre and regular outings. Peaceful semi-rural setting.', '634 Old Northern Road', 'Dural', 'NSW', '2158', 'Independent Living, Aged Care', 420000, 620000, 170, 250, 102, 8, ARRAY['Pool', 'Gardens', 'Community Centre', 'Library', 'BBQ Areas', 'Aged Care'], '02 9651 4400', 'dural@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Maroubra', 'Respect', 'Eastern suburbs retirement living minutes from Maroubra Beach. Contemporary apartments with coastal lifestyle, swimming pool and community facilities. Active social program with beach walks and local outings.', '88 Bunnerong Road', 'Maroubra', 'NSW', '2035', 'Independent Living, Aged Care', 520000, 740000, 200, 290, 76, 3, ARRAY['Pool', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 9661 5400', 'maroubra@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Southern Cross Care Nagle', 'Southern Cross Care', 'Established Blacktown retirement village with supportive community atmosphere. Independent living villas with bowling green, chapel and community centre. On-site aged care facility available. Close to Blacktown Hospital and Westpoint shopping.', '24 Qualita Street', 'Blacktown', 'NSW', '2148', 'Independent Living, Aged Care', 300000, 450000, 130, 200, 112, 7, ARRAY['Bowling Green', 'Chapel', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 8757 3100', 'nagle@sccliving.org.au', 'https://www.sccliving.org.au', 'Active'),

('Adventist Retirement Plus Cooranbong', 'Adventist Retirement Plus', 'Lake Macquarie retirement village set in peaceful surroundings near Avondale University. Villas and apartments with community centre, pool and beautiful gardens. Active lifestyle with emphasis on health and wellbeing.', '175 Avondale Road', 'Cooranbong', 'NSW', '2265', 'Independent Living', 280000, 420000, 120, 190, 148, 9, ARRAY['Pool', 'Community Centre', 'Gardens', 'Walking Trails', 'BBQ Areas'], '02 4977 2200', 'cooranbong@adventistretirementplus.org.au', 'https://www.retirementplus.com.au', 'Active'),

('Summerset Manly Waters', 'Summerset', 'Premium Northern Beaches retirement living with water views. Luxury apartments near Manly beach and harbour. Resort-style pool, gym, cinema and dining room. Concierge service and vibrant community. Walk to Manly Wharf and beaches.', '88 North Steyne', 'Manly', 'NSW', '2095', 'Independent Living', 780000, 1150000, 280, 410, 68, 2, ARRAY['Pool', 'Gym', 'Cinema', 'Dining Room', 'Concierge', 'Rooftop Terrace', 'Library'], '02 9977 4500', 'manlywaters@summerset.net.au', 'https://www.summerset.com.au', 'Active'),

('Estia Health Blakehurst', 'Estia Health', 'Modern South Sydney retirement community with independent units and aged care residence. Close to Westfield Hurstville and quality medical facilities. Swimming pool, gardens and regular activities program.', '42 Flora Street', 'Blakehurst', 'NSW', '2221', 'Independent Living, Aged Care', 460000, 640000, 180, 260, 84, 5, ARRAY['Pool', 'Gardens', 'Community Centre', 'Library', 'Aged Care'], '02 9546 4200', 'blakehurst@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Bupa Aged Care Maroubra', 'Bupa', 'Beachside retirement living in Sydney''s East with independent living apartments. Modern facilities including pool, gym and cinema room. Short walk to Maroubra Beach, cafes and shops. Excellent public transport connections.', '756 Anzac Parade', 'Maroubra', 'NSW', '2035', 'Independent Living, Aged Care', 540000, 760000, 210, 300, 92, 6, ARRAY['Pool', 'Gym', 'Cinema', 'Library', 'Gardens', 'Aged Care'], '1300 280 334', 'maroubra@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Albury Wodonga', 'Allity', 'Border region retirement village offering affordable independent living and aged care. Spacious villas with bowling green, community hall and gardens. Friendly country atmosphere with active social program.', '1186 Mate Street', 'Lavington', 'NSW', '2641', 'Independent Living, Aged Care', 220000, 380000, 100, 170, 94, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'BBQ Areas', 'Library', 'Aged Care'], '02 6025 7100', 'alburywodonga@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Macquarie Park', 'Bolton Clarke', 'Contemporary retirement village in thriving Macquarie Park precinct. Modern apartments with resort amenities including heated pool, gym, cinema and cafe. Walk to Macquarie University and Macquarie Centre. Excellent healthcare nearby.', '12 Waterloo Road', 'Macquarie Park', 'NSW', '2113', 'Independent Living, Aged Care', 560000, 820000, 220, 320, 126, 7, ARRAY['Pool', 'Gym', 'Cinema', 'Cafe', 'Library', 'Gardens', 'Aged Care'], '1300 228 655', 'macquariepark@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Villa Maria Catholic Homes Punchbowl', 'Villa Maria Catholic Homes', 'Established inner-west retirement community with chapel and strong Catholic ethos. Independent villas and aged care facility. Beautiful gardens, community activities and pastoral care services. Close to local shops and medical centre.', '10-12 Winifred Street', 'Punchbowl', 'NSW', '2196', 'Independent Living, Aged Care', 340000, 490000, 140, 210, 78, 4, ARRAY['Chapel', 'Gardens', 'Community Centre', 'Library', 'Aged Care'], '02 9740 0111', 'punchbowl@vmch.com.au', 'https://www.vmch.com.au', 'Active'),

('Resthaven Riverside', 'Resthaven', 'Modern Penrith retirement village along Nepean River. Spacious villas with river views, community centre and bowling green. Easy access to Penrith CBD, Panthers precinct and quality hospitals. Active lifestyle community.', '88 River Road', 'Emu Plains', 'NSW', '2750', 'Independent Living', 340000, 480000, 150, 220, 116, 9, ARRAY['Bowling Green', 'Community Centre', 'River Views', 'Gardens', 'BBQ Areas'], '02 4735 2200', 'riverside@resthaven.asn.au', 'https://www.resthaven.asn.au', 'Active'),

('Japara Retravill House', 'Japara', 'Castle Hill retirement community with independent living and residential aged care. Set in landscaped gardens with modern facilities. Close to Castle Towers, Hills Private Hospital and public transport. Vibrant community activities.', '14-16 Carrington Road', 'Castle Hill', 'NSW', '2154', 'Independent Living, Aged Care', 420000, 620000, 170, 250, 88, 5, ARRAY['Gardens', 'Community Centre', 'Library', 'Chapel', 'Aged Care'], '1800 52 72 72', 'retravill@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Elanora Heights', 'Tricare', 'Northern Beaches retirement village near Narrabeen Lake. Modern villas and apartments surrounded by nature with lake and ocean proximity. Pool, community centre and active social program. Peaceful coastal lifestyle.', '45 Irambang Street', 'Elanora Heights', 'NSW', '2101', 'Independent Living, Aged Care', 580000, 820000, 220, 310, 72, 3, ARRAY['Pool', 'Community Centre', 'Gardens', 'Lake Views', 'Aged Care'], '02 9913 9400', 'elanoraheights@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Brighton-Le-Sands', 'Mayflower', 'Bayside retirement community minutes from Brighton Beach. Contemporary apartments with water glimpses, rooftop terrace and community facilities. Walk to cafes, restaurants and Rockdale Plaza. Easy city access via train.', '14-22 Waterview Street', 'Carlton', 'NSW', '2218', 'Independent Living, Aged Care', 490000, 710000, 190, 280, 96, 6, ARRAY['Rooftop Terrace', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 9587 3455', 'brighton@mayflower.org.au', 'https://www.mayflower.org.au', 'Active');
