-- NSW Batch 10: 25 Hunter Valley & Mid North Coast Retirement Villages  
-- Geographic Focus: Newcastle, Lake Macquarie, Port Macquarie, Taree, Forster
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Stockland Alloura Waters', 'Stockland', 'Lake Macquarie waterfront retirement resort. Premium villas with stunning lake views and marina access. Pool, gym, cinema, bowling green and community hub. Water activities and fishing paradise.', '1 Lakefront Drive', 'Toronto', 'NSW', '2283', 'Independent Living', 420000, 640000, 170, 260, 196, 13, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Marina', 'Lake Views', 'Community Centre'], '1800 550 550', 'allourawaters@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Lendlease Harbourside Newcastle', 'Lendlease', 'Premium Newcastle retirement living with harbor views. Luxury apartments overlooking Newcastle Harbor. Rooftop terrace, pool, gym, cinema and fine dining. Walk to Honeysuckle precinct and beaches.', '88 Wharf Road', 'Newcastle', 'NSW', '2300', 'Independent Living', 680000, 980000, 260, 380, 118, 6, ARRAY['Rooftop Terrace', 'Pool', 'Gym', 'Cinema', 'Harbour Views', 'Fine Dining', 'Concierge'], '1300 326 033', 'newcastle@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Aveo Durack Palms', 'Aveo Group', 'Hunter region retirement village in Durack. Modern villas and apartments with resort amenities. Pool, gym, bowling green and community centre. Close to all Maitland shopping and medical facilities.', '1 Palm Court', 'Durack', 'NSW', '2325', 'Independent Living', 340000, 520000, 150, 230, 168, 11, ARRAY['Pool', 'Gym', 'Bowling Green', 'Community Centre', 'Gardens', 'Workshop'], '1300 283 000', 'durack@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Anglicare The Shores Belmont', 'Anglicare', 'Lake Macquarie waterfront retirement community. Independent villas with lake views. Chapel, community centre, bowling green and gardens. Walk to Belmont shops and lake foreshore. Boating and fishing.', '88 Macquarie Street', 'Belmont', 'NSW', '2280', 'Independent Living, Aged Care', 360000, 540000, 150, 230, 94, 7, ARRAY['Lake Views', 'Chapel', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '02 4945 3100', 'belmont@anglicare.org.au', 'https://www.anglicare.org.au', 'Active'),

('IRT John Lindfield Village', 'IRT Group', 'Hunter Valley retirement village in Cessnock wine country. Spacious villas with mountain views. Bowling green, community centre and gardens. Explore local wineries and country lifestyle.', '88 Wollombi Road', 'Cessnock', 'NSW', '2325', 'Independent Living, Aged Care', 260000, 400000, 110, 180, 102, 8, ARRAY['Bowling Green', 'Mountain Views', 'Community Centre', 'Gardens', 'Wine Country', 'Aged Care'], '1300 157 677', 'cessnock@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Uniting Mayfield', 'Uniting', 'Newcastle suburb retirement community near beaches. Modern villas and apartments with pool and community facilities. Close to Westfield Kotara and John Hunter Hospital. Easy coastal access and train.', '42 Hanbury Street', 'Mayfield', 'NSW', '2304', 'Independent Living', 340000, 510000, 150, 230, 116, 9, ARRAY['Pool', 'Community Centre', 'Gardens', 'Library', 'BBQ Areas'], '1300 864 846', 'mayfield@uniting.org', 'https://www.uniting.org', 'Active'),

('Opal Aged Care Charlestown', 'Opal Aged Care', 'Lake Macquarie retirement living near Charlestown Square. Contemporary apartments with pool, gym and community hub. Walk to major shopping centre, cinemas and medical facilities. Excellent amenities.', '88 Pearson Street', 'Charlestown', 'NSW', '2290', 'Independent Living, Aged Care', 380000, 560000, 160, 240, 132, 10, ARRAY['Pool', 'Gym', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '1300 672 524', 'charlestown@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('Presbyterian Aged Care Adamstown', 'Presbyterian Aged Care NSW & ACT', 'Newcastle retirement village near university. Independent units with chapel and community centre. Close to Westfield Kotara, beaches and quality medical facilities. Established friendly community.', '14 Brunker Road', 'Adamstown', 'NSW', '2289', 'Independent Living, Aged Care', 340000, 510000, 150, 230, 84, 6, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 4952 3100', 'adamstown@pac.org.au', 'https://www.pac.org.au', 'Active'),

('Baptistcare Cooinda Village', 'BaptistCare', 'Mid North Coast retirement village in Taree. Spacious villas with Manning River views. Chapel, bowling green and community facilities. Enjoy coastal town lifestyle with nearby beaches and fishing.', '88 Victoria Street', 'Taree', 'NSW', '2430', 'Independent Living, Aged Care', 260000, 400000, 110, 180, 96, 7, ARRAY['Chapel', 'Bowling Green', 'River Views', 'Community Centre', 'Gardens', 'Aged Care'], '02 6552 3100', 'taree@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Regis Aged Care Warners Bay', 'Regis Aged Care', 'Lake Macquarie waterfront retirement community. Quality villas with lake views and boat ramp access. Pool, bowling green and community centre. Walk to Warners Bay village shops and cafes. Water lifestyle.', '1 Lake Road', 'Warners Bay', 'NSW', '2282', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 108, 8, ARRAY['Pool', 'Bowling Green', 'Lake Views', 'Boat Ramp', 'Community Centre', 'Aged Care'], '02 4948 4100', 'warnersbay@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Maitland', 'Respect', 'Hunter region retirement village in heritage Maitland. Comfortable villas with community centre and gardens. Close to Maitland Hospital, shopping and Hunter Valley wineries. Affordable regional living.', '42 High Street', 'Maitland', 'NSW', '2320', 'Independent Living, Aged Care', 260000, 400000, 110, 180, 94, 7, ARRAY['Community Centre', 'Gardens', 'Bowling Green', 'Library', 'Aged Care'], '02 4933 3100', 'maitland@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Southern Cross Care Lake Heights', 'Southern Cross Care', 'Lake Illawarra retirement community with water views. Spacious villas near lake foreshore. Bowling green, community hall and gardens. Fishing, water activities and coastal lifestyle. Close to Warilla shops.', '88 Lake Avenue', 'Lake Heights', 'NSW', '2502', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 102, 8, ARRAY['Bowling Green', 'Lake Views', 'Community Centre', 'Gardens', 'Fishing', 'Aged Care'], '02 4274 3100', 'lakeheights@sccliving.org.au', 'https://www.sccliving.org.au', 'Active'),

('Adventist Retirement Plus Dora Creek', 'Adventist Retirement Plus', 'Lake Macquarie retirement village near Morisset. Health-focused community with villas and wellness programs. Pool, gardens and lake views. Peaceful setting with water activities and walking trails.', '88 Dora Street', 'Dora Creek', 'NSW', '2264', 'Independent Living', 240000, 380000, 100, 170, 118, 10, ARRAY['Pool', 'Lake Views', 'Wellness Centre', 'Gardens', 'Walking Trails'], '02 4973 4200', 'doracreek@adventistretirementplus.org.au', 'https://www.retirementplus.com.au', 'Active'),

('Estia Health Hamilton', 'Estia Health', 'Newcastle city fringe retirement community. Modern apartments near Beaumont Street cafes and shops. Pool, gym and community facilities. Walk to restaurants, parks and Newcastle beaches. Urban retirement.', '88 Denison Street', 'Hamilton', 'NSW', '2303', 'Independent Living, Aged Care', 420000, 620000, 170, 250, 96, 6, ARRAY['Pool', 'Gym', 'Community Centre', 'Gardens', 'Urban Location', 'Aged Care'], '02 4961 3100', 'hamilton@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Bupa Aged Care Eleebana', 'Bupa', 'Lake Macquarie waterfront retirement village. Comfortable villas with stunning lake views. Bowling green, community centre and boat ramp. Perfect for water enthusiasts. Walk to Eleebana shops and cafes.', '22 Fishing Point Road', 'Eleebana', 'NSW', '2282', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 88, 7, ARRAY['Bowling Green', 'Lake Views', 'Boat Ramp', 'Community Centre', 'Gardens', 'Aged Care'], '1300 280 334', 'eleebana@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Swansea', 'Allity', 'Lake Macquarie channel entrance retirement village. Modern villas near beaches and lake. Community centre, pool and gardens. Walk to Swansea shops and Blacksmiths Beach. Perfect coastal retirement.', '88 Pacific Highway', 'Swansea', 'NSW', '2281', 'Independent Living', 320000, 480000, 140, 210, 104, 8, ARRAY['Pool', 'Community Centre', 'Lake & Ocean', 'Gardens', 'BBQ Areas'], '02 4971 3100', 'swansea@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Laurieton', 'Bolton Clarke', 'Mid North Coast retirement village near beaches. Comfortable villas close to Camden Haven River and coast. Community centre, bowling green and gardens. Enjoy relaxed coastal town lifestyle.', '42 Bold Street', 'Laurieton', 'NSW', '2443', 'Independent Living, Aged Care', 280000, 430000, 120, 190, 78, 6, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'River Views', 'Aged Care'], '1300 228 655', 'laurieton@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Villa Maria Catholic Homes Broadmeadow', 'Villa Maria Catholic Homes', 'Newcastle retirement community near city centre. Catholic heritage with chapel and pastoral care. Independent villas with community facilities and aged care. Close to John Hunter Hospital.', '88 Broadmeadow Road', 'Broadmeadow', 'NSW', '2292', 'Independent Living, Aged Care', 340000, 510000, 150, 230, 86, 5, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 4952 4200', 'broadmeadow@vmch.com.au', 'https://www.vmch.com.au', 'Active'),

('Japara Singleton', 'Japara', 'Upper Hunter retirement village in mining town. Affordable villas and aged care facility. Bowling green, community centre and gardens. Regional country living with close-knit community atmosphere.', '42 George Street', 'Singleton', 'NSW', '2330', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 74, 7, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '1800 52 72 72', 'singleton@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Valentine', 'Tricare', 'Lake Macquarie lakeside retirement village. Modern villas with water access and views. Pool, community centre and bowling green. Marina nearby for boating. Walk to Valentine shops and lake foreshore.', '1 Kanangra Avenue', 'Valentine', 'NSW', '2280', 'Independent Living, Aged Care', 360000, 540000, 150, 230, 92, 6, ARRAY['Pool', 'Bowling Green', 'Lake Views', 'Water Access', 'Community Centre', 'Aged Care'], '02 4943 3100', 'valentine@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Caves Beach', 'Mayflower', 'Lake Macquarie beachside retirement village. Premium villas near Caves Beach and lake. Pool, community facilities and coastal walks. Enjoy dual water lifestyle with ocean and lake access. Premium location.', '88 Beach Road', 'Caves Beach', 'NSW', '2281', 'Independent Living', 480000, 720000, 190, 280, 64, 3, ARRAY['Pool', 'Beach Access', 'Lake Access', 'Community Centre', 'Coastal Walks'], '02 4972 1234', 'cavesbeach@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL LifeCare Wallsend', 'RSL LifeCare', 'Newcastle suburb retirement village with veterans services. Affordable villas with bowling green and community hall. RSL club facilities nearby. Close to Westfield Kotara and medical facilities.', '88 Nelson Street', 'Wallsend', 'NSW', '2287', 'Independent Living, Aged Care', 280000, 430000, 120, 190, 98, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'RSL Services', 'Aged Care'], '02 4951 3100', 'wallsend@rsllifecare.org.au', 'https://www.rsllifecare.org.au', 'Active'),

('Ingenia Lifestyle Soldiers Point North', 'Ingenia Communities', 'Port Stephens over-50s resort on pristine waterfront. Modern manufactured homes with marina and beach access. Pool, bowling green, clubhouse. Boating, fishing and dolphins. Ultimate coastal resort living.', '88 Koala Drive', 'Soldiers Point', 'NSW', '2317', 'Independent Living', 240000, 420000, 95, 160, 224, 19, ARRAY['Pool', 'Bowling Green', 'Marina', 'Beach Access', 'Clubhouse', 'Fishing'], '02 4919 1234', 'soldiersnorth@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Active'),

('NewDirection Care Speers Point', 'NewDirection Care', 'Lake Macquarie waterfront retirement living. Contemporary apartments with panoramic lake views. Pool, gym, community facilities and aged care. Walk to Speers Point Park and boat ramp. Premium lakefront position.', '1 Macquarie Road', 'Speers Point', 'NSW', '2284', 'Independent Living, Aged Care', 400000, 620000, 170, 260, 114, 9, ARRAY['Pool', 'Gym', 'Lake Views', 'Boat Ramp', 'Community Centre', 'Aged Care'], '02 4958 3100', 'speerspoint@newdirection.com.au', 'https://www.newdirection.com.au', 'Active'),

('Arcare Tea Gardens', 'Arcare', 'Port Stephens coastal retirement village with water views. Modern villas near beaches and Myall Lakes. Pool, community centre and marina access. Perfect for fishing, boating and relaxed coastal lifestyle.', '88 Myall Street', 'Tea Gardens', 'NSW', '2324', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 72, 5, ARRAY['Pool', 'Water Views', 'Marina Access', 'Community Centre', 'Gardens', 'Aged Care'], '1300 272 273', 'teagardens@arcare.com.au', 'https://www.arcare.com.au', 'Active');
