-- NSW Batch 07: 25 Regional & Coastal Retirement Villages
-- Geographic Focus: Central Coast, Newcastle, South Coast, Regional NSW
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Peninsula Villages Umina', 'Peninsula Villages', 'Premier Central Coast retirement community with ocean views. Spacious villas and apartments near Umina Beach. Resort-style pool, bowling green, workshop and community centre. Vibrant social program with beach lifestyle.', '93 Trafalgar Avenue', 'Umina Beach', 'NSW', '2257', 'Independent Living', 380000, 580000, 160, 240, 168, 11, ARRAY['Pool', 'Bowling Green', 'Workshop', 'Community Centre', 'Gardens', 'Ocean Views', 'BBQ Areas'], '02 4344 9199', 'umina@peninsulavillages.com.au', 'https://www.peninsulavillages.com.au', 'Active'),

('Bluetree Group The Shores', 'Bluetree Group', 'Luxury lakeside retirement living at Gwandalan. Premium villas with Lake Macquarie views, marina access, and resort amenities. Swimming pool, gym, cinema and restaurant. Perfect for water-loving retirees.', '1 Lakeside Drive', 'Gwandalan', 'NSW', '2259', 'Independent Living', 520000, 780000, 200, 290, 124, 7, ARRAY['Pool', 'Gym', 'Cinema', 'Restaurant', 'Marina', 'Lake Views', 'Gardens'], '02 4976 1234', 'theshores@bluetree.com.au', 'https://www.bluetree.com.au', 'Active'),

('NewDirection Care Merewether', 'NewDirection Care', 'Newcastle beachside retirement village near Merewether Beach. Modern apartments with ocean proximity, pool and community facilities. Walk to cafes, surf club and coastal walks. Active lifestyle community.', '22 Ocean Street', 'Merewether', 'NSW', '2291', 'Independent Living, Aged Care', 420000, 620000, 170, 250, 86, 5, ARRAY['Pool', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 4963 2100', 'merewether@newdirection.com.au', 'https://www.newdirection.com.au', 'Active'),

('Aurrum Terrigal', 'Aurrum', 'Premium Central Coast retirement living with stunning ocean views. Luxury apartments overlooking Terrigal Beach. Rooftop terrace, pool, gym and fine dining. Walk to beach, cafes and restaurants. Five-star retirement lifestyle.', '1 Ocean View Drive', 'Terrigal', 'NSW', '2260', 'Independent Living', 680000, 980000, 260, 380, 78, 3, ARRAY['Rooftop Terrace', 'Pool', 'Gym', 'Fine Dining', 'Ocean Views', 'Concierge', 'Cinema'], '02 4385 4200', 'terrigal@aurrum.com.au', 'https://www.aurrum.com.au', 'Active'),

('RSL LifeCare Horizons Raymond Terrace', 'RSL LifeCare', 'Hunter Valley retirement village with affordable villas and aged care. Bowling green, community hall and gardens. Strong RSL heritage with veterans'' services available. Close to Raymond Terrace town centre.', '1 William Street', 'Raymond Terrace', 'NSW', '2324', 'Independent Living, Aged Care', 240000, 380000, 110, 180, 102, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'BBQ Areas', 'Library', 'Aged Care'], '02 4966 9600', 'raymondterrace@rsllifecare.org.au', 'https://www.rsllifecare.org.au', 'Active'),

('Anglicare Wakehurst Gardens', 'Anglicare', 'Northern Beaches retirement village in Belrose. Peaceful setting with native bushland surrounds. Independent villas and units with community centre, chapel and gardens. Close to shops and medical facilities.', '77 Wakehurst Parkway', 'Belrose', 'NSW', '2085', 'Independent Living, Aged Care', 480000, 680000, 190, 270, 94, 6, ARRAY['Chapel', 'Gardens', 'Community Centre', 'Library', 'Bushland Setting', 'Aged Care'], '02 9986 4100', 'wakehurst@anglicare.org.au', 'https://www.anglicare.org.au', 'Active'),

('Uniting Berkeley', 'Uniting', 'Affordable Wollongong retirement village close to beaches. Comfortable villas with community centre and gardens. Friendly atmosphere with regular social activities. Easy access to Lake Illawarra and Wollongong CBD.', '2 Koorabel Avenue', 'Berkeley', 'NSW', '2506', 'Independent Living', 280000, 420000, 120, 190, 118, 9, ARRAY['Community Centre', 'Gardens', 'BBQ Areas', 'Library'], '02 4271 3100', 'berkeley@uniting.org', 'https://www.uniting.org', 'Active'),

('Watermark Palm Lake Ballina', 'Palm Lake Resort', 'Over-50s resort community on NSW North Coast. Modern manufactured homes with resort facilities including pool, tennis courts, bowling green and clubhouse. Minutes to Ballina beaches and Byron Bay.', '1 Palm Lake Drive', 'Ballina', 'NSW', '2478', 'Independent Living', 280000, 450000, 100, 160, 186, 14, ARRAY['Pool', 'Tennis Courts', 'Bowling Green', 'Clubhouse', 'Workshop', 'Gardens'], '02 6686 9200', 'ballina@palmlakeresort.com.au', 'https://www.palmlakeresort.com.au', 'Active'),

('Southern Cross Care Riverside Gardens', 'Southern Cross Care', 'Port Macquarie riverside retirement village with water views. Spacious villas and apartments near Hastings River. Pool, bowling green and community centre. Short walk to town centre and beaches.', '14 Riverside Drive', 'Port Macquarie', 'NSW', '2444', 'Independent Living, Aged Care', 360000, 540000, 150, 230, 142, 10, ARRAY['Pool', 'Bowling Green', 'River Views', 'Community Centre', 'Gardens', 'Aged Care'], '02 6588 2100', 'portmacquarie@sccliving.org.au', 'https://www.sccliving.org.au', 'Active'),

('Aveo Albury Wodonga', 'Aveo Group', 'Border city retirement living with modern apartments and villas. Resort amenities including pool, gym, cinema and community facilities. Close to major shopping centres and quality hospitals. Affordable regional pricing.', '720 David Street', 'Albury', 'NSW', '2640', 'Independent Living', 260000, 420000, 120, 190, 156, 12, ARRAY['Pool', 'Gym', 'Cinema', 'Community Centre', 'Gardens', 'BBQ Areas'], '1300 283 000', 'albury@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Embracia Toormina', 'Embracia Health', 'Coffs Harbour retirement community near beaches and town. Independent villas with bowling green, pool and community hall. Aged care facility on-site. Enjoy coastal lifestyle with year-round mild climate.', '88 Isles Drive', 'Toormina', 'NSW', '2452', 'Independent Living, Aged Care', 280000, 430000, 120, 190, 96, 7, ARRAY['Pool', 'Bowling Green', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 6658 4200', 'toormina@embracia.com.au', 'https://www.embracia.com.au', 'Active'),

('Greengate Village Killara', 'Independent Operator', 'Boutique North Shore retirement village with spacious garden villas. Peaceful setting with established gardens and mature trees. Community centre and bowling green. Close to Killara shops, station and Gordon village.', '17 Greengate Road', 'Killara', 'NSW', '2071', 'Independent Living', 620000, 840000, 240, 320, 42, 2, ARRAY['Bowling Green', 'Gardens', 'Community Centre', 'Library'], '02 9498 3300', 'office@greengatevillage.com.au', 'https://www.greengatevillage.com.au', 'Active'),

('Presbyterian Aged Care Cowra', 'Presbyterian Aged Care NSW & ACT', 'Central West NSW retirement village with affordable villas. Quiet country setting with gardens, bowling green and community hall. Aged care facility available. Friendly rural community atmosphere.', '16 Vaux Street', 'Cowra', 'NSW', '2794', 'Independent Living, Aged Care', 180000, 300000, 90, 150, 68, 6, ARRAY['Bowling Green', 'Gardens', 'Community Centre', 'Chapel', 'Aged Care'], '02 6342 2866', 'cowra@pac.org.au', 'https://www.pac.org.au', 'Active'),

('Baptistcare The Orchards', 'BaptistCare', 'Orange retirement village in beautiful Central West NSW. Modern villas set among established orchards and gardens. Community centre, chapel and bowling green. Cool climate living with four distinct seasons.', '54 Woodward Street', 'Orange', 'NSW', '2800', 'Independent Living, Aged Care', 240000, 380000, 110, 180, 84, 7, ARRAY['Bowling Green', 'Chapel', 'Gardens', 'Community Centre', 'BBQ Areas', 'Aged Care'], '02 6362 6100', 'orange@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Adventist Retirement Plus Morisset', 'Adventist Retirement Plus', 'Lake Macquarie retirement village with water views. Spacious villas and units near lake foreshore. Pool, community centre and beautiful gardens. Health-focused community with wellness programs.', '1 Dora Street', 'Morisset', 'NSW', '2264', 'Independent Living', 260000, 400000, 110, 170, 126, 10, ARRAY['Pool', 'Lake Views', 'Community Centre', 'Gardens', 'Walking Trails'], '02 4973 1234', 'morisset@adventistretirementplus.org.au', 'https://www.retirementplus.com.au', 'Active'),

('IRT Greenwell Gardens', 'IRT Group', 'Established Dapto retirement village near Wollongong. Comfortable villas with bowling green, community hall and gardens. On-site aged care available. Close to Stockland Shellharbour shopping and beaches.', '91 Bong Bong Road', 'Dapto', 'NSW', '2530', 'Independent Living, Aged Care', 300000, 450000, 130, 200, 112, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Library', 'BBQ Areas', 'Aged Care'], '1300 157 677', 'dapto@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Opal Aged Care Glenfield Park', 'Opal Aged Care', 'Modern South-West Sydney retirement community. Contemporary apartments and villas with resort amenities. Pool, gym, cinema and cafe. Close to new Glenfield precinct development and Macarthur region facilities.', '1 Glenfield Park Drive', 'Glenfield', 'NSW', '2167', 'Independent Living, Aged Care', 380000, 560000, 150, 230, 148, 11, ARRAY['Pool', 'Gym', 'Cinema', 'Cafe', 'Gardens', 'Library', 'Aged Care'], '1300 672 524', 'glenfield@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('Estia Health Forster', 'Estia Health', 'Great Lakes coastal retirement living near Forster-Tuncurry beaches. Independent villas with community facilities and aged care. Bowling green, pool and gardens. Perfect beachside retirement location.', '88 Lake Street', 'Forster', 'NSW', '2428', 'Independent Living, Aged Care', 320000, 480000, 140, 210, 92, 6, ARRAY['Pool', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '02 6554 7200', 'forster@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Regis Aged Care Tamworth', 'Regis Aged Care', 'Regional NSW retirement village in Tamworth. Spacious villas with country hospitality, bowling green and gardens. Independent living and residential aged care. Close to Tamworth Base Hospital and shopping centres.', '42 Marius Street', 'Tamworth', 'NSW', '2340', 'Independent Living, Aged Care', 220000, 360000, 100, 170, 86, 7, ARRAY['Bowling Green', 'Gardens', 'Community Centre', 'Library', 'Aged Care'], '02 6766 4100', 'tamworth@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Wagga Wagga', 'Respect', 'Riverina retirement community with modern facilities. Independent villas and aged care in regional city setting. Community centre, bowling green and gardens. Affordable country living near all amenities.', '88 Kincaid Street', 'Wagga Wagga', 'NSW', '2650', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 78, 6, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 6925 3100', 'wagga@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Bupa Aged Care Dubbo', 'Bupa', 'Central West retirement village with independent living and aged care. Modern villas with community facilities, bowling green and gardens. Regional affordability with quality healthcare nearby.', '142 Cobra Street', 'Dubbo', 'NSW', '2830', 'Independent Living, Aged Care', 210000, 350000, 95, 165, 94, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '1300 280 334', 'dubbo@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Nepean Shores', 'Allity', 'Penrith retirement community along Nepean River. Spacious villas with river access, fishing and walking trails. Community centre, bowling green and gardens. Enjoy riverside living with city convenience.', '21 River Road', 'Penrith', 'NSW', '2750', 'Independent Living', 340000, 490000, 150, 220, 104, 9, ARRAY['Bowling Green', 'River Access', 'Walking Trails', 'Community Centre', 'Gardens'], '02 4721 8200', 'penrith@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Grafton', 'Bolton Clarke', 'Clarence Valley retirement village in historic Grafton. Comfortable villas with jacaranda-lined street views. Community centre, gardens and chapel. Close to Grafton Base Hospital and city centre.', '88 Prince Street', 'Grafton', 'NSW', '2460', 'Independent Living, Aged Care', 240000, 380000, 110, 180, 72, 5, ARRAY['Chapel', 'Gardens', 'Community Centre', 'Library', 'Aged Care'], '1300 228 655', 'grafton@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Villa Maria Catholic Homes Bathurst', 'Villa Maria Catholic Homes', 'Central Tablelands retirement village with Catholic heritage. Independent villas with chapel, gardens and community facilities. Peaceful country setting in historic Bathurst. On-site aged care available.', '42 Ribbon Gum Drive', 'Bathurst', 'NSW', '2795', 'Independent Living, Aged Care', 220000, 360000, 100, 170, 68, 6, ARRAY['Chapel', 'Gardens', 'Community Centre', 'Library', 'Aged Care'], '02 6331 4200', 'bathurst@vmch.com.au', 'https://www.vmch.com.au', 'Active'),

('Japara The Grange Goulburn', 'Japara', 'Southern Tablelands retirement community in Goulburn. Modern villas and aged care facility. Bowling green, community centre and gardens. Cool climate living between Sydney and Canberra.', '88 Lagoon Street', 'Goulburn', 'NSW', '2580', 'Independent Living, Aged Care', 240000, 380000, 110, 180, 86, 7, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '1800 52 72 72', 'goulburn@japara.com.au', 'https://www.japara.com.au', 'Active');
