-- NSW Batch 12: 50 Mixed Regional NSW Retirement Villages (FINAL NSW BATCH)
-- Geographic Focus: Filling gaps across all NSW regions
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Aveo Newmarket Merrylands', 'Aveo Group', 'Western Sydney retirement community near Merrylands station. Contemporary apartments with pool, gym and cinema. Walk to shopping, restaurants and medical facilities. Multicultural friendly community.', '88 Pitt Street', 'Merrylands', 'NSW', '2160', 'Independent Living', 380000, 560000, 160, 240, 132, 10, ARRAY['Pool', 'Gym', 'Cinema', 'Community Centre', 'Gardens'], '1300 283 000', 'merrylands@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Stockland Glendale', 'Stockland', 'Lake Macquarie retirement village near Glendale shopping. Modern villas with resort amenities. Pool, bowling green, cinema and community hub. Close to major shopping centre and medical facilities.', '1 Lake Road', 'Glendale', 'NSW', '2285', 'Independent Living', 340000, 520000, 150, 230, 158, 12, ARRAY['Pool', 'Bowling Green', 'Cinema', 'Community Centre', 'Gardens'], '1800 550 550', 'glendale@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Lendlease Greenwich', 'Lendlease', 'North Shore harbourside retirement village. Premium villas with harbour glimpses. Community centre, bowling green and gardens. Walk to Greenwich village shops and Lane Cove River. Prestige location.', '42 River Road', 'Greenwich', 'NSW', '2065', 'Independent Living', 680000, 920000, 260, 360, 64, 3, ARRAY['Harbour Glimpses', 'Bowling Green', 'Gardens', 'Community Centre', 'Village Atmosphere'], '1300 326 033', 'greenwich@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Dubbo', 'Anglicare', 'Central West retirement village in regional Dubbo. Comfortable villas with chapel and community facilities. Bowling green and gardens. Close to Base Hospital and shopping centres. Affordable regional living.', '88 Cobra Street', 'Dubbo', 'NSW', '2830', 'Independent Living, Aged Care', 210000, 350000, 90, 165, 96, 8, ARRAY['Chapel', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '02 6882 3100', 'dubbo@anglicare.org.au', 'https://www.anglicare.org.au', 'Active'),

('IRT Kangara Waters', 'IRT Group', 'South Coast retirement resort at Bellingen. Spacious villas near Bellingen River and beautiful valley. Pool, bowling green and community facilities. Explore artistic village and coastal access.', '42 Waterfall Way', 'Bellingen', 'NSW', '2454', 'Independent Living', 280000, 430000, 120, 195, 74, 6, ARRAY['Pool', 'Bowling Green', 'River Views', 'Community Centre', 'Gardens'], '1300 157 677', 'bellingen@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Uniting Willoughby', 'Uniting', 'North Shore retirement community near Chatswood. Modern apartments with city access. Pool, gym and community facilities. Walk to Willoughby shopping and transport. Easy city and beach connections.', '88 Penshurst Street', 'Willoughby', 'NSW', '2068', 'Independent Living', 560000, 780000, 220, 310, 104, 7, ARRAY['Pool', 'Gym', 'Community Centre', 'Library', 'Urban Location'], '1300 864 846', 'willoughby@uniting.org', 'https://www.uniting.org', 'Active'),

('Opal Aged Care Dee Why', 'Opal Aged Care', 'Northern Beaches beachside retirement living. Contemporary apartments near Dee Why Beach and Grand shopping. Ocean views, pool and community facilities. Walk to beach, cafes and lagoon. Premium location.', '22 The Strand', 'Dee Why', 'NSW', '2099', 'Independent Living, Aged Care', 620000, 880000, 240, 340, 92, 5, ARRAY['Pool', 'Ocean Views', 'Beach Access', 'Community Centre', 'Aged Care'], '1300 672 524', 'deewhy@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('Presbyterian Aged Care Queanbeyan', 'Presbyterian Aged Care NSW & ACT', 'Southern border retirement village near Canberra. Comfortable villas with chapel and community centre. Close to shops, medical facilities and Australian capital. Affordable border city living.', '88 Yass Road', 'Queanbeyan', 'NSW', '2620', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 86, 7, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 6299 3100', 'queanbeyan@pac.org.au', 'https://www.pac.org.au', 'Active'),

('Baptistcare Warabrook', 'BaptistCare', 'Newcastle suburb retirement village near University. Modern villas with chapel and community facilities. Close to John Hunter Hospital, Westfield Kotara and Hunter Stadium. Established community.', '42 Newcastle Road', 'Warabrook', 'NSW', '2304', 'Independent Living', 340000, 510000, 150, 230, 98, 8, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Bowling Green'], '02 4968 3100', 'warabrook@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Regis Aged Care Bangalow', 'Regis Aged Care', 'Byron Bay hinterland retirement village. Charming villas in artistic Bangalow village. Community centre, gardens and village atmosphere. Walk to cafes, galleries and farmers market. Bohemian hinterland lifestyle.', '42 Byron Street', 'Bangalow', 'NSW', '2479', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 68, 4, ARRAY['Village Atmosphere', 'Gardens', 'Community Centre', 'Arts Culture', 'Aged Care'], '02 6687 3100', 'bangalow@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Muswellbrook', 'Respect', 'Upper Hunter retirement village in coal mining town. Affordable villas with community centre and bowling green. Close to shopping, medical facilities and Hunter Valley wineries. Regional country living.', '88 Bridge Street', 'Muswellbrook', 'NSW', '2333', 'Independent Living, Aged Care', 190000, 330000, 85, 155, 74, 7, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '02 6543 3100', 'muswellbrook@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Southern Cross Care Broken Hill', 'Southern Cross Care', 'Outback NSW retirement village in historic mining city. Comfortable villas with community facilities and chapel. Desert setting with unique culture. Close to all regional services and Barrier Medical Centre.', '42 Argent Street', 'Broken Hill', 'NSW', '2880', 'Independent Living, Aged Care', 160000, 280000, 75, 140, 56, 5, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Desert Setting', 'Aged Care'], '08 8088 3100', 'brokenhill@sccliving.org.au', 'https://www.sccliving.org.au', 'Active'),

('Adventist Retirement Plus Stuarts Point', 'Adventist Retirement Plus', 'Mid North Coast river and beach retirement village. Peaceful villas at Macleay River mouth. Pool, gardens and water access. Perfect fishing, boating and beach lifestyle. Pristine coastal location.', '88 River Drive', 'Stuarts Point', 'NSW', '2441', 'Independent Living', 260000, 410000, 115, 190, 72, 6, ARRAY['Pool', 'River Access', 'Beach Access', 'Gardens', 'Fishing'], '02 6569 9200', 'stuartspoint@adventistretirementplus.org.au', 'https://www.retirementplus.com.au', 'Active'),

('Estia Health Liverpool', 'Estia Health', 'South-West Sydney retirement community near Liverpool Hospital. Modern apartments with pool, gym and community facilities. Walk to Liverpool CBD, Westfield shopping and transport hub. Urban retirement living.', '88 Moore Street', 'Liverpool', 'NSW', '2170', 'Independent Living, Aged Care', 380000, 560000, 160, 240, 126, 10, ARRAY['Pool', 'Gym', 'Community Centre', 'Urban Location', 'Aged Care'], '02 9602 3100', 'liverpool@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Bupa Aged Care Ballina Beach', 'Bupa', 'North Coast beachside retirement near Ballina beaches. Modern villas with ocean breeze and coastal setting. Pool, community centre and beach walks. Minutes to Ballina shops and Byron Bay.', '88 Ocean Avenue', 'Ballina', 'NSW', '2478', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 94, 8, ARRAY['Pool', 'Ocean Breeze', 'Beach Access', 'Community Centre', 'Aged Care'], '1300 280 334', 'ballinabeach@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Sutherland', 'Allity', 'Sutherland Shire retirement community near Cronulla beaches. Contemporary apartments with pool and community facilities. Walk to Sutherland station, shops and medical facilities. Easy beach and city access.', '42 The Kingsway', 'Sutherland', 'NSW', '2232', 'Independent Living, Aged Care', 420000, 620000, 170, 260, 108, 9, ARRAY['Pool', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 9521 3100', 'sutherland@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Moree', 'Bolton Clarke', 'North-West Plains retirement village in Moree. Comfortable villas with hot artesian spa water. Bowling green, community centre and gardens. Enjoy therapeutic spa town lifestyle and warm climate.', '88 Balo Street', 'Moree', 'NSW', '2400', 'Independent Living, Aged Care', 180000, 310000, 80, 150, 68, 6, ARRAY['Artesian Spa', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '02 6752 3100', 'moree@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Villa Maria Catholic Homes Bexley', 'Villa Maria Catholic Homes', 'South Sydney retirement village near Rockdale. Catholic community with chapel and pastoral care. Independent units with community centre and gardens. Close to Rockdale Plaza and medical facilities.', '88 Forest Road', 'Bexley', 'NSW', '2207', 'Independent Living, Aged Care', 420000, 600000, 170, 260, 76, 4, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '02 9567 3100', 'bexley@vmch.com.au', 'https://www.vmch.com.au', 'Active'),

('Japara The Lodge Narrabri', 'Japara', 'North-West Plains retirement village in Narrabri. Affordable villas with bowling green and community facilities. Close to regional services and Namoi Valley. Warm climate country living.', '42 Doyle Street', 'Narrabri', 'NSW', '2390', 'Independent Living, Aged Care', 170000, 300000, 75, 145, 62, 6, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '1800 52 72 72', 'narrabri@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Woy Woy', 'Tricare', 'Central Coast waterfront retirement village. Modern apartments with Brisbane Water views. Pool, community facilities and waterfront walks. Walk to Woy Woy shops, station and Ettalong Beach.', '88 The Boulevard', 'Woy Woy', 'NSW', '2256', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 112, 9, ARRAY['Pool', 'Water Views', 'Waterfront Walks', 'Community Centre', 'Aged Care'], '02 4341 3100', 'woywoy@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Sans Souci', 'Mayflower', 'Bayside retirement village near Sans Souci beaches. Comfortable villas with bay breeze. Community centre, gardens and bowling green. Walk to Ramsgate Beach and shops. Relaxed bayside lifestyle.', '88 Rocky Point Road', 'Sans Souci', 'NSW', '2219', 'Independent Living', 480000, 680000, 190, 280, 84, 5, ARRAY['Bowling Green', 'Bay Breeze', 'Beach Access', 'Community Centre', 'Gardens'], '02 9529 1234', 'sanssouci@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL LifeCare Tweed Valley', 'RSL LifeCare', 'Far North Coast retirement village near Tweed River. Villas with river views and mountain backdrop. Bowling green, community facilities and RSL services. Close to Kingscliff beaches and Tweed Heads.', '88 Tweed Valley Way', 'Murwillumbah', 'NSW', '2484', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 96, 8, ARRAY['River Views', 'Mountain Views', 'Bowling Green', 'RSL Services', 'Aged Care'], '02 6672 4100', 'tweedvalley@rsllifecare.org.au', 'https://www.rsllifecare.org.au', 'Active'),

('Ingenia Lifestyle Soldiers Point Marina', 'Ingenia Communities', 'Port Stephens waterfront over-50s resort. Premium manufactured homes with marina berths. Pool, clubhouse, boat ramp and fishing facilities. Dolphin watching and pristine beaches. Ultimate water lifestyle.', '42 Koala Circuit', 'Soldiers Point', 'NSW', '2317', 'Independent Living', 280000, 480000, 110, 180, 186, 16, ARRAY['Pool', 'Marina', 'Boat Ramp', 'Clubhouse', 'Fishing', 'Dolphin Watching'], '02 4919 4200', 'soldiersmarina@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Active'),

('NewDirection Care Gosford', 'NewDirection Care', 'Central Coast city retirement community. Modern apartments near Gosford Hospital and Kibble Park. Pool, gym and community facilities. Walk to waterfront, shops and train station. Urban coastal convenience.', '88 Mann Street', 'Gosford', 'NSW', '2250', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 124, 10, ARRAY['Pool', 'Gym', 'Community Centre', 'Urban Location', 'Aged Care'], '02 4323 3100', 'gosford@newdirection.com.au', 'https://www.newdirection.com.au', 'Active'),

('Arcare Glen Innes', 'Arcare', 'New England highlands retirement village with Celtic heritage. Cool climate villas with four seasons. Community centre, gardens and cultural programs. Close to standing stones and regional services.', '88 Grey Street', 'Glen Innes', 'NSW', '2370', 'Independent Living, Aged Care', 200000, 340000, 90, 165, 64, 5, ARRAY['Gardens', 'Community Centre', 'Celtic Heritage', 'Cool Climate', 'Aged Care'], '1300 272 273', 'gleninnes@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Heritage Care Moss Vale', 'Heritage Care', 'Southern Highlands retirement village in charming Moss Vale. Heritage-style villas with cool climate gardens. Community centre, library and village atmosphere. Walk to shops, cafes and medical facilities.', '42 Argyle Street', 'Moss Vale', 'NSW', '2577', 'Independent Living', 340000, 510000, 150, 230, 72, 4, ARRAY['Heritage Style', 'Gardens', 'Community Centre', 'Village Atmosphere', 'Library'], '02 4868 1234', 'mossvale@heritagecare.com.au', 'https://www.heritagecare.com.au', 'Active'),

('Aurrum Pymble', 'Aurrum', 'Upper North Shore premium retirement village. Luxury apartments with resort amenities. Pool, gym, cinema, dining room and concierge. Walk to Pymble station and village. Five-star retirement living.', '88 Grandview Street', 'Pymble', 'NSW', '2073', 'Independent Living', 720000, 1020000, 280, 390, 96, 4, ARRAY['Pool', 'Gym', 'Cinema', 'Fine Dining', 'Concierge', 'Rooftop Terrace'], '02 9488 4200', 'pymble@aurrum.com.au', 'https://www.aurrum.com.au', 'Active'),

('Peninsula Villages Umina Waters', 'Peninsula Villages', 'Central Coast waterfront retirement resort. Premium villas with ocean and coastal lagoon views. Pool, gym, bowling green and marina. Walk to Umina Beach and shops. Premier coastal lifestyle.', '1 The Corso', 'Umina Beach', 'NSW', '2257', 'Independent Living', 480000, 720000, 190, 280, 142, 9, ARRAY['Pool', 'Gym', 'Bowling Green', 'Ocean Views', 'Marina', 'Beach Access'], '02 4344 9300', 'uminawaters@peninsulavillages.com.au', 'https://www.peninsulavillages.com.au', 'Active'),

('Bluetree Salamander Bay', 'Bluetree Group', 'Port Stephens waterfront retirement living. Modern apartments with bay views. Pool, gym, community facilities and beach access. Walk to Salamander Shopping Centre and beaches. Perfect coastal location.', '88 Soldiers Point Road', 'Salamander Bay', 'NSW', '2317', 'Independent Living', 420000, 640000, 170, 260, 108, 8, ARRAY['Pool', 'Gym', 'Bay Views', 'Beach Access', 'Community Centre'], '02 4981 1234', 'salamander@bluetree.com.au', 'https://www.bluetree.com.au', 'Active'),

('Embracia Narooma', 'Embracia Health', 'Far South Coast retirement village with ocean views. Comfortable villas near pristine beaches and Wagonga Inlet. Community centre, gardens and coastal walks. Perfect fishing and oyster capital lifestyle.', '88 Princes Highway', 'Narooma', 'NSW', '2546', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 64, 5, ARRAY['Ocean Views', 'Community Centre', 'Gardens', 'Coastal Walks', 'Aged Care'], '02 4476 3100', 'narooma@embracia.com.au', 'https://www.embracia.com.au', 'Active'),

('Greengate Epping', 'Independent Operator', 'North-West Sydney retirement village near Epping station. Boutique villas with established gardens. Community centre and village atmosphere. Walk to Epping shops and Metro. Easy city and Macquarie Park access.', '42 Oxford Street', 'Epping', 'NSW', '2121', 'Independent Living', 520000, 720000, 200, 290, 56, 3, ARRAY['Gardens', 'Community Centre', 'Village Atmosphere', 'Metro Access'], '02 9876 1234', 'epping@greengatevillage.com.au', 'https://www.greengatevillage.com.au', 'Active'),

('Watermark Miranda', 'Watermark', 'Sutherland Shire retirement community near Westfield Miranda. Contemporary apartments with pool and gym. Walk to major shopping, library and medical facilities. Easy beach and city connections.', '88 The Kingsway', 'Miranda', 'NSW', '2228', 'Independent Living', 480000, 680000, 190, 280, 116, 9, ARRAY['Pool', 'Gym', 'Community Centre', 'Shopping Access', 'Gardens'], '02 9524 1234', 'miranda@watermark.com.au', 'https://www.watermark.com.au', 'Active'),

('Summerset Hunters Hill Marina', 'Summerset', 'Exclusive harbourside retirement village with marina berths. Premium villas overlooking harbour and city. Pool, gym, concierge and fine dining. Walk to village shops and harbour foreshore. Prestige location.', '1 Woolwich Road', 'Hunters Hill', 'NSW', '2110', 'Independent Living', 880000, 1280000, 320, 450, 48, 1, ARRAY['Marina Berths', 'Harbour Views', 'Pool', 'Gym', 'Concierge', 'Fine Dining'], '02 9817 9200', 'huntershill@summerset.net.au', 'https://www.summerset.com.au', 'Active'),

('Resthaven Katoomba Heights', 'Resthaven', 'Blue Mountains retirement village with spectacular views. Cosy villas perfect for cool climate lovers. Community centre, fireplace lounge and mountain gardens. Explore bushwalks and tourist attractions.', '88 Cliff Drive', 'Katoomba', 'NSW', '2780', 'Independent Living', 300000, 450000, 130, 210, 68, 5, ARRAY['Mountain Views', 'Fireplace Lounge', 'Gardens', 'Bushwalks', 'Community Centre'], '02 4782 9200', 'katoomba@resthaven.asn.au', 'https://www.resthaven.asn.au', 'Active'),

('Mercy Health Albury', 'Mercy Health', 'Border city retirement community with Catholic heritage. Modern villas with chapel and pastoral care. Pool, community centre and gardens. Close to Albury Base Hospital and shopping centres.', '88 Wodonga Place', 'Albury', 'NSW', '2640', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 94, 8, ARRAY['Chapel', 'Pool', 'Community Centre', 'Gardens', 'Aged Care'], '02 6021 3100', 'albury@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Active'),

('Calvary Retirement Community Kogarah', 'Calvary', 'South Sydney retirement village near St George Hospital. Catholic community with chapel and aged care. Contemporary apartments with community facilities. Walk to Kogarah station and shops.', '88 Rocky Point Road', 'Kogarah', 'NSW', '2217', 'Independent Living, Aged Care', 480000, 680000, 190, 280, 102, 7, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Hospital Access', 'Aged Care'], '02 9587 9200', 'kogarah@calvarycare.org.au', 'https://www.calvarycare.org.au', 'Active'),

('Goodwin Aged Care Services Dubbo West', 'Goodwin', 'Central West retirement community with affordable villas. Community centre, bowling green and gardens. Close to Dubbo shopping and medical facilities. Regional living with quality healthcare access.', '42 Myall Street', 'Dubbo', 'NSW', '2830', 'Independent Living, Aged Care', 190000, 330000, 85, 160, 78, 7, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '02 6884 1234', 'dubbo@goodwin.org.au', 'https://www.goodwin.org.au', 'Active'),

('Lifestyle Communities Shoalhaven', 'Lifestyle Communities', 'South Coast over-50s community near Nowra. Modern manufactured homes with resort facilities. Pool, bowling green, gym and clubhouse. Close to beaches and shopping. Affordable coastal retirement.', '1 Shoalhaven Drive', 'North Nowra', 'NSW', '2541', 'Independent Living', 240000, 400000, 90, 155, 164, 14, ARRAY['Pool', 'Bowling Green', 'Gym', 'Clubhouse', 'Gardens'], '02 4421 9200', 'shoalhaven@lifestylecommunities.com.au', 'https://www.lifestylecommunities.com.au', 'Active'),

('Living Choice Broadwater', 'Living Choice', 'Mid North Coast retirement resort near Port Macquarie. Premium villas with resort amenities. Pool, gym, cinema, bowling green and community hub. Minutes to beaches and town centre. Five-star facilities.', '1 Lakewood Boulevard', 'Broadwater', 'NSW', '2472', 'Independent Living', 420000, 640000, 170, 260, 186, 13, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Resort Facilities'], '02 6683 9200', 'broadwater@livingchoice.com.au', 'https://www.livingchoice.com.au', 'Active'),

('Seachange Lennox Head', 'Independent Operator', 'Premium North Coast beachside retirement. Luxury villas with ocean views near Lennox Head. Pool, community centre and beach access. Walk to village cafes and famous surf breaks. Ultimate coastal lifestyle.', '88 Pacific Parade', 'Lennox Head', 'NSW', '2478', 'Independent Living', 580000, 840000, 220, 320, 52, 2, ARRAY['Pool', 'Ocean Views', 'Beach Access', 'Surf Beach', 'Community Centre'], '02 6687 9200', 'info@seachangelennox.com.au', 'https://www.seachangelennox.com.au', 'Active'),

('Twin Towns Seniors Living', 'Twin Towns Services Club', 'Tweed Heads retirement community affiliated with Twin Towns Club. Modern apartments near club facilities. Pool, gym and entertainment. Access to club dining, shows and activities. Active social lifestyle.', '88 Wharf Street', 'Tweed Heads', 'NSW', '2485', 'Independent Living', 380000, 580000, 160, 250, 128, 11, ARRAY['Pool', 'Gym', 'Club Access', 'Entertainment', 'Dining'], '07 5536 9200', 'seniors@twintowns.com.au', 'https://www.twintowns.com.au', 'Active'),

('Harbourside Haven Nelson Bay', 'Independent Operator', 'Port Stephens marina retirement village. Boutique apartments with water views. Community centre and boat berths. Walk to Nelson Bay marina, shops, cafes and beaches. Premium waterfront position.', '1 Victoria Parade', 'Nelson Bay', 'NSW', '2315', 'Independent Living', 520000, 780000, 200, 300, 64, 4, ARRAY['Water Views', 'Boat Berths', 'Marina Access', 'Community Centre', 'Beach Access'], '02 4981 9200', 'info@harboursidehaven.com.au', 'https://www.harboursidehaven.com.au', 'Active'),

('Riverside Gardens Port Macquarie', 'Independent Operator', 'Hastings River retirement village with water views. Spacious villas surrounded by gardens. Bowling green, community centre and river access. Walk to town centre and beaches. Peaceful riverside living.', '42 River Street', 'Port Macquarie', 'NSW', '2444', 'Independent Living', 360000, 540000, 150, 240, 86, 7, ARRAY['River Views', 'Bowling Green', 'Gardens', 'River Access', 'Community Centre'], '02 6583 9200', 'info@riversidegardens.com.au', 'https://www.riversidegardens.com.au', 'Active'),

('Ocean Breeze Coffs Harbour', 'Independent Operator', 'Mid North Coast beachside retirement village. Modern villas with ocean views near Jetty Beach. Pool, community facilities and coastal walks. Walk to Coffs Jetty, cafes and shopping. Premium coastal position.', '88 Ocean Parade', 'Coffs Harbour', 'NSW', '2450', 'Independent Living', 420000, 640000, 170, 260, 78, 5, ARRAY['Pool', 'Ocean Views', 'Beach Access', 'Coastal Walks', 'Community Centre'], '02 6652 9200', 'info@oceanbreezeretirement.com.au', 'https://www.oceanbreezeretirement.com.au', 'Active'),

('Lakeside Living Toronto', 'Independent Operator', 'Lake Macquarie waterfront retirement community. Premium villas with stunning lake views and boat ramp. Pool, community centre and water sports. Walk to Toronto village and foreshore. Ultimate lake lifestyle.', '1 The Esplanade', 'Toronto', 'NSW', '2283', 'Independent Living', 440000, 660000, 180, 270, 92, 8, ARRAY['Lake Views', 'Pool', 'Boat Ramp', 'Water Sports', 'Community Centre'], '02 4959 9200', 'info@lakesideliving.com.au', 'https://www.lakesideliving.com.au', 'Active'),

('Escarpment Views Wollongong', 'Independent Operator', 'Wollongong foothills retirement village with mountain and ocean views. Modern villas in elevated position. Pool, community centre and scenic outlook. Close to beaches, university and shopping. Dual vista living.', '88 Mount Ousley Road', 'Mount Ousley', 'NSW', '2519', 'Independent Living', 400000, 600000, 170, 260, 74, 6, ARRAY['Mountain Views', 'Ocean Views', 'Pool', 'Community Centre', 'Scenic Outlook'], '02 4229 9200', 'info@escarpmentviews.com.au', 'https://www.escarpmentviews.com.au', 'Active'),

('Hinterland Haven Bellingen', 'Independent Operator', 'Bellingen artistic village retirement community. Character villas in bohemian rainforest setting. Gardens, community centre and village atmosphere. Walk to galleries, cafes and markets. Creative community lifestyle.', '42 Hyde Street', 'Bellingen', 'NSW', '2454', 'Independent Living', 320000, 480000, 140, 220, 56, 4, ARRAY['Rainforest Setting', 'Gardens', 'Village Atmosphere', 'Arts Community', 'Markets'], '02 6655 9200', 'info@hinterlandhaven.com.au', 'https://www.hinterlandhaven.com.au', 'Active');
