-- QLD Batch 01: 25 Brisbane Metro Retirement Villages
-- Geographic Focus: Brisbane Inner City, Bayside, Logan, Ipswich
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Aveo Durack', 'Aveo Group', 'Western Brisbane retirement community near Inala shopping. Modern villas with pool, gym and community facilities. Close to Centenary Motorway and medical facilities. Affordable Brisbane living.', '88 Blunder Road', 'Durack', 'QLD', '4077', 'Independent Living', 340000, 520000, 150, 230, 142, 12, ARRAY['Pool', 'Gym', 'Community Centre', 'Gardens', 'Shopping Access'], '1300 283 000', 'durack@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Stockland Retirement Keperra', 'Stockland', 'Northern Brisbane retirement village near Brookside shopping. Contemporary villas with resort amenities. Pool, gym, bowling green and community hub. Close to shops, medical facilities and transport. Convenient northern location.', '1 Settlement Drive', 'Keperra', 'QLD', '4054', 'Independent Living', 380000, 580000, 160, 250, 168, 14, ARRAY['Pool', 'Gym', 'Bowling Green', 'Community Centre', 'Gardens'], '1800 550 550', 'keperra@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Lendlease Newstead', 'Lendlease', 'Premium inner-city Brisbane retirement living. Luxury apartments with river and city views. Rooftop terrace, pool, gym, cinema and fine dining. Walk to Gasworks Plaza, restaurants and ferries. Ultimate urban lifestyle.', '88 Commercial Road', 'Newstead', 'QLD', '4006', 'Independent Living', 720000, 1020000, 280, 390, 112, 6, ARRAY['River Views', 'Rooftop Terrace', 'Pool', 'Gym', 'Cinema', 'Fine Dining', 'Concierge'], '1300 326 033', 'newstead@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Wooloowin', 'Anglicare', 'Inner northern Brisbane retirement community. Independent villas with chapel and community facilities. Close to Wooloowin station, Kedron shops and medical facilities. Established inner-north community.', '42 Maygar Street', 'Wooloowin', 'QLD', '4030', 'Independent Living, Aged Care', 420000, 620000, 170, 260, 96, 7, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Station Access', 'Aged Care'], '07 3357 3100', 'wooloowin@anglicaresq.org.au', 'https://www.anglicaresq.org.au', 'Active'),

('Baptistcare Ashgrove', 'BaptistCare', 'Western suburbs retirement village in leafy Ashgrove. Comfortable villas with chapel and bowling green. Community centre and gardens. Close to Ashgrove Shopping Village and medical facilities. Established family area.', '88 Waterworks Road', 'Ashgrove', 'QLD', '4060', 'Independent Living, Aged Care', 440000, 660000, 180, 270, 94, 6, ARRAY['Chapel', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '07 3366 3100', 'ashgrove@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Uniting AgeWell Sandgate', 'Uniting AgeWell', 'Bayside Brisbane retirement near beaches. Modern villas with bay breezes. Pool, community facilities and coastal walks. Walk to Sandgate village, Shorncliffe Pier and beaches. Bayside lifestyle living.', '88 Brighton Road', 'Sandgate', 'QLD', '4017', 'Independent Living', 420000, 640000, 170, 260, 108, 8, ARRAY['Pool', 'Bay Breezes', 'Beach Access', 'Community Centre', 'Coastal Walks'], '1300 783 435', 'sandgate@unitingagewell.org', 'https://www.unitingagewell.org', 'Active'),

('Opal Aged Care Carindale', 'Opal Aged Care', 'Eastern suburbs retirement near Westfield Carindale. Contemporary apartments with pool, gym and cinema. Walk to major shopping, library and medical facilities. Premium eastside location.', '42 Old Cleveland Road', 'Carindale', 'QLD', '4152', 'Independent Living, Aged Care', 480000, 700000, 190, 290, 126, 10, ARRAY['Pool', 'Gym', 'Cinema', 'Shopping Access', 'Community Centre', 'Aged Care'], '1300 672 524', 'carindale@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Lutwyche', 'IRT Group', 'Inner northern Brisbane retirement community. Modern villas near Lutwyche City shopping centre. Pool, community facilities and gardens. Walk to shops, medical facilities and Lutwyche bus station. Inner-city convenience.', '88 Lutwyche Road', 'Lutwyche', 'QLD', '4030', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 104, 8, ARRAY['Pool', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '1300 157 677', 'lutwyche@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Regis Aged Care Indooroopilly', 'Regis Aged Care', 'Western suburbs retirement near Indooroopilly Shopping Centre. Quality villas with community facilities and aged care. Close to University of Queensland, shops and medical facilities. Premium western location.', '88 Moggill Road', 'Indooroopilly', 'QLD', '4068', 'Independent Living, Aged Care', 520000, 760000, 200, 300, 98, 6, ARRAY['Community Centre', 'Gardens', 'University Access', 'Shopping Access', 'Aged Care'], '07 3878 3100', 'indooroopilly@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Logan', 'Respect', 'Southern Brisbane retirement community in Logan. Affordable villas with multicultural community. Pool, community centre and gardens. Close to Logan Hyperdome shopping and Logan Hospital. Growth corridor living.', '42 Wembley Road', 'Logan Central', 'QLD', '4114', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 132, 12, ARRAY['Pool', 'Community Centre', 'Gardens', 'Cultural Diversity', 'Aged Care'], '07 3299 3100', 'logan@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Arcare Yeronga', 'Arcare', 'Inner southern Brisbane retirement community. Contemporary apartments near Yeronga train station. Pool, gym and community facilities. Walk to Fairfield shops, medical facilities and river. Inner-city convenience.', '88 Kadumba Street', 'Yeronga', 'QLD', '4104', 'Independent Living, Aged Care', 480000, 700000, 190, 290, 92, 7, ARRAY['Pool', 'Gym', 'Station Access', 'Community Centre', 'Aged Care'], '1300 272 273', 'yeronga@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Bupa Aged Care Ipswich', 'Bupa', 'Western corridor retirement community in Ipswich. Modern villas near Riverlink shopping. Pool, community facilities and gardens. Close to Ipswich Hospital and historical attractions. Affordable regional city living.', '88 Brisbane Street', 'Ipswich', 'QLD', '4305', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 118, 11, ARRAY['Pool', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '1300 280 334', 'ipswich@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Chermside', 'Allity', 'Northern suburbs retirement near Westfield Chermside. Contemporary apartments with pool and gym. Walk to major shopping centre, Prince Charles Hospital and transport. Prime northern location.', '42 Gympie Road', 'Chermside', 'QLD', '4032', 'Independent Living, Aged Care', 440000, 660000, 180, 270, 108, 9, ARRAY['Pool', 'Gym', 'Shopping Access', 'Hospital Access', 'Aged Care'], '07 3350 3100', 'chermside@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Nundah', 'Bolton Clarke', 'Inner eastern Brisbane retirement community. Quality villas near Nundah Village and train station. Community centre, gardens and aged care. Walk to shops, cafes and medical facilities. Village atmosphere.', '88 Bage Street', 'Nundah', 'QLD', '4012', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 96, 7, ARRAY['Village Atmosphere', 'Station Access', 'Community Centre', 'Gardens', 'Aged Care'], '1300 228 655', 'nundah@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Estia Health Wynnum', 'Estia Health', 'Bayside Brisbane retirement near beaches. Modern villas with bay breezes. Pool, community facilities and waterfront access. Walk to Wynnum Esplanade, shops and ferry. Bayside lifestyle.', '88 Florence Street', 'Wynnum', 'QLD', '4178', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 102, 8, ARRAY['Pool', 'Bay Breezes', 'Waterfront Access', 'Community Centre', 'Aged Care'], '07 3393 3100', 'wynnum@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Coorparoo', 'Japara', 'Inner eastern Brisbane retirement community. Modern apartments near Coorparoo Square. Pool, community facilities and urban amenities. Walk to shops, restaurants and Old Cleveland Road. Inner-city convenience.', '88 Old Cleveland Road', 'Coorparoo', 'QLD', '4151', 'Independent Living, Aged Care', 460000, 680000, 190, 280, 88, 6, ARRAY['Pool', 'Urban Location', 'Shopping Access', 'Community Centre', 'Aged Care'], '1800 52 72 72', 'coorparoo@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Springwood', 'Tricare', 'Southern Brisbane retirement community near Logan Hyperdome. Modern villas with pool and community facilities. Close to shopping, medical facilities and Springwood station. Convenient southern location.', '42 Rochedale Road', 'Springwood', 'QLD', '4127', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 114, 10, ARRAY['Pool', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '07 3341 3100', 'springwood@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Tarragindi', 'Mayflower', 'Southern suburbs retirement village. Comfortable villas with community facilities. Bowling green, gardens and village atmosphere. Close to Holland Park and Sunnybank shopping. Established southern community.', '88 Toohey Road', 'Tarragindi', 'QLD', '4121', 'Independent Living', 400000, 600000, 170, 260, 84, 7, ARRAY['Bowling Green', 'Gardens', 'Village Atmosphere', 'Community Centre'], '07 3349 1234', 'tarragindi@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care Greenslopes', 'RSL Care', 'Inner southern Brisbane retirement with veterans services. Quality villas near Greenslopes Private Hospital. Bowling green, community facilities and RSL services. Close to medical precinct and shopping.', '42 Newdegate Street', 'Greenslopes', 'QLD', '4120', 'Independent Living, Aged Care', 480000, 700000, 190, 290, 92, 6, ARRAY['Bowling Green', 'Hospital Access', 'RSL Services', 'Community Centre', 'Aged Care'], '07 3394 3100', 'greenslopes@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('BlueCare Paddington', 'BlueCare', 'Inner-city retirement community in prestigious Paddington. Heritage-style apartments near Given Terrace. Community facilities and village atmosphere. Walk to boutique shops, cafes and Suncorp Stadium. Elite inner-city address.', '88 Given Terrace', 'Paddington', 'QLD', '4064', 'Independent Living', 580000, 840000, 220, 320, 68, 3, ARRAY['Heritage Style', 'Village Atmosphere', 'Shopping Access', 'Stadium Access'], '07 3367 1234', 'paddington@bluecare.org.au', 'https://www.bluecare.org.au', 'Active'),

('Mercy Health Beenleigh', 'Mercy Health', 'Southern corridor retirement community. Catholic heritage with chapel and pastoral care. Modern villas with community facilities and aged care. Close to Beenleigh Marketplace and Logan Hospital.', '88 Main Street', 'Beenleigh', 'QLD', '4207', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 106, 9, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '07 3287 3100', 'beenleigh@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Active'),

('Benetas Redcliffe', 'Benetas', 'Peninsula bayside retirement community. Modern villas near beaches and Redcliffe waterfront. Pool, community facilities and ocean breezes. Walk to Settlement Cove, shops and medical facilities. Bayside peninsula lifestyle.', '88 Anzac Avenue', 'Redcliffe', 'QLD', '4020', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 116, 10, ARRAY['Pool', 'Ocean Breezes', 'Waterfront Access', 'Community Centre', 'Aged Care'], '07 3284 3100', 'redcliffe@benetas.com.au', 'https://www.benetas.com.au', 'Active'),

('Embracia Manly', 'Embracia Health', 'Bayside Brisbane retirement near harbour and beaches. Modern villas with waterfront proximity. Pool, community facilities and coastal walks. Walk to Manly Harbour Village, marina and waterfront dining. Premium bayside position.', '42 Cambridge Parade', 'Manly', 'QLD', '4179', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 94, 7, ARRAY['Pool', 'Waterfront Access', 'Marina Views', 'Coastal Walks', 'Aged Care'], '07 3396 3100', 'manly@embracia.com.au', 'https://www.embracia.com.au', 'Active'),

('Warrigal Care Mount Gravatt', 'Warrigal Care', 'Southern Brisbane retirement community near Garden City shopping. Modern villas with pool and community facilities. Close to major shopping centre, medical facilities and transport. Convenient southern location.', '88 Logan Road', 'Mount Gravatt', 'QLD', '4122', 'Independent Living, Aged Care', 400000, 600000, 170, 260, 108, 9, ARRAY['Pool', 'Shopping Access', 'Community Centre', 'Gardens', 'Aged Care'], '07 3349 4100', 'mountgravatt@warrigal.com.au', 'https://www.warrigal.com.au', 'Active'),

('Living Choice Alloura Waters', 'Living Choice', 'Eastern Brisbane waterfront retirement resort. Premium villas with lake views and resort amenities. Pool, gym, cinema, bowling green and community hub. Minutes to Gateway Motorway and Port of Brisbane.', '1 Lakeside Drive', 'Lytton', 'QLD', '4178', 'Independent Living', 480000, 720000, 190, 280, 152, 12, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Lake Views', 'Resort Amenities'], '07 3899 1234', 'allourawaters@livingchoice.com.au', 'https://www.livingchoice.com.au', 'Active');
