-- QLD Batch 04: 25 Regional QLD Retirement Villages
-- Geographic Focus: Toowoomba, Ipswich, Logan, Scenic Rim, Darling Downs
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Aveo Toowoomba', 'Aveo Group', 'Darling Downs regional city retirement. Modern villas with mountain views. Pool, gym, bowling green and community facilities. Close to Grand Central shopping, hospital and Range. Garden city living.', '88 Ruthven Street', 'Toowoomba', 'QLD', '4350', 'Independent Living', 300000, 460000, 130, 210, 142, 12, ARRAY['Pool', 'Gym', 'Bowling Green', 'Mountain Views', 'Community Centre'], '1300 283 000', 'toowoomba@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Stockland Springfield', 'Stockland', 'Western corridor retirement resort. Contemporary villas in master-planned community. Pool, gym, cinema, bowling green and community hub. Close to Orion shopping, medical facilities and train. Growth city living.', '1 Springfield Central Boulevard', 'Springfield Central', 'QLD', '4300', 'Independent Living', 360000, 540000, 150, 240, 186, 15, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Community Centre', 'Train Access'], '1800 550 550', 'springfield@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Lendlease Heritage Park Logan', 'Lendlease', 'Logan central retirement community. Quality villas near Heritage Park shopping. Pool, bowling green and community facilities. Close to Logan Hospital and medical facilities. Regional accessibility.', '42 Heritage Park Drive', 'Heritage Park', 'QLD', '4118', 'Independent Living', 320000, 480000, 140, 220, 124, 11, ARRAY['Pool', 'Bowling Green', 'Shopping Access', 'Hospital Access', 'Community Centre'], '1300 326 033', 'logan@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Gatton', 'Anglicare', 'Lockyer Valley rural retirement village. Independent villas with chapel and community facilities. Beautiful country gardens and bowling green. Close to Gatton town centre and medical facilities. Rural lifestyle.', '88 William Street', 'Gatton', 'QLD', '4343', 'Independent Living, Aged Care', 220000, 360000, 95, 165, 84, 8, ARRAY['Chapel', 'Bowling Green', 'Country Gardens', 'Rural Setting', 'Aged Care'], '07 5462 3100', 'gatton@anglicaresq.org.au', 'https://www.anglicaresq.org.au', 'Active'),

('Baptistcare Beenleigh', 'BaptistCare', 'Southern corridor retirement community. Modern villas with chapel and community facilities. Pool, gardens and aged care. Close to Beenleigh Marketplace and Logan Hospital. Regional corridor living.', '88 City Road', 'Beenleigh', 'QLD', '4207', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 102, 9, ARRAY['Pool', 'Chapel', 'Community Centre', 'Gardens', 'Aged Care'], '07 3807 3100', 'beenleigh@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Uniting AgeWell Beaudesert', 'Uniting AgeWell', 'Scenic Rim retirement village. Comfortable villas with mountain views. Community centre, gardens and bowling green. Close to Beaudesert town centre and medical facilities. Country town lifestyle.', '88 Brisbane Street', 'Beaudesert', 'QLD', '4285', 'Independent Living', 260000, 410000, 115, 190, 76, 7, ARRAY['Bowling Green', 'Mountain Views', 'Community Centre', 'Gardens'], '1300 783 435', 'beaudesert@unitingagewell.org', 'https://www.unitingagewell.org', 'Active'),

('Opal Aged Care Warwick', 'Opal Aged Care', 'Southern Downs retirement community. Modern villas in heritage Rose City. Pool, community facilities and gardens. Close to Warwick Hospital and historic centre. Country city living.', '42 Palmerin Street', 'Warwick', 'QLD', '4370', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 88, 8, ARRAY['Pool', 'Heritage Setting', 'Community Centre', 'Gardens', 'Aged Care'], '1300 672 524', 'warwick@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Dalby', 'IRT Group', 'Western Downs retirement village. Affordable villas in regional farming centre. Community facilities, bowling green and gardens. Close to Dalby Hospital and shopping. Rural city living.', '88 Cunningham Street', 'Dalby', 'QLD', '4405', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 74, 7, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Regional Setting', 'Aged Care'], '1300 157 677', 'dalby@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Regis Aged Care Toowoomba Heights', 'Regis Aged Care', 'Darling Downs retirement on Range escarpment. Quality villas with valley views. Community facilities, bowling green and aged care. Close to shops, medical facilities and scenic lookouts.', '88 Range Street', 'Toowoomba', 'QLD', '4350', 'Independent Living, Aged Care', 320000, 480000, 140, 220, 96, 8, ARRAY['Bowling Green', 'Valley Views', 'Community Centre', 'Gardens', 'Aged Care'], '07 4632 3100', 'toowoombahts@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Jimboomba', 'Respect', 'Scenic Rim growth corridor retirement. Affordable villas in developing area. Pool, community centre and gardens. Close to shopping and medical facilities. Growth corridor affordability.', '42 Brisbane Street', 'Jimboomba', 'QLD', '4280', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 118, 11, ARRAY['Pool', 'Community Centre', 'Gardens', 'Growth Corridor', 'Aged Care'], '07 5547 3100', 'jimboomba@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Arcare Browns Plains', 'Arcare', 'Southern Logan retirement community. Contemporary villas near Grand Plaza shopping. Pool, gym and community facilities. Close to shopping centres and medical facilities. Regional corridor convenience.', '1 Mt Lindesay Highway', 'Browns Plains', 'QLD', '4118', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 126, 12, ARRAY['Pool', 'Gym', 'Shopping Access', 'Community Centre', 'Aged Care'], '1300 272 273', 'brownsplains@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Bupa Aged Care Kingaroy', 'Bupa', 'South Burnett peanut capital retirement. Comfortable villas in regional centre. Community facilities, bowling green and gardens. Close to Kingaroy Hospital and shopping. Country town lifestyle.', '88 Haly Street', 'Kingaroy', 'QLD', '4610', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 68, 6, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Regional Setting', 'Aged Care'], '1300 280 334', 'kingaroy@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Loganlea', 'Allity', 'Southern corridor retirement community. Modern villas near Logan City shopping. Pool, community facilities and gardens. Close to medical facilities and transport. Corridor accessibility.', '88 Bryants Road', 'Loganlea', 'QLD', '4131', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 108, 10, ARRAY['Pool', 'Shopping Access', 'Community Centre', 'Gardens', 'Aged Care'], '07 3290 3100', 'loganlea@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Chinchilla', 'Bolton Clarke', 'Western Downs retirement village. Affordable villas in regional town. Community centre, gardens and aged care. Close to town centre and medical facilities. Rural Queensland living.', '88 Heeney Street', 'Chinchilla', 'QLD', '4413', 'Independent Living, Aged Care', 180000, 310000, 80, 150, 62, 6, ARRAY['Community Centre', 'Gardens', 'Regional Setting', 'Aged Care'], '1300 228 655', 'chinchilla@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Estia Health Stanthorpe', 'Estia Health', 'Granite Belt retirement village. Cool climate villas in wine country. Pool, community facilities and gardens. Close to Stanthorpe town centre, wineries and medical facilities. Four seasons living.', '88 High Street', 'Stanthorpe', 'QLD', '4380', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 72, 7, ARRAY['Pool', 'Cool Climate', 'Wine Country', 'Community Centre', 'Aged Care'], '07 4681 3100', 'stanthorpe@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Redbank Plains', 'Japara', 'Western corridor retirement community. Modern villas near Redbank Plaza. Community facilities and aged care. Close to shopping centres and medical facilities. Corridor convenience.', '42 Redbank Plains Road', 'Redbank Plains', 'QLD', '4301', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 94, 9, ARRAY['Shopping Access', 'Community Centre', 'Gardens', 'Aged Care'], '1800 52 72 72', 'redbankplains@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Goodna', 'Tricare', 'Western corridor retirement community. Comfortable villas near Ipswich Riverlink. Pool, community facilities and gardens. Close to shopping, medical facilities and transport. Regional accessibility.', '88 Queen Street', 'Goodna', 'QLD', '4300', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 102, 10, ARRAY['Pool', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '07 3818 3100', 'goodna@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Laidley', 'Mayflower', 'Lockyer Valley rural retirement village. Peaceful villas in farming district. Community centre, gardens and country atmosphere. Close to Laidley town centre and medical facilities. Rural Queensland lifestyle.', '88 Patrick Street', 'Laidley', 'QLD', '4341', 'Independent Living', '200000', 340000, 90, 160, 64, 6, ARRAY['Country Setting', 'Community Centre', 'Gardens', 'Rural Lifestyle'], '07 5465 1234', 'laidley@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care Toowoomba', 'RSL Care', 'Darling Downs retirement with veterans services. Quality villas near Toowoomba Base Hospital. Bowling green, community facilities and RSL services. Close to shopping and medical precinct.', '42 Tor Street', 'Toowoomba', 'QLD', '4350', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 104, 9, ARRAY['Bowling Green', 'Hospital Access', 'RSL Services', 'Community Centre', 'Aged Care'], '07 4639 3100', 'toowoomba@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('BlueCare Highfields', 'BlueCare', 'Toowoomba escarpment retirement community. Modern villas with Range views. Pool, community facilities and mountain atmosphere. Close to Highfields shops and medical facilities. Escarpment lifestyle.', '88 Highfields Road', 'Highfields', 'QLD', '4352', 'Independent Living', 320000, 480000, 140, 220, 86, 8, ARRAY['Pool', 'Range Views', 'Mountain Setting', 'Community Centre'], '07 4615 1234', 'highfields@bluecare.org.au', 'https://www.bluecare.org.au', 'Active'),

('Mercy Health Woodridge', 'Mercy Health', 'Southern Logan retirement community. Catholic heritage with chapel and pastoral care. Modern villas with community facilities and aged care. Close to Logan Hyperdome and medical facilities.', '88 Wembley Road', 'Woodridge', 'QLD', '4114', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 112, 11, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '07 3808 3100', 'woodridge@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Active'),

('Living Choice Glenvale', 'Living Choice', 'Toowoomba retirement resort. Premium villas with resort amenities. Pool, gym, cinema, bowling green and community hub. Close to Toowoomba Hospital, shopping and Range attractions.', '1 Range View Drive', 'Glenvale', 'QLD', '4350', 'Independent Living', 360000, 540000, 150, 240, 148, 12, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Range Views'], '07 4636 1234', 'glenvale@livingchoice.com.au', 'https://www.livingchoice.com.au', 'Active'),

('Palm Lake Resort Bethania', 'Palm Lake Resort', 'Southern corridor over-50s resort. Modern manufactured homes with resort facilities. Pool, tennis, bowling green and clubhouse. Close to Hyperdome shopping and medical facilities. Affordable resort living.', '1 Gowan Road', 'Bethania', 'QLD', '4205', 'Independent Living', 240000, 400000, 95, 160, 186, 15, ARRAY['Pool', 'Tennis Courts', 'Bowling Green', 'Clubhouse', 'Gardens'], '07 3804 9200', 'bethania@palmlakeresort.com.au', 'https://www.palmlakeresort.com.au', 'Active'),

('Ingenia Lifestyle Park Ridge', 'Ingenia Communities', 'Southern corridor over-50s community. Contemporary manufactured homes with community facilities. Pool, bowling green and clubhouse. Close to Grand Plaza shopping and Logan Hospital.', '1 Mount Lindesay Highway', 'Park Ridge', 'QLD', '4125', 'Independent Living', 220000, 380000, 85, 145, 164, 14, ARRAY['Pool', 'Bowling Green', 'Clubhouse', 'Community Centre'], '07 3200 9200', 'parkridge@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Active'),

('Watermark Crestmead', 'Watermark', 'Southern Logan retirement community. Modern villas near Logan Hyperdome. Pool, community facilities and gardens. Close to major shopping, medical facilities and transport. Regional corridor convenience.', '88 Station Road', 'Crestmead', 'QLD', '4132', 'Independent Living', 300000, 460000, 130, 210, 96, 9, ARRAY['Pool', 'Shopping Access', 'Community Centre', 'Gardens'], '07 3803 1234', 'crestmead@watermark.com.au', 'https://www.watermark.com.au', 'Active');
