-- QLD Batch 05: 25 Far North & Central QLD Retirement Villages (FINAL QLD BATCH)
-- Geographic Focus: Cairns, Townsville, Mackay, Rockhampton, Bundaberg, Fraser Coast
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Aveo Cairns', 'Aveo Group', 'Tropical Far North Queensland retirement. Modern villas near beaches and Reef. Pool, gym, community facilities and tropical gardens. Close to Cairns Central shopping and medical facilities. Gateway to the Reef.', '88 Mulgrave Road', 'Cairns', 'QLD', '4870', 'Independent Living', 320000, 480000, 140, 220, 128, 11, ARRAY['Pool', 'Gym', 'Tropical Gardens', 'Beach Access', 'Community Centre'], '1300 283 000', 'cairns@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Stockland Townsville', 'Stockland', 'North Queensland regional city retirement. Contemporary villas with mountain and coastal views. Pool, gym, bowling green and community hub. Close to shopping, Castle Hill and medical facilities.', '1 Ross River Road', 'Townsville', 'QLD', '4810', 'Independent Living', 300000, 460000, 130, 210, 152, 13, ARRAY['Pool', 'Gym', 'Bowling Green', 'Mountain Views', 'Community Centre'], '1800 550 550', 'townsville@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Lendlease Mackay', 'Lendlease', 'Central Queensland coastal city retirement. Quality villas near beaches and marina. Pool, bowling green and community facilities. Close to Caneland Central shopping and medical facilities. Tropical coastal living.', '42 Harbour Road', 'Mackay', 'QLD', '4740', 'Independent Living', 280000, 430000, 120, 195, 116, 10, ARRAY['Pool', 'Bowling Green', 'Beach Access', 'Marina Views', 'Community Centre'], '1300 326 033', 'mackay@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Rockhampton', 'Anglicare', 'Central Queensland beef capital retirement. Independent villas with chapel and community facilities. Bowling green and gardens. Close to Stockland Rockhampton shopping and medical facilities. Regional city living.', '88 Musgrave Street', 'Rockhampton', 'QLD', '4700', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 102, 9, ARRAY['Chapel', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '07 4927 3100', 'rockhampton@anglicaresq.org.au', 'https://www.anglicaresq.org.au', 'Active'),

('Baptistcare Bundaberg', 'BaptistCare', 'Fraser Coast retirement community. Modern villas near rum city and beaches. Chapel, pool, bowling green and gardens. Close to Bundaberg Hospital, shopping and Reef access. Regional coastal lifestyle.', '88 Bourbong Street', 'Bundaberg', 'QLD', '4670', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 94, 8, ARRAY['Pool', 'Chapel', 'Bowling Green', 'Beach Access', 'Aged Care'], '07 4151 3100', 'bundaberg@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Uniting AgeWell Hervey Bay', 'Uniting AgeWell', 'Fraser Coast retirement near pristine beaches. Comfortable villas with bay breezes and whale watching. Pool, community facilities and coastal walks. Close to Stockland shopping and Fraser Island access.', '88 Main Street', 'Pialba', 'QLD', '4655', 'Independent Living', 300000, 460000, 130, 210, 118, 10, ARRAY['Pool', 'Bay Breezes', 'Whale Watching', 'Community Centre'], '1300 783 435', 'herveybay@unitingagewell.org', 'https://www.unitingagewell.org', 'Active'),

('Opal Aged Care Gladstone', 'Opal Aged Care', 'Central Queensland port city retirement. Modern villas near marina and harbour. Pool, community facilities and waterfront access. Close to shopping, medical facilities and industrial heritage.', '42 Goondoon Street', 'Gladstone', 'QLD', '4680', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 88, 8, ARRAY['Pool', 'Waterfront Access', 'Marina Views', 'Community Centre', 'Aged Care'], '1300 672 524', 'gladstone@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Maryborough', 'IRT Group', 'Fraser Coast heritage city retirement. Comfortable villas in historic Maryborough. Community facilities, bowling green and aged care. Close to medical facilities and shopping. Heritage Queensland living.', '88 Wharf Street', 'Maryborough', 'QLD', '4650', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 84, 7, ARRAY['Bowling Green', 'Heritage Setting', 'Community Centre', 'Aged Care'], '1300 157 677', 'maryborough@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Regis Aged Care Port Douglas', 'Regis Aged Care', 'Tropical paradise retirement near iconic Four Mile Beach. Premium villas with rainforest and ocean proximity. Pool, community facilities and tropical gardens. Walk to Macrossan Street, marina and Reef tours.', '42 Davidson Street', 'Port Douglas', 'QLD', '4877', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 72, 5, ARRAY['Pool', 'Rainforest Setting', 'Beach Access', 'Tropical Gardens', 'Aged Care'], '07 4099 3100', 'portdouglas@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Emerald', 'Respect', 'Central Highlands mining town retirement. Affordable villas in regional centre. Community facilities and gardens. Close to Emerald Hospital and shopping. Mining region lifestyle.', '88 Egerton Street', 'Emerald', 'QLD', '4720', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 64, 6, ARRAY['Community Centre', 'Gardens', 'Regional Setting', 'Aged Care'], '07 4982 3100', 'emerald@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Arcare Thuringowa', 'Arcare', 'Townsville southern suburbs retirement. Contemporary villas near University Hospital. Pool, gym and community facilities. Close to Willows shopping, James Cook University and medical facilities.', '1 University Drive', 'Thuringowa', 'QLD', '4817', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 104, 9, ARRAY['Pool', 'Gym', 'Hospital Access', 'University Access', 'Aged Care'], '1300 272 273', 'thuringowa@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Bupa Aged Care Innisfail', 'Bupa', 'Tropical Far North Queensland retirement. Comfortable villas near rainforest and beaches. Pool, community facilities and tropical setting. Close to Innisfail town centre and medical facilities. Wet tropics living.', '88 Edith Street', 'Innisfail', 'QLD', '4860', 'Independent Living, Aged Care', 220000, 360000, 95, 165, 68, 6, ARRAY['Pool', 'Rainforest Setting', 'Beach Access', 'Community Centre', 'Aged Care'], '1300 280 334', 'innisfail@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Yeppoon', 'Allity', 'Capricorn Coast beachside retirement. Modern villas near beautiful beaches. Pool, community facilities and coastal walks. Close to Yeppoon town centre, Keppel Bay Marina and medical facilities. Coastal lifestyle.', '88 James Street', 'Yeppoon', 'QLD', '4703', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 86, 7, ARRAY['Pool', 'Beach Access', 'Coastal Walks', 'Marina Views', 'Aged Care'], '07 4939 3100', 'yeppoon@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Ayr', 'Bolton Clarke', 'North Queensland rural retirement village. Comfortable villas in farming district. Community facilities, gardens and bowling green. Close to Ayr town centre and medical facilities. Rural Queensland lifestyle.', '88 Queen Street', 'Ayr', 'QLD', '4807', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 72, 7, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Rural Setting', 'Aged Care'], '1300 228 655', 'ayr@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Estia Health Mount Isa', 'Estia Health', 'Outback mining city retirement. Affordable villas in remote regional centre. Pool, community facilities and desert setting. Close to Mount Isa Hospital and shopping. Outback Queensland lifestyle.', '88 Miles Street', 'Mount Isa', 'QLD', '4825', 'Independent Living, Aged Care', 180000, 310000, 80, 150, 62, 6, ARRAY['Pool', 'Desert Setting', 'Community Centre', 'Mining Town', 'Aged Care'], '07 4743 3100', 'mountisa@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Atherton', 'Japara', 'Atherton Tablelands retirement village. Cool climate villas on tropical highlands. Community facilities, gardens and mountain views. Close to Atherton town centre and Tablelands attractions. Highland lifestyle.', '42 Main Street', 'Atherton', 'QLD', '4883', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 74, 7, ARRAY['Cool Climate', 'Mountain Views', 'Community Centre', 'Gardens', 'Aged Care'], '1800 52 72 72', 'atherton@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Gympie', 'Tricare', 'Mary Valley retirement community. Comfortable villas in regional centre. Pool, community facilities and gardens. Close to Gympie Hospital, shopping and Mary River. Regional valley lifestyle.', '88 Mary Street', 'Gympie', 'QLD', '4570', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 92, 8, ARRAY['Pool', 'River Views', 'Community Centre', 'Gardens', 'Aged Care'], '07 5482 3100', 'gympie@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Bowen', 'Mayflower', 'Whitsundays coast retirement village. Tropical villas near pristine beaches. Community centre, gardens and coastal setting. Close to Bowen town centre and medical facilities. Tropical coastal lifestyle.', '88 Herbert Street', 'Bowen', 'QLD', '4805', 'Independent Living', 220000, 360000, 95, 165, 64, 6, ARRAY['Beach Access', 'Tropical Setting', 'Community Centre', 'Gardens'], '07 4786 1234', 'bowen@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care Charters Towers', 'RSL Care', 'North Queensland heritage city retirement with veterans services. Comfortable villas in historic goldfields town. Bowling green, community facilities and RSL services. Heritage Queensland living.', '42 Gill Street', 'Charters Towers', 'QLD', '4820', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 68, 7, ARRAY['Bowling Green', 'Heritage Setting', 'RSL Services', 'Community Centre', 'Aged Care'], '07 4787 3100', 'charterstowers@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('BlueCare Aitkenvale', 'BlueCare', 'Townsville suburbs retirement community. Modern villas near Willows shopping. Pool, community facilities and tropical gardens. Close to major shopping centre and medical facilities. Regional city convenience.', '88 Ross River Road', 'Aitkenvale', 'QLD', '4814', 'Independent Living', 280000, 430000, 120, 195, 96, 9, ARRAY['Pool', 'Shopping Access', 'Tropical Gardens', 'Community Centre'], '07 4725 1234', 'aitkenvale@bluecare.org.au', 'https://www.bluecare.org.au', 'Active'),

('Mercy Health Maryborough West', 'Mercy Health', 'Fraser Coast retirement community. Catholic heritage with chapel and pastoral care. Modern villas with community facilities and aged care. Close to medical facilities and shopping.', '88 Alice Street', 'Maryborough', 'QLD', '4650', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 84, 8, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Aged Care'], '07 4121 3100', 'maryboroughwest@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Active'),

('Living Choice Kawana Waters', 'Living Choice', 'Central Queensland retirement resort. Premium villas with resort amenities. Pool, gym, cinema, bowling green and community hub. Close to beaches, shopping and medical facilities.', '1 Reef Drive', 'Kawana Waters', 'QLD', '4575', 'Independent Living', 380000, 580000, 160, 250, 142, 12, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Resort Amenities'], '07 5493 4100', 'kawana@livingchoice.com.au', 'https://www.livingchoice.com.au', 'Active'),

('Palm Lake Resort Bargara', 'Palm Lake Resort', 'Fraser Coast beachside over-50s resort. Modern manufactured homes near beautiful beaches. Pool, tennis, bowling green and clubhouse. Perfect Coral Coast lifestyle. Affordable beachside living.', '1 Esplanade', 'Bargara', 'QLD', '4670', 'Independent Living', 260000, 420000, 100, 170, 168, 14, ARRAY['Pool', 'Tennis Courts', 'Bowling Green', 'Beach Access', 'Clubhouse'], '07 4159 9200', 'bargara@palmlakeresort.com.au', 'https://www.palmlakeresort.com.au', 'Active'),

('Ingenia Lifestyle Rainbow Beach', 'Ingenia Communities', 'Fraser Coast hinterland over-50s community. Contemporary manufactured homes near Rainbow Beach. Pool, bowling green, clubhouse and beach access. Perfect fishing and 4WD lifestyle.', '1 Rainbow Drive', 'Rainbow Beach', 'QLD', '4581', 'Independent Living', 240000, 400000, 95, 160, 132, 12, ARRAY['Pool', 'Bowling Green', 'Beach Access', 'Fishing', 'Clubhouse'], '07 5486 9200', 'rainbowbeach@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Active'),

('Watermark Kirwan', 'Watermark', 'Townsville southern suburbs retirement. Modern villas near Riverway shopping. Pool, community facilities and tropical gardens. Close to shopping centre, medical facilities and Riverway stadium.', '88 Riverway Drive', 'Kirwan', 'QLD', '4817', 'Independent Living', 280000, 430000, 120, 195, 104, 10, ARRAY['Pool', 'Shopping Access', 'Tropical Gardens', 'Community Centre'], '07 4723 1234', 'kirwan@watermark.com.au', 'https://www.watermark.com.au', 'Active');
