-- QLD Batch 02: 25 Gold Coast Retirement Villages
-- Geographic Focus: Gold Coast, Tweed Heads Border, Hinterland
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Stockland Halcyon Lakeside Varsity Lakes', 'Stockland', 'Premium Gold Coast waterfront retirement resort. Contemporary villas with lake and golf course views. Pool, gym, cinema, bowling green and community hub. Minutes to Robina Town Centre and beaches.', '1 Varsity Parade', 'Varsity Lakes', 'QLD', '4227', 'Independent Living', 420000, 640000, 170, 260, 206, 17, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Lake Views', 'Golf Course'], '1800 550 550', 'varsitylakes@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Aveo Duranbah', 'Aveo Group', 'Gold Coast northern beaches retirement community. Modern villas near beautiful beaches. Pool, gym, bowling green and community facilities. Walk to shops, cafes and pristine coastline. Premium coastal lifestyle.', '88 Golden Four Drive', 'Bilinga', 'QLD', '4225', 'Independent Living', 420000, 640000, 170, 260, 134, 11, ARRAY['Pool', 'Gym', 'Bowling Green', 'Beach Access', 'Community Centre'], '1300 283 000', 'duranbah@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Lendlease Burleigh Heads', 'Lendlease', 'Premium beachside retirement near iconic Burleigh Beach. Luxury apartments with ocean views. Rooftop terrace, pool, gym and fine dining. Walk to James Street cafes, beach and headland. Elite Gold Coast address.', '88 Goodwin Terrace', 'Burleigh Heads', 'QLD', '4220', 'Independent Living', 680000, 980000, 260, 380, 96, 5, ARRAY['Ocean Views', 'Rooftop Terrace', 'Pool', 'Gym', 'Beach Access', 'Fine Dining'], '1300 326 033', 'burleigh@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Southport', 'Anglicare', 'Central Gold Coast retirement community. Independent villas with chapel and community facilities. Close to Australia Fair shopping, tram and medical facilities. Convenient central location.', '42 Scarborough Street', 'Southport', 'QLD', '4215', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 112, 10, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Tram Access', 'Aged Care'], '07 5532 3100', 'southport@anglicaresq.org.au', 'https://www.anglicaresq.org.au', 'Active'),

('Baptistcare Palm Beach', 'BaptistCare', 'Southern Gold Coast beachside retirement. Modern villas near Palm Beach and Currumbin. Chapel, pool and community facilities. Walk to beaches, cafes and coastal walks. Pristine southern beaches lifestyle.', '88 Fifth Avenue', 'Palm Beach', 'QLD', '4221', 'Independent Living', 440000, 660000, 180, 270, 92, 7, ARRAY['Pool', 'Chapel', 'Beach Access', 'Coastal Walks', 'Community Centre'], '07 5598 3100', 'palmbeach@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Uniting AgeWell Mudgeeraba', 'Uniting AgeWell', 'Gold Coast hinterland retirement village. Peaceful villas with mountain views. Community centre, pool and gardens. Close to Robina, Mudgeeraba village and Springbrook. Hinterland tranquility.', '88 Railway Street', 'Mudgeeraba', 'QLD', '4213', 'Independent Living', 360000, 540000, 150, 240, 104, 9, ARRAY['Pool', 'Mountain Views', 'Community Centre', 'Gardens', 'Hinterland Setting'], '1300 783 435', 'mudgeeraba@unitingagewell.org', 'https://www.unitingagewell.org', 'Active'),

('Opal Aged Care Broadbeach', 'Opal Aged Care', 'Premium Gold Coast beachside retirement. Contemporary apartments near Broadbeach and Pacif Fair. Ocean views, pool, gym and cinema. Walk to beach, casino and shopping. Ultimate coastal luxury.', '42 Old Burleigh Road', 'Broadbeach', 'QLD', '4218', 'Independent Living, Aged Care', 580000, 840000, 220, 320, 108, 6, ARRAY['Pool', 'Gym', 'Cinema', 'Ocean Views', 'Beach Access', 'Aged Care'], '1300 672 524', 'broadbeach@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Runaway Bay', 'IRT Group', 'Northern Gold Coast waterfront retirement. Modern villas with marina and broadwater views. Pool, community facilities and water access. Close to Harbour Town shopping and medical facilities. Waterfront lifestyle.', '88 Bayview Street', 'Runaway Bay', 'QLD', '4216', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 118, 10, ARRAY['Pool', 'Marina Views', 'Water Access', 'Community Centre', 'Aged Care'], '1300 157 677', 'runawaybay@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Regis Aged Care Robina', 'Regis Aged Care', 'Central Gold Coast retirement near Robina Town Centre. Quality villas with community facilities and aged care. Close to major shopping, hospital and medical facilities. Premium central location.', '88 Robina Town Centre Drive', 'Robina', 'QLD', '4226', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 104, 8, ARRAY['Shopping Access', 'Hospital Access', 'Community Centre', 'Gardens', 'Aged Care'], '07 5578 3100', 'robina@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Coolangatta', 'Respect', 'Southern Gold Coast beachside retirement. Comfortable villas near Coolangatta beaches and airport. Pool, community facilities and ocean breezes. Walk to beach, shops and Queensland/NSW border. Southern beaches living.', '42 Griffith Street', 'Coolangatta', 'QLD', '4225', 'Independent Living, Aged Care', 400000, 600000, 170, 260, 94, 7, ARRAY['Pool', 'Ocean Breezes', 'Beach Access', 'Community Centre', 'Aged Care'], '07 5536 3100', 'coolangatta@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Arcare Helensvale', 'Arcare', 'Northern Gold Coast retirement community. Contemporary villas near Westfield Helensvale. Pool, gym and community facilities. Close to tram, shopping and theme parks. Family entertainment precinct.', '1 Millaroo Drive', 'Helensvale', 'QLD', '4212', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 126, 11, ARRAY['Pool', 'Gym', 'Tram Access', 'Shopping Access', 'Aged Care'], '1300 272 273', 'helensvale@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Bupa Aged Care Currumbin', 'Bupa', 'Southern Gold Coast wildlife sanctuary retirement. Modern villas near Currumbin Wildlife Sanctuary. Pool, community facilities and rainforest setting. Walk to Currumbin Beach and village. Nature and beach lifestyle.', '88 Currumbin Creek Road', 'Currumbin', 'QLD', '4223', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 88, 7, ARRAY['Pool', 'Rainforest Setting', 'Beach Access', 'Wildlife', 'Aged Care'], '1300 280 334', 'currumbin@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Benowa', 'Allity', 'Central Gold Coast retirement near golf courses. Contemporary villas with resort setting. Pool, community facilities and gardens. Close to Benowa Gardens shopping and medical facilities. Premium residential area.', '88 Ashmore Road', 'Benowa', 'QLD', '4217', 'Independent Living, Aged Care', 400000, 600000, 170, 260, 102, 8, ARRAY['Pool', 'Resort Setting', 'Community Centre', 'Gardens', 'Aged Care'], '07 5564 3100', 'benowa@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Mermaid Beach', 'Bolton Clarke', 'Gold Coast beachside retirement. Quality villas near beautiful Mermaid Beach. Pool, community facilities and coastal walks. Walk to Nobby Beach, cafes and Pacific Fair. Premium beachside position.', '88 Hedges Avenue', 'Mermaid Beach', 'QLD', '4218', 'Independent Living, Aged Care', 520000, 760000, 200, 300, 92, 6, ARRAY['Pool', 'Beach Access', 'Coastal Walks', 'Community Centre', 'Aged Care'], '1300 228 655', 'mermaidbeach@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Estia Health Nerang', 'Estia Health', 'Gold Coast hinterland retirement village. Modern villas with mountain backdrop. Pool, community facilities and gardens. Close to Nerang town centre and medical facilities. Valley setting with coastal access.', '88 Station Street', 'Nerang', 'QLD', '4211', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 114, 10, ARRAY['Pool', 'Mountain Views', 'Community Centre', 'Gardens', 'Aged Care'], '07 5596 3100', 'nerang@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Labrador', 'Japara', 'Gold Coast broadwater retirement community. Modern apartments with water views. Pool, community facilities and marina access. Walk to Harbour Town Outlet shopping and waterfront dining. Waterfront lifestyle.', '42 Marine Parade', 'Labrador', 'QLD', '4215', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 96, 7, ARRAY['Pool', 'Water Views', 'Marina Access', 'Shopping Access', 'Aged Care'], '1800 52 72 72', 'labrador@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Tugun', 'Tricare', 'Southern Gold Coast beachside retirement near airport. Modern villas with ocean breezes. Pool, community facilities and beach access. Walk to Tugun village, beach and coastal walks. Convenient southern location.', '42 Coolangatta Road', 'Tugun', 'QLD', '4224', 'Independent Living, Aged Care', 400000, 600000, 170, 260, 88, 7, ARRAY['Pool', 'Ocean Breezes', 'Beach Access', 'Community Centre', 'Aged Care'], '07 5534 3100', 'tugun@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Surfers Paradise', 'Mayflower', 'Premium high-rise retirement in Surfers Paradise. Luxury apartments with ocean and river views. Rooftop pool, gym, spa and concierge. Walk to beaches, Cavill Avenue and entertainment. Ultimate coastal luxury.', '88 Ferny Avenue', 'Surfers Paradise', 'QLD', '4217', 'Independent Living', 620000, 880000, 240, 340, 84, 4, ARRAY['Rooftop Pool', 'Gym', 'Spa', 'Ocean Views', 'Concierge', 'Beach Access'], '07 5538 1234', 'surfersparadise@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care Tugun', 'RSL Care', 'Southern Gold Coast retirement with veterans services. Comfortable villas near beaches and airport. Bowling green, community facilities and RSL services. Close to shops and medical facilities. Southern beaches living.', '88 Gold Coast Highway', 'Tugun', 'QLD', '4224', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 102, 9, ARRAY['Bowling Green', 'RSL Services', 'Beach Access', 'Community Centre', 'Aged Care'], '07 5534 4100', 'tugun@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('BlueCare Biggera Waters', 'BlueCare', 'Northern Gold Coast waterfront retirement. Modern villas with broadwater and marina views. Pool, community facilities and water activities. Close to Harbour Town shopping and medical facilities. Premium waterfront position.', '42 Hollywell Road', 'Biggera Waters', 'QLD', '4216', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 104, 8, ARRAY['Pool', 'Waterfront Views', 'Marina Access', 'Community Centre', 'Aged Care'], '07 5537 1234', 'biggerawaters@bluecare.org.au', 'https://www.bluecare.org.au', 'Active'),

('Mercy Health Ashmore', 'Mercy Health', 'Central Gold Coast retirement community. Catholic heritage with chapel and pastoral care. Modern villas with community facilities and aged care. Close to shopping centres and medical facilities.', '88 Currumburra Road', 'Ashmore', 'QLD', '4214', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 116, 10, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '07 5564 4100', 'ashmore@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Active'),

('Living Choice Broadwater Court', 'Living Choice', 'Northern Gold Coast waterfront resort. Premium villas with stunning broadwater views. Pool, gym, cinema, bowling green and marina berths. Walk to restaurants, cafes and waterfront. Luxury waterfront lifestyle.', '1 Marine Parade', 'Southport', 'QLD', '4215', 'Independent Living', 520000, 780000, 200, 300, 142, 10, ARRAY['Pool', 'Gym', 'Cinema', 'Marina Berths', 'Waterfront Views', 'Bowling Green'], '07 5591 1234', 'broadwatercourt@livingchoice.com.au', 'https://www.livingchoice.com.au', 'Active'),

('Palm Lake Resort Gold Coast', 'Palm Lake Resort', 'Northern Gold Coast over-50s resort community. Modern manufactured homes with resort facilities. Pool, tennis, bowling green, gym and clubhouse. Close to theme parks and beaches. Affordable resort living.', '1 Pacific Pines Boulevard', 'Pacific Pines', 'QLD', '4211', 'Independent Living', 280000, 450000, 100, 160, 196, 16, ARRAY['Pool', 'Tennis Courts', 'Bowling Green', 'Gym', 'Clubhouse'], '07 5573 9200', 'goldcoast@palmlakeresort.com.au', 'https://www.palmlakeresort.com.au', 'Active'),

('Ingenia Lifestyle Tweed Shores', 'Ingenia Communities', 'Tweed River over-50s resort on QLD/NSW border. Contemporary manufactured homes with river access. Pool, bowling green, clubhouse and fishing facilities. Perfect river and coastal lifestyle. Affordable waterfront.', '1 Riverside Drive', 'Tweed Heads South', 'QLD', '4221', 'Independent Living', 240000, 400000, 95, 160, 186, 15, ARRAY['Pool', 'Bowling Green', 'River Access', 'Fishing', 'Clubhouse'], '07 5536 9200', 'tweedshores@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Active'),

('Watermark Sanctuary Cove', 'Watermark', 'Premium Gold Coast marina resort retirement. Luxury villas in exclusive Sanctuary Cove. Golf course, marina berths, resort pool and fine dining. Walk to Sanctuary Cove Village and waterways. Elite address.', '1 Santa Barbara Road', 'Hope Island', 'QLD', '4212', 'Independent Living', 780000, 1180000, 300, 420, 64, 2, ARRAY['Golf Course', 'Marina Berths', 'Resort Pool', 'Fine Dining', 'Waterways', 'Concierge'], '07 5577 1234', 'sanctuarycove@watermark.com.au', 'https://www.watermark.com.au', 'Active');
