-- QLD Batch 03: 25 Sunshine Coast & Moreton Bay Retirement Villages
-- Geographic Focus: Sunshine Coast, Noosa, Caloundra, Caboolture, Moreton Bay
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Stockland Halcyon Lakeside Bli Bli', 'Stockland', 'Premium Sunshine Coast retirement resort. Contemporary villas with lakefront setting and resort amenities. Pool, gym, cinema, bowling green and community hub. Minutes to Maroochydore and beaches.', '1 Lake Eden Drive', 'Bli Bli', 'QLD', '4560', 'Independent Living', 420000, 640000, 170, 260, 216, 18, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Lake Views', 'Community Centre'], '1800 550 550', 'blibli@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Aveo Peregian Springs', 'Aveo Group', 'Sunshine Coast hinterland retirement community. Modern villas near Noosa and beaches. Pool, gym, bowling green and golf course. Close to Peregian Beach and shopping. Premium coastal hinterland.', '88 Ridgeview Drive', 'Peregian Springs', 'QLD', '4573', 'Independent Living', 440000, 660000, 180, 270, 152, 12, ARRAY['Pool', 'Gym', 'Bowling Green', 'Golf Course', 'Community Centre'], '1300 283 000', 'peregiansprings@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Lendlease Noosa', 'Lendlease', 'Premium Noosa retirement living near world-famous beaches. Luxury apartments with hinterland views. Pool, gym, spa and fine dining. Walk to Hastings Street, restaurants and Noosa National Park. Elite coastal address.', '88 Noosa Drive', 'Noosa Heads', 'QLD', '4567', 'Independent Living', 680000, 980000, 260, 380, 94, 5, ARRAY['Pool', 'Gym', 'Spa', 'Hinterland Views', 'Beach Access', 'Fine Dining'], '1300 326 033', 'noosa@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Caloundra', 'Anglicare', 'Sunshine Coast beachside retirement community. Independent villas with chapel and community facilities. Close to Bulcock Beach, Stockland shopping and medical facilities. Coastal town lifestyle.', '42 Bowman Road', 'Caloundra', 'QLD', '4551', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 118, 10, ARRAY['Chapel', 'Beach Access', 'Community Centre', 'Gardens', 'Aged Care'], '07 5491 3100', 'caloundra@anglicaresq.org.au', 'https://www.anglicaresq.org.au', 'Active'),

('Baptistcare Buderim', 'BaptistCare', 'Sunshine Coast hinterland retirement village. Modern villas with mountain views. Chapel, pool, bowling green and community centre. Walk to Buderim village, shops and cafes. Hinterland village atmosphere.', '88 Main Street', 'Buderim', 'QLD', '4556', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 104, 8, ARRAY['Pool', 'Chapel', 'Bowling Green', 'Mountain Views', 'Aged Care'], '07 5476 3100', 'buderim@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Uniting AgeWell Maroochydore', 'Uniting AgeWell', 'Central Sunshine Coast retirement community. Contemporary villas near beach and shopping. Pool, community facilities and coastal access. Walk to Maroochydore Beach, Ocean Street and Sunshine Plaza.', '88 Aerodrome Road', 'Maroochydore', 'QLD', '4558', 'Independent Living', 400000, 600000, 170, 260, 126, 11, ARRAY['Pool', 'Beach Access', 'Shopping Access', 'Community Centre'], '1300 783 435', 'maroochydore@unitingagewell.org', 'https://www.unitingagewell.org', 'Active'),

('Opal Aged Care Mooloolaba', 'Opal Aged Care', 'Premium Sunshine Coast beachside retirement. Contemporary apartments with ocean views. Pool, gym and community facilities. Walk to Mooloolaba Beach, esplanade and restaurants. Ultimate coastal lifestyle.', '42 Brisbane Road', 'Mooloolaba', 'QLD', '4557', 'Independent Living, Aged Care', 520000, 760000, 200, 300, 96, 7, ARRAY['Pool', 'Gym', 'Ocean Views', 'Beach Access', 'Aged Care'], '1300 672 524', 'mooloolaba@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Kawana Waters', 'IRT Group', 'Sunshine Coast waterfront retirement community. Modern villas with lake and ocean access. Pool, community facilities and waterfront walks. Close to Kawana Shoppingworld and beaches. Waterfront lifestyle.', '88 Nicklin Way', 'Kawana Waters', 'QLD', '4575', 'Independent Living, Aged Care', 400000, 600000, 170, 260, 132, 12, ARRAY['Pool', 'Lake Access', 'Ocean Access', 'Community Centre', 'Aged Care'], '1300 157 677', 'kawanawaters@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Regis Aged Care Nambour', 'Regis Aged Care', 'Sunshine Coast hinterland retirement village. Quality villas near Nambour General Hospital. Community facilities, bowling green and aged care. Close to shopping and medical facilities. Regional centre location.', '88 Currie Street', 'Nambour', 'QLD', '4560', 'Independent Living, Aged Care', 320000, 480000, 140, 220, 102, 9, ARRAY['Bowling Green', 'Hospital Access', 'Community Centre', 'Gardens', 'Aged Care'], '07 5441 3100', 'nambour@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Caboolture', 'Respect', 'Moreton Bay regional retirement community. Affordable villas near Caboolture Hospital. Pool, community centre and gardens. Close to shopping centres and Bruce Highway. Regional accessibility.', '42 King Street', 'Caboolture', 'QLD', '4510', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 124, 11, ARRAY['Pool', 'Hospital Access', 'Community Centre', 'Gardens', 'Aged Care'], '07 5499 3100', 'caboolture@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Arcare Mooloolah Valley', 'Arcare', 'Sunshine Coast hinterland retirement village. Contemporary villas with valley and mountain views. Pool, gym and community facilities. Close to Australia Zoo and Glass House Mountains. Valley lifestyle.', '1 Bray Road', 'Mooloolah Valley', 'QLD', '4553', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 108, 10, ARRAY['Pool', 'Gym', 'Mountain Views', 'Valley Setting', 'Aged Care'], '1300 272 273', 'mooloolah@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Bupa Aged Care Bribie Island', 'Bupa', 'Moreton Bay island retirement community. Comfortable villas near beaches and waterways. Pool, community facilities and water access. Walk to Bribie Island village, beaches and fishing. Island lifestyle living.', '88 Welsby Parade', 'Bongaree', 'QLD', '4507', 'Independent Living, Aged Care', 320000, 480000, 140, 220, 94, 8, ARRAY['Pool', 'Beach Access', 'Water Access', 'Fishing', 'Aged Care'], '1300 280 334', 'bribieisland@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Redcliffe Peninsula', 'Allity', 'Moreton Bay peninsula retirement community. Modern villas near beaches and waterfront. Pool, community facilities and bay breezes. Close to Redcliffe shopping, jetty and medical facilities. Peninsula lifestyle.', '88 Oxley Avenue', 'Woody Point', 'QLD', '4019', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 116, 10, ARRAY['Pool', 'Beach Access', 'Bay Breezes', 'Community Centre', 'Aged Care'], '07 3284 4100', 'redcliffe@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Currimundi', 'Bolton Clarke', 'Sunshine Coast lakeside retirement community. Quality villas with lake views and beach access. Pool, bowling green and community facilities. Walk to Currimundi Lake, beach and shopping. Lake and ocean lifestyle.', '88 Nicklin Way', 'Currimundi', 'QLD', '4551', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 102, 9, ARRAY['Pool', 'Bowling Green', 'Lake Views', 'Beach Access', 'Aged Care'], '1300 228 655', 'currimundi@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Estia Health Narangba', 'Estia Health', 'Northern Moreton Bay retirement community. Modern villas in growing area. Pool, community facilities and gardens. Close to Narangba Valley Tavern and medical facilities. Growth corridor living.', '88 Golden Wattle Drive', 'Narangba', 'QLD', '4504', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 118, 11, ARRAY['Pool', 'Community Centre', 'Gardens', 'Growth Area', 'Aged Care'], '07 3886 3100', 'narangba@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Coolum Beach', 'Japara', 'Sunshine Coast beachside retirement village. Modern villas near beautiful Coolum Beach. Pool, community facilities and coastal walks. Walk to Coolum village, beach and restaurants. Premium coastal position.', '42 Birtwill Street', 'Coolum Beach', 'QLD', '4573', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 88, 7, ARRAY['Pool', 'Beach Access', 'Coastal Walks', 'Community Centre', 'Aged Care'], '1800 52 72 72', 'coolum@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Marcoola', 'Tricare', 'Sunshine Coast beachside retirement near airport. Modern villas with ocean breezes. Pool, community facilities and beach access. Walk to Marcoola Beach and cafes. Convenient coastal location.', '42 David Low Way', 'Marcoola', 'QLD', '4564', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 92, 8, ARRAY['Pool', 'Ocean Breezes', 'Beach Access', 'Community Centre', 'Aged Care'], '07 5448 3100', 'marcoola@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Deception Bay', 'Mayflower', 'Moreton Bay waterfront retirement community. Comfortable villas with water views. Community centre, gardens and waterfront access. Close to shopping centres and medical facilities. Bayside living.', '88 Bay Avenue', 'Deception Bay', 'QLD', '4508', 'Independent Living', 300000, 460000, 130, 210, 104, 9, ARRAY['Water Views', 'Waterfront Access', 'Community Centre', 'Gardens'], '07 3204 1234', 'deceptionbay@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care North Lakes', 'RSL Care', 'Northern Brisbane retirement community with veterans services. Modern villas near Westfield North Lakes. Pool, bowling green and RSL facilities. Close to major shopping, medical facilities and transport.', '42 Anzac Avenue', 'North Lakes', 'QLD', '4509', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 128, 12, ARRAY['Pool', 'Bowling Green', 'RSL Services', 'Shopping Access', 'Aged Care'], '07 3480 3100', 'northlakes@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('BlueCare Alexandra Headland', 'BlueCare', 'Sunshine Coast beachside retirement. Modern villas near Alex Beach. Pool, community facilities and coastal walks. Walk to Alexandra Headland Beach, cafes and shopping. Popular surf beach lifestyle.', '42 Alexandra Parade', 'Alexandra Headland', 'QLD', '4572', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 86, 7, ARRAY['Pool', 'Beach Access', 'Coastal Walks', 'Surf Beach', 'Aged Care'], '07 5443 1234', 'alexandraheadland@bluecare.org.au', 'https://www.bluecare.org.au', 'Active'),

('Mercy Health Strathpine', 'Mercy Health', 'Northern Brisbane retirement community. Catholic heritage with chapel and pastoral care. Modern villas with community facilities and aged care. Close to Westfield Strathpine and medical facilities.', '88 Gympie Road', 'Strathpine', 'QLD', '4500', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 112, 10, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '07 3205 3100', 'strathpine@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Active'),

('Living Choice Kawana Island', 'Living Choice', 'Sunshine Coast waterfront retirement resort. Premium villas with lake and ocean views. Pool, gym, cinema, bowling green and marina berths. Walk to beaches and shopping. Luxury island lifestyle.', '1 Island Drive', 'Kawana Waters', 'QLD', '4575', 'Independent Living', 520000, 780000, 200, 300, 156, 12, ARRAY['Pool', 'Gym', 'Cinema', 'Marina Berths', 'Lake Views', 'Bowling Green'], '07 5493 1234', 'kawanaisland@livingchoice.com.au', 'https://www.livingchoice.com.au', 'Active'),

('Palm Lake Resort Beachmere', 'Palm Lake Resort', 'Moreton Bay coastal over-50s resort. Modern manufactured homes with waterfront access. Pool, tennis, bowling green and clubhouse. Close to beaches, fishing and Caboolture. Affordable coastal resort.', '1 Esplanade', 'Beachmere', 'QLD', '4510', 'Independent Living', 220000, 380000, 85, 145, 176, 14, ARRAY['Pool', 'Tennis Courts', 'Bowling Green', 'Waterfront Access', 'Clubhouse'], '07 5496 9200', 'beachmere@palmlakeresort.com.au', 'https://www.palmlakeresort.com.au', 'Active'),

('Ingenia Lifestyle Noosaville', 'Ingenia Communities', 'Noosa River over-50s resort community. Contemporary manufactured homes with river proximity. Pool, bowling green, clubhouse and fishing facilities. Walk to Noosaville shops and Gympie Terrace. River lifestyle.', '1 River Drive', 'Noosaville', 'QLD', '4566', 'Independent Living', 280000, 460000, 110, 180, 164, 13, ARRAY['Pool', 'Bowling Green', 'River Proximity', 'Fishing', 'Clubhouse'], '07 5449 9200', 'noosaville@ingeniacommunities.com.au', 'https://www.ingeniacommunities.com.au', 'Active'),

('Watermark Minyama', 'Watermark', 'Sunshine Coast waterfront retirement community. Premium villas with canal and ocean access. Boat berths, pool and community facilities. Walk to Kawana Shoppingworld and beaches. Waterways lifestyle.', '1 Minyama Drive', 'Minyama', 'QLD', '4575', 'Independent Living', 520000, 780000, 200, 300, 94, 6, ARRAY['Boat Berths', 'Pool', 'Canal Access', 'Ocean Access', 'Community Centre'], '07 5444 1234', 'minyama@watermark.com.au', 'https://www.watermark.com.au', 'Active');
