-- SA Batch 01: 25 South Australia Retirement Villages
-- Geographic Focus: Adelaide Metro, Barossa, Adelaide Hills, Regional SA
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Aveo Glengowrie', 'Aveo Group', 'Southern Adelaide retirement community. Modern villas near beaches and city. Pool, gym, bowling green and community facilities. Close to Marion Shopping Centre, medical facilities and beaches. Convenient southern location.', '88 Diagonal Road', 'Glengowrie', 'SA', '5044', 'Independent Living', 360000, 540000, 150, 240, 126, 11, ARRAY['Pool', 'Gym', 'Bowling Green', 'Beach Access', 'Community Centre'], '1300 283 000', 'glengowrie@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Stockland Adelaide', 'Stockland', 'Northern Adelaide retirement community. Contemporary villas with resort amenities. Pool, gym, cinema, bowling green and community hub. Close to shopping centres and medical facilities. Northern suburbs convenience.', '1 Main North Road', 'Salisbury', 'SA', '5108', 'Independent Living', 320000, 480000, 140, 220, 148, 13, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Community Centre'], '1800 550 550', 'adelaide@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Lendlease Brighton', 'Lendlease', 'Beachside Adelaide retirement living. Quality villas near Holdfast Bay beaches. Pool, bowling green and community facilities. Walk to Jetty Road shops, cafes and beach. Premium coastal lifestyle.', '42 Jetty Road', 'Brighton', 'SA', '5048', 'Independent Living', 420000, 640000, 170, 260, 104, 9, ARRAY['Pool', 'Bowling Green', 'Beach Access', 'Shopping Access', 'Community Centre'], '1300 326 033', 'brighton@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Aldersgate', 'Anglicare', 'Adelaide hills retirement village in Prospect. Independent villas with chapel and community facilities. Close to Prospect Road shopping, medical facilities and city access. Established inner northern location.', '88 Prospect Road', 'Prospect', 'SA', '5082', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 98, 8, ARRAY['Chapel', 'Community Centre', 'Gardens', 'City Access', 'Aged Care'], '08 8269 3100', 'aldersgate@anglicaresa.org.au', 'https://www.anglicaresa.com.au', 'Active'),

('Baptistcare Paradise', 'BaptistCare', 'Eastern suburbs retirement community. Modern villas with chapel and bowling green. Pool, community facilities and gardens. Close to Newton shopping, medical facilities and Tea Tree Plaza. Eastern suburbs convenience.', '88 Lower North East Road', 'Paradise', 'SA', '5075', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 112, 10, ARRAY['Pool', 'Chapel', 'Bowling Green', 'Shopping Access', 'Aged Care'], '08 8337 3100', 'paradise@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('ACH Group Kingswood', 'ACH Group', 'Southern Adelaide retirement community. Quality villas with pool and community facilities. Close to Mitcham Square shopping and medical facilities. Established southern foothills location.', '88 Shepherds Hill Road', 'Mitcham', 'SA', '5062', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 116, 10, ARRAY['Pool', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '08 8159 3100', 'kingswood@ach.org.au', 'https://www.ach.org.au', 'Active'),

('Resthaven Marion', 'Resthaven', 'Southern Adelaide retirement village. Comfortable villas near Westfield Marion. Community facilities, bowling green and aged care. Walk to major shopping centre and medical facilities. Southern accessibility.', '88 Sturt Road', 'Marion', 'SA', '5043', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 124, 12, ARRAY['Bowling Green', 'Shopping Access', 'Community Centre', 'Gardens', 'Aged Care'], '08 8379 3100', 'marion@resthaven.asn.au', 'https://www.resthaven.asn.au', 'Active'),

('Bupa Aged Care Glenelg', 'Bupa', 'Beachside Adelaide retirement near iconic Glenelg Beach. Modern villas with bay breezes. Pool, community facilities and coastal walks. Walk to Jetty Road shops, beach and tram. Premium coastal address.', '42 Sussex Street', 'Glenelg', 'SA', '5045', 'Independent Living, Aged Care', 480000, 720000, 190, 280, 86, 6, ARRAY['Pool', 'Bay Breezes', 'Beach Access', 'Tram Access', 'Aged Care'], '1300 280 334', 'glenelg@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Regis Aged Care Burnside', 'Regis Aged Care', 'Eastern suburbs retirement in prestigious Burnside. Quality villas with gardens and community facilities. Close to Burnside Village shopping, medical facilities and parklands. Premium eastern location.', '88 Greenhill Road', 'Burnside', 'SA', '5066', 'Independent Living, Aged Care', 480000, 720000, 190, 280, 92, 7, ARRAY['Gardens', 'Shopping Access', 'Community Centre', 'Parklands', 'Aged Care'], '08 8333 3100', 'burnside@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Allity Fullarton', 'Allity', 'Inner eastern Adelaide retirement community. Contemporary villas near city centre. Pool, community facilities and gardens. Close to Fullarton Road shops, medical facilities and parklands. Inner-city convenience.', '88 Fullarton Road', 'Fullarton', 'SA', '5063', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 94, 8, ARRAY['Pool', 'Community Centre', 'Gardens', 'City Access', 'Aged Care'], '08 8373 3100', 'fullarton@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Estia Health Morphett Vale', 'Estia Health', 'Southern Adelaide retirement community. Modern villas near southern suburbs. Pool, community facilities and gardens. Close to Colonnades Shopping Centre and medical facilities. Southern suburbs living.', '88 Main South Road', 'Morphett Vale', 'SA', '5162', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 118, 11, ARRAY['Pool', 'Shopping Access', 'Community Centre', 'Gardens', 'Aged Care'], '08 8382 3100', 'morphettvale@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Grange', 'Japara', 'Western Adelaide beachside retirement. Modern villas near Henley and Grange beaches. Pool, community facilities and coastal walks. Walk to beach, cafes and shops. Western beaches lifestyle.', '42 Military Road', 'Grange', 'SA', '5022', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 104, 9, ARRAY['Pool', 'Beach Access', 'Coastal Walks', 'Community Centre', 'Aged Care'], '1800 52 72 72', 'grange@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Whyalla', 'Tricare', 'Spencer Gulf regional city retirement. Comfortable villas near steelworks city and coast. Community facilities, bowling green and gardens. Close to Westlands shopping and medical facilities. Industrial city living.', '88 Ekblom Street', 'Whyalla', 'SA', '5600', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 82, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Coastal Access', 'Aged Care'], '08 8645 3100', 'whyalla@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Brighton Beach', 'Mayflower', 'Holdfast Bay beachside retirement. Contemporary villas near beaches and Jetty Road. Pool, community facilities and coastal living. Walk to beach, restaurants and shopping. Premium beachside location.', '88 Brighton Road', 'Glenelg South', 'SA', '5045', 'Independent Living', 420000, 640000, 170, 260, 88, 7, ARRAY['Pool', 'Beach Access', 'Shopping Access', 'Community Centre'], '08 8376 1234', 'brightonbeach@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care Highercombe', 'RSL Care', 'Adelaide Hills retirement with veterans services. Quality villas with hills views. Bowling green, community facilities and RSL services. Close to shopping, medical facilities and Mount Lofty. Hills lifestyle.', '42 Black Road', 'Highercombe', 'SA', '5083', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 96, 8, ARRAY['Bowling Green', 'Hills Views', 'RSL Services', 'Community Centre', 'Aged Care'], '08 8347 3100', 'highercombe@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('Helping Hand Walkerville', 'Helping Hand', 'Inner eastern Adelaide retirement community. Heritage-style villas near Linear Park. Community facilities, gardens and aged care. Walk to Walkerville village, parklands and city access. Prestige inner-east location.', '88 Walkerville Terrace', 'Walkerville', 'SA', '5081', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 84, 6, ARRAY['Heritage Style', 'Gardens', 'Parklands Access', 'Community Centre', 'Aged Care'], '08 8269 9200', 'walkerville@helpinghand.org.au', 'https://www.helpinghand.org.au', 'Active'),

('Calvary Retirement Community Norwood', 'Calvary', 'Inner eastern Adelaide retirement. Catholic heritage with chapel and pastoral care. Contemporary apartments near Norwood Parade. Walk to restaurants, shops and medical facilities. Premium eastern location.', '88 The Parade', 'Norwood', 'SA', '5067', 'Independent Living, Aged Care', 480000, 720000, 190, 280, 76, 5, ARRAY['Chapel', 'Shopping Access', 'Community Centre', 'City Access', 'Aged Care'], '08 8362 1234', 'norwood@calvarycare.org.au', 'https://www.calvarycare.org.au', 'Active'),

('Southern Cross Care Oaklands Park', 'Southern Cross Care', 'Southern Adelaide retirement community. Modern villas with community facilities. Pool, bowling green and gardens. Close to Westfield Marion and medical facilities. Southern suburbs convenience.', '88 Diagonal Road', 'Oaklands Park', 'SA', '5046', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 112, 10, ARRAY['Pool', 'Bowling Green', 'Shopping Access', 'Community Centre', 'Aged Care'], '08 8377 3100', 'oaklandspark@sccliving.org.au', 'https://www.sccliving.org.au', 'Active'),

('Uniting Communities Mount Barker', 'Uniting Communities', 'Adelaide Hills regional retirement village. Modern villas with hills and valley views. Pool, community facilities and gardens. Close to Mount Barker shopping, medical facilities and wineries. Hills country living.', '88 Gawler Street', 'Mount Barker', 'SA', '5251', 'Independent Living', 320000, 480000, 140, 220, 104, 9, ARRAY['Pool', 'Hills Views', 'Wine Country', 'Community Centre'], '08 8391 1234', 'mountbarker@unitingcommunities.org', 'https://www.unitingcommunities.org', 'Active'),

('Barossa Village Tanunda', 'Independent Operator', 'Barossa Valley wine country retirement. Character villas surrounded by vineyards. Pool, community facilities and winery tours. Walk to Tanunda village, cellar doors and restaurants. Premium wine country lifestyle.', '1 Murray Street', 'Tanunda', 'SA', '5352', 'Independent Living', 340000, 520000, 150, 230, 86, 7, ARRAY['Pool', 'Wine Country', 'Vineyard Views', 'Village Atmosphere'], '08 8563 1234', 'info@barossavillage.com.au', 'https://www.barossavillage.com.au', 'Active'),

('Port Lincoln Retirement Village', 'Independent Operator', 'Eyre Peninsula coastal retirement. Comfortable villas near pristine tuna coast. Community facilities and fishing access. Close to Port Lincoln marina, shopping and medical facilities. Fishing paradise lifestyle.', '88 Liverpool Street', 'Port Lincoln', 'SA', '5606', 'Independent Living', 240000, 380000, 105, 175, 74, 7, ARRAY['Fishing Access', 'Marina Views', 'Community Centre', 'Gardens'], '08 8682 1234', 'info@portlincolnretirement.com.au', 'https://www.portlincolnretirement.com.au', 'Active'),

('Victor Harbor Retirement Village', 'Independent Operator', 'Fleurieu Peninsula coastal retirement. Modern villas near beaches and Granite Island. Pool, community facilities and coastal walks. Walk to Encounter Bay, causeway and shops. Premium coastal lifestyle.', '88 Victoria Street', 'Victor Harbor', 'SA', '5211', 'Independent Living', 340000, 520000, 150, 230, 96, 8, ARRAY['Pool', 'Beach Access', 'Coastal Walks', 'Community Centre'], '08 8552 1234', 'info@victorharborretirement.com.au', 'https://www.victorharborretirement.com.au', 'Active'),

('Murray Bridge Retirement Living', 'Independent Operator', 'Murraylands river town retirement. Affordable villas near Murray River. Community facilities, bowling green and river access. Close to Murray Bridge shopping and medical facilities. River country lifestyle.', '88 Swanport Road', 'Murray Bridge', 'SA', '5253', 'Independent Living', 220000, 360000, 95, 165, 82, 8, ARRAY['Bowling Green', 'River Access', 'Community Centre', 'Gardens'], '08 8532 1234', 'info@murraybridgeretirement.com.au', 'https://www.murraybridgeretirement.com.au', 'Active'),

('Clare Valley Retirement Estate', 'Independent Operator', 'Mid North wine country retirement. Peaceful villas in Clare Valley vineyards. Community facilities and winery proximity. Close to Clare town centre, cellar doors and Riesling Trail. Wine valley lifestyle.', '1 Main North Road', 'Clare', 'SA', '5453', 'Independent Living', 260000, 410000, 115, 190, 68, 6, ARRAY['Wine Country', 'Community Centre', 'Gardens', 'Village Atmosphere'], '08 8842 1234', 'info@clarevalleyretirement.com.au', 'https://www.clarevalleyretirement.com.au', 'Active'),

('Lifestyle Communities Glenelg North', 'Lifestyle Communities', 'Beachside Adelaide over-50s community. Modern manufactured homes near beaches. Pool, bowling green, gym and clubhouse. Walk to beach, tram and shops. Affordable coastal living.', '1 Partridge Street', 'Glenelg North', 'SA', '5045', 'Independent Living', 260000, 430000, 100, 170, 154, 13, ARRAY['Pool', 'Bowling Green', 'Gym', 'Beach Access', 'Clubhouse'], '08 8295 9200', 'glenelgnorth@lifestylecommunities.com.au', 'https://www.lifestylecommunities.com.au', 'Active');
