-- TAS/ACT/NT Batch 01: 10 Tasmania, ACT & Northern Territory Retirement Villages (FINAL BATCH!)
-- Geographic Focus: Hobart, Launceston, Canberra, Darwin
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Aveo Goodwood', 'Aveo Group', 'Northern Hobart retirement community. Modern villas with mountain views. Pool, gym, bowling green and community facilities. Close to Northgate shopping, medical facilities and city access. Tasmanian lifestyle.', '88 Main Road', 'Glenorchy', 'TAS', '7010', 'Independent Living', 320000, 480000, 140, 220, 104, 9, ARRAY['Pool', 'Gym', 'Bowling Green', 'Mountain Views', 'Community Centre'], '1300 283 000', 'goodwood@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Lendlease Battery Point', 'Lendlease', 'Premium Hobart waterfront retirement. Luxury apartments with harbour views. Pool, gym, community facilities and heritage setting. Walk to Salamanca Market, restaurants and waterfront. Elite Tasmanian address.', '42 Hampden Road', 'Battery Point', 'TAS', '7004', 'Independent Living', 520000, 780000, 200, 300, 68, 4, ARRAY['Harbour Views', 'Pool', 'Gym', 'Heritage Setting', 'Waterfront Access'], '1300 326 033', 'batterypoint@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Launceston', 'Anglicare', 'Northern Tasmania retirement community. Independent villas with chapel and community facilities. Bowling green and gardens. Close to Launceston General Hospital, shopping and Cataract Gorge. Regional city living.', '88 Elphin Road', 'Launceston', 'TAS', '7250', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 94, 8, ARRAY['Chapel', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '03 6224 3100', 'launceston@anglicaretas.org.au', 'https://www.anglicaretas.org.au', 'Active'),

('Regis Aged Care Devonport', 'Regis Aged Care', 'North-West Tasmania coastal retirement. Quality villas near Bass Strait and Spirit of Tasmania. Community facilities and aged care. Close to shopping, beaches and medical facilities. Coastal Tasmanian living.', '88 Best Street', 'Devonport', 'TAS', '7310', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 76, 7, ARRAY['Coastal Access', 'Community Centre', 'Gardens', 'Ferry Terminal', 'Aged Care'], '03 6424 3100', 'devonport@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Bupa Aged Care Kingston', 'Bupa', 'Southern Hobart retirement community. Modern villas near Channel Highway. Pool, community facilities and mountain views. Close to Kingston Beach, shopping centres and medical facilities. Southern Tasmanian lifestyle.', '42 Channel Highway', 'Kingston', 'TAS', '7050', 'Independent Living, Aged Care', 320000, 480000, 140, 220, 86, 7, ARRAY['Pool', 'Mountain Views', 'Beach Access', 'Community Centre', 'Aged Care'], '1300 280 334', 'kingston@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Goodwin Aged Care Canberra', 'Goodwin', 'ACT national capital retirement community. Modern villas near Parliament House. Pool, community facilities and national attractions. Close to Woden shopping, medical facilities and cultural institutions. Capital lifestyle.', '88 Melrose Drive', 'Phillip', 'ACT', '2606', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 124, 11, ARRAY['Pool', 'Community Centre', 'Gardens', 'Cultural Access', 'Aged Care'], '02 6293 3100', 'canberra@goodwin.org.au', 'https://www.goodwin.org.au', 'Active'),

('Calvary Retirement Community Bruce', 'Calvary', 'Northern Canberra retirement. Catholic heritage with chapel and pastoral care. Contemporary villas near Australian National University. Close to Belconnen shopping, medical facilities and Lake Burley Griffin.', '88 Haydon Drive', 'Bruce', 'ACT', '2617', 'Independent Living, Aged Care', 400000, 600000, 170, 260, 96, 8, ARRAY['Chapel', 'University Access', 'Lake Access', 'Community Centre', 'Aged Care'], '02 6201 1234', 'bruce@calvarycare.org.au', 'https://www.calvarycare.org.au', 'Active'),

('Southern Cross Care Canberra', 'Southern Cross Care', 'Inner south Canberra retirement community. Quality villas near Manuka and Kingston. Community facilities, gardens and aged care. Walk to parliamentary triangle, shops and lake. Premium capital location.', '88 Canberra Avenue', 'Griffith', 'ACT', '2603', 'Independent Living, Aged Care', 480000, 720000, 190, 280, 88, 6, ARRAY['Gardens', 'Parliamentary Triangle', 'Lake Access', 'Community Centre', 'Aged Care'], '02 6282 1234', 'canberra@sccliving.org.au', 'https://www.sccliving.org.au', 'Active'),

('Allity Darwin', 'Allity', 'Tropical Northern Territory capital retirement. Modern villas with tropical setting. Pool, community facilities and gardens. Close to Darwin shopping, Mindil Beach and medical facilities. Tropical Top End lifestyle.', '88 Stuart Highway', 'Parap', 'NT', '0820', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 94, 8, ARRAY['Pool', 'Tropical Gardens', 'Beach Access', 'Community Centre', 'Aged Care'], '08 8941 3100', 'darwin@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Estia Health Alice Springs', 'Estia Health', 'Red Centre outback retirement. Comfortable villas in desert setting. Pool, community facilities and outback atmosphere. Close to Alice Springs town centre, medical facilities and cultural attractions. Iconic outback living.', '88 Gap Road', 'Alice Springs', 'NT', '0870', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 64, 6, ARRAY['Pool', 'Desert Setting', 'Community Centre', 'Cultural Access', 'Aged Care'], '08 8952 3100', 'alicesprings@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active');
