-- VIC Batch 03: 25 Mornington Peninsula, Gippsland & South-East VIC Retirement Villages
-- Geographic Focus: Mornington, Frankston South, Mornington Peninsula, Gippsland Coast
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Stockland Halcyon Lakeside Pakenham', 'Stockland', 'South-eastern growth corridor retirement resort. Modern villas with lakefront setting. Pool, gym, cinema, bowling green and community hub. Close to Pakenham shopping and Cardinia Lakes. Resort amenities.', '1 Lakeside Boulevard', 'Pakenham', 'VIC', '3810', 'Independent Living', 340000, 520000, 150, 230, 206, 17, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Lake Views', 'Community Centre'], '1800 550 550', 'pakenham@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Aveo Mornington', 'Aveo Group', 'Premium Mornington Peninsula retirement living. Contemporary apartments near Mornington village and beaches. Pool, gym, community facilities and bay views. Walk to Main Street shops, cafes and pier. Peninsula lifestyle.', '88 The Esplanade', 'Mornington', 'VIC', '3931', 'Independent Living', 480000, 720000, 190, 280, 116, 8, ARRAY['Pool', 'Gym', 'Bay Views', 'Beach Access', 'Community Centre'], '1300 283 000', 'mornington@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Lendlease Safety Beach', 'Lendlease', 'Bayside peninsula retirement village near beaches. Quality villas with bay breezes. Pool, bowling green and community facilities. Walk to Safety Beach and Dromana village. Perfect peninsula coastal living.', '42 Marine Parade', 'Safety Beach', 'VIC', '3936', 'Independent Living', 420000, 640000, 170, 260, 98, 7, ARRAY['Pool', 'Bowling Green', 'Bay Breezes', 'Beach Access', 'Community Centre'], '1300 326 033', 'safetybeach@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Peninsula Pines', 'Anglicare', 'Mornington Peninsula retirement community in Mount Eliza. Independent villas with chapel and gardens. Community centre and bushland setting. Close to Mount Eliza village and Canadian Bay beaches. Peaceful peninsula location.', '88 Mount Eliza Way', 'Mount Eliza', 'VIC', '3930', 'Independent Living, Aged Care', 420000, 620000, 170, 260, 94, 6, ARRAY['Chapel', 'Gardens', 'Bushland Setting', 'Community Centre', 'Aged Care'], '03 9787 3100', 'mounteliza@anglicare.vic.org.au', 'https://www.anglicarevic.org.au', 'Active'),

('Baptistcare Sorrento', 'BaptistCare', 'Premium peninsula tip retirement village. Luxury villas near Sorrento beaches and village. Chapel, pool and community facilities. Walk to cafes, galleries and ocean beaches. Elite peninsula address.', '88 Ocean Beach Road', 'Sorrento', 'VIC', '3943', 'Independent Living', 580000, 840000, 220, 320, 68, 3, ARRAY['Pool', 'Chapel', 'Beach Access', 'Village Atmosphere', 'Ocean Views'], '03 5984 3100', 'sorrento@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Uniting AgeWell Berwick', 'Uniting AgeWell', 'South-eastern suburbs retirement community. Modern villas with community facilities. Pool, community centre and gardens. Close to Eden Rise shopping, Berwick village and Casey Hospital. Growth corridor living.', '42 High Street', 'Berwick', 'VIC', '3806', 'Independent Living', 340000, 510000, 150, 230, 124, 11, ARRAY['Pool', 'Community Centre', 'Gardens', 'Shopping Access'], '1300 783 435', 'berwick@unitingagewell.org', 'https://www.unitingagewell.org', 'Active'),

('Opal Aged Care Lakes Entrance', 'Opal Aged Care', 'Gippsland coastal retirement village near pristine lakes. Modern villas with lake and ocean access. Pool, community facilities and waterfront walks. Perfect fishing, boating and beach lifestyle. Gippsland paradise.', '88 The Esplanade', 'Lakes Entrance', 'VIC', '3909', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 76, 6, ARRAY['Pool', 'Lake Access', 'Beach Access', 'Fishing', 'Community Centre', 'Aged Care'], '1300 672 524', 'lakesentrance@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Cranbourne', 'IRT Group', 'South-eastern growth area retirement community. Affordable villas with community facilities. Bowling green, gardens and activity programs. Close to Cranbourne Park shopping and Casey Hospital. Family area living.', '88 South Gippsland Highway', 'Cranbourne', 'VIC', '3977', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 132, 12, ARRAY['Bowling Green', 'Gardens', 'Community Centre', 'Shopping Access', 'Aged Care'], '1300 157 677', 'cranbourne@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Regis Aged Care Rye', 'Regis Aged Care', 'Peninsula coastal village retirement near back beaches. Quality villas with ocean breezes. Pool, bowling green and community facilities. Walk to Rye village, beaches and pier. Ultimate peninsula lifestyle.', '42 Point Nepean Road', 'Rye', 'VIC', '3941', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 84, 7, ARRAY['Pool', 'Bowling Green', 'Ocean Breezes', 'Beach Access', 'Aged Care'], '03 5985 3100', 'rye@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Sale', 'Respect', 'Gippsland regional city retirement community. Comfortable villas near Sale city centre. Community facilities, bowling green and gardens. Close to Sale Hospital and shopping. Affordable regional living.', '88 York Street', 'Sale', 'VIC', '3850', 'Independent Living, Aged Care', 220000, 360000, 95, 165, 86, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Regional Setting', 'Aged Care'], '03 5144 3100', 'sale@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Arcare Frankston South', 'Arcare', 'Bayside retirement community near Frankston beaches. Contemporary apartments with bay views. Pool, gym and community facilities. Walk to beach, golf course and Frankston. Premium bayside position.', '88 Olivers Road', 'Frankston South', 'VIC', '3199', 'Independent Living, Aged Care', 420000, 620000, 170, 260, 102, 8, ARRAY['Pool', 'Gym', 'Bay Views', 'Beach Access', 'Aged Care'], '1300 272 273', 'frankstonsouth@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Bupa Aged Care Bairnsdale', 'Bupa', 'East Gippsland retirement village near Mitchell River. Comfortable villas with regional setting. Community centre, bowling green and gardens. Close to Bairnsdale city centre and medical facilities. Country town living.', '42 Main Street', 'Bairnsdale', 'VIC', '3875', 'Independent Living, Aged Care', 220000, 360000, 95, 165, 78, 7, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'River Views', 'Aged Care'], '1300 280 334', 'bairnsdale@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Narre Warren', 'Allity', 'South-eastern suburbs retirement community. Modern villas near Fountain Gate shopping. Pool, community facilities and gardens. Close to Casey Hospital and Monash Freeway. Convenient growth corridor location.', '88 Princes Highway', 'Narre Warren', 'VIC', '3805', 'Independent Living, Aged Care', 340000, 510000, 150, 230, 118, 10, ARRAY['Pool', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '03 9704 3100', 'narrewarren@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Mount Martha', 'Bolton Clarke', 'Premium peninsula village retirement. Quality villas with bay views and beaches nearby. Pool, community facilities and coastal walks. Walk to Mount Martha village, cafes and beaches. Prestigious peninsula address.', '88 The Esplanade', 'Mount Martha', 'VIC', '3934', 'Independent Living, Aged Care', 480000, 720000, 190, 280, 92, 6, ARRAY['Pool', 'Bay Views', 'Beach Access', 'Coastal Walks', 'Aged Care'], '1300 228 655', 'mountmartha@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Estia Health Traralgon', 'Estia Health', 'Gippsland regional city retirement community. Modern villas near Traralgon CBD. Pool, community centre and gardens. Close to Latrobe Regional Hospital and shopping. Central Gippsland location.', '88 Princes Highway', 'Traralgon', 'VIC', '3844', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 94, 8, ARRAY['Pool', 'Community Centre', 'Gardens', 'Regional Setting', 'Aged Care'], '03 5174 3100', 'traralgon@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Hastings', 'Japara', 'Western Port retirement village near beaches. Comfortable villas with community facilities and aged care. Close to Hastings village, marina and beaches. Peaceful coastal town atmosphere.', '42 Marine Parade', 'Hastings', 'VIC', '3915', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 86, 7, ARRAY['Community Centre', 'Gardens', 'Marina Access', 'Beach Access', 'Aged Care'], '1800 52 72 72', 'hastings@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Warragul', 'Tricare', 'Gippsland hills retirement village. Cool climate villas with mountain views. Community centre, bowling green and gardens. Close to Warragul town centre and medical facilities. Country town lifestyle.', '88 Queen Street', 'Warragul', 'VIC', '3820', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 74, 6, ARRAY['Bowling Green', 'Mountain Views', 'Community Centre', 'Gardens', 'Aged Care'], '03 5623 3100', 'warragul@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Dromana', 'Mayflower', 'Mornington Peninsula bayside village retirement. Comfortable villas near Dromana beaches. Community centre, gardens and bay access. Walk to Dromana village, pier and cafes. Classic peninsula lifestyle.', '88 Point Nepean Road', 'Dromana', 'VIC', '3936', 'Independent Living', 360000, 540000, 150, 240, 78, 5, ARRAY['Bay Access', 'Beach Nearby', 'Community Centre', 'Gardens'], '03 5987 1234', 'dromana@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care Wonthaggi', 'RSL Care', 'Bass Coast retirement village near beaches. Affordable villas with veterans services. Bowling green, community centre and gardens. Close to Wonthaggi town centre and Cape Paterson beaches. Coastal country living.', '42 Graham Street', 'Wonthaggi', 'VIC', '3995', 'Independent Living, Aged Care', 220000, 360000, 95, 165, 68, 6, ARRAY['Bowling Green', 'RSL Services', 'Community Centre', 'Gardens', 'Aged Care'], '03 5672 3100', 'wonthaggi@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('Mercy Health Officer', 'Mercy Health', 'South-eastern suburbs retirement community. Catholic heritage with chapel and pastoral care. Modern villas with community facilities and aged care. Close to Officer shopping and medical facilities.', '88 Tivendale Road', 'Officer', 'VIC', '3809', 'Independent Living, Aged Care', 340000, 510000, 150, 230, 106, 9, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '03 5943 3100', 'officer@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Active'),

('Benetas Morwell', 'Benetas', 'Latrobe Valley retirement community. Affordable villas with community facilities. Bowling green, gardens and aged care. Close to Morwell town centre, Mid Valley shopping and medical facilities. Regional living.', '88 Princes Drive', 'Morwell', 'VIC', '3840', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 82, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Regional Setting', 'Aged Care'], '03 5133 3100', 'morwell@benetas.com.au', 'https://www.benetas.com.au', 'Active'),

('Embracia Inverloch', 'Embracia Health', 'Bass Coast beachside retirement village. Modern villas near pristine Inverloch beaches. Pool, community facilities and coastal walks. Perfect fishing, surfing and beach lifestyle. Popular coastal destination.', '42 Ramsey Boulevard', 'Inverloch', 'VIC', '3996', 'Independent Living, Aged Care', 320000, 480000, 140, 220, 72, 5, ARRAY['Pool', 'Beach Access', 'Coastal Walks', 'Fishing', 'Aged Care'], '03 5674 3100', 'inverloch@embracia.com.au', 'https://www.embracia.com.au', 'Active'),

('Warrigal Care Blairgowrie', 'Warrigal Care', 'Peninsula tip retirement village near back beaches. Premium villas with ocean access. Community facilities and coastal setting. Walk to Blairgowrie village, beaches and Sorrento ferry. Elite peninsula position.', '88 Nepean Highway', 'Blairgowrie', 'VIC', '3942', 'Independent Living', 480000, 720000, 190, 280, 64, 3, ARRAY['Ocean Access', 'Beach Nearby', 'Community Centre', 'Village Atmosphere'], '03 5988 1234', 'blairgowrie@warrigal.com.au', 'https://www.warrigal.com.au', 'Active'),

('Peninsula Villages McCrae', 'Peninsula Villages', 'Mornington Peninsula beachside retirement. Contemporary villas near McCrae Beach. Pool, bowling green and community facilities. Walk to beach, foreshore trails and cafes. Classic peninsula living.', '1 Nepean Highway', 'McCrae', 'VIC', '3938', 'Independent Living', 380000, 580000, 160, 250, 96, 8, ARRAY['Pool', 'Bowling Green', 'Beach Access', 'Foreshore Trails', 'Community Centre'], '03 5981 3100', 'mccrae@peninsulavillages.com.au', 'https://www.peninsulavillages.com.au', 'Active'),

('Resthaven Leongatha', 'Resthaven', 'South Gippsland retirement village. Comfortable villas in regional town setting. Community centre, bowling green and gardens. Close to Leongatha town centre and medical facilities. Peaceful country living.', '88 Bair Street', 'Leongatha', 'VIC', '3953', 'Independent Living, Aged Care', 210000, 350000, 90, 160, 64, 6, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Country Setting', 'Aged Care'], '03 5662 1234', 'leongatha@resthaven.asn.au', 'https://www.resthaven.asn.au', 'Active');
