-- VIC Batch 01: 25 Melbourne Metro Retirement Villages
-- Geographic Focus: Inner Melbourne, Bayside, Eastern Suburbs
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Aveo Brighton East', 'Aveo Group', 'Premium bayside retirement living near Brighton Beach. Contemporary apartments with bay glimpses. Pool, gym, cinema and rooftop terrace. Walk to Church Street shops, cafes and beach. Elite Melbourne location.', '88 New Street', 'Brighton East', 'VIC', '3187', 'Independent Living', 620000, 880000, 240, 340, 124, 7, ARRAY['Pool', 'Gym', 'Cinema', 'Rooftop Terrace', 'Bay Glimpses', 'Concierge'], '1300 283 000', 'brightoneast@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Stockland Mernda', 'Stockland', 'Northern Melbourne retirement community near new train station. Modern villas with resort amenities. Pool, gym, cinema, bowling green and community hub. Close to Plenty Valley shopping and medical facilities.', '1 Mernda Village Drive', 'Mernda', 'VIC', '3754', 'Independent Living', 380000, 580000, 160, 250, 196, 15, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Community Centre', 'Gardens'], '1800 550 550', 'mernda@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Lendlease Retirement Docklands', 'Lendlease', 'Luxury Melbourne city retirement living. Premium apartments with harbour and city views. Rooftop terrace, pool, gym, cinema and fine dining. Walk to Harbour Town shopping and waterfront dining. Ultimate urban living.', '88 Waterfront Way', 'Docklands', 'VIC', '3008', 'Independent Living', 780000, 1180000, 300, 430, 142, 6, ARRAY['Harbour Views', 'Rooftop Terrace', 'Pool', 'Gym', 'Cinema', 'Fine Dining', 'Concierge'], '1300 326 033', 'docklands@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Whitehorse', 'Anglicare', 'Eastern suburbs retirement community in Box Hill. Independent villas with chapel and community facilities. Close to Box Hill Central shopping, hospital and transport. Established multicultural community.', '42 Canterbury Road', 'Box Hill', 'VIC', '3128', 'Independent Living, Aged Care', 420000, 620000, 170, 260, 112, 9, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '03 9896 3100', 'whitehorse@anglicare.vic.org.au', 'https://www.anglicarevic.org.au', 'Active'),

('Baptistcare Wyndham Lodge', 'BaptistCare', 'Western suburbs retirement village in Werribee. Comfortable villas with chapel and bowling green. Community centre and gardens. Close to Werribee Plaza, hospital and train station. Affordable western growth area.', '88 Watton Street', 'Werribee', 'VIC', '3030', 'Independent Living, Aged Care', 320000, 480000, 140, 220, 126, 11, ARRAY['Chapel', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '03 9741 3100', 'werribee@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Uniting AgeWell Balwyn', 'Uniting AgeWell', 'Eastern suburbs retirement living in leafy Balwyn. Quality apartments with pool, gym and community facilities. Walk to Balwyn village shops, cafes and trams. Prestige family area with excellent amenities.', '88 Whitehorse Road', 'Balwyn', 'VIC', '3103', 'Independent Living', 580000, 820000, 220, 320, 96, 5, ARRAY['Pool', 'Gym', 'Community Centre', 'Gardens', 'Tram Access'], '1300 783 435', 'balwyn@unitingagewell.org', 'https://www.unitingagewell.org', 'Active'),

('Opal Aged Care Glen Waverley', 'Opal Aged Care', 'Eastern suburbs retirement near major shopping. Contemporary apartments with pool, gym and cinema. Walk to Glen Waverley station, The Glen shopping and medical facilities. Premium location convenience.', '42 Springvale Road', 'Glen Waverley', 'VIC', '3150', 'Independent Living, Aged Care', 480000, 680000, 190, 280, 138, 10, ARRAY['Pool', 'Gym', 'Cinema', 'Community Centre', 'Shopping Access', 'Aged Care'], '1300 672 524', 'glenwaverley@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Royal Freemasons Footscray', 'IRT Group', 'Inner-west Melbourne retirement community. Modern apartments near Footscray Hospital. Pool, community centre and gardens. Walk to Footscray Market, station and multicultural restaurants. Diverse urban community.', '22 Buckley Street', 'Footscray', 'VIC', '3011', 'Independent Living, Aged Care', 380000, 560000, 160, 250, 104, 8, ARRAY['Pool', 'Community Centre', 'Gardens', 'Urban Location', 'Aged Care'], '1300 157 677', 'footscray@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Regis Aged Care Templestowe', 'Regis Aged Care', 'Eastern suburbs retirement village in leafy Templestowe. Quality villas with gardens and bushland setting. Community centre, bowling green and aged care. Close to Westfield Doncaster and Manningham Medical Centre.', '88 Reynolds Road', 'Templestowe', 'VIC', '3106', 'Independent Living, Aged Care', 480000, 680000, 190, 280, 92, 6, ARRAY['Bowling Green', 'Gardens', 'Bushland Setting', 'Community Centre', 'Aged Care'], '03 9850 3100', 'templestowe@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Coburg', 'Respect', 'Northern suburbs retirement community near Coburg station. Modern villas with multicultural community atmosphere. Pool, community centre and gardens. Walk to Sydney Road shops and trams. Affordable inner-north living.', '42 Bell Street', 'Coburg', 'VIC', '3058', 'Independent Living, Aged Care', 380000, 560000, 160, 250, 116, 9, ARRAY['Pool', 'Community Centre', 'Gardens', 'Tram Access', 'Aged Care'], '03 9354 3100', 'coburg@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Arcare Burnside', 'Arcare', 'Western suburbs retirement village in Burnside Heights. Contemporary villas with resort facilities. Pool, gym, bowling green and community hub. Close to shopping centres and medical facilities. Modern growth area living.', '1 Boardwalk Boulevard', 'Burnside', 'VIC', '3023', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 148, 12, ARRAY['Pool', 'Gym', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '1300 272 273', 'burnside@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Bupa Aged Care Cheltenham', 'Bupa', 'Bayside retirement community near Southland shopping. Modern apartments with community facilities. Walk to Southland, Cheltenham station and medical facilities. Easy beach and city access. Premium bayside location.', '88 Charman Road', 'Cheltenham', 'VIC', '3192', 'Independent Living, Aged Care', 480000, 680000, 190, 280, 108, 7, ARRAY['Community Centre', 'Gardens', 'Shopping Access', 'Station Access', 'Aged Care'], '1300 280 334', 'cheltenham@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Dandenong', 'Allity', 'South-eastern suburbs retirement community. Affordable villas with multicultural friendly environment. Community centre, bowling green and gardens. Close to Dandenong Market, hospital and Plaza. Diverse community.', '42 Foster Street', 'Dandenong', 'VIC', '3175', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 94, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Cultural Centre', 'Aged Care'], '03 9791 3100', 'dandenong@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Doncaster', 'Bolton Clarke', 'Eastern suburbs retirement village near Westfield Doncaster. Quality villas with community facilities and aged care. Pool, bowling green and gardens. Walk to major shopping and medical facilities. Premium eastern location.', '88 Williamsons Road', 'Doncaster', 'VIC', '3108', 'Independent Living, Aged Care', 520000, 740000, 200, 300, 112, 8, ARRAY['Pool', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '1300 228 655', 'doncaster@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Estia Health Keilor', 'Estia Health', 'Western suburbs retirement community near Keilor Downs. Modern villas with pool and community facilities. Close to shopping centres, medical facilities and Calder Freeway. Convenient western suburbs living.', '22 Taylors Road', 'Keilor Downs', 'VIC', '3038', 'Independent Living, Aged Care', 340000, 510000, 150, 230, 102, 9, ARRAY['Pool', 'Community Centre', 'Gardens', 'Library', 'Aged Care'], '03 9390 3100', 'keilor@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Glenrowan', 'Japara', 'Inner-eastern retirement community in Hawthorn. Heritage-style villas near Glenferrie Road. Community centre, gardens and aged care. Walk to trams, shops, cafes and Swinburne University. Prestige inner suburb.', '88 Burwood Road', 'Hawthorn', 'VIC', '3122', 'Independent Living, Aged Care', 580000, 820000, 220, 320, 76, 4, ARRAY['Heritage Style', 'Gardens', 'Community Centre', 'Tram Access', 'Aged Care'], '1800 52 72 72', 'hawthorn@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Frankston', 'Tricare', 'Bayside retirement village near Frankston Beach. Modern villas with bay breezes. Pool, bowling green and community facilities. Walk to Bayside Shopping Centre, station and beaches. Affordable bayside living.', '88 Nepean Highway', 'Frankston', 'VIC', '3199', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 132, 11, ARRAY['Pool', 'Bowling Green', 'Bay Breezes', 'Community Centre', 'Aged Care'], '03 9783 3100', 'frankston@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Brighton', 'Mayflower', 'Premium bayside retirement living near Middle Brighton Beach. Luxury apartments with bay views. Rooftop terrace, pool, gym and concierge. Walk to Church Street shopping, cafes and beach. Elite Melbourne address.', '88 Martin Street', 'Brighton', 'VIC', '3186', 'Independent Living', 720000, 1020000, 280, 390, 84, 3, ARRAY['Bay Views', 'Rooftop Terrace', 'Pool', 'Gym', 'Concierge', 'Beach Access'], '03 9592 1234', 'brighton@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care Heidelberg', 'RSL Care', 'Northern suburbs retirement village near Austin Hospital. Villas with veterans services and community facilities. Bowling green, gardens and RSL club nearby. Close to Heidelberg station and shopping. Strong community spirit.', '42 Lower Plenty Road', 'Heidelberg', 'VIC', '3084', 'Independent Living, Aged Care', 420000, 620000, 170, 260, 96, 7, ARRAY['Bowling Green', 'Gardens', 'RSL Services', 'Community Centre', 'Aged Care'], '03 9450 3100', 'heidelberg@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('Peninsula Villages Rosebud', 'Peninsula Villages', 'Mornington Peninsula coastal retirement resort. Modern villas near Rosebud Beach. Pool, gym, bowling green and community hub. Walk to beach, shops and cafes. Ultimate peninsula lifestyle.', '1 Boneo Road', 'Rosebud', 'VIC', '3939', 'Independent Living', 380000, 580000, 160, 250, 164, 13, ARRAY['Pool', 'Gym', 'Bowling Green', 'Beach Access', 'Community Centre'], '03 5986 3100', 'rosebud@peninsulavillages.com.au', 'https://www.peninsulavillages.com.au', 'Active'),

('Mercy Health Werribee', 'Mercy Health', 'Western growth corridor retirement community with Catholic heritage. Modern villas with chapel and pastoral care. Pool, community centre and gardens. Close to Werribee Mercy Hospital and shopping.', '88 Heaths Road', 'Werribee', 'VIC', '3030', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 118, 10, ARRAY['Chapel', 'Pool', 'Community Centre', 'Gardens', 'Aged Care'], '03 9742 3100', 'werribee@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Active'),

('Benetas Heidelberg West', 'Benetas', 'Northern suburbs retirement community with Greek heritage services. Multicultural friendly villas with community facilities. Chapel, gardens and cultural programs. Close to shopping and medical facilities.', '42 Banksia Street', 'Heidelberg West', 'VIC', '3081', 'Independent Living, Aged Care', 320000, 480000, 140, 220, 88, 7, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Cultural Centre', 'Aged Care'], '03 9854 3100', 'heidelbergwest@benetas.com.au', 'https://www.benetas.com.au', 'Active'),

('Embracia Eltham', 'Embracia Health', 'North-eastern suburbs retirement village in leafy Eltham. Villas surrounded by native bushland. Community centre, gardens and art gallery nearby. Enjoy artistic community and nature. Bohemian green wedge living.', '88 Main Road', 'Eltham', 'VIC', '3095', 'Independent Living, Aged Care', 420000, 620000, 170, 260, 84, 6, ARRAY['Bushland Setting', 'Gardens', 'Community Centre', 'Arts Culture', 'Aged Care'], '03 9439 3100', 'eltham@embracia.com.au', 'https://www.embracia.com.au', 'Active'),

('Resthaven Williamstown', 'Resthaven', 'Western suburbs harbourside retirement village. Modern apartments with water views. Pool, community facilities and waterfront walks. Walk to Nelson Place cafes, beach and Williamstown station. Historic maritime location.', '88 The Strand', 'Williamstown', 'VIC', '3016', 'Independent Living', 520000, 760000, 200, 300, 92, 5, ARRAY['Water Views', 'Pool', 'Waterfront Walks', 'Community Centre', 'Maritime Heritage'], '03 9397 1234', 'williamstown@resthaven.asn.au', 'https://www.resthaven.asn.au', 'Active'),

('Warrigal Care Bundoora', 'Warrigal Care', 'Northern suburbs retirement community near La Trobe University. Modern villas with community facilities and aged care. Pool, gardens and activity programs. Close to university hospital and Plenty Road shopping.', '88 Plenty Road', 'Bundoora', 'VIC', '3083', 'Independent Living, Aged Care', 380000, 560000, 160, 250, 108, 9, ARRAY['Pool', 'Gardens', 'Community Centre', 'University Access', 'Aged Care'], '03 9467 3100', 'bundoora@warrigal.com.au', 'https://www.warrigal.com.au', 'Active');
