-- VIC Batch 05: 25 Regional Victoria Retirement Villages (FINAL VIC BATCH)
-- Geographic Focus: Ballarat, Bendigo, Shepparton, Wodonga, Warrnambool, Regional Cities
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Aveo Ballarat', 'Aveo Group', 'Regional city retirement community in historic Ballarat. Modern villas near Lake Wendouree. Pool, gym, bowling green and community facilities. Close to shops, medical facilities and Sovereign Hill. Heritage city living.', '88 Sturt Street', 'Ballarat', 'VIC', '3350', 'Independent Living', 280000, 430000, 120, 195, 136, 11, ARRAY['Pool', 'Gym', 'Bowling Green', 'Lake Views', 'Community Centre'], '1300 283 000', 'ballarat@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Stockland Bendigo', 'Stockland', 'Central Victorian goldfields retirement resort. Contemporary villas with resort amenities. Pool, gym, cinema, bowling green and community hub. Close to Bendigo Hospital, shopping and historic centre.', '1 Strathdale Drive', 'Bendigo', 'VIC', '3550', 'Independent Living', 300000, 460000, 130, 210, 174, 14, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Community Centre', 'Gardens'], '1800 550 550', 'bendigo@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Lendlease Wodonga', 'Lendlease', 'Border city retirement community near Albury. Quality villas with mountain views. Pool, bowling green and community facilities. Close to Gateway Village shopping and Border Medical Centre. Regional affordability.', '42 High Street', 'Wodonga', 'VIC', '3690', 'Independent Living', 260000, 410000, 115, 190, 118, 10, ARRAY['Pool', 'Bowling Green', 'Mountain Views', 'Community Centre', 'Gardens'], '1300 326 033', 'wodonga@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Shepparton', 'Anglicare', 'Goulburn Valley regional retirement community. Independent villas with chapel and community facilities. Bowling green and gardens. Close to Shepparton hospital, marketplace and medical facilities. Regional city living.', '88 Wyndham Street', 'Shepparton', 'VIC', '3630', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 102, 9, ARRAY['Chapel', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '03 5831 3100', 'shepparton@anglicare.vic.org.au', 'https://www.anglicarevic.org.au', 'Active'),

('Baptistcare Mildura', 'BaptistCare', 'Sunraysia region retirement community. Modern villas near Murray River. Chapel, pool, bowling green and community centre. Close to Mildura Centro shopping and hospital. Warm climate river lifestyle.', '88 Deakin Avenue', 'Mildura', 'VIC', '3500', 'Independent Living, Aged Care', 220000, 360000, 95, 165, 96, 8, ARRAY['Pool', 'Chapel', 'Bowling Green', 'River Views', 'Aged Care'], '03 5021 3100', 'mildura@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Uniting AgeWell Echuca', 'Uniting AgeWell', 'Murray River retirement village in historic Echuca. Comfortable villas near riverfront and paddle steamers. Community centre, gardens and river atmosphere. Walk to shops, port and medical facilities. River heritage living.', '42 High Street', 'Echuca', 'VIC', '3564', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 84, 7, ARRAY['River Views', 'Community Centre', 'Gardens', 'Heritage Port', 'Aged Care'], '1300 783 435', 'echuca@unitingagewell.org', 'https://www.unitingagewell.org', 'Active'),

('Opal Aged Care Warrnambool', 'Opal Aged Care', 'Great Ocean Road coastal city retirement. Modern villas near Warrnambool beaches. Pool, community facilities and coastal walks. Close to shopping, medical facilities and whale watching. Regional coastal lifestyle.', '88 Raglan Parade', 'Warrnambool', 'VIC', '3280', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 108, 9, ARRAY['Pool', 'Beach Access', 'Coastal Walks', 'Community Centre', 'Aged Care'], '1300 672 524', 'warrnambool@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Wangaratta', 'IRT Group', 'North-eastern regional retirement community. Spacious villas near Ovens River and wineries. Bowling green, community centre and gardens. Close to Wangaratta town centre and hospital. Wine country living.', '88 Parfitt Road', 'Wangaratta', 'VIC', '3677', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 92, 8, ARRAY['Bowling Green', 'River Views', 'Wine Country', 'Community Centre', 'Aged Care'], '1300 157 677', 'wangaratta@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Regis Aged Care Swan Hill', 'Regis Aged Care', 'Murray River retirement village in Swan Hill. Comfortable villas with river setting. Community centre, bowling green and gardens. Close to Swan Hill Pioneer Settlement and shopping. River town lifestyle.', '42 Campbell Street', 'Swan Hill', 'VIC', '3585', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 76, 7, ARRAY['Bowling Green', 'River Setting', 'Community Centre', 'Gardens', 'Aged Care'], '03 5032 3100', 'swanhill@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Horsham', 'Respect', 'Wimmera region retirement village. Affordable villas in regional centre. Community facilities, bowling green and gardens. Close to Horsham Haven shopping and Wimmera Base Hospital. Regional country living.', '88 Firebrace Street', 'Horsham', 'VIC', '3400', 'Independent Living, Aged Care', 190000, 330000, 85, 155, 82, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Regional Setting', 'Aged Care'], '03 5382 3100', 'horsham@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Arcare Colac', 'Arcare', 'Western districts retirement community. Modern villas near Lake Colac. Pool, community facilities and gardens. Close to Colac town centre and medical facilities. Gateway to Otways and coast.', '88 Murray Street', 'Colac', 'VIC', '3250', 'Independent Living, Aged Care', 240000, 380000, 105, 175, 74, 6, ARRAY['Pool', 'Lake Views', 'Community Centre', 'Gardens', 'Aged Care'], '1300 272 273', 'colac@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Bupa Aged Care Portland', 'Bupa', 'Western coastal retirement village near Portland Bay. Comfortable villas with ocean proximity. Community centre, gardens and coastal setting. Close to Portland town centre and Cape Nelson. Coastal regional living.', '42 Percy Street', 'Portland', 'VIC', '3305', 'Independent Living, Aged Care', 220000, 360000, 95, 165, 64, 5, ARRAY['Coastal Setting', 'Community Centre', 'Gardens', 'Bay Views', 'Aged Care'], '1300 280 334', 'portland@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Seymour', 'Allity', 'Northern regional retirement village near Goulburn Valley. Affordable villas with community facilities. Bowling green, gardens and aged care. Close to Seymour town centre and railway station. Regional accessibility.', '88 Emily Street', 'Seymour', 'VIC', '3660', 'Independent Living, Aged Care', 220000, 360000, 95, 165, 86, 8, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Station Access', 'Aged Care'], '03 5792 3100', 'seymour@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Hamilton', 'Bolton Clarke', 'Western districts retirement community in historic Hamilton. Quality villas with heritage atmosphere. Community centre, bowling green and gardens. Close to Hamilton Hospital and shopping. Southern Grampians location.', '88 Gray Street', 'Hamilton', 'VIC', '3300', 'Independent Living, Aged Care', 220000, 360000, 95, 165, 72, 6, ARRAY['Bowling Green', 'Heritage Setting', 'Community Centre', 'Gardens', 'Aged Care'], '1300 228 655', 'hamilton@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Estia Health Moe', 'Estia Health', 'Gippsland retirement village in Latrobe Valley. Affordable villas with community facilities. Pool, gardens and aged care. Close to Moe town centre and medical facilities. Valley regional living.', '88 Lloyd Street', 'Moe', 'VIC', '3825', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 88, 8, ARRAY['Pool', 'Community Centre', 'Gardens', 'Valley Setting', 'Aged Care'], '03 5127 3100', 'moe@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Benalla', 'Japara', 'North-eastern regional retirement village. Comfortable villas in country town setting. Community centre, bowling green and gardens. Close to Benalla Hospital and Lake Benalla. Regional wine country lifestyle.', '42 Bridge Street', 'Benalla', 'VIC', '3672', 'Independent Living, Aged Care', 210000, 350000, 90, 160, 68, 6, ARRAY['Bowling Green', 'Lake Views', 'Community Centre', 'Wine Country', 'Aged Care'], '1800 52 72 72', 'benalla@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Castlemaine', 'Tricare', 'Central highlands retirement village in heritage goldfields town. Character villas with arts culture. Community centre, gardens and gallery district. Walk to historic shops, cafes and medical facilities. Artistic heritage living.', '88 Barker Street', 'Castlemaine', 'VIC', '3450', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 64, 5, ARRAY['Heritage Setting', 'Arts Culture', 'Community Centre', 'Gardens', 'Aged Care'], '03 5472 3100', 'castlemaine@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Stawell', 'Mayflower', 'Grampians region retirement village. Comfortable villas with mountain views. Community centre, bowling green and gardens. Close to Stawell town centre and Grampians National Park. Regional country living.', '88 Main Street', 'Stawell', 'VIC', '3380', 'Independent Living', 200000, 340000, 90, 160, 62, 6, ARRAY['Bowling Green', 'Mountain Views', 'Community Centre', 'Gardens'], '03 5358 1234', 'stawell@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care Bacchus Marsh', 'RSL Care', 'Western regional retirement village between Melbourne and Ballarat. Villas with veterans services. Bowling green, community centre and gardens. Close to Bacchus Marsh Avenue of Honour and shopping. Regional accessibility.', '42 Main Street', 'Bacchus Marsh', 'VIC', '3340', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 86, 7, ARRAY['Bowling Green', 'RSL Services', 'Community Centre', 'Gardens', 'Aged Care'], '03 5367 3100', 'bacchusmarsh@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('Mercy Health Kyneton', 'Mercy Health', 'Macedon Ranges retirement village in historic Kyneton. Catholic heritage with chapel and pastoral care. Villas with cool climate gardens. Close to Kyneton Hospital and Piper Street shopping. Heritage town living.', '88 Piper Street', 'Kyneton', 'VIC', '3444', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 72, 6, ARRAY['Chapel', 'Cool Climate', 'Gardens', 'Heritage Town', 'Aged Care'], '03 5422 3100', 'kyneton@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Active'),

('Benetas Maryborough', 'Benetas', 'Central Victorian goldfields retirement community. Affordable villas in heritage town. Community centre, bowling green and gardens. Close to Maryborough Hospital and historic railway station. Goldfields heritage.', '88 Nolan Street', 'Maryborough', 'VIC', '3465', 'Independent Living, Aged Care', 190000, 330000, 85, 155, 76, 7, ARRAY['Bowling Green', 'Heritage Setting', 'Community Centre', 'Gardens', 'Aged Care'], '03 5460 3100', 'maryborough@benetas.com.au', 'https://www.benetas.com.au', 'Active'),

('Embracia Yarrawonga', 'Embracia Health', 'Murray River retirement village with water views. Modern villas near Lake Mulwala. Pool, community facilities and river access. Perfect fishing, boating and golf. Popular holiday and retirement destination.', '88 Irvine Parade', 'Yarrawonga', 'VIC', '3730', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 94, 8, ARRAY['Pool', 'Lake Views', 'River Access', 'Golf Course', 'Aged Care'], '03 5744 3100', 'yarrawonga@embracia.com.au', 'https://www.embracia.com.au', 'Active'),

('Warrigal Care Kyabram', 'Warrigal Care', 'Goulburn Valley retirement village in regional Kyabram. Comfortable villas with community facilities and aged care. Bowling green and gardens. Close to Kyabram town centre and medical facilities. Regional farming community.', '88 Allan Street', 'Kyabram', 'VIC', '3620', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 68, 6, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Regional Setting', 'Aged Care'], '03 5852 3100', 'kyabram@warrigal.com.au', 'https://www.warrigal.com.au', 'Active'),

('Peninsula Villages Daylesford', 'Peninsula Villages', 'Spa country retirement village in artistic Daylesford. Character villas near mineral springs. Community centre, gardens and spa atmosphere. Walk to galleries, cafes and Lake Daylesford. Weekend getaway destination.', '1 Vincent Street', 'Daylesford', 'VIC', '3460', 'Independent Living', 300000, 460000, 130, 210, 56, 4, ARRAY['Spa Country', 'Gardens', 'Lake Views', 'Arts Culture', 'Community Centre'], '03 5348 3100', 'daylesford@peninsulavillages.com.au', 'https://www.peninsulavillages.com.au', 'Active'),

('Resthaven Ararat', 'Resthaven', 'Western districts retirement village in historic Ararat. Comfortable villas with mountain views. Community centre, bowling green and gardens. Close to Ararat Hospital and Grampians peaks. Regional heritage living.', '88 Barkly Street', 'Ararat', 'VIC', '3377', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 74, 7, ARRAY['Bowling Green', 'Mountain Views', 'Community Centre', 'Gardens', 'Aged Care'], '03 5352 1234', 'ararat@resthaven.asn.au', 'https://www.resthaven.asn.au', 'Active');
