-- VIC Batch 04: 25 Northern Melbourne & Growth Corridor Retirement Villages
-- Geographic Focus: Whittlesea, Craigieburn, Epping, Greensborough, Diamond Creek
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Stockland Highlands Craigieburn', 'Stockland', 'Northern growth corridor retirement resort. Contemporary villas with resort amenities. Pool, gym, cinema, bowling green and community hub. Close to Highlands shopping and medical facilities. Modern growth area.', '1 Highlands Boulevard', 'Craigieburn', 'VIC', '3064', 'Independent Living', 340000, 520000, 150, 230, 196, 16, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Community Centre', 'Gardens'], '1800 550 550', 'craigieburn@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Aveo Epping North', 'Aveo Group', 'Northern suburbs retirement community near Pacific Epping. Modern villas with pool and community facilities. Walk to shopping centre, medical facilities and train station. Convenient northern location.', '88 Cooper Street', 'Epping', 'VIC', '3076', 'Independent Living', 380000, 560000, 160, 250, 142, 12, ARRAY['Pool', 'Community Centre', 'Gardens', 'Shopping Access', 'Station Access'], '1300 283 000', 'eppingnorth@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Lendlease Doreen', 'Lendlease', 'Northern growth area retirement village. Quality villas in family-friendly location. Pool, bowling green and community facilities. Close to Laurimar Town Centre and future train station. Growing community.', '42 Bridge Inn Road', 'Doreen', 'VIC', '3754', 'Independent Living', 360000, 540000, 150, 240, 126, 11, ARRAY['Pool', 'Bowling Green', 'Community Centre', 'Gardens', 'Growth Area'], '1300 326 033', 'doreen@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Reservoir', 'Anglicare', 'Northern suburbs retirement community near Reservoir station. Independent villas with chapel and community facilities. Close to Northland shopping, medical facilities and public transport. Established northern suburbs.', '42 Spring Street', 'Reservoir', 'VIC', '3073', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 104, 9, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Station Access', 'Aged Care'], '03 9462 3100', 'reservoir@anglicare.vic.org.au', 'https://www.anglicarevic.org.au', 'Active'),

('Baptistcare Greensborough', 'BaptistCare', 'North-eastern suburbs retirement village. Comfortable villas with chapel and bowling green. Community centre and gardens. Close to Greensborough Plaza, medical facilities and train station. Leafy northern suburb.', '88 Grimshaw Street', 'Greensborough', 'VIC', '3088', 'Independent Living, Aged Care', 400000, 600000, 170, 260, 96, 7, ARRAY['Chapel', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '03 9435 3100', 'greensborough@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Uniting AgeWell Mill Park', 'Uniting AgeWell', 'Northern suburbs retirement community. Modern villas with community facilities. Pool, community centre and gardens. Close to Westfield Plenty Valley shopping and medical facilities. Family-friendly location.', '42 Childs Road', 'Mill Park', 'VIC', '3082', 'Independent Living', 360000, 540000, 150, 240, 132, 11, ARRAY['Pool', 'Community Centre', 'Gardens', 'Shopping Access'], '1300 783 435', 'millpark@unitingagewell.org', 'https://www.unitingagewell.org', 'Active'),

('Opal Aged Care Whittlesea', 'Opal Aged Care', 'Northern growth corridor retirement village. Contemporary villas near Whittlesea township. Pool, community facilities and gardens. Close to medical facilities and shopping. Regional atmosphere with city access.', '88 Church Street', 'Whittlesea', 'VIC', '3757', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 94, 8, ARRAY['Pool', 'Community Centre', 'Gardens', 'Regional Atmosphere', 'Aged Care'], '1300 672 524', 'whittlesea@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Eltham', 'IRT Group', 'North-eastern suburbs retirement community in green wedge. Villas surrounded by bushland and art galleries. Community centre, gardens and artistic atmosphere. Walk to Eltham village, shops and train station.', '88 Main Road', 'Eltham', 'VIC', '3095', 'Independent Living, Aged Care', 420000, 620000, 170, 260, 88, 6, ARRAY['Bushland Setting', 'Community Centre', 'Gardens', 'Arts Culture', 'Aged Care'], '1300 157 677', 'eltham@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Regis Aged Care Preston', 'Regis Aged Care', 'Inner northern suburbs retirement community. Quality villas near Preston Market and High Street. Community facilities and aged care. Walk to trams, shops and medical facilities. Multicultural inner-north living.', '42 Tyler Street', 'Preston', 'VIC', '3072', 'Independent Living, Aged Care', 400000, 600000, 170, 260, 92, 7, ARRAY['Community Centre', 'Gardens', 'Tram Access', 'Market Access', 'Aged Care'], '03 9470 3100', 'preston@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Thomastown', 'Respect', 'Northern suburbs retirement community near Thomastown station. Affordable villas with multicultural community. Pool, community centre and gardens. Close to shopping and medical facilities. Diverse northern community.', '88 High Street', 'Thomastown', 'VIC', '3074', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 116, 10, ARRAY['Pool', 'Community Centre', 'Gardens', 'Cultural Diversity', 'Aged Care'], '03 9465 3100', 'thomastown@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Arcare Wallan', 'Arcare', 'Northern regional retirement village. Modern villas in growing township. Community centre, pool and gardens. Close to Wallan Plaza and medical facilities. Country atmosphere with Melbourne access.', '1 High Street', 'Wallan', 'VIC', '3756', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 108, 10, ARRAY['Pool', 'Community Centre', 'Gardens', 'Regional Setting', 'Aged Care'], '1300 272 273', 'wallan@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Bupa Aged Care Diamond Creek', 'Bupa', 'North-eastern suburbs retirement village in green wedge. Comfortable villas near Diamond Creek and Eltham. Community facilities, gardens and bushland setting. Walk to shops and train station. Leafy valley location.', '42 Main Hurstbridge Road', 'Diamond Creek', 'VIC', '3089', 'Independent Living, Aged Care', 400000, 600000, 170, 260, 84, 6, ARRAY['Bushland Setting', 'Community Centre', 'Gardens', 'Station Access', 'Aged Care'], '1300 280 334', 'diamondcreek@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Wollert', 'Allity', 'Northern growth corridor retirement community. Contemporary villas in new development area. Pool, community centre and gardens. Close to Epping Plaza and medical facilities. New growth area living.', '1 Harvest Home Road', 'Wollert', 'VIC', '3750', 'Independent Living', 320000, 480000, 140, 220, 138, 13, ARRAY['Pool', 'Community Centre', 'Gardens', 'New Development'], '03 9404 3100', 'wollert@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Macleod', 'Bolton Clarke', 'Northern suburbs retirement community near Macleod station. Quality villas with community facilities and aged care. Close to Macleod village, medical facilities and transport. Established northern location.', '88 Aberdeen Road', 'Macleod', 'VIC', '3085', 'Independent Living, Aged Care', 400000, 600000, 170, 260, 96, 7, ARRAY['Community Centre', 'Gardens', 'Station Access', 'Shopping Access', 'Aged Care'], '1300 228 655', 'macleod@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Estia Health Broadmeadows', 'Estia Health', 'Northern suburbs multicultural retirement community. Modern villas near Broadmeadows station and shopping. Pool, community facilities and cultural programs. Diverse community atmosphere with excellent transport.', '42 Pascoe Vale Road', 'Broadmeadows', 'VIC', '3047', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 124, 11, ARRAY['Pool', 'Community Centre', 'Cultural Centre', 'Station Access', 'Aged Care'], '03 9302 3100', 'broadmeadows@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Ivanhoe', 'Japara', 'Inner northern suburbs retirement community. Heritage-style villas in prestigious Ivanhoe. Community facilities, gardens and aged care. Walk to Upper Heidelberg Road shops, cafes and train station. Premium northern suburb.', '88 Upper Heidelberg Road', 'Ivanhoe', 'VIC', '3079', 'Independent Living, Aged Care', 520000, 740000, 200, 300, 78, 4, ARRAY['Heritage Style', 'Gardens', 'Community Centre', 'Station Access', 'Aged Care'], '1800 52 72 72', 'ivanhoe@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Sunbury', 'Tricare', 'North-western regional retirement village. Comfortable villas in historic Sunbury township. Community centre, bowling green and gardens. Close to Sunbury Square shopping and Hume Highway. Regional living with city access.', '88 Evans Street', 'Sunbury', 'VIC', '3429', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 102, 9, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Historic Town', 'Aged Care'], '03 9744 3100', 'sunbury@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Northcote', 'Mayflower', 'Inner northern suburbs retirement community near High Street. Contemporary apartments with urban village atmosphere. Community facilities and gardens. Walk to trams, shops, cafes and medical facilities. Vibrant inner-north living.', '88 High Street', 'Northcote', 'VIC', '3070', 'Independent Living', 480000, 680000, 190, 280, 72, 5, ARRAY['Urban Village', 'Community Centre', 'Gardens', 'Tram Access'], '03 9482 1234', 'northcote@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care Rosanna', 'RSL Care', 'North-eastern suburbs retirement village with veterans services. Comfortable villas near Rosanna station and golf course. Bowling green, community facilities and RSL services. Easy access to La Trobe University.', '42 Lower Plenty Road', 'Rosanna', 'VIC', '3084', 'Independent Living, Aged Care', 420000, 620000, 170, 260, 86, 6, ARRAY['Bowling Green', 'RSL Services', 'Community Centre', 'Station Access', 'Aged Care'], '03 9457 3100', 'rosanna@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('Mercy Health Glenroy', 'Mercy Health', 'Northern suburbs retirement community with Catholic heritage. Modern villas with chapel and pastoral care. Pool, community facilities and gardens. Close to Glenroy station and Pascoe Vale Road shopping.', '88 Glenroy Road', 'Glenroy', 'VIC', '3046', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 104, 8, ARRAY['Chapel', 'Pool', 'Community Centre', 'Gardens', 'Aged Care'], '03 9306 3100', 'glenroy@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Active'),

('Benetas Brunswick', 'Benetas', 'Inner northern suburbs multicultural retirement community. Contemporary villas near Sydney Road. Cultural programs, community centre and gardens. Walk to trams, restaurants and shops. Diverse urban community.', '42 Sydney Road', 'Brunswick', 'VIC', '3056', 'Independent Living, Aged Care', 420000, 620000, 170, 260, 88, 6, ARRAY['Cultural Centre', 'Community Centre', 'Gardens', 'Tram Access', 'Aged Care'], '03 9388 3100', 'brunswick@benetas.com.au', 'https://www.benetas.com.au', 'Active'),

('Embracia Kinglake', 'Embracia Health', 'Ranges retirement village with mountain views. Peaceful villas in bushland setting. Community centre, gardens and walking trails. Close to Kinglake township and Yarra Valley. Cool climate mountain living.', '42 Whittlesea-Kinglake Road', 'Kinglake', 'VIC', '3763', 'Independent Living', 240000, 380000, 105, 175, 52, 4, ARRAY['Mountain Views', 'Bushland Setting', 'Walking Trails', 'Community Centre'], '03 5786 1234', 'kinglake@embracia.com.au', 'https://www.embracia.com.au', 'Active'),

('Warrigal Care Lalor', 'Warrigal Care', 'Northern suburbs retirement community near Epping. Modern villas with community facilities and aged care. Pool, gardens and activity programs. Close to Pacific Epping shopping and medical facilities.', '88 May Road', 'Lalor', 'VIC', '3075', 'Independent Living, Aged Care', 340000, 510000, 150, 230, 112, 10, ARRAY['Pool', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '03 9465 4100', 'lalor@warrigal.com.au', 'https://www.warrigal.com.au', 'Active'),

('Peninsula Villages Hurstbridge', 'Peninsula Villages', 'Yarra Valley retirement community in green wedge. Contemporary villas surrounded by nature. Community centre, gardens and bushland walks. Close to Hurstbridge village, wineries and galleries. Valley lifestyle.', '1 Main Road', 'Hurstbridge', 'VIC', '3099', 'Independent Living', 360000, 540000, 150, 240, 68, 5, ARRAY['Bushland Setting', 'Gardens', 'Community Centre', 'Valley Views'], '03 9718 3100', 'hurstbridge@peninsulavillages.com.au', 'https://www.peninsulavillages.com.au', 'Active'),

('Resthaven Kilmore', 'Resthaven', 'Northern regional retirement village in historic Kilmore. Comfortable villas with country atmosphere. Community centre, bowling green and gardens. Close to Kilmore town centre and medical facilities. Regional living.', '88 Sydney Street', 'Kilmore', 'VIC', '3764', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 74, 7, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Historic Town', 'Aged Care'], '03 5782 1234', 'kilmore@resthaven.asn.au', 'https://www.resthaven.asn.au', 'Active');
