-- VIC Batch 02: 25 Western Suburbs, Geelong & Bellarine Peninsula Retirement Villages
-- Geographic Focus: Geelong, Werribee, Melton, Bellarine Peninsula, Surf Coast
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Stockland Peninsula Waves', 'Stockland', 'Premium Bellarine Peninsula retirement resort near beaches. Contemporary villas with bay views. Pool, gym, cinema, bowling green and community hub. Minutes to Portarlington and Ocean Grove beaches.', '1 Peninsula Drive', 'Portarlington', 'VIC', '3223', 'Independent Living', 380000, 580000, 160, 250, 186, 14, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Bay Views', 'Community Centre'], '1800 550 550', 'portarlington@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Aveo Sanctuary Lakes', 'Aveo Group', 'Western suburbs waterfront retirement community. Modern apartments overlooking lakes and golf course. Pool, gym, cinema and community facilities. Close to Point Cook shopping and coastal trail.', '88 Sanctuary Boulevard', 'Point Cook', 'VIC', '3030', 'Independent Living', 420000, 620000, 170, 260, 142, 10, ARRAY['Pool', 'Gym', 'Cinema', 'Lake Views', 'Golf Course', 'Community Centre'], '1300 283 000', 'sanctuarylakes@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Lendlease Geelong', 'Lendlease', 'Coastal city retirement living in regional Geelong. Quality apartments with bay glimpses. Pool, gym, bowling green and community facilities. Walk to waterfront, restaurants and shopping. Regional affordability.', '88 Moorabool Street', 'Geelong', 'VIC', '3220', 'Independent Living', 380000, 560000, 160, 250, 124, 9, ARRAY['Pool', 'Gym', 'Bowling Green', 'Bay Glimpses', 'Community Centre'], '1300 326 033', 'geelong@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare The Vines', 'Anglicare', 'Western suburbs retirement village in Hoppers Crossing. Independent villas with chapel and community facilities. Bowling green and gardens. Close to Pacific Werribee shopping and medical facilities.', '42 Heaths Road', 'Hoppers Crossing', 'VIC', '3029', 'Independent Living, Aged Care', 320000, 480000, 140, 220, 118, 11, ARRAY['Chapel', 'Bowling Green', 'Community Centre', 'Gardens', 'Aged Care'], '03 9749 3100', 'hopperscrossing@anglicare.vic.org.au', 'https://www.anglicarevic.org.au', 'Active'),

('Baptistcare Ocean Grove', 'BaptistCare', 'Bellarine Peninsula coastal retirement village. Modern villas near Ocean Grove beaches. Chapel, pool, bowling green and community centre. Walk to shops, cafes and surf beaches. Coastal lifestyle living.', '88 The Terrace', 'Ocean Grove', 'VIC', '3226', 'Independent Living', 380000, 580000, 160, 250, 94, 7, ARRAY['Pool', 'Chapel', 'Bowling Green', 'Beach Access', 'Community Centre'], '03 5255 3100', 'oceangrove@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Uniting AgeWell Wyndham Vale', 'Uniting AgeWell', 'Western growth corridor retirement community. Contemporary villas with resort amenities. Pool, gym, community centre and gardens. Close to Wyndham Village shopping and Manor Lakes. Affordable growth area.', '1 Lakeview Drive', 'Wyndham Vale', 'VIC', '3024', 'Independent Living', 340000, 520000, 150, 230, 156, 13, ARRAY['Pool', 'Gym', 'Community Centre', 'Gardens', 'Lake Views'], '1300 783 435', 'wyndhamvale@unitingagewell.org', 'https://www.unitingagewell.org', 'Active'),

('Opal Aged Care Torquay', 'Opal Aged Care', 'Surf Coast retirement village near world-famous beaches. Modern villas with ocean breeze. Pool, community facilities and coastal walks. Walk to Torquay village and Bells Beach. Ultimate surf coast lifestyle.', '42 Surf Coast Highway', 'Torquay', 'VIC', '3228', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 86, 6, ARRAY['Pool', 'Ocean Breeze', 'Coastal Walks', 'Community Centre', 'Aged Care'], '1300 672 524', 'torquay@opalaged.care', 'https://www.opalagedcare.com.au', 'Active'),

('IRT Geelong West', 'IRT Group', 'Regional Geelong retirement community near Pakington Street. Comfortable villas with community facilities and aged care. Walk to cafes, shops and medical facilities. Established neighbourhood community.', '88 Pakington Street', 'Geelong West', 'VIC', '3218', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 92, 8, ARRAY['Community Centre', 'Gardens', 'Bowling Green', 'Aged Care'], '1300 157 677', 'geelongwest@irt.org.au', 'https://www.irt.org.au', 'Active'),

('Regis Aged Care Barwon Heads', 'Regis Aged Care', 'Bellarine Peninsula coastal village retirement. Premium villas near Barwon River mouth and beaches. Pool, bowling green and community facilities. Perfect fishing, boating and coastal lifestyle. Pristine location.', '88 Hitchcock Avenue', 'Barwon Heads', 'VIC', '3227', 'Independent Living, Aged Care', 420000, 640000, 170, 260, 78, 5, ARRAY['Pool', 'Bowling Green', 'River Views', 'Beach Access', 'Aged Care'], '03 5254 3100', 'barwonheads@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Respect Aged Care Melton', 'Respect', 'Western growth corridor retirement village. Affordable villas with community centre and bowling green. Close to Woodgrove shopping centre and Melton Hospital. Family-friendly regional atmosphere.', '42 High Street', 'Melton', 'VIC', '3337', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 124, 12, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '03 9747 3100', 'melton@respect.com.au', 'https://www.respect.com.au', 'Active'),

('Arcare Sanctuary Point', 'Arcare', 'Point Cook waterfront retirement community. Contemporary apartments with lake and coastal views. Pool, gym, community facilities and walking trails. Minutes to Sanctuary Lakes shopping and beaches.', '1 Point Cook Road', 'Point Cook', 'VIC', '3030', 'Independent Living, Aged Care', 400000, 600000, 170, 260, 108, 9, ARRAY['Pool', 'Gym', 'Lake Views', 'Walking Trails', 'Aged Care'], '1300 272 273', 'pointcook@arcare.com.au', 'https://www.arcare.com.au', 'Active'),

('Bupa Aged Care Queenscliff', 'Bupa', 'Historic Bellarine Peninsula coastal village retirement. Heritage-style villas near iconic Queenscliff beaches and ferry. Community centre, gardens and maritime atmosphere. Walk to cafes, galleries and waterfront.', '88 Hesse Street', 'Queenscliff', 'VIC', '3225', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 64, 4, ARRAY['Heritage Style', 'Maritime Setting', 'Beach Access', 'Community Centre', 'Aged Care'], '1300 280 334', 'queenscliff@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Lara', 'Allity', 'Northern Geelong retirement community. Modern villas near Waurn Ponds shopping and Deakin University. Community centre, pool and gardens. Affordable regional living with excellent facilities.', '88 Corio-Lara Road', 'Lara', 'VIC', '3212', 'Independent Living, Aged Care', 280000, 430000, 120, 195, 102, 10, ARRAY['Pool', 'Community Centre', 'Gardens', 'University Access', 'Aged Care'], '03 5282 3100', 'lara@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Bolton Clarke Newcomb', 'Bolton Clarke', 'Geelong bayside retirement village near beaches. Comfortable villas with bay breezes. Community centre, bowling green and gardens. Walk to Newcomb Central shopping and medical facilities. Bay lifestyle.', '42 Bellarine Highway', 'Newcomb', 'VIC', '3219', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 96, 8, ARRAY['Bowling Green', 'Bay Breeze', 'Community Centre', 'Gardens', 'Aged Care'], '1300 228 655', 'newcomb@boltonclarke.com.au', 'https://www.boltonclarke.com.au', 'Active'),

('Estia Health Altona Meadows', 'Estia Health', 'Western suburbs retirement community near beaches. Modern villas with coastal access. Pool, community facilities and gardens. Close to Point Cook Coastal Park and shopping. Affordable coastal living.', '88 Central Avenue', 'Altona Meadows', 'VIC', '3028', 'Independent Living, Aged Care', 340000, 510000, 150, 230, 114, 11, ARRAY['Pool', 'Coastal Access', 'Community Centre', 'Gardens', 'Aged Care'], '03 9395 3100', 'altonameadows@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Geelong East', 'Japara', 'Eastern Geelong retirement community near hospital precinct. Quality villas with community facilities and aged care. Close to University Hospital Geelong and Waurn Ponds shopping. Medical precinct convenience.', '88 Ryrie Street', 'Geelong East', 'VIC', '3219', 'Independent Living, Aged Care', 320000, 480000, 140, 220, 88, 7, ARRAY['Community Centre', 'Gardens', 'Hospital Access', 'Bowling Green', 'Aged Care'], '1800 52 72 72', 'geelongeast@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Anglesea', 'Tricare', 'Surf Coast retirement village near pristine beaches. Coastal villas with ocean views. Pool, community centre and coastal walks. Walk to Anglesea village, golf club and surf beaches. Great Ocean Road lifestyle.', '42 Great Ocean Road', 'Anglesea', 'VIC', '3230', 'Independent Living', 380000, 580000, 160, 250, 72, 5, ARRAY['Pool', 'Ocean Views', 'Beach Access', 'Coastal Walks', 'Community Centre'], '03 5263 3100', 'anglesea@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Drysdale', 'Mayflower', 'Bellarine Peninsula rural village retirement. Peaceful villas with country atmosphere. Community centre, gardens and bowling green. Close to Drysdale village shops and Portarlington beaches. Quiet peninsula living.', '88 Jetty Road', 'Drysdale', 'VIC', '3222', 'Independent Living', 300000, 460000, 130, 210, 84, 7, ARRAY['Bowling Green', 'Gardens', 'Community Centre', 'Country Setting'], '03 5251 1234', 'drysdale@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care Geelong', 'RSL Care', 'Regional Geelong retirement village with veterans services. Comfortable villas near Geelong RSL. Bowling green, community facilities and aged care. Close to waterfront, shopping and medical facilities.', '42 Moorabool Street', 'Geelong', 'VIC', '3220', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 106, 9, ARRAY['Bowling Green', 'RSL Services', 'Community Centre', 'Gardens', 'Aged Care'], '03 5222 3100', 'geelong@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('Mercy Health Werribee Mercy', 'Mercy Health', 'Western suburbs retirement community adjacent to Werribee Mercy Hospital. Catholic heritage with chapel and pastoral care. Modern villas with excellent healthcare access. Gardens and community facilities.', '1 Healy Road', 'Werribee', 'VIC', '3030', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 116, 10, ARRAY['Chapel', 'Hospital Adjacent', 'Community Centre', 'Gardens', 'Aged Care'], '03 9742 4100', 'werribeemercy@mercyhealth.com.au', 'https://www.mercyhealth.com.au', 'Active'),

('Benetas Leopold', 'Benetas', 'Geelong southern suburbs retirement village. Modern villas near Bellarine Highway. Community centre, pool and gardens. Close to Leopold shopping and Geelong Ring Road. Convenient regional location.', '88 Bellarine Highway', 'Leopold', 'VIC', '3224', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 94, 8, ARRAY['Pool', 'Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '03 5250 3100', 'leopold@benetas.com.au', 'https://www.benetas.com.au', 'Active'),

('Embracia Tarneit', 'Embracia Health', 'Western growth corridor retirement community. Contemporary villas with modern amenities. Pool, gym, community centre and gardens. Close to Tarneit Central shopping and medical facilities. New growth area living.', '1 Tarneit Road', 'Tarneit', 'VIC', '3029', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 138, 12, ARRAY['Pool', 'Gym', 'Community Centre', 'Gardens', 'Aged Care'], '03 9748 3100', 'tarneit@embracia.com.au', 'https://www.embracia.com.au', 'Active'),

('Warrigal Care Clifton Springs', 'Warrigal Care', 'Bellarine Peninsula waterfront retirement village. Modern villas with bay views. Pool, community facilities and waterfront access. Walk to Clifton Springs jetty and beaches. Peaceful bay lifestyle.', '88 Jetty Road', 'Clifton Springs', 'VIC', '3222', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 86, 7, ARRAY['Pool', 'Bay Views', 'Waterfront Access', 'Community Centre', 'Aged Care'], '03 5251 4100', 'cliftonsprings@warrigal.com.au', 'https://www.warrigal.com.au', 'Active'),

('Peninsula Villages Bellarine', 'Peninsula Villages', 'Premium Bellarine Peninsula retirement resort. Contemporary villas with bay and golf course views. Pool, gym, bowling green, cinema and clubhouse. Minutes to Ocean Grove beaches and village. Resort lifestyle.', '1 Golf Links Road', 'Barwon Heads', 'VIC', '3227', 'Independent Living', 420000, 640000, 170, 260, 148, 11, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Golf Course', 'Bay Views'], '03 5254 4100', 'bellarine@peninsulavillages.com.au', 'https://www.peninsulavillages.com.au', 'Active'),

('Resthaven Avalon', 'Resthaven', 'Bellarine Peninsula coastal village retirement. Comfortable villas near Avalon Airport and beaches. Community centre, gardens and bowling green. Close to Point Wilson and coastal parks. Peaceful peninsula location.', '88 Beach Road', 'Avalon', 'VIC', '3212', 'Independent Living', 280000, 430000, 120, 195, 76, 6, ARRAY['Bowling Green', 'Gardens', 'Beach Access', 'Community Centre'], '03 5275 1234', 'avalon@resthaven.asn.au', 'https://www.resthaven.asn.au', 'Active');
