-- WA Batch 01: 25 Perth Metro & Coastal Retirement Villages
-- Geographic Focus: Perth, Fremantle, Joondalup, Rockingham, Swan Valley
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Aveo Wembley', 'Aveo Group', 'Inner Perth retirement community near city. Contemporary apartments with modern amenities. Pool, gym and community facilities. Walk to Wembley village, City Beach road and transport. Urban Perth living.', '88 Cambridge Street', 'Wembley', 'WA', '6014', 'Independent Living', 420000, 640000, 170, 260, 118, 9, ARRAY['Pool', 'Gym', 'Community Centre', 'Urban Location'], '1300 283 000', 'wembley@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Stockland The Pines Mandurah', 'Stockland', 'Peel region coastal retirement resort. Contemporary villas with waterfront and resort amenities. Pool, gym, cinema, bowling green and community hub. Minutes to Mandurah Ocean Marina and shopping.', '1 Pinjarra Road', 'Mandurah', 'WA', '6210', 'Independent Living', 360000, 540000, 150, 240, 196, 16, ARRAY['Pool', 'Gym', 'Cinema', 'Bowling Green', 'Waterfront', 'Community Centre'], '1800 550 550', 'mandurah@stockland.com.au', 'https://www.stockland.com.au/retirement', 'Active'),

('Lendlease Joondalup', 'Lendlease', 'Northern suburbs retirement community near city centre. Quality villas with modern amenities. Pool, bowling green and community facilities. Walk to Joondalup Health Campus, Lakeside shopping and train.', '42 Grand Boulevard', 'Joondalup', 'WA', '6027', 'Independent Living', 400000, 600000, 170, 260, 132, 11, ARRAY['Pool', 'Bowling Green', 'Shopping Access', 'Hospital Access', 'Community Centre'], '1300 326 033', 'joondalup@lendlease.com', 'https://www.lendlease.com/au/retirement', 'Active'),

('Anglicare Waikiki', 'Anglicare', 'Southern suburbs beachside retirement. Independent villas with chapel and community facilities. Near beautiful Waikiki Beach. Close to Rockingham shopping and medical facilities. Coastal lifestyle living.', '88 Willmott Drive', 'Waikiki', 'WA', '6169', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 102, 9, ARRAY['Chapel', 'Beach Access', 'Community Centre', 'Gardens', 'Aged Care'], '08 9527 3100', 'waikiki@anglicarewa.org.au', 'https://www.anglicarewa.org.au', 'Active'),

('Baptistcare Gracehaven', 'BaptistCare', 'Southern suburbs retirement village in Rockingham. Modern villas with chapel and bowling green. Pool, community centre and gardens. Close to shopping centres and medical facilities. Coastal region living.', '88 Dixon Road', 'Rockingham', 'WA', '6168', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 114, 10, ARRAY['Pool', 'Chapel', 'Bowling Green', 'Community Centre', 'Aged Care'], '08 9528 3100', 'gracehaven@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('MercyCare Wembley', 'MercyCare', 'Inner Perth retirement community. Catholic heritage with chapel and pastoral care. Contemporary apartments with community facilities. Walk to Cambridge Street shops, cafes and medical facilities.', '88 Harborne Street', 'Wembley', 'WA', '6014', 'Independent Living, Aged Care', 420000, 620000, 170, 260, 96, 7, ARRAY['Chapel', 'Community Centre', 'Gardens', 'Urban Location', 'Aged Care'], '08 9442 3100', 'wembley@mercycare.com.au', 'https://www.mercycare.com.au', 'Active'),

('Regis Aged Care Nedlands', 'Regis Aged Care', 'Western suburbs retirement near Swan River. Quality villas in prestigious Nedlands. Community facilities, gardens and aged care. Close to University of Western Australia, Hollywood Hospital and shopping.', '88 Stirling Highway', 'Nedlands', 'WA', '6009', 'Independent Living, Aged Care', 520000, 760000, 200, 300, 88, 6, ARRAY['River Views', 'University Access', 'Community Centre', 'Gardens', 'Aged Care'], '08 9386 3100', 'nedlands@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Bupa Aged Care Morley', 'Bupa', 'Eastern suburbs retirement near Morley Galleria. Modern villas with pool and community facilities. Walk to major shopping centre, medical facilities and Tonkin Highway. Convenient eastern location.', '42 Crimea Street', 'Morley', 'WA', '6062', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 112, 10, ARRAY['Pool', 'Shopping Access', 'Community Centre', 'Gardens', 'Aged Care'], '1300 280 334', 'morley@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('Allity Inglewood', 'Allity', 'Inner eastern Perth retirement community. Contemporary villas near Mount Lawley. Community facilities, gardens and urban amenities. Close to Inglewood shopping, cafes and medical facilities. Inner-city convenience.', '88 Beaufort Street', 'Inglewood', 'WA', '6052', 'Independent Living', 420000, 620000, 170, 260, 84, 7, ARRAY['Urban Location', 'Shopping Access', 'Community Centre', 'Gardens'], '08 9371 3100', 'inglewood@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Estia Health Balcatta', 'Estia Health', 'Northern suburbs retirement community. Modern villas near Westfield Innaloo. Pool, community facilities and gardens. Close to major shopping, medical facilities and transport. Northern Perth convenience.', '88 Erindale Road', 'Balcatta', 'WA', '6021', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 104, 9, ARRAY['Pool', 'Shopping Access', 'Community Centre', 'Gardens', 'Aged Care'], '08 9344 3100', 'balcatta@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Japara Cottesloe', 'Japara', 'Premium western suburbs beachside retirement. Luxury villas near iconic Cottesloe Beach. Pool, community facilities and ocean proximity. Walk to beach, cafes and prestigious village. Elite beachside address.', '42 Eric Street', 'Cottesloe', 'WA', '6011', 'Independent Living, Aged Care', 680000, 980000, 260, 380, 68, 3, ARRAY['Pool', 'Beach Access', 'Ocean Proximity', 'Village Atmosphere', 'Aged Care'], '1800 52 72 72', 'cottesloe@japara.com.au', 'https://www.japara.com.au', 'Active'),

('Tricare Midland', 'Tricare', 'Eastern suburbs retirement near Swan Valley. Comfortable villas with valley proximity. Community facilities, bowling green and gardens. Close to Midland Gate shopping, hospital and heritage precinct.', '88 Great Eastern Highway', 'Midland', 'WA', '6056', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 116, 11, ARRAY['Bowling Green', 'Valley Proximity', 'Community Centre', 'Gardens', 'Aged Care'], '08 9274 3100', 'midland@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Scarborough', 'Mayflower', 'Coastal Perth beachside retirement. Contemporary apartments near Scarborough Beach. Pool, gym and ocean views. Walk to beach, esplanade and Scarborough Square shopping. Premium coastal lifestyle.', '88 The Esplanade', 'Scarborough', 'WA', '6019', 'Independent Living', 520000, 760000, 200, 300, 92, 6, ARRAY['Pool', 'Gym', 'Ocean Views', 'Beach Access', 'Shopping Access'], '08 9245 1234', 'scarborough@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('RSL Care Victoria Park', 'RSL Care', 'Inner southern Perth retirement with veterans services. Comfortable villas near Burswood. Bowling green, community facilities and RSL services. Close to Crown Perth, Optus Stadium and medical facilities.', '42 Albany Highway', 'Victoria Park', 'WA', '6100', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 98, 8, ARRAY['Bowling Green', 'RSL Services', 'Community Centre', 'Gardens', 'Aged Care'], '08 9362 3100', 'victoriapark@rslcare.org.au', 'https://www.rslcare.org.au', 'Active'),

('SwanCare Bentley Park', 'SwanCare', 'Southern suburbs retirement community. Modern villas with pool and community facilities. Close to Carousel shopping centre and Curtin University. Convenient southern Perth location.', '1 Bentley Park Drive', 'Bentley', 'WA', '6102', 'Independent Living, Aged Care', 360000, 540000, 150, 240, 124, 11, ARRAY['Pool', 'Shopping Access', 'University Access', 'Community Centre', 'Aged Care'], '08 9455 1234', 'bentleypark@swancare.org.au', 'https://www.swancare.com.au', 'Active'),

('Bethanie Gwelup', 'Bethanie', 'Northern suburbs retirement community. Quality villas with gardens and community facilities. Bowling green and aged care. Close to Karrinyup Shopping Centre and medical facilities. Leafy northern location.', '88 Gwelup Drive', 'Gwelup', 'WA', '6018', 'Independent Living, Aged Care', 380000, 580000, 160, 250, 104, 9, ARRAY['Bowling Green', 'Gardens', 'Shopping Access', 'Community Centre', 'Aged Care'], '08 9207 1234', 'gwelup@bethanie.com.au', 'https://www.bethanie.com.au', 'Active'),

('Juniper Merriwa', 'Juniper', 'Northern suburbs retirement village. Modern villas in growing Ridgewood area. Pool, community facilities and gardens. Close to shopping centres and medical facilities. Northern growth corridor.', '1 Merriwa Avenue', 'Ridgewood', 'WA', '6030', 'Independent Living', 340000, 520000, 150, 230, 118, 11, ARRAY['Pool', 'Community Centre', 'Gardens', 'Growth Corridor'], '08 9400 1234', 'merriwa@juniper.org.au', 'https://www.juniper.org.au', 'Active'),

('Southern Plus Carine', 'Southern Plus', 'Northern beaches retirement community. Comfortable villas near Carine shopping. Community facilities, bowling green and gardens. Close to shops, medical facilities and coastal access.', '88 Beach Road', 'Carine', 'WA', '6020', 'Independent Living', 360000, 540000, 150, 240, 96, 8, ARRAY['Bowling Green', 'Coastal Access', 'Community Centre', 'Gardens'], '08 9246 1234', 'carine@southernplus.org.au', 'https://www.southernplus.org.au', 'Active'),

('Amana Living Canning Vale', 'Amana Living', 'Southern suburbs retirement community. Modern villas near Livingston Marketplace. Pool, community facilities and gardens. Close to shopping, medical facilities and Roe Highway. Southern accessibility.', '88 Amherst Road', 'Canning Vale', 'WA', '6155', 'Independent Living, Aged Care', 340000, 520000, 150, 230, 124, 12, ARRAY['Pool', 'Shopping Access', 'Community Centre', 'Gardens', 'Aged Care'], '08 9314 1234', 'canningvale@amanaliving.com.au', 'https://www.amanaliving.com.au', 'Active'),

('Arcadia Waters Mandurah', 'Independent Operator', 'Peel region waterfront retirement resort. Premium villas with canal and ocean access. Boat berths, pool and community facilities. Walk to Mandurah Foreshore, restaurants and marina. Luxury waterfront lifestyle.', '1 Marina Drive', 'Mandurah', 'WA', '6210', 'Independent Living', 480000, 720000, 190, 280, 142, 10, ARRAY['Boat Berths', 'Pool', 'Canal Access', 'Ocean Access', 'Waterfront'], '08 9535 1234', 'info@arcadiawaters.com.au', 'https://www.arcadiawaters.com.au', 'Active'),

('Halls Head Retirement Village', 'Independent Operator', 'Mandurah beachside retirement community. Comfortable villas near pristine beaches. Pool, bowling green and community facilities. Walk to Halls Head Beach, shops and cafes. Coastal Peel lifestyle.', '88 Ormsby Terrace', 'Halls Head', 'WA', '6210', 'Independent Living', 320000, 480000, 140, 220, 104, 10, ARRAY['Pool', 'Bowling Green', 'Beach Access', 'Community Centre'], '08 9581 1234', 'info@hallshead.com.au', 'https://www.hallshead.com.au', 'Active'),

('Lifestyle Communities Ocean Reef', 'Lifestyle Communities', 'Northern beaches over-50s community. Modern manufactured homes with resort facilities. Pool, bowling green, gym and clubhouse. Close to Ocean Reef Marina and beaches. Affordable coastal living.', '1 Ocean Reef Road', 'Ocean Reef', 'WA', '6027', 'Independent Living', 240000, 400000, 90, 155, 186, 16, ARRAY['Pool', 'Bowling Green', 'Gym', 'Marina Access', 'Clubhouse'], '08 9307 9200', 'oceanreef@lifestylecommunities.com.au', 'https://www.lifestylecommunities.com.au', 'Active'),

('Seacrest Village Secret Harbour', 'Independent Operator', 'Southern Perth coastal retirement village. Modern villas near Secret Harbour beaches. Pool, community facilities and coastal walks. Walk to beach, marina and shopping. South coast lifestyle.', '88 Secret Harbour Boulevard', 'Secret Harbour', 'WA', '6173', 'Independent Living', 360000, 540000, 150, 240, 116, 11, ARRAY['Pool', 'Beach Access', 'Marina Access', 'Coastal Walks', 'Community Centre'], '08 9524 1234', 'info@seacrest.com.au', 'https://www.seacrest.com.au', 'Active'),

('Beachside Village Quinns Rocks', 'Independent Operator', 'Northern beaches retirement community. Contemporary villas near Quinns Beach. Pool, bowling green and coastal access. Walk to beach, shops and cafes. Northern coastal lifestyle.', '42 Tapping Way', 'Quinns Rocks', 'WA', '6030', 'Independent Living', 320000, 480000, 140, 220, 108, 10, ARRAY['Pool', 'Bowling Green', 'Beach Access', 'Community Centre'], '08 9305 1234', 'info@beachsidevillage.com.au', 'https://www.beachsidevillage.com.au', 'Active'),

('Swan Valley Retirement Estate', 'Independent Operator', 'Swan Valley wine country retirement. Peaceful villas surrounded by vineyards. Pool, community facilities and winery tours. Close to Swan Valley wineries, restaurants and Perth Airport. Valley lifestyle.', '1 West Swan Road', 'West Swan', 'WA', '6055', 'Independent Living', 340000, 520000, 150, 230, 92, 8, ARRAY['Pool', 'Wine Country', 'Vineyard Views', 'Community Centre'], '08 9274 9200', 'info@swanvalleyretirement.com.au', 'https://www.swanvalleyretirement.com.au', 'Active');
