-- WA Batch 02: 15 Regional WA Retirement Villages (FINAL WA BATCH)
-- Geographic Focus: Bunbury, Albany, Geraldton, Busselton, Margaret River Region
-- Import via Admin Dashboard

INSERT INTO villages_3bba8be8 (name, operator, description, address, suburb, state, postcode, care_type, entry_cost_min, entry_cost_max, weekly_fee_min, weekly_fee_max, total_units, available_units, amenities, contact_phone, contact_email, website, status) VALUES

('Aveo Bunbury', 'Aveo Group', 'South West regional city retirement. Modern villas near beaches and city centre. Pool, gym, bowling green and community facilities. Close to Bunbury Forum shopping and St John of God Hospital. Regional coastal living.', '88 Spencer Street', 'Bunbury', 'WA', '6230', 'Independent Living', 280000, 430000, 120, 195, 124, 11, ARRAY['Pool', 'Gym', 'Bowling Green', 'Beach Access', 'Community Centre'], '1300 283 000', 'bunbury@aveo.com.au', 'https://www.aveo.com.au', 'Active'),

('Bethanie Albany', 'Bethanie', 'Great Southern coastal city retirement. Quality villas near historic town and beaches. Pool, community facilities and bowling green. Close to Albany shopping, medical facilities and stunning coastline. Southern Ocean lifestyle.', '88 York Street', 'Albany', 'WA', '6330', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 102, 9, ARRAY['Pool', 'Bowling Green', 'Beach Access', 'Community Centre', 'Aged Care'], '08 9842 1234', 'albany@bethanie.com.au', 'https://www.bethanie.com.au', 'Active'),

('MercyCare Geraldton', 'MercyCare', 'Mid West coastal city retirement. Catholic heritage with chapel and pastoral care. Modern villas near beaches and marina. Close to Geraldton shopping, hospital and Batavia Coast. Coral Coast lifestyle.', '88 Shenton Street', 'Geraldton', 'WA', '6530', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 94, 8, ARRAY['Chapel', 'Beach Access', 'Marina Views', 'Community Centre', 'Aged Care'], '08 9921 1234', 'geraldton@mercycare.com.au', 'https://www.mercycare.com.au', 'Active'),

('Regis Aged Care Busselton', 'Regis Aged Care', 'South West coastal retirement near beautiful beaches. Quality villas with bay breezes. Pool, community facilities and coastal walks. Close to Busselton Jetty, shops and medical facilities. Margaret River region.', '88 Queen Street', 'Busselton', 'WA', '6280', 'Independent Living, Aged Care', 320000, 480000, 140, 220, 86, 7, ARRAY['Pool', 'Bay Breezes', 'Beach Access', 'Coastal Walks', 'Aged Care'], '08 9754 1234', 'busselton@regis.com.au', 'https://www.regis.com.au', 'Active'),

('Bupa Aged Care Kalgoorlie', 'Bupa', 'Goldfields mining city retirement. Comfortable villas in outback regional centre. Community facilities and gardens. Close to Kalgoorlie Hospital and Hannan Street shopping. Historic mining heritage.', '88 Hannan Street', 'Kalgoorlie', 'WA', '6430', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 74, 7, ARRAY['Community Centre', 'Gardens', 'Mining Heritage', 'Regional Setting', 'Aged Care'], '1300 280 334', 'kalgoorlie@bupa.com.au', 'https://www.bupa.com.au', 'Active'),

('SwanCare Australind', 'SwanCare', 'South West retirement village near Leschenault Inlet. Modern villas with waterfront proximity. Pool, community facilities and water activities. Close to Bunbury, beaches and inlet. Coastal regional living.', '1 Paris Road', 'Australind', 'WA', '6233', 'Independent Living', 280000, 430000, 120, 195, 96, 9, ARRAY['Pool', 'Waterfront Proximity', 'Community Centre', 'Gardens'], '08 9797 1234', 'australind@swancare.org.au', 'https://www.swancare.com.au', 'Active'),

('Juniper Kwinana', 'Juniper', 'Southern Perth industrial suburb retirement. Affordable villas near Kwinana shopping. Community facilities and gardens. Close to medical facilities and Freeway. Regional affordability.', '88 Sulphur Road', 'Kwinana', 'WA', '6167', 'Independent Living, Aged Care', 260000, 410000, 115, 190, 108, 10, ARRAY['Community Centre', 'Gardens', 'Shopping Access', 'Aged Care'], '08 9419 1234', 'kwinana@juniper.org.au', 'https://www.juniper.org.au', 'Active'),

('Amana Living Collie', 'Amana Living', 'South West coal mining town retirement. Affordable villas in regional centre. Community facilities, bowling green and gardens. Close to Collie Hospital and shopping. Country town lifestyle.', '88 Throssell Street', 'Collie', 'WA', '6225', 'Independent Living, Aged Care', 200000, 340000, 90, 160, 68, 6, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Regional Setting', 'Aged Care'], '08 9734 1234', 'collie@amanaliving.com.au', 'https://www.amanaliving.com.au', 'Active'),

('Southern Plus Esperance', 'Southern Plus', 'South Coast coastal town retirement. Comfortable villas near pristine beaches and Pink Lake. Community facilities and coastal setting. Close to Esperance town centre and medical facilities. Coastal paradise.', '88 Dempster Street', 'Esperance', 'WA', '6450', 'Independent Living', 240000, 380000, 105, 175, 64, 6, ARRAY['Beach Access', 'Community Centre', 'Coastal Setting', 'Gardens'], '08 9071 1234', 'esperance@southernplus.org.au', 'https://www.southernplus.org.au', 'Active'),

('Baptistcare Dunsborough', 'BaptistCare', 'Margaret River region coastal retirement. Modern villas near stunning beaches. Chapel, pool and community facilities. Walk to Dunsborough town centre, beaches and wineries. Premium south west lifestyle.', '88 Dunn Bay Road', 'Dunsborough', 'WA', '6281', 'Independent Living', 360000, 540000, 150, 240, 72, 5, ARRAY['Pool', 'Chapel', 'Beach Access', 'Wine Country'], '08 9756 1234', 'dunsborough@baptistcare.org.au', 'https://www.baptistcare.org.au', 'Active'),

('Allity Narrogin', 'Allity', 'Wheatbelt regional retirement village. Affordable villas in farming centre. Community facilities, bowling green and gardens. Close to Narrogin Hospital and shopping. Rural country living.', '88 Fortune Street', 'Narrogin', 'WA', '6312', 'Independent Living, Aged Care', 180000, 310000, 80, 150, 62, 6, ARRAY['Bowling Green', 'Community Centre', 'Gardens', 'Rural Setting', 'Aged Care'], '08 9881 1234', 'narrogin@allity.com.au', 'https://www.allity.com.au', 'Active'),

('Estia Health Broome', 'Estia Health', 'Kimberley tropical coast retirement. Modern villas near Cable Beach. Pool, community facilities and tropical gardens. Close to Broome town centre, beaches and pearling heritage. Tropical paradise lifestyle.', '88 Hamersley Street', 'Broome', 'WA', '6725', 'Independent Living, Aged Care', 300000, 460000, 130, 210, 68, 5, ARRAY['Pool', 'Beach Access', 'Tropical Gardens', 'Pearling Heritage', 'Aged Care'], '08 9192 1234', 'broome@estiahealth.com.au', 'https://www.estiahealth.com.au', 'Active'),

('Tricare Northam', 'Tricare', 'Avon Valley retirement village. Comfortable villas in heritage wheatbelt town. Community facilities, bowling green and gardens. Close to Northam Hospital and shopping. Valley country living.', '88 Fitzgerald Street', 'Northam', 'WA', '6401', 'Independent Living, Aged Care', '200000', 340000, 90, 160, 74, 7, ARRAY['Bowling Green', 'Heritage Setting', 'Community Centre', 'Gardens', 'Aged Care'], '08 9622 1234', 'northam@tricare.com.au', 'https://www.tricare.com.au', 'Active'),

('Mayflower Rockingham Beach', 'Mayflower', 'Southern Perth beachside retirement. Modern villas near beautiful beaches. Pool, community facilities and coastal walks. Walk to Rockingham Beach, cafes and shops. Coastal lifestyle living.', '88 Kent Street', 'Rockingham', 'WA', '6168', 'Independent Living', 360000, 540000, 150, 240, 94, 8, ARRAY['Pool', 'Beach Access', 'Coastal Walks', 'Community Centre'], '08 9527 9200', 'rockinghambeach@mayflower.org.au', 'https://www.mayflower.org.au', 'Active'),

('Lifestyle Communities Mandurah Waters', 'Lifestyle Communities', 'Peel waterfront over-50s resort. Modern manufactured homes with canal access. Boat berths, pool, bowling green and clubhouse. Perfect fishing, boating and waterways lifestyle. Affordable waterfront.', '1 Canals Drive', 'Mandurah', 'WA', '6210', 'Independent Living', 260000, 430000, 100, 170, 176, 15, ARRAY['Boat Berths', 'Pool', 'Bowling Green', 'Canal Access', 'Clubhouse'], '08 9535 9200', 'mandurahwaters@lifestylecommunities.com.au', 'https://www.lifestylecommunities.com.au', 'Active');
