// Seed script to populate retirement villages database
// Run this by calling the /villages/seed endpoint

export const sampleVillages = [
  {
    name: "Aveo Newstead",
    operatorName: "Aveo Group",
    operatorEmail: "info@aveo.com.au",
    address: "25 Commercial Road",
    suburb: "Newstead",
    state: "QLD",
    postcode: "4006",
    description: "Modern retirement living in the heart of Brisbane's vibrant Newstead precinct. Featuring contemporary apartments with resort-style facilities including pool, gym, cinema, and restaurant.",
    villageType: "independent",
    unitTypes: ["1-bed", "2-bed", "3-bed"],
    priceRange: { min: 450000, max: 850000 },
    monthlyFees: { min: 450, max: 750 },
    features: ["pool", "gym", "restaurant", "cinema", "library", "common-room", "workshop"],
    careServices: ["emergency-call", "on-site-manager"],
    lat: -27.4517,
    lng: 153.0415,
    totalUnits: 156,
    availableUnits: 8,
    petFriendly: true,
    featured: true,
    status: "approved",
  },
  {
    name: "Lendlease Retirement Living - The Grange",
    operatorName: "Lendlease",
    operatorEmail: "contact@lendlease.com",
    address: "142-178 Ferny Avenue",
    suburb: "Surfers Paradise",
    state: "QLD",
    postcode: "4217",
    description: "Luxury beachside retirement living on the Gold Coast. Spacious villas and apartments with ocean views, heated pool, bowling green, and easy beach access.",
    villageType: "independent",
    unitTypes: ["2-bed", "3-bed"],
    priceRange: { min: 520000, max: 1200000 },
    monthlyFees: { min: 550, max: 850 },
    features: ["pool", "gym", "bowling-green", "library", "common-room", "bbq-area", "workshop"],
    careServices: ["emergency-call", "on-site-manager", "visiting-nurse"],
    lat: -28.0023,
    lng: 153.4283,
    totalUnits: 204,
    availableUnits: 12,
    petFriendly: true,
    featured: true,
    status: "approved",
  },
  {
    name: "Stockland Retire Living - Willowdale",
    operatorName: "Stockland",
    operatorEmail: "retirement@stockland.com.au",
    address: "6 Willowdale Drive",
    suburb: "Denham Court",
    state: "NSW",
    postcode: "2565",
    description: "Peaceful village set amongst gardens in Sydney's southwest. Modern homes with community center, heated pool, and close to shopping centers.",
    villageType: "independent",
    unitTypes: ["2-bed", "3-bed"],
    priceRange: { min: 485000, max: 725000 },
    monthlyFees: { min: 420, max: 680 },
    features: ["pool", "library", "common-room", "bbq-area", "garden", "workshop"],
    careServices: ["emergency-call", "on-site-manager"],
    lat: -33.9847,
    lng: 150.8542,
    totalUnits: 142,
    availableUnits: 5,
    petFriendly: true,
    featured: false,
    status: "approved",
  },
  {
    name: "Ingenia Lifestyle - Marion Bay",
    operatorName: "Ingenia Communities",
    operatorEmail: "hello@ingeniacommunities.com.au",
    address: "15 Marion Bay Road",
    suburb: "Marion Bay",
    state: "TAS",
    postcode: "7175",
    description: "Coastal retirement village with stunning bay views. Affordable manufactured homes in a peaceful seaside setting with bowling green and community hall.",
    villageType: "independent",
    unitTypes: ["2-bed", "3-bed"],
    priceRange: { min: 195000, max: 385000 },
    monthlyFees: { min: 180, max: 320 },
    features: ["bowling-green", "common-room", "bbq-area", "garden"],
    careServices: ["emergency-call"],
    lat: -42.9667,
    lng: 147.9333,
    totalUnits: 68,
    availableUnits: 3,
    petFriendly: true,
    featured: false,
    status: "approved",
  },
  {
    name: "Baptcare Westhaven",
    operatorName: "Baptcare",
    operatorEmail: "westhaven@baptcare.org.au",
    address: "75 Hopetoun Avenue",
    suburb: "Werribee",
    state: "VIC",
    postcode: "3030",
    description: "Faith-based retirement community in Melbourne's west. Welcoming village with modern units, chapel, community center, and aged care services available.",
    villageType: "assisted",
    unitTypes: ["1-bed", "2-bed"],
    priceRange: { min: 320000, max: 480000 },
    monthlyFees: { min: 380, max: 580 },
    features: ["chapel", "library", "common-room", "garden", "hairdresser"],
    careServices: ["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"],
    lat: -37.9,
    lng: 144.6633,
    totalUnits: 94,
    availableUnits: 7,
    petFriendly: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Uniting AgeWell - Strathdon",
    operatorName: "Uniting AgeWell",
    operatorEmail: "info@unitingagewell.org",
    address: "127 Canterbury Road",
    suburb: "Canterbury",
    state: "VIC",
    postcode: "3126",
    description: "Inner-city Melbourne retirement village with easy access to shops, cafes and transport. Modern apartments with full aged care services on-site.",
    villageType: "aged-care",
    unitTypes: ["1-bed", "2-bed"],
    priceRange: { min: 420000, max: 620000 },
    monthlyFees: { min: 480, max: 720 },
    features: ["library", "common-room", "garden", "hairdresser", "cafe"],
    careServices: ["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "transport", "24hr-care"],
    lat: -37.8267,
    lng: 145.0633,
    totalUnits: 112,
    availableUnits: 4,
    petFriendly: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Ryman Healthcare - Charles Upham",
    operatorName: "Ryman Healthcare",
    operatorEmail: "enquiry@rymanhealthcare.com",
    address: "83-101 Mein Street",
    suburb: "Newtown",
    state: "VIC",
    postcode: "3220",
    description: "Premium retirement village in Geelong with independent villas, serviced apartments, and care facilities. Features include pool, gym, bowling green, cinema, and restaurant.",
    villageType: "aged-care",
    unitTypes: ["1-bed", "2-bed", "3-bed"],
    priceRange: { min: 480000, max: 920000 },
    monthlyFees: { min: 520, max: 850 },
    features: ["pool", "gym", "bowling-green", "cinema", "restaurant", "library", "common-room", "hairdresser", "cafe", "garden"],
    careServices: ["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"],
    lat: -38.1542,
    lng: 144.3283,
    totalUnits: 238,
    availableUnits: 15,
    petFriendly: true,
    featured: true,
    status: "approved",
  },
  {
    name: "Bethanie Waters",
    operatorName: "Bethanie Group",
    operatorEmail: "enquiries@bethanie.com.au",
    address: "1 Bethanie Way",
    suburb: "Southern River",
    state: "WA",
    postcode: "6110",
    description: "Large retirement village in Perth's southeast with beautiful lake views. Offers independent living villas and full residential aged care. Extensive facilities including pool, gym, and bowling green.",
    villageType: "aged-care",
    unitTypes: ["2-bed", "3-bed"],
    priceRange: { min: 395000, max: 695000 },
    monthlyFees: { min: 420, max: 680 },
    features: ["pool", "gym", "bowling-green", "library", "common-room", "chapel", "hairdresser", "cafe", "bbq-area", "garden"],
    careServices: ["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "transport", "24hr-care", "dementia-care"],
    lat: -32.1,
    lng: 115.9433,
    totalUnits: 176,
    availableUnits: 9,
    petFriendly: true,
    featured: false,
    status: "approved",
  },
  {
    name: "Anglicare Sydney - Ryde Gardens",
    operatorName: "Anglicare Sydney",
    operatorEmail: "info@anglicare.org.au",
    address: "45 Victoria Road",
    suburb: "Ryde",
    state: "NSW",
    postcode: "2112",
    description: "Well-established retirement village in Sydney's north with peaceful gardens. Independent living units and serviced apartments with strong community focus.",
    villageType: "assisted",
    unitTypes: ["1-bed", "2-bed"],
    priceRange: { min: 495000, max: 685000 },
    monthlyFees: { min: 460, max: 650 },
    features: ["library", "common-room", "chapel", "garden", "hairdresser"],
    careServices: ["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"],
    lat: -33.8142,
    lng: 151.1042,
    totalUnits: 86,
    availableUnits: 3,
    petFriendly: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Keyton Halcyon Landing",
    operatorName: "Keyton",
    operatorEmail: "hello@keyton.com.au",
    address: "89 Wellington Road",
    suburb: "Clayton",
    state: "VIC",
    postcode: "3168",
    description: "Modern apartments for over 55s in Melbourne's southeast. Contemporary design with rooftop terrace, gym, cinema, and workshop. Close to Monash Medical Centre and Westfield Southland.",
    villageType: "independent",
    unitTypes: ["1-bed", "2-bed"],
    priceRange: { min: 420000, max: 620000 },
    monthlyFees: { min: 390, max: 580 },
    features: ["gym", "cinema", "library", "common-room", "workshop", "bbq-area", "rooftop-terrace"],
    careServices: ["emergency-call", "on-site-manager"],
    lat: -37.9217,
    lng: 145.1233,
    totalUnits: 142,
    availableUnits: 11,
    petFriendly: true,
    featured: false,
    status: "approved",
  },
  {
    name: "Estia Villages - The Palms",
    operatorName: "Estia Health",
    operatorEmail: "villages@estiahealth.com.au",
    address: "156 Palms Road",
    suburb: "Mudgeeraba",
    state: "QLD",
    postcode: "4213",
    description: "Tropical retirement village in Gold Coast hinterland. Spacious villas surrounded by palm trees with pool, community center, and close to shopping village.",
    villageType: "independent",
    unitTypes: ["2-bed", "3-bed"],
    priceRange: { min: 385000, max: 625000 },
    monthlyFees: { min: 380, max: 580 },
    features: ["pool", "bowling-green", "common-room", "library", "bbq-area", "garden"],
    careServices: ["emergency-call", "on-site-manager", "visiting-nurse"],
    lat: -28.0817,
    lng: 153.3717,
    totalUnits: 98,
    availableUnits: 6,
    petFriendly: true,
    featured: false,
    status: "approved",
  },
  {
    name: "Peninsula Villages - Umina Beach",
    operatorName: "Peninsula Villages",
    operatorEmail: "info@pvl.com.au",
    address: "55 Trafalgar Avenue",
    suburb: "Umina Beach",
    state: "NSW",
    postcode: "2257",
    description: "Beachside retirement village on the Central Coast. Short walk to beach and shops. Independent villas and serviced apartments with pool, bowling green, and community center.",
    villageType: "assisted",
    unitTypes: ["1-bed", "2-bed", "3-bed"],
    priceRange: { min: 425000, max: 785000 },
    monthlyFees: { min: 420, max: 680 },
    features: ["pool", "bowling-green", "library", "common-room", "bbq-area", "garden", "hairdresser"],
    careServices: ["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"],
    lat: -33.5242,
    lng: 151.3158,
    totalUnits: 164,
    availableUnits: 8,
    petFriendly: true,
    featured: false,
    status: "approved",
  },
  {
    name: "Arcadia Waters",
    operatorName: "Arcadia Care",
    operatorEmail: "info@arcadiacare.com.au",
    address: "12 Lake Drive",
    suburb: "Pakenham",
    state: "VIC",
    postcode: "3810",
    description: "Family-owned village in Melbourne's southeast growth corridor. Modern homes around central lake with emphasis on community and affordability.",
    villageType: "independent",
    unitTypes: ["2-bed", "3-bed"],
    priceRange: { min: 325000, max: 525000 },
    monthlyFees: { min: 320, max: 480 },
    features: ["common-room", "library", "bbq-area", "garden", "workshop"],
    careServices: ["emergency-call", "on-site-manager"],
    lat: -38.0733,
    lng: 145.4833,
    totalUnits: 72,
    availableUnits: 4,
    petFriendly: true,
    featured: false,
    status: "approved",
  },
  {
    name: "Masonic Care - Narelle Cox",
    operatorName: "Masonic Care Queensland",
    operatorEmail: "enquiries@masoniccare.org.au",
    address: "88 Ewing Road",
    suburb: "Woodridge",
    state: "QLD",
    postcode: "4114",
    description: "Affordable retirement living in Logan with strong community spirit. Independent units with access to community center, library, and regular social activities.",
    villageType: "independent",
    unitTypes: ["1-bed", "2-bed"],
    priceRange: { min: 185000, max: 325000 },
    monthlyFees: { min: 220, max: 380 },
    features: ["library", "common-room", "bbq-area", "garden"],
    careServices: ["emergency-call", "on-site-manager"],
    lat: -27.6392,
    lng: 153.1092,
    totalUnits: 54,
    availableUnits: 2,
    petFriendly: true,
    featured: false,
    status: "approved",
  },
  {
    name: "Japara Bayview Gardens",
    operatorName: "Japara Healthcare",
    operatorEmail: "enquiries@japara.com.au",
    address: "234 Bay Road",
    suburb: "Sandringham",
    state: "VIC",
    postcode: "3191",
    description: "Premium bayside retirement living with aged care services. Close to beach, cafes, and Sandringham village. Modern apartments with resort-style amenities.",
    villageType: "aged-care",
    unitTypes: ["1-bed", "2-bed"],
    priceRange: { min: 580000, max: 850000 },
    monthlyFees: { min: 520, max: 780 },
    features: ["pool", "gym", "library", "common-room", "hairdresser", "cafe", "garden"],
    careServices: ["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"],
    lat: -37.9525,
    lng: 145.0042,
    totalUnits: 128,
    availableUnits: 6,
    petFriendly: false,
    featured: true,
    status: "approved",
  },
  {
    name: "Villa Maria Catholic Homes - Greenacres",
    operatorName: "Villa Maria Catholic Homes",
    operatorEmail: "info@vmch.com.au",
    address: "45-55 Greenacres Road",
    suburb: "Oakleigh South",
    state: "VIC",
    postcode: "3167",
    description: "Catholic retirement community with values-based care. Independent villas and full aged care facility with chapel, community spaces, and strong pastoral support.",
    villageType: "aged-care",
    unitTypes: ["1-bed", "2-bed"],
    priceRange: { min: 385000, max: 565000 },
    monthlyFees: { min: 420, max: 620 },
    features: ["chapel", "library", "common-room", "garden", "hairdresser", "cafe"],
    careServices: ["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"],
    lat: -37.9333,
    lng: 145.0933,
    totalUnits: 96,
    availableUnits: 5,
    petFriendly: false,
    featured: false,
    status: "approved",
  },
];
