-- Batch 5: QLD Retirement Villages (15 villages)
-- Execute this in Supabase SQL Editor
-- Adds villages across Brisbane, Gold Coast, Sunshine Coast

INSERT INTO retirement_villages (
  name,
  operator,
  location,
  suburb,
  postcode,
  state,
  latitude,
  longitude,
  village_type,
  care_level,
  entry_price_min,
  entry_price_max,
  monthly_fees_min,
  monthly_fees_max,
  dmf_structure,
  dmf_percentage,
  dmf_cap,
  amenities,
  care_services,
  activities,
  pet_friendly,
  total_units,
  bedrooms,
  age_restriction,
  contact_phone,
  contact_email,
  website,
  description,
  status,
  source,
  verified
) VALUES

-- 1. Aveo Cleveland - Cleveland (Bay side Brisbane)
(
  'Aveo Cleveland',
  'Aveo Group',
  '231 Shore Street West',
  'Cleveland',
  '4163',
  'QLD',
  -27.5286,
  153.2617,
  'Mixed',
  'Mixed',
  380000,
  680000,
  420,
  650,
  'DMF',
  6,
  30,
  ARRAY['Pool', 'Gym', 'Library', 'Community hall', 'Garden', 'BBQ area'],
  ARRAY['Aged care', 'Memory support', '24/7 nursing', 'Allied health'],
  ARRAY['Swimming', 'Exercise classes', 'Social events', 'Entertainment'],
  true,
  160,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '1300 283 648',
  'cleveland@aveo.com.au',
  'https://www.aveo.com.au',
  'Bayside retirement living near Stradbroke Island with beautiful water views.',
  'approved',
  'manual',
  true
),

-- 2. Lendlease Newstead - Newstead (Inner Brisbane)
(
  'Lendlease Newstead',
  'Lendlease Retirement Living',
  '88 Commercial Road',
  'Newstead',
  '4006',
  'QLD',
  -27.4474,
  153.0485,
  'Serviced Apartments',
  'Independent',
  750000,
  1400000,
  700,
  1100,
  'DMF',
  5,
  20,
  ARRAY['Pool', 'Gym', 'Cinema', 'Concierge', 'Rooftop terrace', 'Dining room', 'Library'],
  ARRAY['Emergency response', 'Concierge services', 'Optional home care'],
  ARRAY['Social dining', 'Entertainment', 'Cultural outings', 'Wine tastings'],
  false,
  150,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  65,
  '1300 635 353',
  'newstead@lendlease.com',
  'https://www.retireinaustralia.com.au',
  'Premium riverside retirement living in trendy Newstead with Brisbane River views.',
  'approved',
  'manual',
  true
),

-- 3. Regis Aged Care Caboolture - Caboolture
(
  'Regis Aged Care Caboolture',
  'Regis Aged Care',
  '1 Hasking Street',
  'Caboolture',
  '4510',
  'QLD',
  -27.0858,
  152.9530,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2400,
  3400,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden', 'Cafe', 'Hair salon', 'Activities room', 'Chapel'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Allied health'],
  ARRAY['Entertainment', 'Exercise programs', 'Art and craft', 'Pet therapy'],
  false,
  100,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 998 100',
  'caboolture@regis.com.au',
  'https://www.regis.com.au',
  'Quality aged care north of Brisbane with caring staff and modern facilities.',
  'approved',
  'manual',
  true
),

-- 4. Bolton Clarke Fairview - Anglesea Street, Maryborough
(
  'Bolton Clarke Fairview',
  'Bolton Clarke',
  '174 Ellena Street',
  'Maryborough',
  '4650',
  'QLD',
  -25.5384,
  152.7021,
  'Mixed',
  'Mixed',
  220000,
  400000,
  350,
  550,
  'DMF',
  6,
  30,
  ARRAY['Pool', 'Library', 'Community hall', 'Garden', 'BBQ area'],
  ARRAY['Aged care', '24/7 nursing', 'Memory support', 'Allied health'],
  ARRAY['Swimming', 'Social events', 'Entertainment', 'Garden club'],
  true,
  90,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '1300 665 566',
  'fairview@boltonclarke.com.au',
  'https://www.boltonclarke.com.au',
  'Affordable retirement living in historic Maryborough with friendly community.',
  'approved',
  'manual',
  true
),

-- 5. Opal Aged Care Brookwater - Springfield Lakes
(
  'Opal Aged Care Brookwater',
  'Opal Aged Care',
  '1 Brookwater Crescent',
  'Springfield Lakes',
  '4300',
  'QLD',
  -27.6712,
  152.9198,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2500,
  3500,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden', 'Cafe', 'Hair salon', 'Cinema', 'Activities room'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Physiotherapy'],
  ARRAY['Entertainment', 'Exercise programs', 'Music therapy', 'Art activities'],
  false,
  110,
  ARRAY['Shared', 'Single room'],
  NULL,
  '07 3470 5100',
  'brookwater@opalagecare.com.au',
  'https://www.opalagecare.com.au',
  'Modern aged care in the growing Brookwater community near Ipswich.',
  'approved',
  'manual',
  true
),

-- 6. Blue Care Anglicare Toowoomba - Toowoomba
(
  'Blue Care Anglicare Toowoomba',
  'Blue Care',
  '185 Russell Street',
  'Toowoomba',
  '4350',
  'QLD',
  -27.5598,
  151.9507,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2300,
  3300,
  NULL,
  NULL,
  NULL,
  ARRAY['Chapel', 'Garden', 'Cafe', 'Hair salon', 'Activities room'],
  ARRAY['24/7 nursing', 'Dementia care', 'Palliative care', 'Respite care'],
  ARRAY['Religious services', 'Entertainment', 'Music therapy', 'Pet therapy'],
  false,
  85,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 258 322',
  'toowoomba@bluecare.org.au',
  'https://www.bluecare.org.au',
  'Established aged care on the Darling Downs with strong community connections.',
  'approved',
  'manual',
  true
),

-- 7. Estia Health Bundaberg - Bundaberg
(
  'Estia Health Bundaberg',
  'Estia Health',
  '166 Barolin Street',
  'Bundaberg',
  '4670',
  'QLD',
  -24.8661,
  152.3489,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2200,
  3200,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden', 'Cafe', 'Hair salon', 'Activities room', 'Outdoor areas'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Allied health'],
  ARRAY['Entertainment', 'Exercise programs', 'Garden activities', 'Music therapy'],
  false,
  95,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 682 833',
  'bundaberg@estiahealth.com.au',
  'https://www.estiahealth.com.au',
  'Quality aged care in the heart of Bundaberg near hospital and services.',
  'approved',
  'manual',
  true
),

-- 8. Mercure Townsville - Townsville (North Queensland)
(
  'Mercure Townsville',
  'Bolton Clarke',
  '22 Morehead Street',
  'Townsville',
  '4810',
  'QLD',
  -19.2590,
  146.8169,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2400,
  3400,
  NULL,
  NULL,
  NULL,
  ARRAY['Tropical gardens', 'Cafe', 'Hair salon', 'Activities room', 'Chapel'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Allied health'],
  ARRAY['Entertainment', 'Exercise programs', 'Music therapy', 'Pet therapy'],
  false,
  90,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 665 566',
  'townsville@boltonclarke.com.au',
  'https://www.boltonclarke.com.au',
  'Tropical North Queensland aged care with warm climate and caring staff.',
  'approved',
  'manual',
  true
),

-- 9. Japara Warringa - Manly West (Brisbane)
(
  'Japara Warringa',
  'Japara Healthcare',
  '196 Wynnum North Road',
  'Manly West',
  '4179',
  'QLD',
  -27.4575,
  153.1811,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2500,
  3500,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden', 'Cafe', 'Hair salon', 'Activities room', 'Outdoor areas'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Physiotherapy'],
  ARRAY['Entertainment', 'Exercise programs', 'Art and craft', 'Music therapy'],
  false,
  100,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 522 272',
  'warringa@japara.com.au',
  'https://www.japara.com.au',
  'Bayside aged care near Wynnum with easy access to waterfront and parks.',
  'approved',
  'manual',
  true
),

-- 10. Arcare Reservoir - Maroochydore (Sunshine Coast)
(
  'Arcare Maroochydore',
  'Arcare',
  '77 Dalton Drive',
  'Maroochydore',
  '4558',
  'QLD',
  -26.6569,
  153.0892,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2600,
  3600,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden', 'Cafe', 'Hair salon', 'Cinema', 'Activities room'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Allied health'],
  ARRAY['Entertainment', 'Exercise programs', 'Beach outings', 'Music therapy'],
  false,
  120,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 272 273',
  'maroochydore@arcare.com.au',
  'https://www.arcare.com.au',
  'Sunshine Coast aged care with beautiful location near beaches and amenities.',
  'approved',
  'manual',
  true
),

-- 11. Mercy Place Worongary - Worongary (Gold Coast Hinterland)
(
  'Mercy Place Worongary',
  'Mercy Health',
  '1 Carramar Drive',
  'Worongary',
  '4213',
  'QLD',
  -28.0465,
  153.3668,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2700,
  3700,
  NULL,
  NULL,
  NULL,
  ARRAY['Chapel', 'Garden', 'Cafe', 'Hair salon', 'Activities room'],
  ARRAY['24/7 nursing', 'Dementia care', 'Palliative care', 'Allied health'],
  ARRAY['Mass', 'Entertainment', 'Music therapy', 'Garden activities'],
  false,
  90,
  ARRAY['Shared', 'Single room'],
  NULL,
  '07 5580 5100',
  'worongary@mercyhealth.com.au',
  'https://www.mercyhealth.com.au',
  'Gold Coast hinterland aged care with peaceful surroundings and quality care.',
  'approved',
  'manual',
  true
),

-- 12. Sinnamon Village - Jindalee (Western Brisbane)
(
  'Sinnamon Village',
  'Sinnamon Village',
  '1 Kookaburra Court',
  'Jindalee',
  '4074',
  'QLD',
  -27.5359,
  152.9395,
  'Mixed',
  'Mixed',
  420000,
  720000,
  480,
  720,
  'DMF',
  6,
  30,
  ARRAY['Pool', 'Gym', 'Library', 'Community hall', 'Garden', 'Bowling green', 'Workshop'],
  ARRAY['Aged care', 'Memory support', '24/7 nursing', 'Allied health'],
  ARRAY['Swimming', 'Bowls', 'Exercise classes', 'Social events', 'Entertainment'],
  true,
  180,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '07 3376 4777',
  'info@sinnamonvillage.com.au',
  'https://www.sinnamonvillage.com.au',
  'Well-established retirement village in Western Brisbane with comprehensive facilities.',
  'approved',
  'manual',
  true
),

-- 13. Keperra Sanctuary - Keperra (North Brisbane)
(
  'Keperra Sanctuary',
  'Sanctuary Retirement Living',
  '1070 Samford Road',
  'Keperra',
  '4054',
  'QLD',
  -27.4145,
  152.9529,
  'Independent Living',
  'Independent',
  380000,
  650000,
  420,
  620,
  'DMF',
  5,
  30,
  ARRAY['Pool', 'Library', 'Community hall', 'Garden', 'BBQ area'],
  ARRAY['Emergency response', 'Weekly wellness checks'],
  ARRAY['Swimming', 'Social events', 'Garden club', 'Bus trips'],
  true,
  110,
  ARRAY['2 bedroom', '3 bedroom'],
  55,
  '07 3354 4600',
  'keperra@sanctuaryretirementliving.com.au',
  'https://www.sanctuaryretirementliving.com.au',
  'Friendly retirement community in leafy Keperra with affordable options.',
  'approved',
  'manual',
  true
),

-- 14. Blue Care Cairns - Cairns (Far North Queensland)
(
  'Blue Care Cairns',
  'Blue Care',
  '152 Lake Street',
  'Cairns',
  '4870',
  'QLD',
  -16.9186,
  145.7781,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2300,
  3300,
  NULL,
  NULL,
  NULL,
  ARRAY['Tropical gardens', 'Cafe', 'Hair salon', 'Activities room', 'Chapel'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Allied health'],
  ARRAY['Entertainment', 'Exercise programs', 'Music therapy', 'Garden activities'],
  false,
  80,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 258 322',
  'cairns@bluecare.org.au',
  'https://www.bluecare.org.au',
  'Far North Queensland aged care with tropical setting and caring community.',
  'approved',
  'manual',
  true
),

-- 15. Caloundra Retirement Village - Caloundra (Sunshine Coast)
(
  'Caloundra Retirement Village',
  'Independent operator',
  '15 Caloundra Road',
  'Caloundra',
  '4551',
  'QLD',
  -26.7989,
  153.1311,
  'Independent Living',
  'Independent',
  320000,
  580000,
  380,
  580,
  'DMF',
  6,
  30,
  ARRAY['Pool', 'Community hall', 'Library', 'Garden', 'BBQ area'],
  ARRAY['Emergency response', 'Weekly wellness checks'],
  ARRAY['Swimming', 'Social events', 'Garden club', 'Beach walks'],
  true,
  85,
  ARRAY['2 bedroom', '3 bedroom'],
  55,
  '07 5491 4200',
  'info@caloundraretirement.com.au',
  'https://www.caloundraretirement.com.au',
  'Affordable Sunshine Coast retirement living close to beaches and amenities.',
  'approved',
  'manual',
  true
);

-- Verify insertion
SELECT COUNT(*) as qld_villages_added FROM retirement_villages WHERE state = 'QLD' AND source = 'manual';
