-- Batch 3: NSW Retirement Villages (20 villages)
-- Execute this in Supabase SQL Editor
-- Adds villages across Greater Sydney and regional NSW

INSERT INTO retirement_villages (
  name,
  operator,
  location,
  suburb,
  postcode,
  state,
  latitude,
  longitude,
  village_type,
  care_level,
  entry_price_min,
  entry_price_max,
  monthly_fees_min,
  monthly_fees_max,
  dmf_structure,
  dmf_percentage,
  dmf_cap,
  amenities,
  care_services,
  activities,
  pet_friendly,
  total_units,
  bedrooms,
  age_restriction,
  contact_phone,
  contact_email,
  website,
  description,
  status,
  source,
  verified
) VALUES

-- 1. Macquarie Lodge Village - North Ryde
(
  'Macquarie Lodge Village',
  'Uniting NSW & ACT',
  '2-4 Cressy Road',
  'North Ryde',
  '2113',
  'NSW',
  -33.7959,
  151.1272,
  'Mixed',
  'Mixed',
  450000,
  750000,
  450,
  750,
  'DMF',
  6,
  30,
  ARRAY['Swimming pool', 'Gym', 'Library', 'Community hall', 'Gardens', 'BBQ area', 'Craft room'],
  ARRAY['On-site nursing', 'Aged care facility', '24/7 emergency response', 'Allied health services'],
  ARRAY['Exercise classes', 'Social events', 'Bus outings', 'Art classes', 'Garden club'],
  true,
  180,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '1300 864 846',
  'macquarielodge@uniting.org',
  'https://www.uniting.org/retirement-living',
  'Nestled in leafy North Ryde with easy access to Macquarie University Hospital and shopping centers. Independent living with on-site aged care facility.',
  'approved',
  'manual',
  true
),

-- 2. Lulworth House - Elizabeth Bay
(
  'Lulworth House',
  'IRT Living',
  '122 Billyard Avenue',
  'Elizabeth Bay',
  '2011',
  'NSW',
  -33.8712,
  151.2278,
  'Serviced Apartments',
  'Independent',
  650000,
  1200000,
  800,
  1200,
  'None',
  NULL,
  NULL,
  ARRAY['Harbour views', 'Concierge', 'Dining room', 'Lounge areas', 'Garden terrace', 'Secure parking'],
  ARRAY['Emergency response', 'Optional home care'],
  ARRAY['Social dining', 'Cultural outings', 'Entertainment'],
  false,
  60,
  ARRAY['1 bedroom', '2 bedroom'],
  65,
  '1300 768 096',
  'enquiries@irt.org.au',
  'https://www.irt.org.au/retirement-living',
  'Luxury retirement living in prestigious Elizabeth Bay with stunning harbour views. Premium independent living apartments.',
  'approved',
  'manual',
  true
),

-- 3. Goodwin Village Manly - Manly Vale
(
  'Goodwin Village Manly',
  'Goodwin Aged Care Services',
  '701 Pittwater Road',
  'Manly Vale',
  '2093',
  'NSW',
  -33.7789,
  151.2644,
  'Mixed',
  'Mixed',
  500000,
  900000,
  550,
  850,
  'DMF',
  5,
  30,
  ARRAY['Pool', 'Gym', 'Cafe', 'Cinema', 'Hair salon', 'Garden', 'Workshop'],
  ARRAY['Aged care', 'Memory support', '24/7 nursing', 'Physiotherapy'],
  ARRAY['Group fitness', 'Swimming', 'Day trips', 'Concerts'],
  true,
  200,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '02 9977 4322',
  'manlyvillage@goodwin.org.au',
  'https://www.goodwin.org.au/retirement-living',
  'Beautiful village near Manly Beach with comprehensive care options. Close to shops, beaches and bushland.',
  'approved',
  'manual',
  true
),

-- 4. Waverley Gardens Village - Bondi Junction
(
  'Waverley Gardens Village',
  'Presbyterian Aged Care NSW',
  '5 Sutherland Street',
  'Paddington',
  '2021',
  'NSW',
  -33.8843,
  151.2287,
  'Independent Living',
  'Independent',
  700000,
  1100000,
  600,
  900,
  'DMF',
  5,
  25,
  ARRAY['Rooftop garden', 'Lounge', 'Library', 'Guest suites', 'Secure parking'],
  ARRAY['Emergency call system', 'Optional home care'],
  ARRAY['Social events', 'Coffee mornings', 'Cultural outings'],
  false,
  45,
  ARRAY['1 bedroom', '2 bedroom'],
  60,
  '02 9369 4588',
  'info@pacare.org.au',
  'https://www.pacare.org.au',
  'Boutique retirement living in the heart of Paddington. Walk to shops, cafes and Oxford Street.',
  'approved',
  'manual',
  true
),

-- 5. Roselea Retirement Village - Penrith
(
  'Roselea Retirement Village',
  'Roselea Group',
  '1 Roselea Crescent',
  'Penrith',
  '2750',
  'NSW',
  -33.7508,
  150.6941,
  'Independent Living',
  'Independent',
  250000,
  450000,
  350,
  500,
  'DMF',
  6,
  30,
  ARRAY['Community hall', 'BBQ area', 'Gardens', 'Bowls green', 'Workshop'],
  ARRAY['Emergency response', 'Weekly wellness checks'],
  ARRAY['Bowls', 'Cards', 'Social events', 'Garden club'],
  true,
  120,
  ARRAY['2 bedroom', '3 bedroom'],
  55,
  '02 4721 9144',
  'info@roselea.com.au',
  'https://www.roselea.com.au',
  'Affordable retirement living in Western Sydney with friendly community atmosphere.',
  'approved',
  'manual',
  true
),

-- 6. The Grange Retirement Village - Castle Hill
(
  'The Grange Retirement Village',
  'Baptist Care NSW',
  '1 Showground Road',
  'Castle Hill',
  '2154',
  'NSW',
  -33.7308,
  151.0025,
  'Mixed',
  'Mixed',
  500000,
  850000,
  500,
  800,
  'DMF',
  5,
  30,
  ARRAY['Pool', 'Gym', 'Library', 'Cafe', 'Cinema', 'Bowling green', 'Gardens'],
  ARRAY['Aged care', 'Memory care', 'Rehabilitation', '24/7 nursing'],
  ARRAY['Fitness classes', 'Swimming', 'Bowls', 'Entertainment', 'Bus trips'],
  true,
  250,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '02 8865 5500',
  'enquiries@baptistcare.org.au',
  'https://www.baptistcare.org.au',
  'Premier retirement village in the Hills District with comprehensive facilities and care services.',
  'approved',
  'manual',
  true
),

-- 7. Opal Aged Care Bankstown - Bankstown
(
  'Opal Aged Care Bankstown',
  'Opal Aged Care',
  '77 Boronia Street',
  'South Granville',
  '2142',
  'NSW',
  -33.8564,
  151.0121,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2500,
  3500,
  NULL,
  NULL,
  NULL,
  ARRAY['Secure gardens', 'Activities room', 'Dining room', 'Lounge areas'],
  ARRAY['24/7 nursing care', 'Dementia care', 'Palliative care', 'Allied health'],
  ARRAY['Music therapy', 'Art activities', 'Garden therapy', 'Entertainment'],
  false,
  80,
  ARRAY['Shared', 'Single room'],
  NULL,
  '02 8711 1400',
  'bankstown@opalagecare.com.au',
  'https://www.opalagecare.com.au',
  'Residential aged care in multicultural Bankstown with specialized dementia care.',
  'approved',
  'manual',
  true
),

-- 8. Regis Aged Care Concord - Concord
(
  'Regis Aged Care Concord',
  'Regis Aged Care',
  '64 Parramatta Road',
  'Concord',
  '2137',
  'NSW',
  -33.8624,
  151.1023,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2800,
  3800,
  NULL,
  NULL,
  NULL,
  ARRAY['Courtyard', 'Cafe', 'Hair salon', 'Activities room', 'Chapel'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Palliative care'],
  ARRAY['Exercise programs', 'Entertainment', 'Art and craft', 'Pet therapy'],
  false,
  100,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 998 100',
  'concord@regis.com.au',
  'https://www.regis.com.au',
  'Premium aged care facility close to Concord Hospital with specialised care programs.',
  'approved',
  'manual',
  true
),

-- 9. Estia Health Dural - Dural
(
  'Estia Health Dural',
  'Estia Health',
  '3 Kenthurst Road',
  'Dural',
  '2158',
  'NSW',
  -33.6850,
  151.0318,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2600,
  3600,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden areas', 'Cafe', 'Activities room', 'Hair salon', 'Cinema'],
  ARRAY['24/7 nursing', 'Dementia care', 'Palliative care', 'Physiotherapy'],
  ARRAY['Group activities', 'Live entertainment', 'Garden club', 'Cooking groups'],
  false,
  90,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 682 833',
  'dural@estiahealth.com.au',
  'https://www.estiahealth.com.au',
  'Modern aged care facility in peaceful Dural with beautiful garden settings.',
  'approved',
  'manual',
  true
),

-- 10. St Vincent's Care Edgecliff - Edgecliff
(
  'St Vincent''s Care Edgecliff',
  'St Vincent''s Care Services',
  '222 New South Head Road',
  'Edgecliff',
  '2027',
  'NSW',
  -33.8798,
  151.2365,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  3000,
  4000,
  NULL,
  NULL,
  NULL,
  ARRAY['Harbour views', 'Chapel', 'Cafe', 'Hair salon', 'Garden terrace'],
  ARRAY['24/7 nursing', 'Palliative care', 'Dementia care', 'Allied health services'],
  ARRAY['Mass and religious services', 'Entertainment', 'Music therapy'],
  false,
  60,
  ARRAY['Shared', 'Single room'],
  NULL,
  '02 9328 2211',
  'edgecliff@svcs.org.au',
  'https://www.svcs.org.au',
  'Premium aged care in prestigious Edgecliff with views and excellent medical access.',
  'approved',
  'manual',
  true
),

-- 11. Anglicare Newmarch House - Kingswood
(
  'Anglicare Newmarch House',
  'Anglicare NSW South',
  '17 Boronia Road',
  'Kingswood',
  '2747',
  'NSW',
  -33.7630,
  150.7305,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2400,
  3400,
  NULL,
  NULL,
  NULL,
  ARRAY['Gardens', 'Activities room', 'Cafe', 'Chapel', 'Outdoor areas'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Physiotherapy'],
  ARRAY['Religious services', 'Entertainment', 'Craft activities', 'Pet therapy'],
  false,
  110,
  ARRAY['Shared', 'Single room'],
  NULL,
  '02 4731 6700',
  'newmarch@anglicare.org.au',
  'https://www.anglicare.org.au',
  'Well-established aged care facility in Western Sydney with strong community connections.',
  'approved',
  'manual',
  true
),

-- 12. BlueCross Apartments Chatswood - Chatswood
(
  'BlueCross Apartments Chatswood',
  'BlueCross',
  '86 Archer Street',
  'Chatswood',
  '2067',
  'NSW',
  -33.7969,
  151.1832,
  'Serviced Apartments',
  'Independent',
  600000,
  1000000,
  650,
  950,
  'DMF',
  5,
  25,
  ARRAY['Rooftop terrace', 'Lounge', 'Library', 'Gym', 'Guest suites'],
  ARRAY['Emergency response', 'Optional home care'],
  ARRAY['Social activities', 'Cultural outings', 'Coffee mornings'],
  false,
  80,
  ARRAY['1 bedroom', '2 bedroom'],
  60,
  '02 8425 1800',
  'chatswood@bluecross.com.au',
  'https://www.bluecross.com.au',
  'Modern retirement apartments in the heart of Chatswood with easy access to transport and shops.',
  'approved',
  'manual',
  true
),

-- 13. Livingstone Gardens - Kareela
(
  'Livingstone Gardens',
  'Uniting NSW & ACT',
  '2 Livingstone Avenue',
  'Kareela',
  '2232',
  'NSW',
  -34.0255,
  151.0707,
  'Mixed',
  'Mixed',
  400000,
  700000,
  450,
  700,
  'DMF',
  6,
  30,
  ARRAY['Pool', 'Gym', 'Library', 'Community hall', 'Garden', 'Workshop'],
  ARRAY['Aged care facility', 'Memory support', '24/7 emergency'],
  ARRAY['Swimming', 'Fitness classes', 'Social events', 'Bus outings'],
  true,
  160,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '02 9528 3855',
  'livingstone@uniting.org',
  'https://www.uniting.org',
  'Sutherland Shire retirement village with comprehensive facilities and adjacent aged care.',
  'approved',
  'manual',
  true
),

-- 14. Catholic Healthcare Ryde - Ryde
(
  'Catholic Healthcare Ryde',
  'Catholic Healthcare',
  '45 Bydown Street',
  'Neutral Bay',
  '2089',
  'NSW',
  -33.8305,
  151.2189,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2800,
  3800,
  NULL,
  NULL,
  NULL,
  ARRAY['Chapel', 'Garden areas', 'Cafe', 'Activities room', 'Hair salon'],
  ARRAY['24/7 nursing', 'Dementia care', 'Palliative care', 'Respite care'],
  ARRAY['Mass', 'Entertainment', 'Music therapy', 'Garden activities'],
  false,
  70,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1800 225 474',
  'ryde@chslimited.org.au',
  'https://www.catholichealthcare.com.au',
  'Catholic aged care facility on the Lower North Shore with harbour views.',
  'approved',
  'manual',
  true
),

-- 15. Peninsula Village - McCarrs Creek Road, Church Point
(
  'Peninsula Village',
  'Peninsula Village',
  '691 McCarrs Creek Road',
  'Church Point',
  '2105',
  'NSW',
  -33.6507,
  151.2877,
  'Mixed',
  'Mixed',
  550000,
  950000,
  550,
  850,
  'DMF',
  5,
  30,
  ARRAY['Pool', 'Gym', 'Library', 'Cinema', 'Bowling green', 'Gardens', 'Marina access'],
  ARRAY['Aged care', 'Dementia care', '24/7 nursing', 'Allied health'],
  ARRAY['Bowls', 'Fitness classes', 'Swimming', 'Entertainment', 'Boating'],
  true,
  180,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '02 9979 5555',
  'info@peninsulavillage.com.au',
  'https://www.peninsulavillage.com.au',
  'Stunning waterfront retirement village on Pittwater with marina and resort-style facilities.',
  'approved',
  'manual',
  true
),

-- 16. Harbison Burradoo - Burradoo (Southern Highlands)
(
  'Harbison Burradoo',
  'Harbison Care',
  '2 Charlotte Street',
  'Burradoo',
  '2576',
  'NSW',
  -34.5121,
  150.4169,
  'Mixed',
  'Mixed',
  350000,
  600000,
  400,
  650,
  'DMF',
  6,
  30,
  ARRAY['Library', 'Community hall', 'Garden', 'Workshop', 'BBQ area'],
  ARRAY['Aged care', 'Dementia care', '24/7 nursing', 'Respite care'],
  ARRAY['Garden club', 'Social events', 'Day trips', 'Art classes'],
  true,
  100,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '02 4868 6200',
  'burradoo@harbisoncare.org.au',
  'https://www.harbisoncare.org.au',
  'Beautiful retirement living in the scenic Southern Highlands near Bowral.',
  'approved',
  'manual',
  true
),

-- 17. Mayflower Brighton Le Sands - Brighton-Le-Sands
(
  'Mayflower Brighton Le Sands',
  'Mayflower Retirement Living',
  '1 Doris Street',
  'Brighton-Le-Sands',
  '2216',
  'NSW',
  -33.9624,
  151.1542,
  'Independent Living',
  'Independent',
  500000,
  850000,
  500,
  750,
  'DMF',
  5,
  25,
  ARRAY['Community lounge', 'Rooftop terrace', 'BBQ area', 'Library'],
  ARRAY['Emergency response', 'Optional home care'],
  ARRAY['Social events', 'Beach walks', 'Coffee mornings'],
  false,
  70,
  ARRAY['1 bedroom', '2 bedroom'],
  60,
  '02 9567 4400',
  'info@mayflower.org.au',
  'https://www.mayflower.org.au',
  'Beachside retirement living with bay views and easy access to cafes and parks.',
  'approved',
  'manual',
  true
),

-- 18. Wesley Gardens Belrose - Belrose
(
  'Wesley Gardens Belrose',
  'Wesley Mission',
  '7 Niangala Close',
  'Belrose',
  '2085',
  'NSW',
  -33.7363,
  151.2112,
  'Mixed',
  'Mixed',
  480000,
  820000,
  500,
  800,
  'DMF',
  6,
  30,
  ARRAY['Pool', 'Library', 'Chapel', 'Community hall', 'Garden', 'Workshop'],
  ARRAY['Aged care', '24/7 nursing', 'Memory support', 'Allied health'],
  ARRAY['Religious services', 'Exercise classes', 'Social events', 'Entertainment'],
  true,
  140,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '02 9451 3200',
  'belrose@wesleymission.org.au',
  'https://www.wesleymission.org.au',
  'Northern Beaches retirement village with Christian values and comprehensive care.',
  'approved',
  'manual',
  true
),

-- 19. Allity Aged Care Terrey Hills - Terrey Hills
(
  'Allity Aged Care Terrey Hills',
  'Allity',
  '8 Aumuna Road',
  'Terrey Hills',
  '2084',
  'NSW',
  -33.6881,
  151.2297,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2700,
  3700,
  NULL,
  NULL,
  NULL,
  ARRAY['Gardens', 'Cafe', 'Hair salon', 'Activities room', 'Cinema'],
  ARRAY['24/7 nursing', 'Dementia care', 'Palliative care', 'Physiotherapy'],
  ARRAY['Entertainment', 'Music therapy', 'Pet therapy', 'Garden activities'],
  false,
  85,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1800 225 489',
  'terreyhills@allity.com.au',
  'https://www.allity.com.au',
  'Peaceful aged care facility surrounded by bushland in the Northern Beaches.',
  'approved',
  'manual',
  true
),

-- 20. Arcare Aged Care Kanwal - Kanwal (Central Coast)
(
  'Arcare Aged Care Kanwal',
  'Arcare',
  '45 Blue Gum Road',
  'Kanwal',
  '2259',
  'NSW',
  -33.2671,
  151.5011,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2500,
  3500,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden', 'Cafe', 'Hair salon', 'Cinema', 'Activities room'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Allied health'],
  ARRAY['Entertainment', 'Exercise programs', 'Art and craft', 'Music therapy'],
  false,
  100,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 272 273',
  'kanwal@arcare.com.au',
  'https://www.arcare.com.au',
  'Modern aged care facility on the Central Coast with beautiful lake district location.',
  'approved',
  'manual',
  true
);

-- Verify insertion
SELECT COUNT(*) as nsw_villages_added FROM retirement_villages WHERE state = 'NSW' AND source = 'manual';
