-- Batch 4: VIC Retirement Villages (20 villages)
-- Execute this in Supabase SQL Editor
-- Adds villages across Greater Melbourne and regional Victoria

INSERT INTO retirement_villages (
  name,
  operator,
  location,
  suburb,
  postcode,
  state,
  latitude,
  longitude,
  village_type,
  care_level,
  entry_price_min,
  entry_price_max,
  monthly_fees_min,
  monthly_fees_max,
  dmf_structure,
  dmf_percentage,
  dmf_cap,
  amenities,
  care_services,
  activities,
  pet_friendly,
  total_units,
  bedrooms,
  age_restriction,
  contact_phone,
  contact_email,
  website,
  description,
  status,
  source,
  verified
) VALUES

-- 1. Ryman Healthcare Weary Dunlop - Wheelers Hill
(
  'Ryman Healthcare Weary Dunlop',
  'Ryman Healthcare',
  '574 Ferntree Gully Road',
  'Wheelers Hill',
  '3150',
  'VIC',
  -37.8987,
  145.1820,
  'Mixed',
  'Mixed',
  550000,
  950000,
  500,
  800,
  'DMF',
  5,
  25,
  ARRAY['Pool', 'Gym', 'Cinema', 'Library', 'Cafe', 'Hair salon', 'Bowling green', 'Workshop'],
  ARRAY['Aged care', 'Memory care', '24/7 nursing', 'Allied health services'],
  ARRAY['Swimming', 'Fitness classes', 'Bowls', 'Entertainment', 'Bus trips'],
  true,
  280,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  65,
  '03 9561 9131',
  'weary.dunlop@rymanhealthcare.com.au',
  'https://www.rymanhealthcare.com.au',
  'Premium retirement village in Wheelers Hill with resort-style facilities and comprehensive care.',
  'approved',
  'manual',
  true
),

-- 2. Regis Aged Care Brighton - Brighton
(
  'Regis Aged Care Brighton',
  'Regis Aged Care',
  '77 Carpenter Street',
  'Brighton',
  '3186',
  'VIC',
  -37.9087,
  145.0013,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2800,
  3800,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden terrace', 'Cafe', 'Hair salon', 'Activities room', 'Chapel'],
  ARRAY['24/7 nursing', 'Dementia care', 'Palliative care', 'Respite care'],
  ARRAY['Exercise programs', 'Entertainment', 'Pet therapy', 'Art activities'],
  false,
  95,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 998 100',
  'brighton@regis.com.au',
  'https://www.regis.com.au',
  'Premium aged care in bayside Brighton with excellent care standards and facilities.',
  'approved',
  'manual',
  true
),

-- 3. Uniting AgeWell Bill Crawford - Doncaster East
(
  'Uniting AgeWell Bill Crawford',
  'Uniting AgeWell',
  '30 Zwar Avenue',
  'Doncaster East',
  '3109',
  'VIC',
  -37.7848,
  145.1595,
  'Mixed',
  'Mixed',
  480000,
  820000,
  520,
  750,
  'DMF',
  6,
  30,
  ARRAY['Pool', 'Gym', 'Library', 'Community hall', 'Garden', 'Cinema', 'BBQ area'],
  ARRAY['Aged care', 'Memory support', '24/7 nursing', 'Physiotherapy'],
  ARRAY['Swimming', 'Exercise classes', 'Social events', 'Entertainment', 'Bus outings'],
  true,
  200,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '03 9841 8033',
  'billcrawford@unitingagewell.org',
  'https://www.unitingagewell.org',
  'Well-established retirement village in leafy Doncaster East with comprehensive facilities.',
  'approved',
  'manual',
  true
),

-- 4. Opal Aged Care South Yarra - South Yarra
(
  'Opal Aged Care South Yarra',
  'Opal Aged Care',
  '51 Walsh Street',
  'South Yarra',
  '3141',
  'VIC',
  -37.8401,
  144.9967,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  3200,
  4200,
  NULL,
  NULL,
  NULL,
  ARRAY['Rooftop garden', 'Cafe', 'Hair salon', 'Activities room', 'Lounge areas'],
  ARRAY['24/7 nursing', 'Dementia care', 'Palliative care', 'Allied health'],
  ARRAY['Entertainment', 'Music therapy', 'Art classes', 'Garden activities'],
  false,
  75,
  ARRAY['Shared', 'Single room'],
  NULL,
  '03 9866 5100',
  'southyarra@opalagecare.com.au',
  'https://www.opalagecare.com.au',
  'Premium inner-city aged care with excellent amenities and care standards.',
  'approved',
  'manual',
  true
),

-- 5. Estia Health Heidelberg - Heidelberg
(
  'Estia Health Heidelberg',
  'Estia Health',
  '82 Turnham Avenue',
  'Heidelberg',
  '3084',
  'VIC',
  -37.7549,
  145.0605,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2600,
  3600,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden areas', 'Cafe', 'Hair salon', 'Activities room', 'Chapel'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Physiotherapy'],
  ARRAY['Entertainment', 'Exercise programs', 'Art and craft', 'Pet therapy'],
  false,
  90,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 682 833',
  'heidelberg@estiahealth.com.au',
  'https://www.estiahealth.com.au',
  'Modern aged care facility close to Austin Hospital with excellent medical access.',
  'approved',
  'manual',
  true
),

-- 6. Respect Aged Care Templestowe - Templestowe
(
  'Respect Aged Care Templestowe',
  'Respect Aged Care',
  '79 James Street',
  'Templestowe',
  '3106',
  'VIC',
  -37.7599,
  145.1489,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2700,
  3700,
  NULL,
  NULL,
  NULL,
  ARRAY['Gardens', 'Cafe', 'Hair salon', 'Activities room', 'Cinema'],
  ARRAY['24/7 nursing', 'Dementia care', 'Palliative care', 'Allied health'],
  ARRAY['Group activities', 'Entertainment', 'Music therapy', 'Garden club'],
  false,
  100,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 144 144',
  'templestowe@respectcare.com.au',
  'https://www.respectcare.com.au',
  'Quality aged care in the Eastern suburbs with personalized care programs.',
  'approved',
  'manual',
  true
),

-- 7. Mecwacare Malvern - Malvern East
(
  'Mecwacare Malvern',
  'Mecwacare',
  '15 Hamilton Road',
  'Malvern East',
  '3145',
  'VIC',
  -37.8743,
  145.0651,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2900,
  3900,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden', 'Cafe', 'Hair salon', 'Activities room', 'Chapel'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Physiotherapy'],
  ARRAY['Entertainment', 'Exercise programs', 'Religious services', 'Art activities'],
  false,
  85,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 163 292',
  'malvern@mecwacare.org.au',
  'https://www.mecwacare.org.au',
  'Established aged care in leafy Malvern East with strong community connections.',
  'approved',
  'manual',
  true
),

-- 8. Lark Ellen Retirement Village - Glen Waverley
(
  'Lark Ellen Retirement Village',
  'Independent operator',
  '69 Kingsway',
  'Glen Waverley',
  '3150',
  'VIC',
  -37.8790,
  145.1632,
  'Independent Living',
  'Independent',
  400000,
  700000,
  450,
  650,
  'DMF',
  5,
  30,
  ARRAY['Community hall', 'Library', 'Garden', 'BBQ area', 'Workshop'],
  ARRAY['Emergency response', 'Weekly wellness checks'],
  ARRAY['Social events', 'Garden club', 'Card games', 'Bus trips'],
  true,
  90,
  ARRAY['2 bedroom', '3 bedroom'],
  55,
  '03 9803 2222',
  'info@larkellen.com.au',
  'https://www.larkellen.com.au',
  'Friendly retirement community in Glen Waverley with affordable living options.',
  'approved',
  'manual',
  true
),

-- 9. Domain Kew - Kew
(
  'Domain Kew',
  'Domain Principal Group',
  '27 Studley Park Road',
  'Kew',
  '3101',
  'VIC',
  -37.8035,
  145.0256,
  'Serviced Apartments',
  'Independent',
  750000,
  1300000,
  700,
  1100,
  'DMF',
  5,
  20,
  ARRAY['Concierge', 'Gym', 'Pool', 'Cinema', 'Dining room', 'Library', 'Terrace'],
  ARRAY['Emergency response', 'Optional home care', 'Concierge services'],
  ARRAY['Social dining', 'Entertainment', 'Cultural outings', 'Wine tastings'],
  false,
  120,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  65,
  '03 9851 9888',
  'kew@domainprincipal.com.au',
  'https://www.domainprincipal.com.au',
  'Luxury retirement living overlooking Yarra River in prestigious Kew.',
  'approved',
  'manual',
  true
),

-- 10. BaptistCare Gracehaven - Cheltenham
(
  'BaptistCare Gracehaven',
  'BaptistCare Victoria',
  '105 Park Road',
  'Cheltenham',
  '3192',
  'VIC',
  -37.9682,
  145.0507,
  'Mixed',
  'Mixed',
  450000,
  750000,
  480,
  720,
  'DMF',
  6,
  30,
  ARRAY['Chapel', 'Community hall', 'Garden', 'Library', 'BBQ area'],
  ARRAY['Aged care', 'Memory support', '24/7 nursing', 'Respite care'],
  ARRAY['Religious services', 'Social events', 'Entertainment', 'Garden club'],
  true,
  130,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '03 9584 8300',
  'gracehaven@baptistcarevic.org.au',
  'https://www.baptistcarevic.org.au',
  'Christian retirement village in bayside Cheltenham with caring community.',
  'approved',
  'manual',
  true
),

-- 11. BlueCross Apartments Wantirna - Wantirna South
(
  'BlueCross Apartments Wantirna',
  'BlueCross',
  '244 Stud Road',
  'Wantirna South',
  '3152',
  'VIC',
  -37.8826,
  145.2298,
  'Serviced Apartments',
  'Independent',
  500000,
  850000,
  550,
  800,
  'DMF',
  5,
  25,
  ARRAY['Lounge', 'Library', 'Garden', 'BBQ area', 'Guest suites'],
  ARRAY['Emergency response', 'Optional home care'],
  ARRAY['Social activities', 'Coffee mornings', 'Entertainment'],
  false,
  100,
  ARRAY['1 bedroom', '2 bedroom'],
  60,
  '03 9801 4444',
  'wantirna@bluecross.com.au',
  'https://www.bluecross.com.au',
  'Modern retirement apartments in Knox with easy access to Westfield Knox.',
  'approved',
  'manual',
  true
),

-- 12. Mercy Place Parkville - Parkville
(
  'Mercy Place Parkville',
  'Mercy Health',
  '7 Flemington Road',
  'Parkville',
  '3052',
  'VIC',
  -37.7927,
  144.9548,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  3000,
  4000,
  NULL,
  NULL,
  NULL,
  ARRAY['Chapel', 'Garden', 'Cafe', 'Hair salon', 'Activities room'],
  ARRAY['24/7 nursing', 'Dementia care', 'Palliative care', 'Allied health'],
  ARRAY['Mass', 'Entertainment', 'Music therapy', 'Art activities'],
  false,
  80,
  ARRAY['Shared', 'Single room'],
  NULL,
  '03 8416 7700',
  'parkville@mercyhealth.com.au',
  'https://www.mercyhealth.com.au',
  'Catholic aged care next to major hospitals with excellent medical access.',
  'approved',
  'manual',
  true
),

-- 13. Japara The Vines - Werribee
(
  'Japara The Vines',
  'Japara Healthcare',
  '450 Derrimut Road',
  'Hoppers Crossing',
  '3029',
  'VIC',
  -37.8760,
  144.7011,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2500,
  3500,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden', 'Cafe', 'Hair salon', 'Activities room', 'Cinema'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Physiotherapy'],
  ARRAY['Entertainment', 'Exercise programs', 'Art and craft', 'Music therapy'],
  false,
  120,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 522 272',
  'thevines@japara.com.au',
  'https://www.japara.com.au',
  'Modern aged care facility in growing Western suburbs with comprehensive care.',
  'approved',
  'manual',
  true
),

-- 14. Villa Maria Catholic Homes - Bundoora
(
  'Villa Maria Catholic Homes',
  'Villa Maria Catholic Homes',
  '14 Burgundy Street',
  'Bundoora',
  '3083',
  'VIC',
  -37.6980,
  145.0604,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2700,
  3700,
  NULL,
  NULL,
  NULL,
  ARRAY['Chapel', 'Garden', 'Cafe', 'Hair salon', 'Activities room'],
  ARRAY['24/7 nursing', 'Dementia care', 'Palliative care', 'Respite care'],
  ARRAY['Mass and prayer', 'Entertainment', 'Music therapy', 'Pet therapy'],
  false,
  110,
  ARRAY['Shared', 'Single room'],
  NULL,
  '03 9467 4444',
  'info@vmch.com.au',
  'https://www.vmch.com.au',
  'Catholic aged care in Bundoora with strong values-based care approach.',
  'approved',
  'manual',
  true
),

-- 15. Earlswood Village - Croydon Hills
(
  'Earlswood Village',
  'Arcare',
  '2-8 Earlswood Drive',
  'Croydon Hills',
  '3136',
  'VIC',
  -37.7835,
  145.2780,
  'Mixed',
  'Mixed',
  420000,
  720000,
  470,
  700,
  'DMF',
  6,
  30,
  ARRAY['Pool', 'Gym', 'Library', 'Community hall', 'Garden', 'Workshop'],
  ARRAY['Aged care', 'Memory support', '24/7 nursing', 'Allied health'],
  ARRAY['Swimming', 'Exercise classes', 'Social events', 'Entertainment'],
  true,
  150,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '03 9724 1200',
  'earlswood@arcare.com.au',
  'https://www.arcare.com.au',
  'Established retirement village in the Yarra Ranges with beautiful surroundings.',
  'approved',
  'manual',
  true
),

-- 16. Glendale Aged Care - Werribee
(
  'Glendale Aged Care',
  'Bupa Aged Care',
  '49 Tarneit Road',
  'Werribee',
  '3030',
  'VIC',
  -37.8972,
  144.6680,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2600,
  3600,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden', 'Cafe', 'Hair salon', 'Activities room', 'Outdoor areas'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Allied health'],
  ARRAY['Entertainment', 'Exercise programs', 'Garden activities', 'Pet therapy'],
  false,
  95,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 282 237',
  'werribee@bupa.com.au',
  'https://www.bupa.com.au/aged-care',
  'Quality aged care in Werribee with professional staff and modern facilities.',
  'approved',
  'manual',
  true
),

-- 17. Arcare Sydenham - Sydenham
(
  'Arcare Sydenham',
  'Arcare',
  '32-42 Overland Drive',
  'Sydenham',
  '3037',
  'VIC',
  -37.6985,
  144.7640,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2500,
  3500,
  NULL,
  NULL,
  NULL,
  ARRAY['Garden', 'Cafe', 'Hair salon', 'Cinema', 'Activities room'],
  ARRAY['24/7 nursing', 'Dementia care', 'Respite care', 'Physiotherapy'],
  ARRAY['Entertainment', 'Exercise programs', 'Art and craft', 'Music therapy'],
  false,
  110,
  ARRAY['Shared', 'Single room'],
  NULL,
  '1300 272 273',
  'sydenham@arcare.com.au',
  'https://www.arcare.com.au',
  'Purpose-built aged care facility in growing Northwest with modern amenities.',
  'approved',
  'manual',
  true
),

-- 18. Mercy Place Fernhill - Niddrie
(
  'Mercy Place Fernhill',
  'Mercy Health',
  '170 Hoffmans Road',
  'Niddrie',
  '3042',
  'VIC',
  -37.7331,
  144.8987,
  'Aged Care Facility',
  'Assisted Living',
  NULL,
  NULL,
  2800,
  3800,
  NULL,
  NULL,
  NULL,
  ARRAY['Chapel', 'Garden', 'Cafe', 'Hair salon', 'Activities room'],
  ARRAY['24/7 nursing', 'Dementia care', 'Palliative care', 'Allied health'],
  ARRAY['Mass', 'Entertainment', 'Music therapy', 'Garden activities'],
  false,
  90,
  ARRAY['Shared', 'Single room'],
  NULL,
  '03 9379 8100',
  'fernhill@mercyhealth.com.au',
  'https://www.mercyhealth.com.au',
  'Catholic aged care in Niddrie with warm, compassionate care environment.',
  'approved',
  'manual',
  true
),

-- 19. IRT Tarrawarra Village - Lilydale
(
  'IRT Tarrawarra Village',
  'IRT Living',
  '94 Maroondah Highway',
  'Lilydale',
  '3140',
  'VIC',
  -37.7556,
  145.3456,
  'Mixed',
  'Mixed',
  380000,
  650000,
  420,
  650,
  'DMF',
  6,
  30,
  ARRAY['Pool', 'Library', 'Community hall', 'Garden', 'BBQ area', 'Workshop'],
  ARRAY['Aged care', '24/7 nursing', 'Memory support', 'Allied health'],
  ARRAY['Swimming', 'Exercise classes', 'Social events', 'Bus outings'],
  true,
  140,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '1300 768 096',
  'tarrawarra@irt.org.au',
  'https://www.irt.org.au',
  'Scenic retirement village in the Yarra Valley with mountain views and wineries nearby.',
  'approved',
  'manual',
  true
),

-- 20. Benetas Village - Heidelberg West
(
  'Benetas Village',
  'Benetas',
  '27 Bell Street',
  'Heidelberg West',
  '3081',
  'VIC',
  -37.7387,
  145.0505,
  'Mixed',
  'Mixed',
  400000,
  700000,
  450,
  700,
  'DMF',
  6,
  30,
  ARRAY['Library', 'Community hall', 'Garden', 'BBQ area', 'Workshop'],
  ARRAY['Aged care', 'Memory support', '24/7 nursing', 'Respite care'],
  ARRAY['Social events', 'Entertainment', 'Garden club', 'Exercise programs'],
  true,
  120,
  ARRAY['1 bedroom', '2 bedroom', '3 bedroom'],
  55,
  '1300 236 382',
  'heidelberg@benetas.com.au',
  'https://www.benetas.com.au',
  'Established retirement village with strong community focus and affordable options.',
  'approved',
  'manual',
  true
);

-- Verify insertion
SELECT COUNT(*) as vic_villages_added FROM retirement_villages WHERE state = 'VIC' AND source = 'manual';
