-- Batch 12: 50 Additional Retirement Villages
-- Brings total to 505 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW (15 villages)
('Lendlease Retirement Living Macquarie Park', 'Lendlease', '125 Herring Road', 'Macquarie Park', 'NSW', '2113', -33.7783, 151.1217, 'independent', 'independent', 645000, 1025000, 640, 980, 24, '["pool", "gym", "cinema", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 154, 55, '02 9888 1501', 'macquariepark@lendlease.com', 'https://lendlease.com', 'Premium North Shore retirement. Pool, gym, cinema, and university nearby.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Caloundra', 'Stockland', '45 Bowman Road', 'Caloundra', 'QLD', '4551', -26.7967, 153.1283, 'independent', 'independent', 425000, 685000, 440, 680, 28, '["pool", "library", "common-room", "bbq-area", "workshop"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 142, 55, '07 5491 1501', 'caloundra@stockland.com.au', 'https://stockland.com', 'Sunshine Coast retirement. Pool and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Strathfield', 'Regis Aged Care', '88 Homebush Road', 'Strathfield', 'NSW', '2135', -33.8783, 151.0917, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '02 9746 1501', 'strathfield@regis.com.au', 'https://regis.com.au', 'Inner west Sydney aged care. Pool, gardens, and train access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Opal Aged Care Parramatta', 'Opal Aged Care', '15 Church Street', 'Parramatta', 'NSW', '2150', -33.8150, 151.0033, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '02 9635 1501', 'parramatta@opalcare.com.au', 'https://opalcare.com.au', 'Central western Sydney aged care. Gardens, cafe, and CBD access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Dubbo', 'Estia Health', '125 Macquarie Street', 'Dubbo', 'NSW', '2830', -32.2567, 148.6050, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '02 6882 1501', 'dubbo@estiahealth.com.au', 'https://estiahealth.com.au', 'Central West NSW aged care. Gardens and regional city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Cabramatta', 'Arcare', '45 John Street', 'Cabramatta', 'NSW', '2166', -33.8950, 150.9367, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '02 9726 1501', 'cabramatta@arcare.com.au', 'https://arcare.com.au', 'Southwest Sydney aged care. Cinema, gardens, and multicultural community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('BaptistCare Morven Gardens', 'BaptistCare NSW & ACT', '88 Windsor Road', 'Baulkham Hills', 'NSW', '2153', -33.7617, 150.9883, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '02 9639 1501', 'morvengardens@baptistcare.org.au', 'https://baptistcare.org.au', 'Hills District aged care. Pool, chapel, gardens, and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Orange', 'Blue Care', '15 Summer Street', 'Orange', 'NSW', '2800', -33.2833, 149.0983, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '02 6361 1501', 'orange@bluecare.org.au', 'https://bluecare.org.au', 'Central West tablelands aged care. Gardens and heritage city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Healthcare Lewisham', 'Catholic Healthcare', '125 Parramatta Road', 'Lewisham', 'NSW', '2049', -33.8950, 151.1450, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '02 9560 1501', 'lewisham@catholichealthcare.com.au', 'https://catholichealthcare.com.au', 'Inner west Sydney aged care. Chapel, cafe, and close to city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('HammondCare Sutherland', 'HammondCare', '45 Kingsway', 'Sutherland', 'NSW', '2232', -34.0317, 151.0583, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '02 9521 1501', 'sutherland@hammond.com.au', 'https://hammond.com.au', 'Sutherland Shire aged care. Gardens and specialist dementia care.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Uniting Wesley Gardens', 'Uniting NSW & ACT', '88 Belgrave Street', 'Kogarah', 'NSW', '2217', -33.9650, 151.1333, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '02 9587 1501', 'wesleygardens@uniting.org', 'https://uniting.org', 'St George aged care. Pool, gardens, and close to train station.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Carinya', 'Japara Healthcare', '15 Redhead Road', 'Hallidays Point', 'NSW', '2430', -32.0883, 152.5150, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '02 6559 1501', 'carinya@japara.com.au', 'https://japara.com.au', 'Mid North Coast aged care. Pool, gardens, and near beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Whiddon Grafton', 'Whiddon Group', '125 Prince Street', 'Grafton', 'NSW', '2460', -29.6883, 152.9333, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '02 6642 1501', 'grafton@whiddon.com.au', 'https://whiddon.com.au', 'Clarence Valley aged care. Gardens and close to Clarence River.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Ulladulla', 'Allity', '45 Princes Highway', 'Ulladulla', 'NSW', '2539', -35.3583, 150.4717, 'aged-care', 'aged-care', 335000, 535000, 370, 570, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '02 4455 1501', 'ulladulla@allity.com.au', 'https://allity.com.au', 'South Coast aged care. Gardens and close to harbour and beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('RSL LifeCare Narara', 'RSL LifeCare', '88 Pacific Highway', 'Narara', 'NSW', '2250', -33.3983, 151.3350, 'independent', 'independent', 365000, 585000, 380, 580, 32, '["bowling-green", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 118, 55, '02 4329 1501', 'narara@rsllifecare.org.au', 'https://rsllifecare.org.au', 'Central Coast retirement. Bowling green and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC (12 villages)
('Regis Aged Care Doncaster', 'Regis Aged Care', '125 Doncaster Road', 'Doncaster', 'VIC', '3108', -37.7817, 145.1250, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 124, 55, '03 9848 4501', 'doncaster@regis.com.au', 'https://regis.com.au', 'Premium eastern suburbs aged care. Pool, gardens, and Westfield nearby.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Traralgon', 'Estia Health', '45 Franklin Street', 'Traralgon', 'VIC', '3844', -38.1950, 146.5417, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '03 5174 4501', 'traralgon@estiahealth.com.au', 'https://estiahealth.com.au', 'Gippsland aged care. Gardens and close to regional city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Burnside', 'Arcare', '88 Toorak Road', 'Hawthorn East', 'VIC', '3123', -37.8333, 145.0500, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 136, 55, '03 9882 4501', 'burnside@arcare.com.au', 'https://arcare.com.au', 'Premium inner east aged care. Pool, gym, cinema, and Toorak Road dining.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bupa Aged Care Dingley Village', 'Bupa', '15 Centre Dandenong Road', 'Dingley Village', 'VIC', '3172', -37.9883, 145.1167, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '03 9551 4501', 'dingleyvillage@bupa.com.au', 'https://bupa.com.au', 'Southeast Melbourne aged care. Gardens and close to shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Melton', 'Bolton Clarke', '125 High Street', 'Melton', 'VIC', '3337', -37.6833, 144.5833, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '03 9743 4501', 'melton@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Western growth corridor aged care. Gardens and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Warrnambool', 'Opal Aged Care', '45 Lava Street', 'Warrnambool', 'VIC', '3280', -38.3817, 142.4850, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '03 5561 4501', 'warrnambool@opalcare.com.au', 'https://opalcare.com.au', 'Southwest coastal aged care. Pool, gardens, and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Box Hill', 'Regis Aged Care', '88 Station Street', 'Box Hill', 'VIC', '3128', -37.8183, 145.1233, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '03 9899 4501', 'boxhill@regis.com.au', 'https://regis.com.au', 'Eastern suburbs aged care. Pool, gardens, and train to city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Shepparton', 'Estia Health', '15 Wyndham Street', 'Shepparton', 'VIC', '3630', -36.3800, 145.3983, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '03 5821 4501', 'shepparton@estiahealth.com.au', 'https://estiahealth.com.au', 'Goulburn Valley aged care. Gardens and regional city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas Heidelberg', 'Benetas', '125 Waterdale Road', 'Heidelberg', 'VIC', '3084', -37.7467, 145.0567, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '03 9457 4501', 'heidelberg@benetas.com.au', 'https://benetas.com.au', 'Northeast Melbourne aged care. Gardens, cafe, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Anglesea', 'Japara Healthcare', '45 Noble Street', 'Anglesea', 'VIC', '3230', -38.4100, 144.1867, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '03 5263 4501', 'anglesea@japara.com.au', 'https://japara.com.au', 'Great Ocean Road aged care. Pool, gardens, and coastal lifestyle.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Wangaratta', 'Mercy Health', '88 Docker Street', 'Wangaratta', 'VIC', '3677', -36.3583, 146.3183, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '03 5721 4501', 'wangaratta@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Northeast Victoria aged care. Chapel, gardens, and wine region.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ryman Healthcare Nellie Melba', 'Ryman Healthcare', '15 Stud Road', 'Wheelers Hill', 'VIC', '3150', -37.9117, 145.1917, 'aged-care', 'aged-care', 505000, 945000, 540, 920, 28, '["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 246, 55, '03 9561 4501', 'nelliemelba@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Large premium southeast retirement village. Pool, gym, bowling green, cinema.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- QLD (12 villages)
('Regis Aged Care Coorparoo', 'Regis Aged Care', '125 Old Cleveland Road', 'Coorparoo', 'QLD', '4151', -27.4950, 153.0617, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '07 3397 2501', 'coorparoo@regis.com.au', 'https://regis.com.au', 'Southeast Brisbane aged care. Gardens, cafe, and bus routes.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Ipswich West', 'Blue Care', '45 Brisbane Street', 'Ipswich', 'QLD', '4305', -27.6150, 152.7600, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '07 3281 2501', 'ipswichwest@bluecare.org.au', 'https://bluecare.org.au', 'Southwest Brisbane region aged care. Gardens and historic city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Robina', 'Opal Aged Care', '88 Robina Town Centre Drive', 'Robina', 'QLD', '4226', -28.0717, 153.3800, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '07 5575 2501', 'robina@opalcare.com.au', 'https://opalcare.com.au', 'Gold Coast premium aged care. Pool, gardens, and shopping center access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('TriCare Aged Care Runaway Bay', 'TriCare', '15 Bayview Street', 'Runaway Bay', 'QLD', '4216', -27.9083, 153.3800, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '07 5537 2501', 'runawaybay@tricare.com.au', 'https://tricare.com.au', 'Gold Coast waterfront aged care. Pool, gardens, and marina access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Indooroopilly', 'Estia Health', '125 Moggill Road', 'Indooroopilly', 'QLD', '4068', -27.4983, 152.9717, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '07 3878 2501', 'indooroopilly@estiahealth.com.au', 'https://estiahealth.com.au', 'Western Brisbane premium aged care. Pool, gardens, and shopping center.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bolton Clarke Redcliffe', 'Bolton Clarke', '45 Anzac Avenue', 'Redcliffe', 'QLD', '4020', -27.2283, 153.1100, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '07 3284 2501', 'redcliffe@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Moreton Bay peninsula aged care. Gardens and waterfront access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Bundaberg', 'Adventist Aged Care', '88 Barolin Street', 'Bundaberg', 'QLD', '4670', -24.8650, 152.3483, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["pool", "library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '07 4153 2501', 'bundaberg@adventistcare.org.au', 'https://adventistcare.org.au', 'Central Queensland coastal aged care. Pool, chapel, gardens.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ozcare Gladstone', 'Ozcare', '15 Goondoon Street', 'Gladstone', 'QLD', '4680', -23.8450, 151.2550, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '07 4972 2501', 'gladstone@ozcare.org.au', 'https://ozcare.org.au', 'Central Queensland port city aged care. Chapel, gardens.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Karinya Place', 'Carinity', '125 Hamilton Road', 'Wavell Heights', 'QLD', '4012', -27.3950, 153.0450, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '07 3266 2501', 'karinyaplace@carinity.org.au', 'https://carinity.org.au', 'North Brisbane aged care. Chapel, gardens, and community focus.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Varsity Lakes', 'Regis Aged Care', '45 Varsity Parade', 'Varsity Lakes', 'QLD', '4227', -28.0933, 153.4017, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '07 5585 2501', 'varsitylakes@regis.com.au', 'https://regis.com.au', 'Gold Coast aged care. Pool, gardens, and lake lifestyle.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Mackay', 'Allity', '88 Sydney Street', 'Mackay', 'QLD', '4740', -21.1400, 149.1833, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '07 4957 2501', 'mackay@allity.com.au', 'https://allity.com.au', 'North Queensland aged care. Pool, gardens, and sugar city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Carseldine', 'Southern Cross Care QLD', '125 Beams Road', 'Carseldine', 'QLD', '4034', -27.3467, 152.9800, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 3263 2501', 'carseldine@scrosscc.com.au', 'https://scrosscc.com.au', 'North Brisbane aged care. Pool, gardens, and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- SA (5 villages)
('Regis Aged Care Kensington Park', 'Regis Aged Care', '88 Kensington Road', 'Kensington Park', 'SA', '5068', -34.9217, 138.6450, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '08 8431 3501', 'kensingtonpark@regis.com.au', 'https://regis.com.au', 'Inner east Adelaide aged care. Gardens, cafe, and village atmosphere.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Mount Barker', 'Estia Health', '15 Gawler Street', 'Mount Barker', 'SA', '5251', -35.0717, 138.8717, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '08 8391 3501', 'mtbarker@estiahealth.com.au', 'https://estiahealth.com.au', 'Adelaide Hills aged care. Gardens and close to town center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Port Adelaide', 'ACH Group', '125 Commercial Road', 'Port Adelaide', 'SA', '5015', -34.8483, 138.5067, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '08 8447 3501', 'portadelaide@ach.org.au', 'https://ach.org.au', 'Northwestern Adelaide aged care. Gardens and historic port area.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Whyalla', 'Southern Cross Care SA', '45 Nicolson Avenue', 'Whyalla', 'SA', '5600', -33.0333, 137.5167, 'aged-care', 'aged-care', 235000, 385000, 280, 460, 36, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 68, 55, '08 8645 3501', 'whyalla@scsa.org.au', 'https://scsa.org.au', 'Spencer Gulf aged care. Gardens and industrial city heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Cowandilla', 'Japara Healthcare', '88 Henley Beach Road', 'Mile End', 'SA', '5031', -34.9267, 138.5683, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '08 8234 3501', 'cowandilla@japara.com.au', 'https://japara.com.au', 'Inner western Adelaide aged care. Gardens, cafe, and tram access.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- WA (4 villages)
('Regis Aged Care Nedlands', 'Regis Aged Care', '125 Stirling Highway', 'Nedlands', 'WA', '6009', -31.9800, 115.8067, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 120, 55, '08 9386 4501', 'nedlands@regis.com.au', 'https://regis.com.au', 'Premium western Perth aged care. Pool, gardens, and river access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bethanie Esprit Menora', 'Bethanie Group', '45 Alexander Drive', 'Menora', 'WA', '6050', -31.9100, 115.8717, 'independent', 'independent', 465000, 745000, 480, 740, 28, '["pool", "gym", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 132, 55, '08 9370 4501', 'menora@bethanie.com.au', 'https://bethanie.com.au', 'Inner Perth retirement. Pool, gym, and close to city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Bunbury', 'Amana Living', '88 Spencer Street', 'Bunbury', 'WA', '6230', -33.3267, 115.6400, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '08 9721 4501', 'bunbury@amana.com.au', 'https://amana.com.au', 'Southwest WA aged care. Gardens and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Geraldton', 'Opal Aged Care', '15 Chapman Road', 'Geraldton', 'WA', '6530', -28.7767, 114.6150, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '08 9921 4501', 'geraldton@opalcare.com.au', 'https://opalcare.com.au', 'Mid-west coastal aged care. Pool, gardens, and fishing port.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Estia Health Launceston', 'Estia Health', '125 Charles Street', 'Launceston', 'TAS', '7250', -41.4367, 147.1400, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '03 6334 9501', 'launceston@estiahealth.com.au', 'https://estiahealth.com.au', 'Northern Tasmania aged care. Gardens and close to city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Aged Care Monash', 'Goodwin', '45 Tench Street', 'Monash', 'ACT', '2904', -35.4150, 149.0933, 'aged-care', 'aged-care', 465000, 715000, 500, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '02 6292 6501', 'monash@goodwin.org.au', 'https://goodwin.org.au', 'South Canberra aged care. Gardens, cafe, and close to Tuggeranong.', 'approved', 'seed_data', true, false, NOW(), NOW());
