-- Batch 15: 50 Additional Retirement Villages
-- Brings total to 655 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW (15 villages)
('Aveo Freedom Macquarie Park', 'Aveo Group', '88 Herring Road', 'Macquarie Park', 'NSW', '2113', -33.7783, 151.1200, 'independent', 'independent', 585000, 895000, 580, 880, 28, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 156, 55, '02 9888 2001', 'macquariepark@aveo.com.au', 'https://aveo.com.au', 'North Sydney retirement hub. Pool, gym, cinema, near university and offices.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Forster', 'Stockland', '45 The Lakes Way', 'Forster', 'NSW', '2428', -32.1817, 152.5150, 'independent', 'independent', 425000, 685000, 420, 660, 30, '[\"pool\", \"bowling-green\", \"library\", \"common-room\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 128, 55, '02 6555 2001', 'forster@stockland.com.au', 'https://stockland.com', 'Lakes coastal retirement. Pool, bowling green, and pristine beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Lendlease Retirement Living Newtown', 'Lendlease', '125 King Street', 'Newtown', 'NSW', '2042', -33.8950, 151.1783, 'independent', 'independent', 625000, 985000, 620, 940, 26, '[\"gym\", \"library\", \"common-room\", \"rooftop-terrace\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 142, 60, '02 9519 2001', 'newtown@lendlease.com', 'https://lendlease.com', 'Inner West urban retirement. Gym, rooftop terrace, cafe culture.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Anglicare Retirement Living Dubbo', 'Anglicare NSW South', '15 Brisbane Street', 'Dubbo', 'NSW', '2830', -32.2567, 148.6017, 'independent', 'independent', 285000, 465000, 320, 510, 34, '[\"library\", \"common-room\", \"chapel\", \"garden\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 94, 55, '02 6885 2001', 'dubbo@anglicare.com.au', 'https://anglicare.com.au', 'Central West retirement. Chapel, gardens, and regional city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Uniting Retirement Living Wollongong', 'Uniting NSW & ACT', '88 Crown Street', 'Wollongong', 'NSW', '2500', -34.4250, 150.8933, 'independent', 'independent', 445000, 685000, 440, 680, 30, '[\"pool\", \"library\", \"common-room\", \"garden\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 118, 55, '02 4228 2001', 'wollongong@uniting.org', 'https://uniting.org', 'Illawarra coastal retirement. Pool, gardens, and beaches nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Retirement Living Chatswood', 'Regis Aged Care', '45 Pacific Highway', 'Chatswood', 'NSW', '2067', -33.7983, 151.1817, 'independent', 'independent', 685000, 1085000, 680, 1060, 24, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"restaurant\", \"concierge\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 164, 60, '02 9411 2001', 'chatswood@regis.com.au', 'https://regis.com.au', 'Premium North Shore retirement. Pool, gym, cinema, restaurant, train hub.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('BaptistCare Retirement Living Orange', 'BaptistCare NSW & ACT', '125 Anson Street', 'Orange', 'NSW', '2800', -33.2833, 149.0983, 'independent', 'independent', 325000, 525000, 340, 540, 32, '[\"library\", \"common-room\", \"chapel\", \"garden\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 102, 55, '02 6361 2001', 'orange@baptistcare.org.au', 'https://baptistcare.org.au', 'Central Tablelands retirement. Chapel, gardens, and cool climate.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('IRT Retirement Villages Bowral', 'IRT Group', '15 Bong Bong Street', 'Bowral', 'NSW', '2576', -34.4783, 150.4183, 'independent', 'independent', 485000, 775000, 480, 760, 28, '[\"pool\", \"bowling-green\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 124, 55, '02 4861 2001', 'bowral@irt.org.au', 'https://irt.org.au', 'Southern Highlands retirement. Pool, bowling green, cool climate charm.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('RSL LifeCare Retirement Villages Dubbo', 'RSL LifeCare', '88 Macquarie Street', 'Dubbo', 'NSW', '2830', -32.2500, 148.6050, 'independent', 'independent', 305000, 505000, 330, 530, 32, '[\"bowling-green\", \"library\", \"common-room\", \"bbq-area\", \"workshop\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 108, 55, '02 6882 2001', 'dubborsL@rsllifecare.org.au', 'https://rsllifecare.org.au', 'Central West retirement. Bowling green, workshop, and regional hub.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Cooranbong', 'Adventist Aged Care', '45 Avondale Road', 'Cooranbong', 'NSW', '2265', -33.0783, 151.4500, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '[\"pool\", \"library\", \"common-room\", \"chapel\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '02 4977 2001', 'cooranbong@adventistcare.org.au', 'https://adventistcare.org.au', 'Hunter Valley aged care. Pool, chapel, lakeside setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Broken Hill', 'Southern Cross Care NSW & ACT', '125 Argent Street', 'Broken Hill', 'NSW', '2880', -31.9583, 141.4650, 'aged-care', 'aged-care', 235000, 395000, 280, 460, 36, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 68, 55, '08 8088 2001', 'brokenhill@scrosscc.com.au', 'https://scrosscc.com.au', 'Far West aged care. Gardens and outback mining heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Albury', 'Mercy Health', '15 Dean Street', 'Albury', 'NSW', '2640', -36.0817, 146.9167, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '[\"library\", \"common-room\", \"chapel\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '02 6021 2001', 'albury@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Murray border aged care. Chapel, gardens, and riverside city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Healthcare Kulnura', 'Japara Healthcare', '88 Woy Woy Road', 'Woy Woy', 'NSW', '2256', -33.4850, 151.3233, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '02 4344 2001', 'woywoy@japara.com.au', 'https://japara.com.au', 'Central Coast waterside aged care. Pool, gardens, and channel views.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Taree', 'Allity', '125 Victoria Street', 'Taree', 'NSW', '2430', -31.9083, 152.4550, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '02 6552 2001', 'taree@allity.com.au', 'https://allity.com.au', 'Mid North Coast aged care. Gardens and Manning River setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Whiddon Group Tamworth', 'Whiddon Group', '45 Peel Street', 'Tamworth', 'NSW', '2340', -31.0917, 150.9300, 'aged-care', 'aged-care', 295000, 475000, 340, 530, 32, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '02 6766 2001', 'tamworth@whiddon.com.au', 'https://whiddon.com.au', 'New England aged care. Gardens and country music capital.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC (12 villages)
('Aveo Retirement Living Werribee', 'Aveo Group', '88 Watton Street', 'Werribee', 'VIC', '3030', -37.9017, 144.6617, 'independent', 'independent', 385000, 625000, 380, 620, 30, '[\"pool\", \"gym\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 134, 55, '03 9741 3001', 'werribee@aveo.com.au', 'https://aveo.com.au', 'Southwest growth area retirement. Pool, gym, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Stockland Retirement Living Mornington', 'Stockland', '125 Main Street', 'Mornington', 'VIC', '3931', -38.2183, 145.0383, 'independent', 'independent', 525000, 845000, 520, 840, 28, '[\"pool\", \"bowling-green\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 148, 55, '03 5975 3001', 'mornington@stockland.com.au', 'https://stockland.com', 'Peninsula seaside retirement. Pool, bowling green, and beaches.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Lendlease Retirement Living Camberwell', 'Lendlease', '45 Burke Road', 'Camberwell', 'VIC', '3124', -37.8317, 145.0583, 'independent', 'independent', 605000, 945000, 600, 920, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"restaurant\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 156, 60, '03 9889 3001', 'camberwell@lendlease.com', 'https://lendlease.com', 'Premium east Melbourne retirement. Pool, gym, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Ryman Healthcare Nellie Melba', 'Ryman Healthcare', '88 Plenty Road', 'Bundoora', 'VIC', '3083', -37.6983, 145.0583, 'aged-care', 'aged-care', 485000, 895000, 520, 880, 28, '[\"pool\", \"gym\", \"bowling-green\", \"cinema\", \"library\", \"common-room\", \"restaurant\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\", \"dementia-care\"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 238, 55, '03 9467 3001', 'nelliemelba@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Large premium village. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Aged Care Shepparton', 'Regis Aged Care', '15 Wyndham Street', 'Shepparton', 'VIC', '3630', -36.3817, 145.3983, 'aged-care', 'aged-care', 315000, 515000, 350, 550, 32, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '03 5831 3001', 'shepparton@regis.com.au', 'https://regis.com.au', 'Goulburn Valley aged care. Gardens and regional city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Warrnambool', 'Estia Health', '125 Raglan Parade', 'Warrnambool', 'VIC', '3280', -38.3817, 142.4850, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '03 5562 3001', 'warrnambool@estiahealth.com.au', 'https://estiahealth.com.au', 'Southwest coastal aged care. Gardens and whale watching city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bupa Aged Care Wodonga', 'Bupa', '45 High Street', 'Wodonga', 'VIC', '3690', -36.1217, 146.8883, 'aged-care', 'aged-care', 335000, 535000, 370, 570, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 90, 55, '02 6024 3001', 'wodonga@bupa.com.au', 'https://bupa.com.au', 'Border twin city aged care. Gardens and close to Murray River.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Footscray', 'Bolton Clarke', '88 Barkly Street', 'Footscray', 'VIC', '3011', -37.7983, 144.9000, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '03 9687 3001', 'footscray@boltonclarke.com.au', 'https://boltonclarke.com.au', 'West Melbourne aged care. Gardens, cafe, and multicultural hub.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Aged Care Burnside', 'Arcare', '125 Toorak Road', 'South Yarra', 'VIC', '3141', -37.8400, 145.0083, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\", \"dementia-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 136, 55, '03 9867 3001', 'burnside@arcare.com.au', 'https://arcare.com.au', 'Premium inner city aged care. Pool, gym, cinema, near Botanical Gardens.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Benetas Aged Care Wantirna', 'Benetas', '15 Burwood Highway', 'Wantirna', 'VIC', '3152', -37.8517, 145.2283, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '03 9801 3001', 'wantirna@benetas.com.au', 'https://benetas.com.au', 'Eastern suburbs aged care. Gardens and shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Mildura', 'Opal Aged Care', '88 Deakin Avenue', 'Mildura', 'VIC', '3500', -34.1867, 142.1617, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '[\"pool\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 80, 55, '03 5021 3001', 'mildura@opalcare.com.au', 'https://opalcare.com.au', 'Sunraysia aged care. Pool, gardens, and Murray River vineyards.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Healthcare Wantirna', 'Japara Healthcare', '125 Mountain Highway', 'Wantirna', 'VIC', '3152', -37.8550, 145.2217, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '03 9800 3001', 'wantirnajapara@japara.com.au', 'https://japara.com.au', 'Eastern Melbourne aged care. Gardens, cafe, and Knox shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- QLD (12 villages)
('Aveo Retirement Living Robina', 'Aveo Group', '88 Scottsdale Drive', 'Robina', 'QLD', '4226', -28.0783, 153.3783, 'independent', 'independent', 465000, 745000, 460, 740, 28, '[\"pool\", \"gym\", \"library\", \"common-room\", \"bbq-area\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 142, 55, '07 5575 4001', 'robina@aveo.com.au', 'https://aveo.com.au', 'Gold Coast retirement. Pool, gym, near shopping and hospital.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Stockland Retirement Living Hervey Bay', 'Stockland', '125 Boat Harbour Drive', 'Hervey Bay', 'QLD', '4655', -25.2883, 152.8450, 'independent', 'independent', 385000, 625000, 380, 620, 30, '[\"pool\", \"bowling-green\", \"library\", \"common-room\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 136, 55, '07 4125 4001', 'herveybay@stockland.com.au', 'https://stockland.com', 'Fraser Coast retirement. Pool, bowling green, whale watching hub.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Lendlease Retirement Living Sunshine Coast', 'Lendlease', '45 Nicklin Way', 'Warana', 'QLD', '4575', -26.7217, 153.1283, 'independent', 'independent', 525000, 845000, 520, 840, 28, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 152, 55, '07 5437 4001', 'sunshinecoast@lendlease.com', 'https://lendlease.com', 'Beachside retirement. Pool, gym, cinema, and pristine beaches.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Aged Care Toowoomba', 'Regis Aged Care', '88 Ruthven Street', 'Toowoomba', 'QLD', '4350', -27.5617, 151.9533, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '07 4632 4001', 'toowoomba@regis.com.au', 'https://regis.com.au', 'Darling Downs aged care. Gardens and Garden City atmosphere.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Bundaberg', 'Blue Care', '15 Woongarra Street', 'Bundaberg', 'QLD', '4670', -24.8650, 152.3483, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '07 4153 4001', 'bundaberg@bluecare.org.au', 'https://bluecare.org.au', 'Wide Bay aged care. Gardens and rum distillery heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Chermside', 'Bolton Clarke', '125 Gympie Road', 'Chermside', 'QLD', '4032', -27.3850, 153.0333, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 3350 4001', 'chermside@boltonclarke.com.au', 'https://boltonclarke.com.au', 'North Brisbane aged care. Gardens, cafe, and major shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('TriCare Aged Care Southport', 'TriCare', '45 Nerang Street', 'Southport', 'QLD', '4215', -27.9700, 153.4067, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '07 5532 4001', 'southport@tricare.com.au', 'https://tricare.com.au', 'Gold Coast central aged care. Pool, cafe, and Broadwater views.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Southern Cross Care Mackay', 'Southern Cross Care QLD', '88 Sydney Street', 'Mackay', 'QLD', '4740', -21.1417, 149.1867, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '[\"pool\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '07 4957 4001', 'mackay@scrosscc.com.au', 'https://scrosscc.com.au', 'Central Queensland coastal aged care. Pool, gardens, and reef access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Rockhampton', 'Estia Health', '125 Quay Street', 'Rockhampton', 'QLD', '4700', -23.3783, 150.5133, 'aged-care', 'aged-care', 295000, 475000, 340, 530, 32, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '07 4922 4001', 'rockhampton@estiahealth.com.au', 'https://estiahealth.com.au', 'Central Queensland aged care. Gardens and Fitzroy River setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Gladstone', 'Opal Aged Care', '15 Goondoon Street', 'Gladstone', 'QLD', '4680', -23.8450, 151.2567, 'aged-care', 'aged-care', 315000, 515000, 350, 550, 32, '[\"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '07 4972 4001', 'gladstone@opalcare.com.au', 'https://opalcare.com.au', 'Central Queensland port city aged care. Gardens and harbour access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Karinya', 'Carinity', '88 Wondall Road', 'Wynnum West', 'QLD', '4178', -27.4417, 153.1617, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '[\"library\", \"common-room\", \"chapel\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '07 3393 4001', 'karinya@carinity.org.au', 'https://carinity.org.au', 'Bayside Brisbane aged care. Chapel, gardens, and waterfront access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Townsville', 'Adventist Aged Care', '125 Charters Towers Road', 'Hermit Park', 'QLD', '4812', -19.2900, 146.8100, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '[\"pool\", \"library\", \"common-room\", \"chapel\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '07 4725 4001', 'townsville@adventistcare.org.au', 'https://adventistcare.org.au', 'North Queensland aged care. Pool, chapel, tropical setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- SA (5 villages)
('Resthaven Aged Care Marion', 'Resthaven', '88 Sturt Road', 'Marion', 'SA', '5043', -35.0067, 138.5550, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '08 8277 5001', 'marion@resthaven.asn.au', 'https://resthaven.asn.au', 'Southern Adelaide aged care. Gardens and Westfield shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Kapara', 'ACH Group', '125 Cross Road', 'Highgate', 'SA', '5063', -34.9550, 138.6017, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\", \"dementia-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '08 8271 5001', 'kapara@ach.org.au', 'https://ach.org.au', 'Premium inner Adelaide aged care. Pool, gardens, cafe, tree-lined streets.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Port Augusta', 'Estia Health', '45 Jervois Street', 'Port Augusta', 'SA', '5700', -32.4917, 137.7650, 'aged-care', 'aged-care', 255000, 425000, 300, 490, 34, '[\"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '08 8641 5001', 'portaugusta@estiahealth.com.au', 'https://estiahealth.com.au', 'Upper Spencer Gulf aged care. Gardens and crossroads city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Glenelg', 'Regis Aged Care', '88 Jetty Road', 'Glenelg', 'SA', '5045', -34.9800, 138.5133, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '08 8376 5001', 'glenelg@regis.com.au', 'https://regis.com.au', 'Premium beachside aged care. Pool, cafe, and iconic jetty beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Southern Cross Care Victor Harbor', 'Southern Cross Care SA', '15 Ocean Street', 'Victor Harbor', 'SA', '5211', -35.5517, 138.6183, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 90, 55, '08 8552 5001', 'victorharbor@scsa.org.au', 'https://scsa.org.au', 'Fleurieu Peninsula aged care. Gardens and coastal retirement haven.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- WA (4 villages)
('Bethanie Aged Care Esprit Mandurah', 'Bethanie Group', '125 Pinjarra Road', 'Mandurah', 'WA', '6210', -32.5300, 115.7250, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '08 9581 6001', 'mandurahaged@bethanie.com.au', 'https://bethanie.com.au', 'Peel region aged care. Pool, gardens, and waterways lifestyle.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Armadale', 'Regis Aged Care', '45 Jull Street', 'Armadale', 'WA', '6112', -32.1467, 116.0117, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '08 9399 6001', 'armadale@regis.com.au', 'https://regis.com.au', 'Southeast Perth aged care. Gardens and shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Bunbury', 'Amana Living', '88 Spencer Street', 'Bunbury', 'WA', '6230', -33.3267, 115.6400, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '08 9721 6001', 'bunbury@amana.com.au', 'https://amana.com.au', 'Southwest coastal aged care. Gardens and dolphin discovery center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Geraldton', 'Opal Aged Care', '125 Marine Terrace', 'Geraldton', 'WA', '6530', -28.7783, 114.6133, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '[\"pool\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '08 9921 6001', 'geraldton@opalcare.com.au', 'https://opalcare.com.au', 'Mid-west coastal aged care. Pool, gardens, and ocean frontage.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Regis Aged Care Launceston', 'Regis Aged Care', '88 Brisbane Street', 'Launceston', 'TAS', '7250', -41.4367, 147.1383, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '03 6331 9001', 'launceston@regis.com.au', 'https://regis.com.au', 'Northern Tasmania aged care. Gardens and heritage city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Aged Care Farrer', 'Goodwin', '125 Bannon Street', 'Farrer', 'ACT', '2607', -35.3767, 149.1050, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '02 6287 7001', 'farrer@goodwin.org.au', 'https://goodwin.org.au', 'South Canberra aged care. Gardens, cafe, and Woden shopping.', 'approved', 'seed_data', true, false, NOW(), NOW());
