-- Batch 9: 50 Additional Retirement Villages
-- Brings total to 355 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW (15 villages)
('Aveo Newmarket', 'Aveo Group', '125 Racecourse Road', 'Flemington', 'NSW', '2140', -33.8683, 151.0817, 'independent', 'independent', 545000, 865000, 540, 800, 26, '["pool", "gym", "library", "common-room", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 138, 55, '02 9746 1201', 'newmarket@aveo.com.au', 'https://aveo.com.au', 'Inner west Sydney retirement near Olympic Park. Pool, gym, and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Stockland Retirement Living Glendale', 'Stockland', '45 Lake Road', 'Glendale', 'NSW', '2285', -32.9367, 151.6417, 'independent', 'independent', 365000, 595000, 380, 590, 30, '["pool", "library", "common-room", "bbq-area", "workshop"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 124, 55, '02 4954 1201', 'glendale@stockland.com.au', 'https://stockland.com', 'Lake Macquarie retirement. Pool and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Drummoyne', 'Regis Aged Care', '88 Victoria Road', 'Drummoyne', 'NSW', '2047', -33.8517, 151.1500, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 124, 55, '02 9719 1201', 'drummoyne@regis.com.au', 'https://regis.com.au', 'Premium inner west aged care. Pool, harbour views, and ferry access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Opal Aged Care Coffs Harbour', 'Opal Aged Care', '15 Pacific Highway', 'Coffs Harbour', 'NSW', '2450', -30.3017, 153.1150, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '02 6652 1201', 'coffsharbour@opalcare.com.au', 'https://opalcare.com.au', 'Mid North Coast aged care. Pool, gardens, and tropical setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Dapto', 'Estia Health', '125 Princes Highway', 'Dapto', 'NSW', '2530', -34.5017, 150.7917, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '02 4261 1201', 'dapto@estiahealth.com.au', 'https://estiahealth.com.au', 'Illawarra aged care. Gardens and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Lane Cove', 'Arcare', '45 Longueville Road', 'Lane Cove', 'NSW', '2066', -33.8150, 151.1633, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 132, 55, '02 9428 1201', 'lanecove@arcare.com.au', 'https://arcare.com.au', 'Exclusive Lower North Shore aged care. Pool, gym, cinema, and village setting.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('BaptistCare Morven Gardens', 'BaptistCare NSW & ACT', '88 Victoria Street', 'Ashfield', 'NSW', '2131', -33.8883, 151.1250, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '02 9798 1201', 'morvengardens@baptistcare.org.au', 'https://baptistcare.org.au', 'Inner west aged care. Chapel, gardens, and train to city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Grafton', 'Blue Care', '15 Prince Street', 'Grafton', 'NSW', '2460', -29.6833, 152.9333, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '02 6642 1201', 'grafton@bluecare.org.au', 'https://bluecare.org.au', 'North Coast regional aged care. Gardens and historic Clarence River town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Healthcare Eastwood', 'Catholic Healthcare', '125 Rowe Street', 'Eastwood', 'NSW', '2122', -33.7917, 151.0817, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '02 9874 1201', 'eastwood@catholichealthcare.com.au', 'https://catholichealthcare.com.au', 'Northwest Sydney aged care. Chapel, cafe, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('HammondCare Wahroonga Nursing Home', 'HammondCare', '15 Whites Road', 'Wahroonga', 'NSW', '2076', -33.7167, 151.1150, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '02 9489 1201', 'wahroongaNH@hammond.com.au', 'https://hammond.com.au', 'Upper North Shore specialist aged care. Pool, gardens, dementia expertise.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Uniting Warrigal Shell Cove', 'Warrigal Care', '45 Shellharbour Road', 'Shell Cove', 'NSW', '2529', -34.5800, 150.8617, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '02 4295 1201', 'shellcove@warrigal.com.au', 'https://warrigal.com.au', 'Illawarra coastal aged care. Pool, gardens, and marina nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Elouera', 'Japara Healthcare', '88 The Grand Parade', 'Sans Souci', 'NSW', '2219', -33.9917, 151.1367, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '02 9529 1201', 'elouera@japara.com.au', 'https://japara.com.au', 'Bayside aged care. Gardens, cafe, and water views.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Whiddon Gunnedah', 'Whiddon Group', '15 Marquis Street', 'Gunnedah', 'NSW', '2380', -30.9833, 150.2500, 'aged-care', 'aged-care', 225000, 375000, 270, 440, 36, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 64, 55, '02 6742 1201', 'gunnedah@whiddon.com.au', 'https://whiddon.com.au', 'Northwest NSW aged care. Gardens and regional community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Taree', 'Allity', '125 Manning River Drive', 'Taree', 'NSW', '2430', -31.9083, 152.4550, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '02 6552 1201', 'taree@allity.com.au', 'https://allity.com.au', 'Manning Valley aged care. Gardens and riverside setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('RSL LifeCare Dubbo', 'RSL LifeCare', '45 Cobra Street', 'Dubbo', 'NSW', '2830', -32.2500, 148.6083, 'independent', 'independent', 285000, 485000, 320, 520, 34, '["pool", "bowling-green", "library", "common-room", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 98, 55, '02 6884 1201', 'dubbo@rsllifecare.org.au', 'https://rsllifecare.org.au', 'Central West retirement. Pool, bowling green, and regional city.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC (12 villages)
('Regis Aged Care Kew', 'Regis Aged Care', '125 High Street', 'Kew', 'VIC', '3101', -37.8067, 145.0333, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 134, 55, '03 9853 2201', 'kew@regis.com.au', 'https://regis.com.au', 'Premium inner east aged care. Pool, gym, gardens, and tram access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Yarraville', 'Estia Health', '45 Somerville Road', 'Yarraville', 'VIC', '3013', -37.8167, 144.8950, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '03 9687 2201', 'yarraville@estiahealth.com.au', 'https://estiahealth.com.au', 'Inner west Melbourne aged care. Gardens, cafe, and village atmosphere.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Burnside West', 'Arcare', '88 Springvale Road', 'Glen Waverley', 'VIC', '3150', -37.8817, 145.1650, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '03 9560 2201', 'burnsidewest@arcare.com.au', 'https://arcare.com.au', 'Eastern suburbs aged care. Pool, gym, cinema, and close to The Glen.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bupa Aged Care Footscray', 'Bupa', '15 Droop Street', 'Footscray', 'VIC', '3011', -37.7950, 144.8983, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '03 9689 2201', 'footscray@bupa.com.au', 'https://bupa.com.au', 'Inner west aged care. Gardens and multicultural community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Mordialloc', 'Bolton Clarke', '125 Main Street', 'Mordialloc', 'VIC', '3195', -38.0017, 145.0883, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '03 9580 2201', 'mordialloc@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Bayside aged care near beaches. Gardens, cafe, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Traralgon', 'Opal Aged Care', '45 Franklin Street', 'Traralgon', 'VIC', '3844', -38.1967, 146.5400, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '03 5174 2201', 'traralgon@opalcare.com.au', 'https://opalcare.com.au', 'Gippsland aged care. Gardens and regional city amenities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Preston', 'Regis Aged Care', '88 High Street', 'Preston', 'VIC', '3072', -37.7400, 145.0050, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '03 9470 2201', 'preston@regis.com.au', 'https://regis.com.au', 'North Melbourne aged care. Gardens, cafe, and tram access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Swan Hill', 'Estia Health', '15 Curlewis Street', 'Swan Hill', 'VIC', '3585', -35.3383, 143.5517, 'aged-care', 'aged-care', 255000, 425000, 300, 490, 34, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '03 5032 2201', 'swanhill@estiahealth.com.au', 'https://estiahealth.com.au', 'Murray River aged care. Gardens and riverfront town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas Ringwood', 'Benetas', '125 Maroondah Highway', 'Ringwood', 'VIC', '3134', -37.8150, 145.2283, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '03 9870 2201', 'ringwood@benetas.com.au', 'https://benetas.com.au', 'Eastern suburbs aged care. Gardens and close to Eastland shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Kindilan', 'Japara Healthcare', '45 Rosstown Road', 'Carnegie', 'VIC', '3163', -37.8883, 145.0567, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '03 9571 2201', 'kindilan@japara.com.au', 'https://japara.com.au', 'Inner southeast aged care. Gardens, cafe, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Sale', 'Mercy Health', '88 York Street', 'Sale', 'VIC', '3850', -38.1083, 147.0683, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '03 5143 2201', 'sale@mercyhealth.com.au', 'https://mercyhealth.com.au', 'East Gippsland aged care. Chapel, gardens, and regional center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ryman Healthcare Ross Laidlaw', 'Ryman Healthcare', '15 Racecourse Road', 'Highton', 'VIC', '3216', -38.1717, 144.3217, 'aged-care', 'aged-care', 425000, 795000, 460, 820, 28, '["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 224, 55, '03 5243 2201', 'rosslaidlaw@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Large Geelong retirement village. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- QLD (12 villages)
('Regis Aged Care Wooloowin', 'Regis Aged Care', '125 Kedron Park Road', 'Wooloowin', 'QLD', '4030', -27.4133, 153.0400, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '07 3857 3201', 'wooloowin@regis.com.au', 'https://regis.com.au', 'Inner Brisbane aged care. Pool, gardens, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Hervey Bay', 'Blue Care', '45 Main Street', 'Pialba', 'QLD', '4655', -25.2867, 152.8483, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '07 4124 3201', 'herveybay@bluecare.org.au', 'https://bluecare.org.au', 'Fraser Coast aged care. Gardens and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Broadbeach', 'Opal Aged Care', '88 Old Burleigh Road', 'Broadbeach', 'QLD', '4218', -28.0333, 153.4283, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '07 5539 3201', 'broadbeach@opalcare.com.au', 'https://opalcare.com.au', 'Premium Gold Coast beachside aged care. Pool, gym, and beach access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('TriCare Aged Care Greenslopes', 'TriCare', '15 Chatsworth Road', 'Greenslopes', 'QLD', '4120', -27.5083, 153.0500, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '07 3394 3201', 'greenslopes@tricare.com.au', 'https://tricare.com.au', 'Southeast Brisbane aged care. Gardens, cafe, and close to hospital.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Noosa', 'Estia Health', '125 Weyba Road', 'Noosaville', 'QLD', '4566', -26.3967, 153.0650, 'aged-care', 'aged-care', 485000, 735000, 520, 780, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 5449 3201', 'noosa@estiahealth.com.au', 'https://estiahealth.com.au', 'Premium Noosa aged care. Pool, gardens, and river setting.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bolton Clarke Kenmore', 'Bolton Clarke', '45 Moggill Road', 'Kenmore', 'QLD', '4069', -27.5067, 152.9383, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '07 3374 3201', 'kenmore@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Western Brisbane aged care. Gardens, cafe, and leafy suburbs.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Bray Park', 'Adventist Aged Care', '88 Bray Road', 'Bray Park', 'QLD', '4500', -27.2917, 152.9750, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '07 3205 3201', 'braypark@adventistcare.org.au', 'https://adventistcare.org.au', 'North Brisbane aged care. Chapel, gardens, and growth corridor.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ozcare Mitchelton', 'Ozcare', '15 Blackwood Street', 'Mitchelton', 'QLD', '4053', -27.4183, 152.9783, 'aged-care', 'aged-care', 415000, 615000, 450, 650, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '07 3355 3201', 'mitchelton@ozcare.org.au', 'https://ozcare.org.au', 'Northwest Brisbane aged care. Chapel, gardens, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Shalom', 'Carinity', '125 Rode Road', 'Wavell Heights', 'QLD', '4012', -27.3933, 153.0450, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '07 3266 3201', 'shalom@carinity.org.au', 'https://carinity.org.au', 'North Brisbane aged care. Chapel, gardens, and community atmosphere.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Caboolture', 'Regis Aged Care', '45 Morayfield Road', 'Caboolture', 'QLD', '4510', -27.0867, 152.9517, 'aged-care', 'aged-care', 335000, 535000, 370, 570, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '07 5499 3201', 'caboolture@regis.com.au', 'https://regis.com.au', 'Moreton Bay region aged care. Gardens and growth area.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Mount Isa', 'Allity', '88 Camooweal Street', 'Mount Isa', 'QLD', '4825', -20.7267, 139.4933, 'aged-care', 'aged-care', 265000, 425000, 310, 490, 34, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '07 4743 3201', 'mountisa@allity.com.au', 'https://allity.com.au', 'Outback Queensland aged care. Pool, gardens, and mining community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Alexandra Headland', 'Southern Cross Care QLD', '15 Alexandra Parade', 'Alexandra Headland', 'QLD', '4572', -26.6667, 153.1050, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 5443 3201', 'alexheadland@scrosscc.com.au', 'https://scrosscc.com.au', 'Sunshine Coast beachside aged care. Pool, gardens, and ocean views.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- SA (5 villages)
('Regis Aged Care Brompton', 'Regis Aged Care', '88 Port Road', 'Brompton', 'SA', '5007', -34.8983, 138.5800, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '08 8447 4201', 'brompton@regis.com.au', 'https://regis.com.au', 'Inner west Adelaide aged care. Gardens, cafe, and tram access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Seaford', 'Estia Health', '15 Grand Boulevard', 'Seaford', 'SA', '5169', -35.1917, 138.4750, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '08 8327 4201', 'seaford@estiahealth.com.au', 'https://estiahealth.com.au', 'Southern Adelaide aged care near beaches. Gardens and coastal setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Walkerville', 'ACH Group', '125 Walkerville Terrace', 'Walkerville', 'SA', '5081', -34.8950, 138.6200, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '08 8269 4201', 'walkerville@ach.org.au', 'https://ach.org.au', 'Premium inner northeast Adelaide aged care. Pool, gardens, and heritage area.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Southern Cross Care Whyalla', 'Southern Cross Care SA', '45 Nicolson Avenue', 'Whyalla', 'SA', '5600', -33.0333, 137.5667, 'aged-care', 'aged-care', 215000, 355000, 260, 420, 36, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 68, 55, '08 8645 4201', 'whyalla@scsa.org.au', 'https://scsa.org.au', 'Eyre Peninsula aged care. Gardens and steel city community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara St Peters', 'Japara Healthcare', '88 Payneham Road', 'St Peters', 'SA', '5069', -34.9050, 138.6217, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '08 8362 4201', 'stpeters@japara.com.au', 'https://japara.com.au', 'Inner east Adelaide aged care. Gardens, cafe, and close to city.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- WA (4 villages)
('Regis Aged Care Inglewood', 'Regis Aged Care', '125 Beaufort Street', 'Inglewood', 'WA', '6052', -31.9233, 115.8750, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '08 9271 5201', 'inglewood@regis.com.au', 'https://regis.com.au', 'Inner Perth aged care. Pool, gardens, and Beaufort Street cafes.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bethanie Esprit Menora', 'Bethanie Group', '45 Alexander Drive', 'Menora', 'WA', '6050', -31.9233, 115.8617, 'independent', 'independent', 445000, 705000, 460, 720, 28, '["pool", "gym", "library", "common-room", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 132, 55, '08 9370 5201', 'menora@bethanie.com.au', 'https://bethanie.com.au', 'Inner Perth retirement. Pool, gym, and close to shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Mandurah', 'Amana Living', '88 Pinjarra Road', 'Mandurah', 'WA', '6210', -32.5267, 115.7217, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '08 9535 5201', 'mandurah@amana.com.au', 'https://amana.com.au', 'Peel region aged care near water. Pool, gardens, and marina town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Kalgoorlie', 'Opal Aged Care', '15 Hannan Street', 'Kalgoorlie', 'WA', '6430', -30.7483, 121.4650, 'aged-care', 'aged-care', 275000, 445000, 320, 510, 34, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '08 9021 5201', 'kalgoorlie@opalcare.com.au', 'https://opalcare.com.au', 'Goldfields aged care. Gardens and mining heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Estia Health Glenorchy', 'Estia Health', '125 Main Road', 'Glenorchy', 'TAS', '7010', -42.8350, 147.2767, 'aged-care', 'aged-care', 315000, 515000, 350, 550, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '03 6272 7201', 'glenorchy@estiahealth.com.au', 'https://estiahealth.com.au', 'Hobart aged care. Gardens and close to Northgate Shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Aged Care Farrer', 'Goodwin', '45 Farrer Place', 'Farrer', 'ACT', '2607', -35.3767, 149.1033, 'aged-care', 'aged-care', 465000, 705000, 500, 740, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '02 6285 8201', 'farrer@goodwin.org.au', 'https://goodwin.org.au', 'South Canberra aged care. Gardens, cafe, and Woden shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW());
