-- Batch 6: 50 Additional Retirement Villages - Continued Expansion
-- Brings total to 205 villages

INSERT INTO retirement_villages (
  name,
  operator,
  location,
  suburb,
  state,
  postcode,
  latitude,
  longitude,
  village_type,
  care_level,
  entry_price_min,
  entry_price_max,
  monthly_fees_min,
  monthly_fees_max,
  dmf_percentage,
  amenities,
  care_services,
  bedrooms,
  pet_friendly,
  total_units,
  age_restriction,
  contact_phone,
  contact_email,
  website,
  description,
  status,
  source,
  verified,
  featured,
  submitted_at,
  approved_at
) VALUES

-- NEW SOUTH WALES (15 villages)

('Warrigal Wollongong', 'Warrigal Care', '125 Crown Street', 'Wollongong', 'NSW', '2500', -34.4250, 150.8933, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 96, 55, '02 4228 1111', 'wollongong@warrigal.com.au', 'https://warrigal.com.au',
'Central Wollongong aged care. Gardens, cafe, and close to hospital and beach.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('HammondCare Miranda', 'HammondCare', '15 Kiora Road', 'Miranda', 'NSW', '2228', -34.0350, 151.1000, 'aged-care', 'aged-care', 495000, 745000, 530, 780, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 112, 55, '02 9531 2222', 'miranda@hammond.com.au', 'https://hammond.com.au',
'Sutherland Shire specialist dementia care. Gardens and close to Westfield Miranda.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Estia Health Dubbo', 'Estia Health', '88 Macquarie Street', 'Dubbo', 'NSW', '2830', -32.2567, 148.6050, 'aged-care', 'aged-care', 245000, 405000, 290, 480, 34,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 78, 55, '02 6882 3333', 'dubbo@estiahealth.com.au', 'https://estiahealth.com.au',
'Regional NSW aged care. Gardens and close to Dubbo Base Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('BaptistCare Aminya Village', 'BaptistCare NSW & ACT', '45 Bardia Avenue', 'Smithfield', 'NSW', '2164', -33.8450, 150.9333, 'independent', 'independent', 385000, 625000, 400, 620, 30,
'["pool", "library", "common-room", "chapel", "bbq-area", "garden"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 118, 55, '02 9609 4444', 'aminya@baptistcare.org.au', 'https://baptistcare.org.au',
'Western Sydney retirement village. Pool, chapel, gardens, and community center.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Mercy Aged Care Singleton', 'Mercy Health', '125 George Street', 'Singleton', 'NSW', '2330', -32.5667, 151.1667, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34,
'["library", "common-room", "chapel", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 72, 55, '02 6572 5555', 'singleton@mercyhealth.com.au', 'https://mercyhealth.com.au',
'Hunter Valley aged care. Chapel, gardens, and mining town heritage.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Whiddon Bathurst', 'Whiddon Group', '15 Keppel Street', 'Bathurst', 'NSW', '2795', -33.4167, 149.5833, 'aged-care', 'aged-care', 265000, 445000, 310, 510, 34,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 84, 55, '02 6331 6666', 'bathurst@whiddon.com.au', 'https://whiddon.com.au',
'Central West aged care in historic Bathurst. Gardens and close to city center.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Regis Aged Care Wagga Wagga', 'Regis Aged Care', '88 Edward Street', 'Wagga Wagga', 'NSW', '2650', -35.1167, 147.3667, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32,
'["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 92, 55, '02 6921 7777', 'wagga@regis.com.au', 'https://regis.com.au',
'Riverina aged care. Pool, gardens, and close to Wagga Base Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('IRT Peakhurst', 'IRT Group', '45 Bonds Road', 'Peakhurst', 'NSW', '2210', -33.9583, 151.0550, 'assisted', 'assisted', 465000, 685000, 480, 700, 28,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb,
ARRAY['1-bed', '2-bed'], true, 94, 55, '02 9533 8888', 'peakhurst@irt.org.au', 'https://irt.org.au',
'South Sydney retirement village. Gardens and close to shopping and transport.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Bethanie Bateau Bay', 'Bethanie Group', '125 Bay Village Road', 'Bateau Bay', 'NSW', '2261', -33.3850, 151.4783, 'independent', 'independent', 425000, 685000, 440, 680, 28,
'["pool", "library", "common-room", "bbq-area", "garden"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 126, 55, '02 4332 9999', 'bateaubay@bethanie.com.au', 'https://bethanie.com.au',
'Central Coast beachside retirement. Pool, gardens, and minutes to beach.',
'approved', 'seat_data', true, false, NOW(), NOW()),

('Estia Health Queanbeyan', 'Estia Health', '15 Collett Street', 'Queanbeyan', 'NSW', '2620', -35.3533, 149.2317, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 88, 55, '02 6297 1000', 'queanbeyan@estiahealth.com.au', 'https://estiahealth.com.au',
'NSW-ACT border aged care. Gardens and close to Canberra.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Arcare Hampstead', 'Arcare', '88 Burwood Road', 'Concord', 'NSW', '2137', -33.8617, 151.1017, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26,
'["pool", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 118, 55, '02 9744 1001', 'hampstead@arcare.com.au', 'https://arcare.com.au',
'Inner west Sydney premium aged care. Pool, cinema, and close to Burwood shopping.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Blue Care Lismore', 'Blue Care', '45 Keen Street', 'Lismore', 'NSW', '2480', -28.8167, 153.2833, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 76, 55, '02 6621 1002', 'lismore@bluecare.org.au', 'https://bluecare.org.au',
'North Coast regional aged care. Gardens and close to Lismore Base Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Opal Aged Care Bankstown', 'Opal Aged Care', '125 Chapel Road', 'Bankstown', 'NSW', '2200', -33.9167, 151.0333, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 102, 55, '02 9707 1003', 'bankstown@opalcare.com.au', 'https://opalcare.com.au',
'Southwest Sydney aged care. Gardens, cafe, and close to Bankstown shopping.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Allity Aged Care Port Macquarie', 'Allity', '15 Gordon Street', 'Port Macquarie', 'NSW', '2444', -31.4333, 152.9083, 'aged-care', 'aged-care', 335000, 535000, 370, 570, 32,
'["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 96, 55, '02 6583 1004', 'portmacquarie@allity.com.au', 'https://allity.com.au',
'Mid North Coast aged care. Pool, gardens, and close to beaches.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Japara Finley', 'Japara Healthcare', '88 Tocumwal Street', 'Finley', 'NSW', '2713', -35.6500, 145.5733, 'aged-care', 'aged-care', 195000, 325000, 240, 400, 36,
'["library", "common-room", "garden", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 58, 55, '03 5883 1005', 'finley@japara.com.au', 'https://japara.com.au',
'Riverina border town aged care. Gardens and close to Murray River.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- VICTORIA (12 villages)

('Estia Health Shepparton', 'Estia Health', '125 Wyndham Street', 'Shepparton', 'VIC', '3630', -36.3817, 145.3983, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 88, 55, '03 5831 2001', 'shepparton@estiahealth.com.au', 'https://estiahealth.com.au',
'Goulburn Valley aged care. Gardens and close to Shepparton Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Regis Aged Care Moonee Ponds', 'Regis Aged Care', '45 Puckle Street', 'Moonee Ponds', 'VIC', '3039', -37.7650, 144.9217, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 114, 55, '03 9370 2002', 'mooneeponds@regis.com.au', 'https://regis.com.au',
'Inner northwest Melbourne aged care. Pool, gardens, and tram access to city.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Bupa Aged Care Greensborough', 'Bupa', '88 Grimshaw Street', 'Greensborough', 'VIC', '3088', -37.7050, 145.1033, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 98, 55, '03 9435 2003', 'greensborough@bupa.com.au', 'https://bupa.com.au',
'Northeast Melbourne aged care. Gardens, cafe, and close to Greensborough Plaza.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Arcare Malvern East', 'Arcare', '15 Waverley Road', 'Malvern East', 'VIC', '3145', -37.8783, 145.0650, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26,
'["pool", "gym", "library", "common-room", "cinema", "hairdresser", "cafe", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 128, 55, '03 9509 2004', 'malverneast@arcare.com.au', 'https://arcare.com.au',
'Premium inner Melbourne aged care. Pool, gym, cinema, and close to Chadstone.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Opal Aged Care Warrnambool', 'Opal Aged Care', '125 Raglan Parade', 'Warrnambool', 'VIC', '3280', -38.3817, 142.4850, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 82, 55, '03 5562 2005', 'warrnambool@opalcare.com.au', 'https://opalcare.com.au',
'Great Ocean Road aged care. Gardens and close to beaches.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Bolton Clarke Ivanhoe', 'Bolton Clarke', '45 Upper Heidelberg Road', 'Ivanhoe', 'VIC', '3079', -37.7717, 145.0400, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 108, 55, '03 9497 2006', 'ivanhoe@boltonclarke.com.au', 'https://boltonclarke.com.au',
'Inner northeast Melbourne aged care. Pool, gardens, and tram access.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Estia Health Mornington', 'Estia Health', '88 Bungower Road', 'Mornington', 'VIC', '3931', -38.2217, 145.0400, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 94, 55, '03 5975 2007', 'mornington@estiahealth.com.au', 'https://estiahealth.com.au',
'Peninsula aged care near beaches. Gardens, cafe, and Main Street access.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Benetas Lilydale', 'Benetas', '15 Anderson Street', 'Lilydale', 'VIC', '3140', -37.7550, 145.3517, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 92, 55, '03 9739 2008', 'lilydale@benetas.com.au', 'https://benetas.com.au',
'Yarra Valley aged care. Gardens and close to Lilydale village.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Japara Millward', 'Japara Healthcare', '125 High Street', 'Wodonga', 'VIC', '3690', -36.1217, 146.8883, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 84, 55, '02 6024 2009', 'millward@japara.com.au', 'https://japara.com.au',
'Border city aged care. Gardens and close to Wodonga Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Regis Aged Care Elwood', 'Regis Aged Care', '15 Ormond Road', 'Elwood', 'VIC', '3184', -37.8883, 144.9783, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 106, 55, '03 9531 2010', 'elwood@regis.com.au', 'https://regis.com.au',
'Premium beachside aged care. Pool, gardens, and minutes to Elwood Beach.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Mercy Health Yarrawonga', 'Mercy Health', '45 Irvine Street', 'Yarrawonga', 'VIC', '3730', -36.0217, 146.0017, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34,
'["library", "common-room", "chapel", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 68, 55, '03 5744 2011', 'yarrawonga@mercyhealth.com.au', 'https://mercyhealth.com.au',
'Murray River aged care. Chapel, gardens, and lake views.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Ryman Healthcare Nellie Melba', 'Ryman Healthcare', '125 Nepean Highway', 'Wheelers Hill', 'VIC', '3150', -37.9117, 145.1783, 'aged-care', 'aged-care', 495000, 945000, 530, 920, 28,
'["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser", "cafe", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed', '3-bed'], true, 252, 55, '03 9561 2012', 'nelliemelba@rymanhealthcare.com', 'https://rymanhealthcare.com',
'Large premium retirement village. Pool, gym, bowling green, cinema, restaurant. Full continuum of care.',
'approved', 'seed_data', true, true, NOW(), NOW()),

-- QUEENSLAND (12 villages)

('Estia Health Maroochydore', 'Estia Health', '88 Aerodrome Road', 'Maroochydore', 'QLD', '4558', -26.6583, 153.0883, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30,
'["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 94, 55, '07 5443 3001', 'maroochydore@estiahealth.com.au', 'https://estiahealth.com.au',
'Sunshine Coast aged care. Pool, gardens, and close to beaches.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Blue Care Caboolture', 'Blue Care', '15 King Street', 'Caboolture', 'QLD', '4510', -27.0833, 152.9500, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 86, 55, '07 5428 3002', 'caboolture@bluecare.org.au', 'https://bluecare.org.au',
'Moreton Bay region aged care. Gardens and close to shopping.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Regis Aged Care Toowoomba', 'Regis Aged Care', '125 Ruthven Street', 'Toowoomba', 'QLD', '4350', -27.5617, 151.9533, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 96, 55, '07 4632 3003', 'toowoomba@regis.com.au', 'https://regis.com.au',
'Garden City aged care. Gardens, cafe, and close to shops.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Opal Aged Care Varsity Lakes', 'Opal Aged Care', '45 Varsity Parade', 'Varsity Lakes', 'QLD', '4227', -28.0717, 153.4117, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28,
'["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 108, 55, '07 5585 3004', 'varsitylakes@opalcare.com.au', 'https://opalcare.com.au',
'Gold Coast aged care near lake. Pool, gym, and close to Bond University.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('TriCare Aged Care Banyo', 'TriCare', '88 Tufnell Road', 'Banyo', 'QLD', '4014', -27.3750, 153.0750, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 98, 55, '07 3267 3005', 'banyo@tricare.com.au', 'https://tricare.com.au',
'Northeast Brisbane aged care. Gardens, cafe, and train access.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Bolton Clarke Lutwyche', 'Bolton Clarke', '15 Lutwyche Road', 'Lutwyche', 'QLD', '4030', -27.4217, 153.0283, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 104, 55, '07 3357 3006', 'lutwyche@boltonclarke.com.au', 'https://boltonclarke.com.au',
'Inner Brisbane aged care. Gardens, cafe, dementia unit, and bus access.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Adventist Aged Care Gladstone', 'Adventist Aged Care', '125 Dawson Highway', 'Gladstone', 'QLD', '4680', -23.8500, 151.2633, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32,
'["library", "common-room", "chapel", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 76, 55, '07 4972 3007', 'gladstone@adventistcare.org.au', 'https://adventistcare.org.au',
'Central Queensland aged care. Chapel, gardens, and close to port.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Ozcare Maryborough', 'Ozcare', '45 John Street', 'Maryborough', 'QLD', '4650', -25.5400, 152.7017, 'aged-care', 'aged-care', 255000, 425000, 300, 490, 34,
'["library", "common-room", "chapel", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 72, 55, '07 4123 3008', 'maryborough@ozcare.org.au', 'https://ozcare.org.au',
'Fraser Coast aged care. Chapel, gardens, and historic town.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Carinity Aged Care Cleveland', 'Carinity', '125 Bloomfield Street', 'Cleveland', 'QLD', '4163', -27.5283, 153.2717, 'aged-care', 'aged-care', 415000, 615000, 450, 650, 30,
'["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 92, 55, '07 3488 3009', 'cleveland@carinity.org.au', 'https://carinity.org.au',
'Redlands aged care. Chapel, gardens, and close to waterfront.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Regis Aged Care Palm Beach', 'Regis Aged Care', '15 Fifth Avenue', 'Palm Beach', 'QLD', '4221', -28.1183, 153.4650, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 112, 55, '07 5534 3010', 'palmbeach@regis.com.au', 'https://regis.com.au',
'Premium Gold Coast beachside aged care. Pool, gardens, and beach access.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Allity Aged Care Cairns North', 'Allity', '88 Sheridan Street', 'Cairns North', 'QLD', '4870', -16.9083, 145.7650, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30,
'["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 88, 55, '07 4031 3011', 'cairnsnorth@allity.com.au', 'https://allity.com.au',
'Tropical Far North aged care. Pool, gardens, and close to Esplanade.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Southern Cross Care Elanora', 'Southern Cross Care QLD', '45 Guineas Creek Road', 'Elanora', 'QLD', '4221', -28.1167, 153.4517, 'independent', 'independent', 465000, 745000, 480, 740, 28,
'["pool", "gym", "bowling-green", "library", "common-room", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 138, 55, '07 5598 3012', 'elanora@scrosscc.com.au', 'https://scrosscc.com.au',
'Gold Coast retirement village. Pool, gym, bowling green, and close to beaches.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- SOUTH AUSTRALIA (5 villages)

('Estia Health Port Adelaide', 'Estia Health', '125 Commercial Road', 'Port Adelaide', 'SA', '5015', -34.8450, 138.5050, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 88, 55, '08 8447 4001', 'portadelaide@estiahealth.com.au', 'https://estiahealth.com.au',
'Port Adelaide aged care. Gardens and close to waterfront.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Regis Aged Care Glenelg', 'Regis Aged Care', '15 Partridge Street', 'Glenelg South', 'SA', '5045', -35.0017, 138.5117, 'aged-care', 'aged-care', 495000, 745000, 530, 780, 28,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 106, 55, '08 8295 4002', 'glenelg@regis.com.au', 'https://regis.com.au',
'Premium beachside Adelaide aged care. Pool, gardens, and tram to beach.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('ACH Group Kapara', 'ACH Group', '88 Anzac Highway', 'Everard Park', 'SA', '5035', -34.9517, 138.5883, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 98, 55, '08 8271 4003', 'kapara@ach.org.au', 'https://ach.org.au',
'Inner southern Adelaide aged care. Gardens, cafe, and close to city.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Southern Cross Care Yankalilla', 'Southern Cross Care SA', '45 Main South Road', 'Yankalilla', 'SA', '5203', -35.4717, 138.3450, 'aged-care', 'aged-care', 235000, 385000, 280, 460, 34,
'["library", "common-room", "garden", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 64, 55, '08 8558 4004', 'yankalilla@scsa.org.au', 'https://scsa.org.au',
'Fleurieu Peninsula coastal aged care. Gardens and close to beaches.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Japara Cowandilla', 'Japara Healthcare', '125 Marion Road', 'Cowandilla', 'SA', '5033', -34.9483, 138.5650, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 94, 55, '08 8293 4005', 'cowandilla@japara.com.au', 'https://japara.com.au',
'Western Adelaide aged care on Marion Road. Gardens and close to beaches.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- WESTERN AUSTRALIA (4 villages)

('Bethanie Esprit Kwinana', 'Bethanie Group', '125 Gilmore Avenue', 'Kwinana', 'WA', '6167', -32.2383, 115.7717, 'independent', 'independent', 325000, 545000, 350, 550, 32,
'["pool", "gym", "library", "common-room", "bbq-area", "workshop"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 128, 55, '08 9419 5001', 'kwinana@bethanie.com.au', 'https://bethanie.com.au',
'Southern Perth retirement village. Pool, gym, and modern facilities.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Regis Aged Care Nedlands', 'Regis Aged Care', '45 Jutland Parade', 'Dalkeith', 'WA', '6009', -31.9883, 115.8050, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24,
'["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 124, 55, '08 9386 5002', 'nedlands@regis.com.au', 'https://regis.com.au',
'Premium Perth riverside aged care. Pool, gym, and river views.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Amana Living Rockingham', 'Amana Living', '88 Counsel Road', 'Rockingham', 'WA', '6168', -32.2750, 115.7333, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 92, 55, '08 9592 5003', 'rockingham@amana.com.au', 'https://amana.com.au',
'Coastal Perth aged care. Gardens and close to beaches and shopping.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Opal Aged Care Ellenbrook', 'Opal Aged Care', '15 The Broadway', 'Ellenbrook', 'WA', '6069', -31.7717, 115.9733, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30,
'["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 96, 55, '08 9297 5004', 'ellenbrook@opalcare.com.au', 'https://opalcare.com.au',
'Northeast Perth growth area aged care. Pool, gardens, and modern facilities.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- TASMANIA (1 village)

('Bupa Aged Care Devonport', 'Bupa', '125 Best Street', 'Devonport', 'TAS', '7310', -41.1783, 146.3500, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 78, 55, '03 6424 6001', 'devonport@bupa.com.au', 'https://bupa.com.au',
'North Tasmania aged care. Gardens and close to Spirit of Tasmania terminal.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- AUSTRALIAN CAPITAL TERRITORY (1 village)

('Southern Cross Care Canberra North', 'Southern Cross Care ACT & NSW', '88 Ginninderra Drive', 'Belconnen', 'ACT', '2617', -35.2383, 149.0667, 'aged-care', 'aged-care', 495000, 745000, 530, 780, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 108, 55, '02 6253 7001', 'canberranorth@sccliving.org.au', 'https://sccliving.org.au',
'North Canberra aged care. Gardens, cafe, and close to Westfield Belconnen.',
'approved', 'seed_data', true, false, NOW(), NOW());
