-- Batch 10: 50 Additional Retirement Villages
-- Brings total to 405 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW (15 villages)
('Lendlease Retirement Living Gladesville', 'Lendlease', '15 Victoria Road', 'Gladesville', 'NSW', '2111', -33.8367, 151.1267, 'independent', 'independent', 625000, 985000, 620, 900, 26, '["pool", "gym", "cinema", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 148, 55, '02 9879 1301', 'gladesville@lendlease.com', 'https://lendlease.com', 'Premium harbour suburb retirement. Pool, gym, cinema, and harbour access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Berkeley Vale', 'Stockland', '88 The Lakesway', 'Berkeley Vale', 'NSW', '2261', -33.3217, 151.4283, 'independent', 'independent', 385000, 625000, 400, 620, 30, '["pool", "library", "common-room", "bbq-area", "workshop"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 132, 55, '02 4389 1301', 'berkeleyvale@stockland.com.au', 'https://stockland.com', 'Central Coast retirement near lakes. Pool and waterways.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Chatswood', 'Regis Aged Care', '125 Pacific Highway', 'Chatswood', 'NSW', '2067', -33.7983, 151.1817, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 138, 55, '02 9411 1301', 'chatswood@regis.com.au', 'https://regis.com.au', 'Premium North Shore aged care. Pool, gym, and train to city.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Opal Aged Care Fairfield', 'Opal Aged Care', '45 Hamilton Road', 'Fairfield', 'NSW', '2165', -33.8700, 150.9550, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '02 9724 1301', 'fairfield@opalcare.com.au', 'https://opalcare.com.au', 'Western Sydney aged care. Gardens and multicultural community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Bowral', 'Estia Health', '88 Bong Bong Street', 'Bowral', 'NSW', '2576', -34.4783, 150.4183, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '02 4861 1301', 'bowral@estiahealth.com.au', 'https://estiahealth.com.au', 'Southern Highlands aged care. Gardens, cafe, and historic town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Pyrmont', 'Arcare', '15 Harris Street', 'Pyrmont', 'NSW', '2009', -33.8717, 151.1917, 'aged-care', 'aged-care', 685000, 1050000, 720, 1040, 22, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 142, 55, '02 9518 1301', 'pyrmont@arcare.com.au', 'https://arcare.com.au', 'Premium inner city aged care. Pool, gym, cinema, and harbour views.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('BaptistCare Rosewood', 'BaptistCare NSW & ACT', '125 Jersey Road', 'Denistone', 'NSW', '2114', -33.7950, 151.0883, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '02 9874 1301', 'rosewood@baptistcare.org.au', 'https://baptistcare.org.au', 'Northwest Sydney aged care. Pool, chapel, gardens, and leafy setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Armidale', 'Blue Care', '45 Butler Street', 'Armidale', 'NSW', '2350', -30.5133, 151.6617, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '02 6772 1301', 'armidale@bluecare.org.au', 'https://bluecare.org.au', 'New England aged care. Gardens and university town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Healthcare Randwick', 'Catholic Healthcare', '88 Avoca Street', 'Randwick', 'NSW', '2031', -33.9150, 151.2433, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 124, 55, '02 9399 1301', 'randwick@catholichealthcare.com.au', 'https://catholichealthcare.com.au', 'Eastern suburbs premium aged care. Chapel, cafe, and near hospitals.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('HammondCare Braeside', 'HammondCare', '15 Braeside Drive', 'Prairiewood', 'NSW', '2176', -33.8550, 150.9050, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '02 9729 1301', 'braeside@hammond.com.au', 'https://hammond.com.au', 'Western Sydney dementia care. Gardens and specialist services.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Uniting Fernhill', 'Uniting NSW & ACT', '125 Old Hume Highway', 'Mittagong', 'NSW', '2575', -34.4500, 150.4467, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '02 4872 1301', 'fernhill@uniting.org', 'https://uniting.org', 'Southern Highlands aged care. Gardens and countryside setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Seaside', 'Japara Healthcare', '45 Soldiers Point Road', 'Soldiers Point', 'NSW', '2317', -32.7117, 152.0617, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '02 4919 1301', 'seaside@japara.com.au', 'https://japara.com.au', 'Port Stephens waterfront aged care. Pool, gardens, and marina.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Whiddon Mudgee', 'Whiddon Group', '88 Market Street', 'Mudgee', 'NSW', '2850', -32.5967, 149.5883, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '02 6372 1301', 'mudgee@whiddon.com.au', 'https://whiddon.com.au', 'Central West wine country aged care. Gardens and historic town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Batemans Bay', 'Allity', '15 Cranbrook Road', 'Batemans Bay', 'NSW', '2536', -35.7100, 150.1783, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '02 4472 1301', 'batemansbay@allity.com.au', 'https://allity.com.au', 'South Coast aged care. Gardens and close to beaches and inlet.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('RSL LifeCare Goulburn', 'RSL LifeCare', '125 Montague Street', 'Goulburn', 'NSW', '2580', -34.7550, 149.7200, 'independent', 'independent', 285000, 485000, 320, 520, 34, '["bowling-green", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 104, 55, '02 4823 1301', 'goulburn@rsllifecare.org.au', 'https://rsllifecare.org.au', 'Southern Tablelands retirement. Bowling green and heritage city.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC (12 villages)
('Regis Aged Care Caulfield', 'Regis Aged Care', '88 Glen Eira Road', 'Caulfield', 'VIC', '3162', -37.8767, 145.0317, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '03 9523 3301', 'caulfield@regis.com.au', 'https://regis.com.au', 'Premium inner southeast aged care. Pool, gardens, and train access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Bentleigh', 'Estia Health', '45 Centre Road', 'Bentleigh', 'VIC', '3204', -37.9200, 145.0350, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '03 9557 3301', 'bentleigh@estiahealth.com.au', 'https://estiahealth.com.au', 'Bayside aged care. Gardens, cafe, and close to village shops.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Knox', 'Arcare', '125 Stud Road', 'Wantirna South', 'VIC', '3152', -37.8800, 145.2317, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 132, 55, '03 9801 3301', 'knox@arcare.com.au', 'https://arcare.com.au', 'Eastern suburbs aged care. Pool, gym, cinema, and Knox shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bupa Aged Care Ascot Vale', 'Bupa', '15 Union Road', 'Ascot Vale', 'VIC', '3032', -37.7750, 144.9217, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '03 9376 3301', 'ascotvale@bupa.com.au', 'https://bupa.com.au', 'Inner northwest Melbourne aged care. Gardens, cafe, and tram route.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Sunbury', 'Bolton Clarke', '88 Oshanassy Street', 'Sunbury', 'VIC', '3429', -37.5783, 144.7167, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '03 9744 3301', 'sunbury@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Northwest growth corridor aged care. Gardens and historic town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Mildura', 'Opal Aged Care', '45 Deakin Avenue', 'Mildura', 'VIC', '3500', -34.1867, 142.1600, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '03 5021 3301', 'mildura@opalcare.com.au', 'https://opalcare.com.au', 'Sunraysia region aged care. Pool, gardens, and Murray River setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Keilor', 'Regis Aged Care', '125 Old Calder Highway', 'Keilor', 'VIC', '3036', -37.7233, 144.8333, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '03 9331 3301', 'keilor@regis.com.au', 'https://regis.com.au', 'Northwest Melbourne aged care. Gardens, cafe, and close to airport.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Portland', 'Estia Health', '15 Cliff Street', 'Portland', 'VIC', '3305', -38.3433, 141.6050, 'aged-care', 'aged-care', 255000, 425000, 300, 490, 34, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '03 5523 3301', 'portland@estiahealth.com.au', 'https://estiahealth.com.au', 'Western Victoria coastal aged care. Gardens and historic port.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas Northcote', 'Benetas', '88 St Georges Road', 'Northcote', 'VIC', '3070', -37.7683, 144.9983, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '03 9489 3301', 'northcote@benetas.com.au', 'https://benetas.com.au', 'Inner north Melbourne aged care. Gardens, cafe, and tram route.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Riverside', 'Japara Healthcare', '45 Punt Road', 'South Yarra', 'VIC', '3141', -37.8417, 145.0017, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 136, 55, '03 9826 3301', 'riverside@japara.com.au', 'https://japara.com.au', 'Premium inner Melbourne aged care. Pool, gym, and Chapel Street.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Mercy Health Horsham', 'Mercy Health', '125 Stawell Road', 'Horsham', 'VIC', '3400', -36.7117, 142.1983, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '03 5382 3301', 'horsham@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Wimmera region aged care. Chapel, gardens, and wheat belt town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ryman Healthcare Geelong', 'Ryman Healthcare', '15 Barrabool Road', 'Highton', 'VIC', '3216', -38.1650, 144.3283, 'aged-care', 'aged-care', 445000, 835000, 480, 860, 28, '["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 238, 55, '03 5244 3301', 'geelong@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Large premium Geelong retirement village. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- QLD (12 villages)
('Regis Aged Care Camp Hill', 'Regis Aged Care', '125 Old Cleveland Road', 'Camp Hill', 'QLD', '4152', -27.4983, 153.0833, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '07 3398 4301', 'camphill@regis.com.au', 'https://regis.com.au', 'Southeast Brisbane aged care. Gardens, cafe, and bus routes.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Capalaba', 'Blue Care', '45 Old Cleveland Road', 'Capalaba', 'QLD', '4157', -27.5233, 153.1983, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '07 3245 4301', 'capalaba@bluecare.org.au', 'https://bluecare.org.au', 'Redlands aged care. Gardens and close to Capalaba Park shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Burleigh Heads', 'Opal Aged Care', '88 West Burleigh Road', 'Burleigh Heads', 'QLD', '4220', -28.0950, 153.4367, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '07 5576 4301', 'burleighheads@opalcare.com.au', 'https://opalcare.com.au', 'Premium Gold Coast beachside aged care. Pool, gardens, and surf beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('TriCare Aged Care Pialba', 'TriCare', '15 Elizabeth Street', 'Pialba', 'QLD', '4655', -25.2883, 152.8433, 'aged-care', 'aged-care', 315000, 515000, 350, 550, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '07 4125 4301', 'pialba@tricare.com.au', 'https://tricare.com.au', 'Hervey Bay aged care. Gardens and close to beaches and whale watching.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Upper Mount Gravatt', 'Estia Health', '125 Logan Road', 'Upper Mount Gravatt', 'QLD', '4122', -27.5500, 153.0750, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '07 3343 4301', 'uppermtgravatt@estiahealth.com.au', 'https://estiahealth.com.au', 'Southeast Brisbane aged care. Gardens, cafe, and shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Thornlands', 'Bolton Clarke', '45 Beverley Road', 'Thornlands', 'QLD', '4164', -27.5350, 153.2617, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '07 3286 4301', 'thornlands@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Redlands aged care. Gardens and close to Thornlands shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Rosslea', 'Adventist Aged Care', '88 Ross River Road', 'Rosslea', 'QLD', '4812', -19.2933, 146.7617, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["pool", "library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '07 4774 4301', 'rosslea@adventistcare.org.au', 'https://adventistcare.org.au', 'Townsville aged care. Pool, chapel, gardens, and tropical setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ozcare Kingaroy', 'Ozcare', '15 Alford Street', 'Kingaroy', 'QLD', '4610', -26.5400, 151.8383, 'aged-care', 'aged-care', 255000, 425000, 300, 490, 34, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '07 4162 4301', 'kingaroy@ozcare.org.au', 'https://ozcare.org.au', 'South Burnett aged care. Chapel, gardens, and peanut capital.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Colthup Manor', 'Carinity', '125 Albany Creek Road', 'Aspley', 'QLD', '4034', -27.3617, 153.0233, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '07 3263 4301', 'colthupmanor@carinity.org.au', 'https://carinity.org.au', 'North Brisbane aged care. Chapel, gardens, and community focus.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Wynnum', 'Regis Aged Care', '45 Bay Terrace', 'Wynnum', 'QLD', '4178', -27.4433, 153.1733, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 3396 4301', 'wynnum@regis.com.au', 'https://regis.com.au', 'Bayside Brisbane aged care. Gardens, cafe, and waterfront access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Yeppoon', 'Allity', '88 Adelaide Park Road', 'Yeppoon', 'QLD', '4703', -23.1283, 150.7417, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '07 4939 4301', 'yeppoon@allity.com.au', 'https://allity.com.au', 'Capricorn Coast aged care. Pool, gardens, and beach town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Labrador', 'Southern Cross Care QLD', '125 Olsen Avenue', 'Labrador', 'QLD', '4215', -27.9433, 153.3917, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '07 5591 4301', 'labrador@scrosscc.com.au', 'https://scrosscc.com.au', 'Gold Coast waterfront aged care. Pool, gardens, and Broadwater access.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- SA (5 villages)
('Regis Aged Care Clarence Gardens', 'Regis Aged Care', '88 Goodwood Road', 'Clarence Gardens', 'SA', '5039', -34.9717, 138.5817, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '08 8293 5301', 'clarencegardens@regis.com.au', 'https://regis.com.au', 'Inner southern Adelaide aged care. Gardens, cafe, and tram access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Victor Harbor', 'Estia Health', '15 Bay Road', 'Victor Harbor', 'SA', '5211', -35.5517, 138.6283, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '08 8552 5301', 'victorharbor@estiahealth.com.au', 'https://estiahealth.com.au', 'Fleurieu Peninsula coastal aged care. Gardens and historic wharf.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Westbourne Park', 'ACH Group', '45 Sir Donald Bradman Drive', 'Cowandilla', 'SA', '5033', -34.9517, 138.5633, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '08 8292 5301', 'westbournepk@ach.org.au', 'https://ach.org.au', 'Western Adelaide aged care. Gardens, cafe, and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Kadina', 'Southern Cross Care SA', '125 Taylor Street', 'Kadina', 'SA', '5554', -33.9633, 137.7150, 'aged-care', 'aged-care', 245000, 405000, 290, 480, 34, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '08 8821 5301', 'kadina@scsa.org.au', 'https://scsa.org.au', 'Yorke Peninsula aged care. Gardens and copper mining heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Sash House', 'Japara Healthcare', '88 Kensington Road', 'Norwood', 'SA', '5067', -34.9200, 138.6350, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '08 8364 5301', 'sashhouse@japara.com.au', 'https://japara.com.au', 'Premium inner Adelaide aged care. Gardens, cafe, and Parade dining.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- WA (4 villages)
('Regis Aged Care Subiaco', 'Regis Aged Care', '125 Hay Street', 'Subiaco', 'WA', '6008', -31.9467, 115.8233, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '08 9381 6301', 'subiaco@regis.com.au', 'https://regis.com.au', 'Premium inner Perth aged care. Pool, gardens, and village atmosphere.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bethanie Esprit Claremont', 'Bethanie Group', '45 Stirling Highway', 'Claremont', 'WA', '6010', -31.9833, 115.7833, 'independent', 'independent', 545000, 865000, 560, 840, 26, '["pool", "gym", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 138, 55, '08 9384 6301', 'claremont@bethanie.com.au', 'https://bethanie.com.au', 'Premium Perth retirement. Pool, gym, and close to Claremont Quarter.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Amana Living Wanneroo', 'Amana Living', '88 Wanneroo Road', 'Wanneroo', 'WA', '6065', -31.7500, 115.8033, 'aged-care', 'aged-care', 355000, 555000, 390, 590, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '08 9405 6301', 'wanneroo@amana.com.au', 'https://amana.com.au', 'Northern Perth growth area aged care. Gardens and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Esperance', 'Opal Aged Care', '15 Pink Lake Road', 'Esperance', 'WA', '6450', -33.8617, 121.8917, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '08 9071 6301', 'esperance@opalcare.com.au', 'https://opalcare.com.au', 'South coast WA aged care. Gardens and pristine beaches nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Regis Aged Care Legana', 'Regis Aged Care', '125 West Tamar Highway', 'Legana', 'TAS', '7277', -41.3667, 147.0333, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '03 6330 7301', 'legana@regis.com.au', 'https://regis.com.au', 'Tamar Valley aged care. Gardens and wine region setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Aged Care MacGregor', 'Goodwin', '45 Hirschfeld Crescent', 'MacGregor', 'ACT', '2615', -35.2117, 149.0117, 'aged-care', 'aged-care', 445000, 685000, 480, 720, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '02 6254 8301', 'macgregor@goodwin.org.au', 'https://goodwin.org.au', 'West Canberra aged care. Gardens, cafe, and close to Belconnen.', 'approved', 'seed_data', true, false, NOW(), NOW());