-- Batch 20: 50 Additional Retirement Villages - Faith-Based & Community Operators
-- Brings total to 905 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW Faith-Based (15 villages)
('BaptistCare Retirement Living Mona Vale', 'BaptistCare NSW & ACT', '88 Barrenjoey Road', 'Mona Vale', 'NSW', '2103', -33.6767, 151.3000, 'independent', 'independent', 625000, 985000, 620, 940, 26, '["pool", "library", "common-room", "chapel", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 136, 55, '02 9979 5501', 'monavale@baptistcare.org.au', 'https://baptistcare.org.au', 'Northern Beaches retirement. Pool, chapel, gardens, and beach lifestyle.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Uniting Retirement Living Turramurra', 'Uniting NSW & ACT', '125 Kissing Point Road', 'Turramurra', 'NSW', '2074', -33.7367, 151.1267, 'independent', 'independent', 665000, 1065000, 660, 1040, 24, '["pool", "gym", "library", "common-room", "garden", "tennis-court"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 148, 60, '02 9488 5501', 'turramurra@uniting.org', 'https://uniting.org', 'Upper North Shore retirement. Pool, gym, tennis court, leafy setting.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Anglicare Retirement Living Epping', 'Anglicare NSW South', '45 Beecroft Road', 'Epping', 'NSW', '2121', -33.7733, 151.0817, 'independent', 'independent', 585000, 925000, 580, 900, 26, '["pool", "library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 132, 55, '02 9876 5501', 'eppingangl@anglicare.com.au', 'https://anglicare.com.au', 'Northwest Sydney retirement. Pool, chapel, gardens, and train hub.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Healthcare Oatlands', 'Catholic Healthcare', '88 Pennant Hills Road', 'Oatlands', 'NSW', '2117', -33.7950, 151.0250, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '02 9683 5501', 'oatlands@catholichealthcare.com.au', 'https://catholichealthcare.com.au', 'Northwest Sydney aged care. Chapel, cafe, gardens, and quality care.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('HammondCare Wahroonga', 'HammondCare', '125 Fox Valley Road', 'Wahroonga', 'NSW', '2076', -33.7183, 151.1117, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '02 9473 5501', 'wahroonga@hammond.com.au', 'https://hammond.com.au', 'Premium Upper North Shore aged care. Pool, cafe, dementia expertise.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Southern Cross Care Daceyville', 'Southern Cross Care NSW & ACT', '15 Bunnerong Road', 'Daceyville', 'NSW', '2032', -33.9317, 151.2267, 'aged-care', 'aged-care', 525000, 795000, 560, 840, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '02 9349 5501', 'daceyville@scrosscc.com.au', 'https://scrosscc.com.au', 'Eastern Suburbs aged care. Chapel, cafe, gardens, and beaches nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health St Joseph''s', 'Mercy Health', '88 Albion Street', 'Harris Park', 'NSW', '2150', -33.8233, 151.0083, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '02 9635 5501', 'stjosephs@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Parramatta aged care. Chapel, gardens, and multicultural services.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Rossmoyne', 'Adventist Aged Care', '125 Burdett Street', 'Wahroonga', 'NSW', '2076', -33.7200, 151.1100, 'aged-care', 'aged-care', 605000, 905000, 640, 920, 24, '["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '02 9487 5501', 'rossmoyne@adventistcare.org.au', 'https://adventistcare.org.au', 'Premium North Shore aged care. Pool, chapel, gardens, holistic care.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Blue Care Wyong', 'Blue Care', '45 Pacific Highway', 'Wyong', 'NSW', '2259', -33.2833, 151.4250, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '02 4352 5501', 'wyong@bluecare.org.au', 'https://bluecare.org.au', 'Central Coast aged care. Gardens and lakeside setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('UnitingCare Ageing Waratah', 'Uniting NSW & ACT', '88 Turton Road', 'Waratah', 'NSW', '2298', -32.9067, 151.7267, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '02 4960 5501', 'waratah@uniting.org', 'https://uniting.org', 'Newcastle aged care. Gardens and city fringe location.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('BaptistCare Aged Care Griffith', 'BaptistCare NSW & ACT', '125 Banna Avenue', 'Griffith', 'NSW', '2680', -34.2883, 146.0500, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '02 6964 5501', 'griffith@baptistcare.org.au', 'https://baptistcare.org.au', 'Riverina aged care. Chapel, gardens, and wine region access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Anglicare Aged Care Coffs Harbour', 'Anglicare NSW South', '15 Park Avenue', 'Coffs Harbour', 'NSW', '2450', -30.3000, 153.1133, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '02 6651 5501', 'coffsharbourangl@anglicare.com.au', 'https://anglicare.com.au', 'Mid North Coast aged care. Chapel, gardens, and coastal lifestyle.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Healthcare Marist Place', 'Catholic Healthcare', '88 Greenacre Road', 'Greenacre', 'NSW', '2190', -33.9000, 151.0533, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '02 9642 5501', 'maristplace@catholichealthcare.com.au', 'https://catholichealthcare.com.au', 'Southwest Sydney aged care. Chapel, cafe, multicultural services.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('HammondCare Hammondville', 'HammondCare', '125 Walder Road', 'Hammondville', 'NSW', '2170', -33.9517, 150.9600, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '02 9825 5501', 'hammondville@hammond.com.au', 'https://hammond.com.au', 'Southwest Sydney aged care. Gardens, cafe, and dementia expertise.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Uniting Retirement Living Denistone', 'Uniting NSW & ACT', '15 Adelaide Street', 'Denistone', 'NSW', '2114', -33.7967, 151.0850, 'independent', 'independent', 625000, 985000, 620, 940, 26, '["pool", "library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 128, 55, '02 9874 5501', 'denistone@uniting.org', 'https://uniting.org', 'Northwest Sydney retirement. Pool, gardens, and leafy suburb.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC Faith-Based (12 villages)
('Benetas Aged Care Canterbury', 'Benetas', '88 Elgar Road', 'Canterbury', 'VIC', '3126', -37.8267, 145.0683, 'aged-care', 'aged-care', 525000, 795000, 560, 840, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '03 9836 6501', 'canterbury@benetas.com.au', 'https://benetas.com.au', 'Inner east aged care. Gardens, cafe, and premium location.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Bethlehem', 'Mercy Health', '125 Victoria Parade', 'Fitzroy', 'VIC', '3065', -37.7983, 144.9833, 'aged-care', 'aged-care', 565000, 855000, 600, 900, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 120, 55, '03 9417 6501', 'bethlehem@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Inner Melbourne aged care. Chapel, cafe, and heritage building.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Uniting AgeWell Brunswick', 'Uniting AgeWell', '45 Sydney Road', 'Brunswick', 'VIC', '3056', -37.7667, 144.9617, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '03 9380 6501', 'brunswick@unitingagewell.org', 'https://unitingagewell.org', 'Inner north aged care. Gardens, cafe, and multicultural community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Homes Heidelberg', 'Catholic Homes', '88 Upper Heidelberg Road', 'Ivanhoe', 'VIC', '3079', -37.7683, 145.0433, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '03 9458 6501', 'heidelberg@catholichomes.com.au', 'https://catholichomes.com.au', 'Northeast aged care. Chapel, cafe, and quality faith-based care.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas Aged Care St Albans', 'Benetas', '125 Main Road', 'St Albans', 'VIC', '3021', -37.7433, 144.8000, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '03 9366 6501', 'stalbans@benetas.com.au', 'https://benetas.com.au', 'West Melbourne aged care. Gardens and multicultural services.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Parkville', 'Mercy Health', '15 Flemington Road', 'Parkville', 'VIC', '3052', -37.7883, 144.9550, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '03 9348 6501', 'parkville@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Inner city aged care. Chapel, cafe, and hospital precinct.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Uniting AgeWell Footscray', 'Uniting AgeWell', '88 Nicholson Street', 'Footscray', 'VIC', '3011', -37.7967, 144.9017, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '03 9689 6501', 'footscrayuniting@unitingagewell.org', 'https://unitingagewell.org', 'West Melbourne aged care. Gardens, cafe, and diverse community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Homes Essendon', 'Catholic Homes', '125 Buckley Street', 'Essendon', 'VIC', '3040', -37.7533, 144.9200, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '03 9379 6501', 'essendon@catholichomes.com.au', 'https://catholichomes.com.au', 'Northwest aged care. Chapel, cafe, and quality faith-based care.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas Aged Care Heidelberg West', 'Benetas', '45 Bell Street', 'Heidelberg West', 'VIC', '3081', -37.7350, 145.0550, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '03 9458 6501', 'heidelbergwest@benetas.com.au', 'https://benetas.com.au', 'Northeast aged care. Gardens and hospital precinct nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Werribee', 'Mercy Health', '88 Watton Street', 'Werribee', 'VIC', '3030', -37.9017, 144.6600, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '03 9749 6501', 'werribee@mercyhealth.com.au', 'https://mercyhealth.com.au', 'West growth area aged care. Chapel, gardens, and hospital nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Uniting AgeWell Sunshine', 'Uniting AgeWell', '125 Furlong Road', 'Sunshine', 'VIC', '3020', -37.7833, 144.8300, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '03 9312 6501', 'sunshine@unitingagewell.org', 'https://unitingagewell.org', 'West Melbourne aged care. Gardens and train hub access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Homes Kew', 'Catholic Homes', '15 Princess Street', 'Kew', 'VIC', '3101', -37.8050, 145.0350, 'aged-care', 'aged-care', 585000, 895000, 620, 940, 26, '["pool", "library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 124, 55, '03 9853 6501', 'kew@catholichomes.com.au', 'https://catholichomes.com.au', 'Premium east aged care. Pool, chapel, cafe, and tree-lined streets.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- QLD Faith-Based (12 villages)
('Blue Care Ashgrove', 'Blue Care', '88 Waterworks Road', 'Ashgrove', 'QLD', '4060', -27.4467, 152.9917, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '07 3366 7501', 'ashgrove@bluecare.org.au', 'https://bluecare.org.au', 'Inner west Brisbane aged care. Gardens, cafe, and leafy suburb.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Brookfield', 'Carinity', '125 Brookfield Road', 'Kenmore Hills', 'QLD', '4069', -27.5050, 152.9367, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 3374 7501', 'brookfield@carinity.org.au', 'https://carinity.org.au', 'Western Brisbane aged care. Chapel, gardens, and scenic hills.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ozcare Keperra', 'Ozcare', '45 Samford Road', 'Keperra', 'QLD', '4054', -27.4000, 152.9533, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '07 3354 7501', 'keperra@ozcare.org.au', 'https://ozcare.org.au', 'Northwest Brisbane aged care. Chapel, gardens, and quality care.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Rosslyn', 'Adventist Aged Care', '88 Rode Road', 'Wavell Heights', 'QLD', '4012', -27.3917, 153.0433, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '07 3266 7501', 'rosslyn@adventistcare.org.au', 'https://adventistcare.org.au', 'North Brisbane aged care. Pool, chapel, gardens, and holistic care.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Sandgate', 'Blue Care', '125 Brighton Road', 'Sandgate', 'QLD', '4017', -27.3217, 153.0683, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '07 3269 7501', 'sandgate@bluecare.org.au', 'https://bluecare.org.au', 'Bayside Brisbane aged care. Gardens and Moreton Bay setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Cedarbrook', 'Carinity', '15 Quinzeh Creek Road', 'Logan Village', 'QLD', '4207', -27.7683, 153.1117, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '07 5546 7501', 'cedarbrook@carinity.org.au', 'https://carinity.org.au', 'Logan aged care. Chapel, gardens, and peaceful rural setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ozcare Labrador', 'Ozcare', '88 Central Street', 'Labrador', 'QLD', '4215', -27.9483, 153.4000, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '07 5528 7501', 'labrador@ozcare.org.au', 'https://ozcare.org.au', 'Gold Coast aged care. Chapel, cafe, and Broadwater access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Sunnybrae', 'Adventist Aged Care', '125 Buderim-Mooloolaba Road', 'Buderim', 'QLD', '4556', -26.6833, 153.0550, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '07 5476 7501', 'sunnybrae@adventistcare.org.au', 'https://adventistcare.org.au', 'Sunshine Coast aged care. Pool, chapel, gardens, and mountain views.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Wynnum', 'Blue Care', '45 Charlotte Street', 'Wynnum', 'QLD', '4178', -27.4383, 153.1683, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 3396 7501', 'wynnum@bluecare.org.au', 'https://bluecare.org.au', 'Bayside Brisbane aged care. Gardens, cafe, and waterfront lifestyle.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Colthup', 'Carinity', '88 Park Ridge Road', 'Park Ridge', 'QLD', '4125', -27.7200, 153.0317, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '07 3805 7501', 'colthupcarinity@carinity.org.au', 'https://carinity.org.au', 'South Brisbane aged care. Chapel, gardens, and peaceful setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ozcare Rochedale', 'Ozcare', '125 Underwood Road', 'Rochedale', 'QLD', '4123', -27.5817, 153.1267, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '07 3341 7501', 'rochedale@ozcare.org.au', 'https://ozcare.org.au', 'South Brisbane aged care. Chapel, gardens, and quality faith-based care.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Holmesville', 'Adventist Aged Care', '15 Elanora Road', 'Elanora', 'QLD', '4221', -28.1233, 153.4300, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '07 5534 7501', 'holmesville@adventistcare.org.au', 'https://adventistcare.org.au', 'South Gold Coast aged care. Pool, chapel, gardens, and beach access.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- SA (5 villages)
('Resthaven Aged Care Leabrook', 'Resthaven', '88 Kensington Road', 'Leabrook', 'SA', '5068', -34.9350, 138.6533, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '08 8333 1001', 'leabrook@resthaven.asn.au', 'https://resthaven.asn.au', 'Premium inner east aged care. Gardens, cafe, and parkside setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Fullarton', 'ACH Group', '125 Fisher Street', 'Fullarton', 'SA', '5063', -34.9517, 138.6117, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '08 8373 1001', 'fullarton@ach.org.au', 'https://ach.org.au', 'Premium inner east aged care. Gardens, cafe, and quality services.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Resthaven Aged Care Malvern', 'Resthaven', '45 Duthy Street', 'Malvern', 'SA', '5061', -34.9583, 138.5817, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '08 8271 1001', 'malvern@resthaven.asn.au', 'https://resthaven.asn.au', 'Inner south aged care. Gardens and heritage suburb charm.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care St Hilarion', 'Southern Cross Care SA', '88 Cross Road', 'St Georges', 'SA', '5064', -34.9500, 138.6067, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '08 8379 1001', 'sthilarion@scsa.org.au', 'https://scsa.org.au', 'Inner Adelaide aged care. Chapel, cafe, and faith-based care.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Woodville', 'ACH Group', '125 Torrens Road', 'Woodville', 'SA', '5011', -34.8733, 138.5433, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '08 8445 1001', 'woodville@ach.org.au', 'https://ach.org.au', 'West Adelaide aged care. Gardens and multicultural services.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- WA (4 villages)
('Bethanie Aged Care Gwelup', 'Bethanie Group', '88 Gwelup Drive', 'Gwelup', 'WA', '6018', -31.8667, 115.7967, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '08 9444 2001', 'gwelup@bethanie.com.au', 'https://bethanie.com.au', 'North Perth aged care. Gardens, cafe, and quality faith-based care.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Carine', 'Amana Living', '125 North Beach Road', 'Carine', 'WA', '6020', -31.8550, 115.7850, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '08 9447 2001', 'carine@amana.com.au', 'https://amana.com.au', 'North Perth aged care. Pool, gardens, and beaches nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bethanie Retirement Living Nollamara', 'Bethanie Group', '45 Morley Drive', 'Nollamara', 'WA', '6061', -31.8783, 115.8600, 'independent', 'independent', 425000, 685000, 420, 680, 30, '["pool", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 118, 55, '08 9349 2001', 'nollamara@bethanie.com.au', 'https://bethanie.com.au', 'Inner north Perth retirement. Pool, gardens, and community living.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Bayswater', 'Amana Living', '88 Guildford Road', 'Bayswater', 'WA', '6053', -31.9167, 115.9183, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '08 9271 2001', 'bayswater@amana.com.au', 'https://amana.com.au', 'East Perth aged care. Gardens and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Regis Aged Care Glenorchy', 'Regis Aged Care', '125 Main Road', 'Glenorchy', 'TAS', '7010', -42.8350, 147.2783, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 90, 55, '03 6272 2101', 'glenorchy@regis.com.au', 'https://regis.com.au', 'North Hobart aged care. Gardens and city fringe location.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Retirement Living Kaleen', 'Goodwin', '15 Maribyrnong Avenue', 'Kaleen', 'ACT', '2617', -35.2283, 149.1017, 'independent', 'independent', 465000, 745000, 460, 740, 28, '["pool", "library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 126, 55, '02 6241 2101', 'kaleen@goodwin.org.au', 'https://goodwin.org.au', 'North Canberra retirement. Pool, gardens, and community facilities.', 'approved', 'seed_data', true, false, NOW(), NOW());
