-- Batch 5: 50 Additional Retirement Villages - National Expansion
-- Brings total to 155 villages

INSERT INTO retirement_villages (
  name,
  operator,
  location,
  suburb,
  state,
  postcode,
  latitude,
  longitude,
  village_type,
  care_level,
  entry_price_min,
  entry_price_max,
  monthly_fees_min,
  monthly_fees_max,
  dmf_percentage,
  amenities,
  care_services,
  bedrooms,
  pet_friendly,
  total_units,
  age_restriction,
  contact_phone,
  contact_email,
  website,
  description,
  status,
  source,
  verified,
  featured,
  submitted_at,
  approved_at
) VALUES

-- NEW SOUTH WALES (15 villages)

('Opal Aged Care Botany', 'Opal Aged Care', '125 Botany Road', 'Botany', 'NSW', '2019', -33.9450, 151.2017, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 104, 55, '02 9316 1111', 'botany@opalcare.com.au', 'https://opalcare.com.au',
'Inner Sydney aged care near airport. Modern facility with gardens and close to shops.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Respect Aged Care Revesby', 'Respect Aged Care', '88 Marco Avenue', 'Revesby', 'NSW', '2212', -33.9550, 151.0167, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 92, 55, '02 9773 2222', 'revesby@respectcare.com.au', 'https://respectcare.com.au',
'Southwest Sydney aged care. Gardens and close to Revesby train station.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Masonic Care Roseville', 'Masonic Homes', '45 Hill Street', 'Roseville', 'NSW', '2069', -33.7850, 151.1783, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 116, 55, '02 9417 3333', 'roseville@masonichomes.com.au', 'https://masonichomes.com.au',
'Upper North Shore premium aged care. Pool, gardens, and close to Roseville village.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('RSL LifeCare Narrabeen', 'RSL LifeCare', '15 Ocean Street', 'Narrabeen', 'NSW', '2101', -33.7117, 151.2967, 'independent', 'independent', 585000, 925000, 580, 860, 26,
'["pool", "gym", "bowling-green", "library", "common-room", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 124, 55, '02 9913 4444', 'narrabeen@rsllifecare.org.au', 'https://rsllifecare.org.au',
'Northern Beaches retirement near ocean. Pool, gym, bowling green, and beach access.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Benetas Ballina', 'Benetas', '88 Cherry Street', 'Ballina', 'NSW', '2478', -28.8667, 153.5667, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32,
'["library", "common-room", "garden", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 76, 55, '02 6686 5555', 'ballina@benetas.com.au', 'https://benetas.com.au',
'North Coast aged care near beaches. Gardens and close to Richmond River.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Villa Maria Catholic Homes Westmead', 'VMCH', '45 Darcy Road', 'Westmead', 'NSW', '2145', -33.8067, 150.9867, 'aged-care', 'aged-care', 475000, 715000, 510, 750, 28,
'["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 98, 55, '02 9891 6666', 'westmead@vmch.com.au', 'https://vmch.com.au',
'Parramatta area Catholic aged care. Chapel, gardens, and close to Westmead Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Japara Anglesea', 'Japara Healthcare', '125 Princess Street', 'Kew', 'NSW', '2439', -31.6333, 152.7167, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 68, 55, '02 6562 7777', 'kew@japara.com.au', 'https://japara.com.au',
'Mid North Coast aged care in Port Macquarie region. Gardens and community atmosphere.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Adventist Aged Care Wahroonga', 'Adventist Aged Care', '15 Fox Valley Road', 'Wahroonga', 'NSW', '2076', -33.7183, 151.1167, 'aged-care', 'aged-care', 595000, 895000, 620, 900, 26,
'["pool", "library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 128, 55, '02 9487 8888', 'wahroonga@adventistcare.org.au', 'https://adventistcare.org.au',
'Premium Upper North Shore aged care. Pool, chapel, gardens, and near San hospital.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Allity Aged Care Campbelltown', 'Allity', '88 Broughton Street', 'Campbelltown', 'NSW', '2560', -34.0650, 150.8167, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 94, 55, '02 4625 9999', 'campbelltown@allity.com.au', 'https://allity.com.au',
'Macarthur region aged care. Gardens and close to Campbelltown Hospital and shopping.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Southern Cross Care Garrawarra', 'Southern Cross Care NSW & ACT', '15 Rawson Avenue', 'Helensburgh', 'NSW', '2508', -34.1817, 150.9933, 'aged-care', 'aged-care', 335000, 535000, 370, 570, 32,
'["library", "common-room", "chapel", "garden", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 84, 55, '02 4294 1000', 'garrawarra@sccliving.org.au', 'https://sccliving.org.au',
'Northern Illawarra aged care in bushland setting. Chapel, gardens, and peaceful environment.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Embracia Aged Care Tamworth', 'Embracia', '45 Marius Street', 'Tamworth', 'NSW', '2340', -31.0917, 150.9333, 'aged-care', 'aged-care', 245000, 405000, 290, 480, 34,
'["library", "common-room", "garden", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 72, 55, '02 6766 1001', 'tamworth@embraciacare.com.au', 'https://embraciacare.com.au',
'Regional NSW aged care. Gardens, BBQ areas, and country hospitality.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Aegis Aged Care Cronulla', 'Aegis', '125 Ewos Parade', 'Cronulla', 'NSW', '2230', -34.0567, 151.1517, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 102, 55, '02 9523 1002', 'cronulla@aegiscare.com.au', 'https://aegiscare.com.au',
'Premium beachside aged care. Pool, gardens, and minutes to Cronulla Beach.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Bupa Aged Care Mosman', 'Bupa', '15 Bradleys Head Road', 'Mosman', 'NSW', '2088', -33.8283, 151.2417, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24,
'["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 124, 55, '02 9960 1003', 'mosman@bupa.com.au', 'https://bupa.com.au',
'Exclusive Lower North Shore aged care. Pool, gym, harbour views, and premium facilities.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Carinity Aged Care Albury', 'Carinity', '88 Dean Street', 'Albury', 'NSW', '2640', -36.0817, 146.9167, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32,
'["library", "common-room", "chapel", "garden", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 88, 55, '02 6021 1004', 'albury@carinity.org.au', 'https://carinity.org.au',
'Murray River aged care. Chapel, gardens, and close to Albury CBD.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('TriCare Aged Care Orange', 'TriCare', '45 Hill Street', 'Orange', 'NSW', '2800', -33.2833, 149.1000, 'aged-care', 'aged-care', 265000, 445000, 310, 510, 34,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 76, 55, '02 6362 1005', 'orange@tricare.com.au', 'https://tricare.com.au',
'Central West aged care. Gardens and close to Orange Base Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- VICTORIA (12 villages)

('Estia Health Heidelberg', 'Estia Health', '15 Burgundy Street', 'Heidelberg', 'VIC', '3084', -37.7583, 145.0617, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 108, 55, '03 9458 2001', 'heidelberg@estiahealth.com.au', 'https://estiahealth.com.au',
'Northeast Melbourne aged care near Austin Hospital. Gardens and cafe.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Regis Aged Care Boronia', 'Regis Aged Care', '88 Dorset Road', 'Boronia', 'VIC', '3155', -37.8633, 145.2833, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 96, 55, '03 9762 2002', 'boronia@regis.com.au', 'https://regis.com.au',
'Eastern suburbs aged care. Pool, gardens, and close to Boronia shops and station.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Arcare Burnside', 'Arcare', '45 Toorak Road', 'South Yarra', 'VIC', '3141', -37.8400, 145.0083, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24,
'["pool", "gym", "library", "common-room", "cinema", "hairdresser", "cafe", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 142, 55, '03 9866 2003', 'burnside@arcare.com.au', 'https://arcare.com.au',
'Premium inner Melbourne aged care. Pool, gym, cinema, and close to Chapel Street.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Bolton Clarke Fawkner', 'Bolton Clarke', '125 Sydney Road', 'Fawkner', 'VIC', '3060', -37.7067, 144.9667, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 92, 55, '03 9359 2004', 'fawkner@boltonclarke.com.au', 'https://boltonclarke.com.au',
'Northern suburbs aged care on Sydney Road. Gardens and tram access.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Bupa Aged Care Templestowe', 'Bupa', '15 James Street', 'Templestowe', 'VIC', '3106', -37.7617, 145.1450, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 104, 55, '03 9846 2005', 'templestowe@bupa.com.au', 'https://bupa.com.au',
'Leafy eastern suburbs aged care. Pool, gardens, and close to Westfield Doncaster.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Opal Aged Care Frankston', 'Opal Aged Care', '88 Nepean Highway', 'Frankston', 'VIC', '3199', -38.1433, 145.1250, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 98, 55, '03 9783 2006', 'frankston@opalcare.com.au', 'https://opalcare.com.au',
'Peninsula aged care. Gardens, cafe, and close to Frankston Hospital and beach.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Benetas St George', 'Benetas', '45 Separation Street', 'Altona', 'VIC', '3018', -37.8683, 144.8333, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 86, 55, '03 9398 2007', 'stgeorge@benetas.com.au', 'https://benetas.com.au',
'Western suburbs beachside aged care. Gardens and close to Altona Beach.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Mecwacare Brighton East', 'Mecwacare', '125 New Street', 'Brighton East', 'VIC', '3187', -37.9117, 145.0083, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 112, 55, '03 9596 2008', 'brightoneast@mecwacare.org.au', 'https://mecwacare.org.au',
'Bayside premium aged care. Pool, gardens, and close to beaches and Bay Street.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Allity Aged Care Bendigo', 'Allity', '15 Barnard Street', 'Bendigo', 'VIC', '3550', -36.7580, 144.2800, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 84, 55, '03 5443 2009', 'bendigo@allity.com.au', 'https://allity.com.au',
'Regional Victoria aged care in historic Bendigo. Gardens and close to city center.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Japara The Grange', 'Japara Healthcare', '88 Grange Road', 'Carnegie', 'VIC', '3163', -37.8867, 145.0550, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 102, 55, '03 9572 2010', 'carnegie@japara.com.au', 'https://japara.com.au',
'Southeast Melbourne aged care. Gardens, cafe, and close to Koornang Road shops.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Wintringham Guildford', 'Wintringham', '45 Moore Street', 'Footscray', 'VIC', '3011', -37.7983, 144.9000, 'aged-care', 'aged-care', 215000, 345000, 260, 420, 36,
'["common-room", "garden", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care"]'::jsonb,
ARRAY['1-bed'], false, 48, 55, '03 9689 2011', 'guildford@wintringham.org.au', 'https://wintringham.org.au',
'Affordable aged care for those in need. Supportive community in Footscray.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Ryman Healthcare Kevin Heinze', 'Ryman Healthcare', '15 Boronia Road', 'Vermont', 'VIC', '3133', -37.8333, 145.1833, 'aged-care', 'aged-care', 485000, 925000, 520, 900, 28,
'["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser", "cafe", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed', '3-bed'], true, 246, 55, '03 9801 2012', 'kevinheinze@rymanhealthcare.com', 'https://rymanhealthcare.com',
'Large premium retirement village in Vermont. Pool, gym, bowling green, cinema, restaurant. Full care.',
'approved', 'seed_data', true, true, NOW(), NOW()),

-- QUEENSLAND (12 villages)

('Regis Aged Care Gympie', 'Regis Aged Care', '88 Mary Street', 'Gympie', 'QLD', '4570', -26.1900, 152.6667, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 74, 55, '07 5482 3001', 'gympie@regis.com.au', 'https://regis.com.au',
'Regional Queensland aged care. Gardens and close to Gympie town center.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Blue Care Chermside', 'Blue Care', '125 Gympie Road', 'Chermside', 'QLD', '4032', -27.3833, 153.0333, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 98, 55, '07 3350 3002', 'chermside@bluecare.org.au', 'https://bluecare.org.au',
'Northside Brisbane aged care. Gardens, cafe, and close to Westfield Chermside.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Opal Aged Care Mermaid Beach', 'Opal Aged Care', '15 Bermuda Street', 'Mermaid Beach', 'QLD', '4218', -28.0450, 153.4333, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26,
'["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 118, 55, '07 5572 3003', 'mermaidbeach@opalcare.com.au', 'https://opalcare.com.au',
'Premium Gold Coast aged care. Pool, gym, and minutes to beach.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('TriCare Aged Care Mount Gravatt', 'TriCare', '45 Logan Road', 'Mount Gravatt', 'QLD', '4122', -27.5283, 153.0817, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 92, 55, '07 3349 3004', 'mtgravatt@tricare.com.au', 'https://tricare.com.au',
'Southeast Brisbane aged care. Gardens and close to Mt Gravatt shopping.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Estia Health Rockhampton', 'Estia Health', '88 Bolsover Street', 'Rockhampton', 'QLD', '4700', -23.3783, 150.5133, 'aged-care', 'aged-care', 265000, 445000, 310, 510, 34,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 76, 55, '07 4927 3005', 'rockhampton@estiahealth.com.au', 'https://estiahealth.com.au',
'Central Queensland aged care. Gardens and close to Rockhampton Base Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Bolton Clarke Ashgrove', 'Bolton Clarke', '15 Waterworks Road', 'Ashgrove', 'QLD', '4060', -27.4450, 152.9950, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 104, 55, '07 3366 3006', 'ashgrove@boltonclarke.com.au', 'https://boltonclarke.com.au',
'Inner Brisbane aged care in leafy Ashgrove. Gardens and close to shops.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Adventist Aged Care Southport', 'Adventist Aged Care', '125 Nerang Street', 'Southport', 'QLD', '4215', -27.9683, 153.4000, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28,
'["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 108, 55, '07 5532 3007', 'southport@adventistcare.org.au', 'https://adventistcare.org.au',
'Central Gold Coast aged care. Pool, chapel, gardens, and close to Australia Fair.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Ozcare Bundaberg', 'Ozcare', '45 Bourbong Street', 'Bundaberg', 'QLD', '4670', -24.8667, 152.3500, 'aged-care', 'aged-care', 245000, 405000, 290, 480, 34,
'["library", "common-room", "chapel", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 68, 55, '07 4151 3008', 'bundaberg@ozcare.org.au', 'https://ozcare.org.au',
'Regional Queensland aged care. Chapel, gardens, and close to Bundaberg Base Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Regis Aged Care Mackay', 'Regis Aged Care', '15 Shakespeare Street', 'Mackay', 'QLD', '4740', -21.1417, 149.1833, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32,
'["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 82, 55, '07 4957 3009', 'mackay@regis.com.au', 'https://regis.com.au',
'North Queensland aged care. Pool, gardens, and tropical setting.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Carinity Aged Care Wishart', 'Carinity', '88 Wishart Road', 'Wishart', 'QLD', '4122', -27.5517, 153.0950, 'aged-care', 'aged-care', 415000, 615000, 450, 650, 30,
'["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 96, 55, '07 3349 3010', 'wishart@carinity.org.au', 'https://carinity.org.au',
'Southeast Brisbane aged care. Pool, chapel, and gardens.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Allity Aged Care Nambour', 'Allity', '125 Currie Street', 'Nambour', 'QLD', '4560', -26.6267, 152.9600, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 78, 55, '07 5441 3011', 'nambour@allity.com.au', 'https://allity.com.au',
'Sunshine Coast hinterland aged care. Gardens and close to Nambour Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Southern Cross Care Wynnum', 'Southern Cross Care QLD', '45 Bay Terrace', 'Wynnum', 'QLD', '4178', -27.4417, 153.1717, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 94, 55, '07 3396 3012', 'wynnum@scrosscc.com.au', 'https://scrosscc.com.au',
'Bayside Brisbane aged care. Gardens, cafe, and close to Moreton Bay waterfront.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- SOUTH AUSTRALIA (5 villages)

('Regis Aged Care Morphett Vale', 'Regis Aged Care', '88 Main South Road', 'Morphett Vale', 'SA', '5162', -35.1267, 138.5183, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 86, 55, '08 8382 4001', 'morphettvale@regis.com.au', 'https://regis.com.au',
'Southern Adelaide aged care. Gardens and close to Colonnades Shopping Centre.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Japara Arberfield', 'Japara Healthcare', '15 Henley Beach Road', 'Mile End', 'SA', '5031', -34.9267, 138.5667, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 102, 55, '08 8234 4002', 'arberfield@japara.com.au', 'https://japara.com.au',
'Inner Adelaide aged care on Henley Beach Road. Gardens and close to city.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('ACH Group Milpara', 'ACH Group', '45 Partridge Street', 'Goolwa', 'SA', '5214', -35.5017, 138.7817, 'aged-care', 'aged-care', 265000, 425000, 310, 490, 34,
'["library", "common-room", "garden", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 72, 55, '08 8555 4003', 'milpara@ach.org.au', 'https://ach.org.au',
'Fleurieu Peninsula aged care near Murray River mouth. Gardens and river views.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Southern Cross Care Oakwood', 'Southern Cross Care SA', '125 North East Road', 'Modbury', 'SA', '5092', -34.8333, 138.6833, 'aged-care', 'aged-care', 415000, 615000, 450, 650, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 108, 55, '08 8264 4004', 'oakwood@scsa.org.au', 'https://scsa.org.au',
'Northeast Adelaide aged care. Gardens, cafe, dementia unit, and close to Tea Tree Plaza.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Estia Health Mount Barker', 'Estia Health', '15 Gawler Street', 'Mount Barker', 'SA', '5251', -35.0667, 138.8667, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 84, 55, '08 8391 4005', 'mtbarker@estiahealth.com.au', 'https://estiahealth.com.au',
'Adelaide Hills aged care. Gardens and close to Mount Barker town center.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- WESTERN AUSTRALIA (4 villages)

('Regis Aged Care South Perth', 'Regis Aged Care', '88 Angelo Street', 'South Perth', 'WA', '6151', -31.9833, 115.8667, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 116, 55, '08 9367 5001', 'southperth@regis.com.au', 'https://regis.com.au',
'Premium Perth aged care with river views. Pool, gardens, and close to zoo.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Bethanie Esprit Alkimos', 'Bethanie Group', '45 Marmion Avenue', 'Alkimos', 'WA', '6038', -31.6333, 115.6833, 'independent', 'independent', 345000, 565000, 360, 560, 32,
'["pool", "gym", "library", "common-room", "bbq-area", "workshop"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 136, 55, '08 9562 5002', 'alkimos@bethanie.com.au', 'https://bethanie.com.au',
'Coastal retirement north of Perth. Pool, gym, and close to beaches.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Amana Living Bunbury', 'Amana Living', '125 Spencer Street', 'Bunbury', 'WA', '6230', -33.3267, 115.6400, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 88, 55, '08 9721 5003', 'bunbury@amana.com.au', 'https://amana.com.au',
'Southwest WA aged care. Gardens and close to Bunbury city center.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Opal Aged Care Geraldton', 'Opal Aged Care', '15 Marine Terrace', 'Geraldton', 'WA', '6530', -28.7767, 114.6133, 'aged-care', 'aged-care', 265000, 425000, 310, 490, 34,
'["library", "common-room", "garden", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 76, 55, '08 9921 5004', 'geraldton@opalcare.com.au', 'https://opalcare.com.au',
'Regional WA coastal aged care. Gardens and ocean views.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- TASMANIA (1 village)

('Regis Aged Care Hobart', 'Regis Aged Care', '45 Sandy Bay Road', 'Sandy Bay', 'TAS', '7005', -42.8950, 147.3283, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 92, 55, '03 6223 6001', 'hobart@regis.com.au', 'https://regis.com.au',
'Sandy Bay aged care near University of Tasmania. Gardens and water views.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- AUSTRALIAN CAPITAL TERRITORY (1 village)

('Goodwin Aged Care Ainslie', 'Goodwin', '125 Majura Avenue', 'Ainslie', 'ACT', '2602', -35.2633, 149.1450, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 104, 55, '02 6248 7001', 'ainslie@goodwin.org.au', 'https://goodwin.org.au',
'Inner Canberra aged care. Gardens, cafe, and close to city center.',
'approved', 'seed_data', true, false, NOW(), NOW());
