-- Batch 2: 30 Additional Retirement Villages Across Australia
-- Brings total to 45 villages with expanded geographic coverage

INSERT INTO retirement_villages (
  name,
  operator,
  location,
  suburb,
  state,
  postcode,
  latitude,
  longitude,
  village_type,
  care_level,
  entry_price_min,
  entry_price_max,
  monthly_fees_min,
  monthly_fees_max,
  dmf_percentage,
  amenities,
  care_services,
  bedrooms,
  pet_friendly,
  total_units,
  age_restriction,
  contact_phone,
  contact_email,
  website,
  description,
  status,
  source,
  verified,
  featured,
  submitted_at,
  approved_at
) VALUES

-- NEW SOUTH WALES (10 villages)

('Aveo Freedom Aged Care Baulkham Hills', 'Aveo Group', '12-14 Renown Avenue', 'Baulkham Hills', 'NSW', '2153', -33.7617, 150.9942, 'aged-care', 'aged-care', 520000, 780000, 580, 820, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 108, 55, '02 9639 8888', 'baulkhamhills@aveo.com.au', 'https://aveo.com.au',
'Premium aged care in Sydney''s Hills District. Modern suites with full care services, beautiful gardens, and close to Castle Towers shopping center.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Lendlease Retirement Living Macquarie Park', 'Lendlease', '88 Talavera Road', 'Macquarie Park', 'NSW', '2113', -33.7783, 151.1183, 'independent', 'independent', 650000, 1100000, 620, 920, 28,
'["pool", "gym", "cinema", "library", "common-room", "workshop", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 186, 55, '02 9878 5555', 'macquariepark@lendlease.com', 'https://lendlease.com',
'Contemporary retirement living near Macquarie University and shopping center. Modern apartments with resort facilities including pool, gym, and cinema.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('IRT Tarran Point', 'IRT Group', '2-8 Downing Street', 'Tarran Point', 'NSW', '2428', -32.3733, 152.4833, 'assisted', 'assisted', 285000, 485000, 320, 520, 32,
'["pool", "bowling-green", "library", "common-room", "bbq-area", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb,
ARRAY['1-bed', '2-bed', '3-bed'], true, 94, 55, '02 4997 2222', 'tarranpoint@irt.org.au', 'https://irt.org.au',
'Lakeside retirement village on the Mid North Coast. Independent villas and serviced apartments with water views, pool, and bowling green.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Southern Cross Care Nagle', 'Southern Cross Care NSW & ACT', '202 Addison Road', 'Marrickville', 'NSW', '2204', -33.9042, 151.1542, 'aged-care', 'aged-care', 480000, 720000, 520, 760, 30,
'["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 122, 55, '02 9564 3333', 'nagle@sccliving.org.au', 'https://sccliving.org.au',
'Inner-west Sydney aged care facility with strong community focus. Modern rooms, chapel, and close to cafes and parks.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Opal Aged Care Miranda', 'Opal Aged Care', '15-25 Kiora Road', 'Miranda', 'NSW', '2228', -34.0342, 151.1008, 'aged-care', 'aged-care', 495000, 745000, 540, 780, 28,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 136, 55, '02 9524 4444', 'miranda@opalcare.com.au', 'https://opalcare.com.au',
'Modern aged care in the Sutherland Shire. Close to Westfield Miranda and public transport. Pool, gardens, and quality care services.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Uniting Gowrie', 'Uniting NSW & ACT', '37 Gowrie Avenue', 'Punchbowl', 'NSW', '2196', -33.9283, 151.0508, 'assisted', 'assisted', 365000, 565000, 380, 580, 30,
'["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb,
ARRAY['1-bed', '2-bed'], true, 88, 55, '02 9750 5555', 'gowrie@uniting.org', 'https://uniting.org',
'Established retirement village in Sydney''s southwest. Independent units and serviced apartments with community center and regular activities.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Respect Aged Care Kingswood', 'Respect Aged Care', '45 Station Street', 'Kingswood', 'NSW', '2747', -33.7617, 150.7217, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 32,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 96, 55, '02 4732 6666', 'kingswood@respectcare.com.au', 'https://respectcare.com.au',
'Quality aged care in Western Sydney. Modern facility with gardens, cafe, and close to Nepean Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Eureka Benevolent Society Hunters Hill', 'Eureka Benevolent Society', '22 Ryde Road', 'Hunters Hill', 'NSW', '2110', -33.8342, 151.1408, 'independent', 'independent', 580000, 920000, 560, 840, 26,
'["pool", "gym", "library", "common-room", "bbq-area", "garden"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 64, 55, '02 9817 7777', 'huntershill@eurekacare.com.au', 'https://eurekacare.com.au',
'Exclusive waterfront retirement living on the Parramatta River. Premium apartments with harbour views, pool, and gym.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Wesley Mission Ashfield', 'Wesley Mission', '55 Liverpool Road', 'Ashfield', 'NSW', '2131', -33.8883, 151.1267, 'assisted', 'assisted', 465000, 685000, 480, 680, 30,
'["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 78, 55, '02 9799 8888', 'ashfield@wesleymission.org.au', 'https://wesleymission.org.au',
'Inner-west retirement village with strong faith community. Close to train station, shops, and medical facilities.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Korian Cherrybrook', 'Korian Australia', '12-18 Shepherds Drive', 'Cherrybrook', 'NSW', '2126', -33.7167, 151.0467, 'aged-care', 'aged-care', 515000, 765000, 560, 800, 28,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 114, 55, '02 9484 9999', 'cherrybrook@korian.com.au', 'https://korian.com.au',
'Modern aged care in the Hills District. Premium facility with pool, landscaped gardens, and specialized dementia care.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- VICTORIA (8 villages)

('Bolton Clarke Woodlands', 'Bolton Clarke', '155 Warrigal Road', 'Burwood', 'VIC', '3125', -37.8517, 145.1133, 'aged-care', 'aged-care', 520000, 780000, 580, 820, 28,
'["pool", "gym", "library", "common-room", "hairdresser", "cafe", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 148, 55, '03 9808 1111', 'woodlands@boltonclarke.com.au', 'https://boltonclarke.com.au',
'Premium aged care in inner Melbourne. Modern facility with pool, gym, and easy access to Deakin University and Burwood Highway shopping.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Arcare Maidstone', 'Arcare', '88 Langs Road', 'Maidstone', 'VIC', '3012', -37.7767, 144.8833, 'aged-care', 'aged-care', 445000, 645000, 480, 680, 30,
'["library", "common-room", "cinema", "hairdresser", "cafe", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 126, 55, '03 9317 2222', 'maidstone@arcare.com.au', 'https://arcare.com.au',
'Modern aged care in Melbourne''s west. Cinema room, cafe, and memory support unit. Close to Highpoint Shopping Centre.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Allity Aged Care Grange', 'Allity', '75 The Avenue', 'Coburg', 'VIC', '3058', -37.7350, 144.9650, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 102, 55, '03 9354 3333', 'grange@allity.com.au', 'https://allity.com.au',
'Established aged care facility in Melbourne''s north. Close to Sydney Road shops and trams. Caring staff and family atmosphere.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Bupa Aged Care Traralgon', 'Bupa', '35 Kay Street', 'Traralgon', 'VIC', '3844', -38.1967, 146.5400, 'aged-care', 'aged-care', 295000, 445000, 350, 520, 32,
'["library", "common-room", "garden", "hairdresser", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 84, 55, '03 5174 4444', 'traralgon@bupa.com.au', 'https://bupa.com.au',
'Regional aged care in Gippsland. Friendly community atmosphere with gardens and regular social activities.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Mecwacare Bundoora', 'Mecwacare', '188 Main Drive', 'Bundoora', 'VIC', '3083', -37.7133, 145.0550, 'assisted', 'assisted', 385000, 585000, 400, 600, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb,
ARRAY['1-bed', '2-bed'], true, 92, 55, '03 9468 5555', 'bundoora@mecwacare.org.au', 'https://mecwacare.org.au',
'Retirement village near La Trobe University. Independent units with support services available. Close to parklands and shopping.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Regis Aged Care Northgate', 'Regis Aged Care', '96 Separation Street', 'Northcote', 'VIC', '3070', -37.7717, 144.9983, 'aged-care', 'aged-care', 540000, 820000, 600, 860, 26,
'["pool", "gym", "library", "common-room", "hairdresser", "cafe", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 132, 55, '03 9482 6666', 'northgate@regis.com.au', 'https://regis.com.au',
'Inner-city Melbourne aged care. Premium facility with pool, gym, and rooftop garden. Close to High Street shops and trams.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Wintringham Port Melbourne Hostel', 'Wintringham', '22 Pickles Street', 'Port Melbourne', 'VIC', '3207', -37.8400, 144.9383, 'aged-care', 'aged-care', 195000, 325000, 280, 420, 35,
'["common-room", "garden", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care"]'::jsonb,
ARRAY['1-bed'], false, 42, 55, '03 9696 7777', 'portmelbourne@wintringham.org.au', 'https://wintringham.org.au',
'Affordable aged care hostel for those in need. Supportive community near the beach and Station Pier.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Seasons Aged Care Ringwood', 'Seasons Aged Care', '45 Oban Road', 'Ringwood', 'VIC', '3134', -37.8133, 145.2283, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 98, 55, '03 9870 8888', 'ringwood@seasonsagedcare.com.au', 'https://seasonsagedcare.com.au',
'Quality aged care in Melbourne''s east. Close to Eastland Shopping Centre and trains. Gardens and community activities.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- QUEENSLAND (6 villages)

('Regis Aged Care Redcliffe', 'Regis Aged Care', '55 Maine Road', 'Clontarf', 'QLD', '4019', -27.2467, 153.0767, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28,
'["pool", "library", "common-room", "hairdresser", "cafe", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 118, 55, '07 3284 1111', 'redcliffe@regis.com.au', 'https://regis.com.au',
'Bayside aged care on the Redcliffe Peninsula. Pool, gardens, and close to Moreton Bay waterfront.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('TriCare Aged Care Runaway Bay', 'TriCare', '123 Bayview Street', 'Runaway Bay', 'QLD', '4216', -27.9117, 153.3917, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28,
'["pool", "gym", "bowling-green", "library", "common-room", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 142, 55, '07 5537 2222', 'runawaybay@tricare.com.au', 'https://tricare.com.au',
'Premium Gold Coast aged care with water views. Pool, gym, bowling green, and close to Harbourtown shopping.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Blue Care Stafford', 'Blue Care', '88 Kitchener Road', 'Stafford', 'QLD', '4053', -27.4183, 153.0117, 'assisted', 'assisted', 395000, 595000, 420, 620, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb,
ARRAY['1-bed', '2-bed'], true, 86, 55, '07 3356 3333', 'stafford@bluecare.org.au', 'https://bluecare.org.au',
'Brisbane northside retirement village. Independent units and serviced apartments with community support.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Oceania Care Company Kawana Waters', 'Oceania Care Company', '6 Sportsmans Parade', 'Bokarina', 'QLD', '4575', -26.7567, 153.1317, 'independent', 'independent', 425000, 725000, 440, 680, 28,
'["pool", "gym", "bowling-green", "library", "common-room", "bbq-area", "workshop"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 156, 55, '07 5493 4444', 'kawana@oceanicare.com.au', 'https://oceanicare.com.au',
'Sunshine Coast retirement living near beaches. Modern villas with pool, gym, bowling green, and close to Kawana Shoppingworld.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Ozcare Labrador', 'Ozcare', '45 Frank Street', 'Labrador', 'QLD', '4215', -27.9467, 153.3950, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30,
'["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 104, 55, '07 5528 5555', 'labrador@ozcare.org.au', 'https://ozcare.org.au',
'Gold Coast aged care with chapel and community focus. Close to Broadwater and Australia Fair shopping.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Adventist Aged Care Rossiter', 'Adventist Aged Care', '88 Chaston Street', 'Manly', 'QLD', '4179', -27.4617, 153.1817, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28,
'["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 96, 55, '07 3396 6666', 'rossiter@adventistcare.org.au', 'https://adventistcare.org.au',
'Bayside Brisbane aged care in Manly. Faith-based community with pool, gardens, and close to waterfront.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- SOUTH AUSTRALIA (3 villages)

('ECH Fullarton', 'ECH', '275 Fullarton Road', 'Fullarton', 'SA', '5063', -34.9550, 138.6217, 'assisted', 'assisted', 385000, 585000, 400, 600, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb,
ARRAY['1-bed', '2-bed'], true, 74, 55, '08 8232 1111', 'fullarton@ech.asn.au', 'https://ech.asn.au',
'Inner Adelaide retirement village on Fullarton Road. Independent units with support services and close to shops and cafes.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Helping Hand Walkerville', 'Helping Hand', '88 Smith Street', 'Walkerville', 'SA', '5081', -34.8967, 138.6117, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 88, 55, '08 8269 2222', 'walkerville@helpinghand.org.au', 'https://helpinghand.org.au',
'Premium aged care in leafy Walkerville. Heritage charm with modern care facilities and beautiful gardens.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Resthaven Paradise', 'Resthaven', '45 Silkes Road', 'Paradise', 'SA', '5075', -34.8783, 138.6783, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30,
'["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 92, 55, '08 8336 3333', 'paradise@resthaven.asn.au', 'https://resthaven.asn.au',
'Adelaide north-east aged care. Established facility with chapel, gardens, and caring community atmosphere.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- WESTERN AUSTRALIA (2 villages)

('Bethanie Beachside', 'Bethanie Group', '88 Beach Road', 'Coogee', 'WA', '6166', -32.1167, 115.7667, 'independent', 'independent', 425000, 725000, 440, 680, 28,
'["pool", "gym", "bowling-green", "library", "common-room", "bbq-area"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 128, 55, '08 9434 1111', 'beachside@bethanie.com.au', 'https://bethanie.com.au',
'Coastal retirement living near Coogee Beach. Modern villas with pool, gym, and short walk to the ocean.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Amana Living Marangaroo', 'Amana Living', '15 Girrawheen Avenue', 'Marangaroo', 'WA', '6064', -31.8333, 115.8333, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 96, 55, '08 9405 2222', 'marangaroo@amana.com.au', 'https://amana.com.au',
'Perth northern suburbs aged care. Caring staff, gardens, and close to Kingsway Shopping Centre.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- AUSTRALIAN CAPITAL TERRITORY (1 village)

('Goodwin Aged Care Farrer', 'Goodwin', '35 Larakia Street', 'Farrer', 'ACT', '2607', -35.3783, 149.1050, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 108, 55, '02 6175 1111', 'farrer@goodwin.org.au', 'https://goodwin.org.au',
'Canberra south aged care facility. Modern care center with specialized dementia unit and beautiful gardens.',
'approved', 'seed_data', true, false, NOW(), NOW());
