-- Batch 7: 50 Additional Retirement Villages
-- Brings total to 255 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW (15 villages)
('Lendlease Retirement Living Manly', 'Lendlease', '15 Raglan Street', 'Manly', 'NSW', '2095', -33.7983, 151.2850, 'independent', 'independent', 685000, 1250000, 680, 1020, 24, '["pool", "gym", "cinema", "library", "common-room"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 142, 55, '02 9977 1111', 'manly@lendlease.com', 'https://lendlease.com', 'Premium beachside retirement. Pool, gym, cinema, and walk to Manly Beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Merrimac', 'Stockland', '88 Gooding Drive', 'Merrimac', 'QLD', '4226', -28.0567, 153.3783, 'independent', 'independent', 445000, 725000, 460, 720, 28, '["pool", "gym", "library", "common-room", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 156, 55, '07 5578 2001', 'merrimac@stockland.com.au', 'https://stockland.com', 'Gold Coast retirement near theme parks. Pool, gym, and family-friendly location.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Belmont', 'Opal Aged Care', '45 Macquarie Road', 'Belmont', 'NSW', '2280', -33.0333, 151.6667, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '02 4945 3001', 'belmont@opalcare.com.au', 'https://opalcare.com.au', 'Lake Macquarie aged care near beaches. Gardens and waterfront access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Hornsby', 'Regis Aged Care', '125 Peats Ferry Road', 'Hornsby', 'NSW', '2077', -33.7033, 151.0983, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '02 9476 4001', 'hornsby@regis.com.au', 'https://regis.com.au', 'Upper North Shore aged care. Pool, gardens, and train access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Bexley', 'Estia Health', '15 Forest Road', 'Bexley', 'NSW', '2207', -33.9517, 151.1167, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '02 9567 5001', 'bexley@estiahealth.com.au', 'https://estiahealth.com.au', 'St George area aged care. Gardens and close to Rockdale Plaza.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare North Shore', 'Arcare', '88 Pacific Highway', 'St Leonards', 'NSW', '2065', -33.8233, 151.1950, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "gym", "library", "common-room", "cinema", "hairdresser", "cafe", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 136, 55, '02 9439 6001', 'northshore@arcare.com.au', 'https://arcare.com.au', 'Premium North Sydney aged care. Pool, gym, cinema, and train access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Blue Care Newcastle', 'Blue Care', '45 Hunter Street', 'Newcastle', 'NSW', '2300', -32.9267, 151.7817, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '02 4929 7001', 'newcastle@bluecare.org.au', 'https://bluecare.org.au', 'Newcastle city aged care. Gardens and close to beach and harbor.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Healthcare Lewisham', 'Catholic Healthcare', '125 Norton Street', 'Lewisham', 'NSW', '2049', -33.8950, 151.1433, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '02 9560 8001', 'lewisham@catholichealthcare.com.au', 'https://catholichealthcare.com.au', 'Inner west aged care. Chapel, gardens, and close to Norton Street cafes.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('HammondCare Castle Hill', 'HammondCare', '15 Showground Road', 'Castle Hill', 'NSW', '2154', -33.7317, 151.0017, 'aged-care', 'aged-care', 495000, 745000, 530, 780, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '02 9899 9001', 'castlehill@hammond.com.au', 'https://hammond.com.au', 'Hills District specialist aged care. Dementia care and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Whiddon Argyle', 'Whiddon Group', '88 Argyle Street', 'Camden', 'NSW', '2570', -34.0567, 150.6967, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 32, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '02 4655 1002', 'argyle@whiddon.com.au', 'https://whiddon.com.au', 'Macarthur region aged care. Gardens and historic Camden setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Anglicare Epping', 'Anglicare Sydney', '45 Bridge Street', 'Epping', 'NSW', '2121', -33.7717, 151.0817, 'assisted', 'assisted', 465000, 685000, 480, 700, 28, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb, ARRAY['1-bed', '2-bed'], true, 92, 55, '02 9869 2002', 'epping@anglicare.org.au', 'https://anglicare.org.au', 'Northwest Sydney retirement. Chapel, gardens, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Goulburn', 'Estia Health', '125 Sloane Street', 'Goulburn', 'NSW', '2580', -34.7517, 149.7183, 'aged-care', 'aged-care', 245000, 405000, 290, 480, 34, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '02 4821 3002', 'goulburn@estiahealth.com.au', 'https://estiahealth.com.au', 'Southern Tablelands aged care. Gardens and historic regional city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('RSL LifeCare Mona Vale', 'RSL LifeCare', '125 Pittwater Road', 'Mona Vale', 'NSW', '2103', -33.6800, 151.3050, 'independent', 'independent', 625000, 985000, 600, 900, 26, '["pool", "bowling-green", "library", "common-room", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 132, 55, '02 9979 4003', 'monavale@rsllifecare.org.au', 'https://rsllifecare.org.au', 'Premium Northern Beaches retirement. Pool, bowling green, and beach access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Uniting Naremburn', 'Uniting NSW & ACT', '15 Central Street', 'Naremburn', 'NSW', '2065', -33.8183, 151.2000, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '02 9437 5003', 'naremburn@uniting.org', 'https://uniting.org', 'Lower North Shore aged care. Gardens, cafe, and close to harbour.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Cooinda', 'Japara Healthcare', '88 Wyong Road', 'Tuggerah', 'NSW', '2259', -33.3083, 151.4167, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '02 4355 6003', 'cooinda@japara.com.au', 'https://japara.com.au', 'Central Coast aged care. Gardens and close to Westfield Tuggerah.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC (12 villages)
('Regis Aged Care Brighton', 'Regis Aged Care', '125 New Street', 'Brighton', 'VIC', '3186', -37.9083, 145.0000, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '03 9592 7001', 'brighton@regis.com.au', 'https://regis.com.au', 'Premium bayside aged care. Pool, gardens, and minutes to beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Geelong West', 'Estia Health', '45 Pakington Street', 'Geelong West', 'VIC', '3218', -38.1367, 144.3450, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '03 5229 8001', 'geelongwest@estiahealth.com.au', 'https://estiahealth.com.au', 'Central Geelong aged care. Gardens and close to Pakington Street shops.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Sydenham', 'Arcare', '88 Centreway', 'Sydenham', 'VIC', '3037', -37.6967, 144.7667, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30, '["pool", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '03 9390 9001', 'sydenham@arcare.com.au', 'https://arcare.com.au', 'Northwest Melbourne aged care. Pool, cinema, and close to shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bupa Aged Care Toorak', 'Bupa', '15 Clendon Road', 'Toorak', 'VIC', '3142', -37.8400, 145.0217, 'aged-care', 'aged-care', 685000, 1050000, 720, 1040, 22, '["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '03 9826 1001', 'toorak@bupa.com.au', 'https://bupa.com.au', 'Exclusive inner Melbourne aged care. Pool, gym, and premium location.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bolton Clarke Camberwell', 'Bolton Clarke', '125 Burke Road', 'Camberwell', 'VIC', '3124', -37.8283, 145.0583, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '03 9889 2001', 'camberwell@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Inner east Melbourne aged care. Pool, gardens, and tram access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Opal Aged Care Dandenong', 'Opal Aged Care', '45 Foster Street', 'Dandenong', 'VIC', '3175', -38.0000, 145.2167, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '03 9792 3001', 'dandenong@opalcare.com.au', 'https://opalcare.com.au', 'Southeast Melbourne aged care. Gardens and close to Dandenong Market.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Sandringham', 'Regis Aged Care', '88 Beach Road', 'Sandringham', 'VIC', '3191', -37.9517, 145.0050, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '03 9598 4001', 'sandringham@regis.com.au', 'https://regis.com.au', 'Premium bayside aged care. Pool, gardens, and beach access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Wonthaggi', 'Estia Health', '15 White Road', 'Wonthaggi', 'VIC', '3995', -38.6067, 145.5900, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '03 5672 5001', 'wonthaggi@estiahealth.com.au', 'https://estiahealth.com.au', 'Bass Coast aged care. Gardens and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas Footscray', 'Benetas', '125 Barkly Street', 'Footscray', 'VIC', '3011', -37.7983, 144.9017, 'aged-care', 'aged-care', 415000, 615000, 450, 650, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '03 9687 6001', 'footscray@benetas.com.au', 'https://benetas.com.au', 'Inner west aged care. Gardens and close to Footscray Market.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Goulburn Valley', 'Japara Healthcare', '45 Fryers Street', 'Echuca', 'VIC', '3564', -36.1400, 144.7517, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '03 5482 7001', 'echuca@japara.com.au', 'https://japara.com.au', 'Murray River aged care. Gardens and historic paddle steamer port.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Albury', 'Mercy Health', '88 Dean Street', 'Albury', 'VIC', '3690', -36.0817, 146.9150, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '02 6041 8001', 'albury@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Border city aged care. Chapel, gardens, and close to CBD.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ryman Healthcare Weary Dunlop II', 'Ryman Healthcare', '88 Chirnside Park Way', 'Chirnside Park', 'VIC', '3116', -37.7333, 145.3167, 'aged-care', 'aged-care', 465000, 885000, 500, 860, 28, '["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 234, 55, '03 9727 9001', 'chirnsidepark@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Large Yarra Valley retirement village. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- QLD (12 villages)
('Regis Aged Care Buderim', 'Regis Aged Care', '125 Burnett Street', 'Buderim', 'QLD', '4556', -26.6867, 153.0567, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '07 5445 1001', 'buderim@regis.com.au', 'https://regis.com.au', 'Sunshine Coast hinterland aged care. Pool, gardens, and village atmosphere.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Redcliffe', 'Blue Care', '45 Anzac Avenue', 'Redcliffe', 'QLD', '4020', -27.2283, 153.1083, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '07 3284 2001', 'redcliffe@bluecare.org.au', 'https://bluecare.org.au', 'Bayside Brisbane aged care. Gardens and close to waterfront.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Robina', 'Opal Aged Care', '88 Robina Town Centre Drive', 'Robina', 'QLD', '4226', -28.0783, 153.3783, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '07 5562 3001', 'robina@opalcare.com.au', 'https://opalcare.com.au', 'Gold Coast aged care. Pool, gym, and close to Robina Town Centre.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('TriCare Aged Care Bracken Ridge', 'TriCare', '15 Norris Road', 'Bracken Ridge', 'QLD', '4017', -27.3167, 153.0333, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '07 3261 4001', 'brackenridge@tricare.com.au', 'https://tricare.com.au', 'North Brisbane aged care. Gardens and close to shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Bundamba', 'Estia Health', '125 Brisbane Road', 'Bundamba', 'QLD', '4304', -27.6167, 152.7667, 'aged-care', 'aged-care', 315000, 515000, 350, 550, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '07 3281 5001', 'bundamba@estiahealth.com.au', 'https://estiahealth.com.au', 'Ipswich aged care. Gardens and close to Ipswich CBD.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Caloundra', 'Bolton Clarke', '45 Pelican Waters Boulevard', 'Caloundra', 'QLD', '4551', -26.7983, 153.1317, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '07 5491 6001', 'caloundra@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Sunshine Coast aged care near beaches. Pool, gardens, and waterways.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Coorparoo', 'Adventist Aged Care', '88 Cavendish Road', 'Coorparoo', 'QLD', '4151', -27.4983, 153.0600, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '07 3397 7001', 'coorparoo@adventistcare.org.au', 'https://adventistcare.org.au', 'Inner Brisbane aged care. Chapel, gardens, and close to CBD.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ozcare Palm Beach', 'Ozcare', '15 Fifth Avenue', 'Palm Beach', 'QLD', '4221', -28.1200, 153.4667, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '07 5534 8001', 'palmbeach@ozcare.org.au', 'https://ozcare.org.au', 'Premium Gold Coast beachside aged care. Pool, gardens, and ocean access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Aged Care Mooloolaba', 'Regis Aged Care', '125 Brisbane Road', 'Mooloolaba', 'QLD', '4557', -26.6817, 153.1200, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 5444 9001', 'mooloolaba@regis.com.au', 'https://regis.com.au', 'Beachside Sunshine Coast aged care. Pool, cafe, and walk to beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Carinity Aged Care Colthup', 'Carinity', '45 Samsonvale Road', 'Strathpine', 'QLD', '4500', -27.3000, 152.9833, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '07 3205 1002', 'colthup@carinity.org.au', 'https://carinity.org.au', 'North Brisbane aged care. Chapel, gardens, and community focus.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Beenleigh', 'Allity', '88 City Road', 'Beenleigh', 'QLD', '4207', -27.7133, 153.2033, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '07 3807 2002', 'beenleigh@allity.com.au', 'https://allity.com.au', 'Logan region aged care. Gardens and close to train station.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Upper Mount Gravatt', 'Southern Cross Care QLD', '125 Newnham Road', 'Upper Mount Gravatt', 'QLD', '4122', -27.5467, 153.0717, 'aged-care', 'aged-care', 415000, 615000, 450, 650, 30, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '07 3343 3002', 'mtgravatt@scrosscc.com.au', 'https://scrosscc.com.au', 'Southeast Brisbane aged care. Gardens, cafe, and dementia care.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- SA (5 villages)
('Regis Aged Care Unley', 'Regis Aged Care', '88 Unley Road', 'Unley', 'SA', '5061', -34.9517, 138.6033, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '08 8272 1001', 'unley@regis.com.au', 'https://regis.com.au', 'Inner Adelaide aged care. Gardens, cafe, and tram access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Norwood', 'Estia Health', '45 The Parade', 'Norwood', 'SA', '5067', -34.9217, 138.6333, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '08 8363 2001', 'norwood@estiahealth.com.au', 'https://estiahealth.com.au', 'Premium Adelaide aged care. Gardens, cafe, and Parade shopping.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('ACH Group Kurralta Park', 'ACH Group', '125 South Road', 'Kurralta Park', 'SA', '5037', -34.9633, 138.5583, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '08 8292 3001', 'kurral tapark@ach.org.au', 'https://ach.org.au', 'Inner southern Adelaide aged care. Gardens and close to beach tram.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Murray Bridge', 'Southern Cross Care SA', '15 Swanport Road', 'Murray Bridge', 'SA', '5253', -35.1200, 139.2750, 'aged-care', 'aged-care', 245000, 405000, 290, 480, 34, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '08 8532 4001', 'murraybridge@scsa.org.au', 'https://scsa.org.au', 'Riverland aged care. Gardens and close to Murray River.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Mitcham', 'Japara Healthcare', '88 Belair Road', 'Mitcham', 'SA', '5062', -34.9800, 138.6233, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '08 8373 5001', 'mitcham@japara.com.au', 'https://japara.com.au', 'Hills aged care. Gardens, cafe, and close to shopping center.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- WA (4 villages)
('Regis Aged Care Applecross', 'Regis Aged Care', '125 Canning Highway', 'Applecross', 'WA', '6153', -32.0167, 115.8333, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '08 9364 1001', 'applecross@regis.com.au', 'https://regis.com.au', 'Premium riverside Perth aged care. Pool, gardens, and river views.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bethanie Esprit Madeley', 'Bethanie Group', '45 Kingsway', 'Madeley', 'WA', '6065', -31.8000, 115.8333, 'independent', 'independent', 365000, 585000, 380, 580, 30, '["pool", "gym", "library", "common-room", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 134, 55, '08 9409 2001', 'madeley@bethanie.com.au', 'https://bethanie.com.au', 'Northern Perth retirement. Pool, gym, and close to shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Busselton', 'Amana Living', '88 Bussell Highway', 'Busselton', 'WA', '6280', -33.6500, 115.3500, 'aged-care', 'aged-care', 315000, 515000, 350, 550, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '08 9752 3001', 'busselton@amana.com.au', 'https://amana.com.au', 'Southwest WA aged care near beaches. Gardens and coastal setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Fremantle', 'Opal Aged Care', '15 High Street', 'Fremantle', 'WA', '6160', -32.0550, 115.7483, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '08 9335 4001', 'fremantle@opalcare.com.au', 'https://opalcare.com.au', 'Historic Fremantle aged care. Gardens, cafe, and close to markets.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Estia Health Burnie', 'Estia Health', '45 Bass Highway', 'Burnie', 'TAS', '7320', -41.0550, 145.9050, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '03 6431 1001', 'burnie@estiahealth.com.au', 'https://estiahealth.com.au', 'Northwest Tasmania aged care. Gardens and close to coast.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Aged Care Kaleen', 'Goodwin', '88 Kaleen Centre Way', 'Kaleen', 'ACT', '2617', -35.2283, 149.1017, 'aged-care', 'aged-care', 465000, 705000, 500, 740, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '02 6241 1001', 'kaleen@goodwin.org.au', 'https://goodwin.org.au', 'North Canberra aged care. Gardens, cafe, and close to shopping.', 'approved', 'seed_data', true, false, NOW(), NOW());
