-- Batch 17: 50 Additional Retirement Villages - Premium Metropolitan Focus
-- Brings total to 755 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW Premium Metro (15 villages)
('Aveo Freedom Concord', 'Aveo Group', '125 Parramatta Road', 'Concord', 'NSW', '2137', -33.8583, 151.1000, 'independent', 'independent', 625000, 985000, 620, 940, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 158, 60, '02 9744 2201', 'concord@aveo.com.au', 'https://aveo.com.au', 'Inner West premium retirement. Pool, gym, cinema, near Rhodes shopping.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Lane Cove', 'Stockland', '45 Burns Bay Road', 'Lane Cove', 'NSW', '2066', -33.8117, 151.1650, 'independent', 'independent', 685000, 1085000, 680, 1060, 24, '[\"pool\", \"gym\", \"bowling-green\", \"library\", \"common-room\", \"restaurant\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 172, 60, '02 9428 2201', 'lanecove@stockland.com.au', 'https://stockland.com', 'Premium Lower North Shore. Pool, gym, bowling green, restaurant, village charm.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Lendlease Retirement Living Roseville', 'Lendlease', '88 Babbage Road', 'Roseville', 'NSW', '2069', -33.7867, 151.1783, 'independent', 'independent', 725000, 1125000, 720, 1100, 22, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"restaurant\", \"art-studio\", \"concierge\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 184, 65, '02 9416 2201', 'roseville@lendlease.com', 'https://lendlease.com', 'Luxury Upper North Shore. Pool, gym, cinema, restaurant, art studio, concierge.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Ryman Healthcare Macquarie Park', 'Ryman Healthcare', '125 Talavera Road', 'Macquarie Park', 'NSW', '2113', -33.7750, 151.1183, 'independent', 'aged-care', 685000, 1185000, 680, 1120, 24, '[\"pool\", \"gym\", \"bowling-green\", \"cinema\", \"library\", \"common-room\", \"restaurant\", \"hairdresser\", \"cafe\", \"art-studio\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\", \"dementia-care\"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 268, 60, '02 9878 2201', 'macquariepark@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Premium North Ryde village. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Retirement Living Mosman', 'Regis Aged Care', '45 Bradleys Head Road', 'Mosman', 'NSW', '2088', -33.8350, 151.2433, 'independent', 'independent', 845000, 1385000, 840, 1360, 20, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"restaurant\", \"harbour-views\", \"concierge\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 142, 65, '02 9969 2201', 'mosman@regis.com.au', 'https://regis.com.au', 'Luxury harbour-side retirement. Pool, gym, cinema, restaurant, harbour views.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Aveo Freedom Glebe', 'Aveo Group', '88 Glebe Point Road', 'Glebe', 'NSW', '2037', -33.8767, 151.1833, 'independent', 'independent', 645000, 1025000, 640, 1000, 24, '[\"gym\", \"library\", \"common-room\", \"rooftop-terrace\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 136, 60, '02 9660 2201', 'glebe@aveo.com.au', 'https://aveo.com.au', 'Inner city urban retirement. Gym, rooftop terrace, cafe, cultural precinct.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Maroubra', 'Stockland', '125 Anzac Parade', 'Maroubra', 'NSW', '2035', -33.9483, 151.2350, 'independent', 'independent', 625000, 985000, 620, 940, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 148, 55, '02 9344 2201', 'maroubra@stockland.com.au', 'https://stockland.com', 'Beachside Eastern Suburbs. Pool, gym, and Maroubra Beach lifestyle.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Lendlease Retirement Living Bondi Junction', 'Lendlease', '15 Spring Street', 'Bondi Junction', 'NSW', '2022', -33.8917, 151.2500, 'independent', 'independent', 745000, 1225000, 740, 1200, 22, '[\"gym\", \"library\", \"common-room\", \"rooftop-pool\", \"cinema\", \"cafe\", \"concierge\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 176, 65, '02 9387 2201', 'bondijunction@lendlease.com', 'https://lendlease.com', 'Iconic Eastern Suburbs. Rooftop pool, gym, cinema, cafe, Westfield access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Anglicare Retirement Living Strathfield', 'Anglicare NSW South', '88 The Boulevarde', 'Strathfield', 'NSW', '2135', -33.8783, 151.0850, 'independent', 'independent', 565000, 895000, 560, 880, 26, '[\"pool\", \"library\", \"common-room\", \"chapel\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 132, 55, '02 9745 2201', 'strathfield@anglicare.com.au', 'https://anglicare.com.au', 'Inner West retirement. Pool, chapel, gardens, and train hub access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('BaptistCare Retirement Living Ashfield', 'BaptistCare NSW & ACT', '125 Liverpool Road', 'Ashfield', 'NSW', '2131', -33.8867, 151.1250, 'independent', 'independent', 585000, 925000, 580, 900, 26, '[\"library\", \"common-room\", \"chapel\", \"garden\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 124, 55, '02 9798 2201', 'ashfield@baptistcare.org.au', 'https://baptistcare.org.au', 'Inner West retirement. Chapel, cafe, gardens, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Uniting Retirement Living Pymble', 'Uniting NSW & ACT', '45 Grandview Street', 'Pymble', 'NSW', '2073', -33.7433, 151.1400, 'independent', 'independent', 685000, 1085000, 680, 1060, 24, '[\"pool\", \"gym\", \"library\", \"common-room\", \"garden\", \"tennis-court\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 152, 60, '02 9488 2201', 'pymble@uniting.org', 'https://uniting.org', 'Premium Upper North Shore. Pool, gym, tennis court, leafy setting.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('IRT Retirement Villages Cronulla', 'IRT Group', '88 Kingsway', 'Cronulla', 'NSW', '2230', -34.0517, 151.1533, 'independent', 'independent', 645000, 1025000, 640, 1000, 24, '[\"pool\", \"gym\", \"library\", \"common-room\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 144, 55, '02 9527 2201', 'cronullaret@irt.org.au', 'https://irt.org.au', 'Premium beachside retirement. Pool, gym, and surf lifestyle.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('RSL LifeCare Retirement Villages Narrabeen', 'RSL LifeCare', '125 Pittwater Road', 'Narrabeen', 'NSW', '2101', -33.7183, 151.2950, 'independent', 'independent', 625000, 985000, 620, 940, 26, '[\"pool\", \"bowling-green\", \"library\", \"common-room\", \"bbq-area\", \"workshop\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 136, 55, '02 9970 2201', 'narrabeenrsl@rsllifecare.org.au', 'https://rsllifecare.org.au', 'Northern Beaches retirement. Pool, bowling green, beach lifestyle.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Aged Care Darlinghurst', 'Regis Aged Care', '15 Forbes Street', 'Darlinghurst', 'NSW', '2010', -33.8783, 151.2200, 'aged-care', 'aged-care', 685000, 1085000, 680, 1060, 22, '[\"library\", \"common-room\", \"rooftop-garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '02 9331 2201', 'darlinghurst@regis.com.au', 'https://regis.com.au', 'Inner city premium aged care. Rooftop garden, cafe, CBD fringe.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Manly', 'Estia Health', '88 Kenneth Road', 'Manly Vale', 'NSW', '2093', -33.7833, 151.2617, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '02 9949 2201', 'manly@estiahealth.com.au', 'https://estiahealth.com.au', 'Premium Northern Beaches aged care. Pool, cafe, beach access.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- VIC Premium Metro (12 villages)
('Aveo Retirement Living Kew', 'Aveo Group', '125 High Street', 'Kew', 'VIC', '3101', -37.8067, 145.0333, 'independent', 'independent', 685000, 1085000, 680, 1060, 24, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 162, 60, '03 9817 4201', 'kew@aveo.com.au', 'https://aveo.com.au', 'Premium Eastern suburbs. Pool, gym, cinema, tree-lined boulevards.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Brighton', 'Stockland', '45 New Street', 'Brighton', 'VIC', '3186', -37.9150, 145.0017, 'independent', 'independent', 725000, 1125000, 720, 1100, 22, '[\"pool\", \"gym\", \"bowling-green\", \"library\", \"common-room\", \"restaurant\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 176, 65, '03 9592 4201', 'brightonret@stockland.com.au', 'https://stockland.com', 'Luxury bayside retirement. Pool, gym, bowling green, restaurant, beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Lendlease Retirement Living Toorak', 'Lendlease', '88 Toorak Road', 'Toorak', 'VIC', '3142', -37.8417, 145.0133, 'independent', 'independent', 845000, 1385000, 840, 1360, 20, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"restaurant\", \"wine-cellar\", \"concierge\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 148, 65, '03 9827 4201', 'toorak@lendlease.com', 'https://lendlease.com', 'Ultra-luxury Melbourne. Pool, gym, cinema, restaurant, wine cellar, concierge.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Ryman Healthcare Glen Waverley', 'Ryman Healthcare', '125 Springvale Road', 'Glen Waverley', 'VIC', '3150', -37.8783, 145.1617, 'independent', 'aged-care', 585000, 1025000, 580, 1000, 26, '[\"pool\", \"gym\", \"bowling-green\", \"cinema\", \"library\", \"common-room\", \"restaurant\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\", \"dementia-care\"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 252, 60, '03 9560 4201', 'glenwaverley@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Premium eastern village. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Retirement Living Hawthorn', 'Regis Aged Care', '15 Burwood Road', 'Hawthorn', 'VIC', '3122', -37.8217, 145.0317, 'independent', 'independent', 705000, 1125000, 700, 1100, 22, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"restaurant\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 158, 60, '03 9819 4201', 'hawthornret@regis.com.au', 'https://regis.com.au', 'Premium inner east. Pool, gym, cinema, restaurant, Glenferrie Road.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Aveo Retirement Living Malvern', 'Aveo Group', '88 Glenferrie Road', 'Malvern', 'VIC', '3144', -37.8583, 145.0283, 'independent', 'independent', 685000, 1085000, 680, 1060, 24, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 154, 60, '03 9509 4201', 'malvern@aveo.com.au', 'https://aveo.com.au', 'Premium Stonnington. Pool, gym, cinema, shopping and cafes nearby.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Balwyn', 'Stockland', '125 Whitehorse Road', 'Balwyn', 'VIC', '3103', -37.8083, 145.0833, 'independent', 'independent', 665000, 1065000, 660, 1040, 24, '[\"pool\", \"gym\", \"bowling-green\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 164, 60, '03 9830 4201', 'balwyn@stockland.com.au', 'https://stockland.com', 'Premium Boroondara. Pool, gym, bowling green, leafy streets.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Lendlease Retirement Living Elsternwick', 'Lendlease', '45 Glen Huntly Road', 'Elsternwick', 'VIC', '3185', -37.8833, 145.0000, 'independent', 'independent', 625000, 985000, 620, 940, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 142, 60, '03 9523 4201', 'elsternwick@lendlease.com', 'https://lendlease.com', 'Bayside retirement. Pool, gym, cinema, train and shopping access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Caulfield', 'Regis Aged Care', '88 Kooyong Road', 'Caulfield North', 'VIC', '3161', -37.8717, 145.0267, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 134, 55, '03 9509 4201', 'caulfield@regis.com.au', 'https://regis.com.au', 'Premium Glen Eira aged care. Pool, cafe, gardens, racecourse nearby.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Box Hill', 'Estia Health', '125 Station Street', 'Box Hill', 'VIC', '3128', -37.8183, 145.1233, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '03 9899 4201', 'boxhill@estiahealth.com.au', 'https://estiahealth.com.au', 'Eastern suburbs aged care. Gardens, cafe, and Box Hill Central.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Aged Care Cheltenham', 'Arcare', '15 Charman Road', 'Cheltenham', 'VIC', '3192', -37.9650, 145.0533, 'aged-care', 'aged-care', 565000, 855000, 600, 900, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\", \"dementia-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 126, 55, '03 9583 4201', 'cheltenhamarcare@arcare.com.au', 'https://arcare.com.au', 'Bayside premium aged care. Pool, gym, cinema, train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bupa Aged Care Doncaster', 'Bupa', '88 Doncaster Road', 'Doncaster', 'VIC', '3108', -37.7867, 145.1233, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '03 9848 4201', 'doncaster@bupa.com.au', 'https://bupa.com.au', 'Eastern suburbs aged care. Gardens, cafe, and Westfield shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- QLD Premium Metro (12 villages)
('Aveo Retirement Living Newstead', 'Aveo Group', '125 Commercial Road', 'Newstead', 'QLD', '4006', -27.4483, 153.0450, 'independent', 'independent', 625000, 985000, 620, 940, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"rooftop-terrace\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 168, 60, '07 3252 6201', 'newstead@aveo.com.au', 'https://aveo.com.au', 'Inner Brisbane urban. Pool, gym, cinema, rooftop terrace, river precinct.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Burleigh Heads', 'Stockland', '45 Goodwin Terrace', 'Burleigh Heads', 'QLD', '4220', -28.1017, 153.4467, 'independent', 'independent', 685000, 1085000, 680, 1060, 24, '[\"pool\", \"gym\", \"library\", \"common-room\", \"bbq-area\", \"ocean-views\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 156, 60, '07 5535 6201', 'burleighheads@stockland.com.au', 'https://stockland.com', 'Premium Gold Coast beachside. Pool, gym, ocean views, surf beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Lendlease Retirement Living Indooroopilly', 'Lendlease', '88 Moggill Road', 'Indooroopilly', 'QLD', '4068', -27.4983, 152.9717, 'independent', 'independent', 625000, 985000, 620, 940, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 148, 60, '07 3878 6201', 'indooroopilly@lendlease.com', 'https://lendlease.com', 'Premium western Brisbane. Pool, gym, cinema, and shopping center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ryman Healthcare Yeronga', 'Ryman Healthcare', '125 Yeronga Road', 'Yeronga', 'QLD', '4104', -27.5217, 153.0117, 'independent', 'aged-care', 585000, 1025000, 580, 1000, 26, '[\"pool\", \"gym\", \"bowling-green\", \"cinema\", \"library\", \"common-room\", \"restaurant\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\", \"dementia-care\"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 246, 60, '07 3892 6201', 'yeronga@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Premium south Brisbane village. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Retirement Living Broadbeach', 'Regis Aged Care', '15 Surf Parade', 'Broadbeach', 'QLD', '4218', -28.0267, 153.4300, 'independent', 'independent', 745000, 1225000, 740, 1200, 22, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"ocean-views\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 164, 65, '07 5539 6201', 'broadbeach@regis.com.au', 'https://regis.com.au', 'Luxury beachfront retirement. Pool, gym, cinema, ocean views, Pacific Fair.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Aveo Retirement Living Kangaroo Point', 'Aveo Group', '88 Main Street', 'Kangaroo Point', 'QLD', '4169', -27.4783, 153.0383, 'independent', 'independent', 645000, 1025000, 640, 1000, 24, '[\"pool\", \"gym\", \"library\", \"common-room\", \"rooftop-terrace\", \"river-views\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 142, 60, '07 3391 6201', 'kangaroopoint@aveo.com.au', 'https://aveo.com.au', 'Inner Brisbane riverside. Pool, gym, rooftop terrace, river views, CBD.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Noosa', 'Stockland', '125 Noosa Drive', 'Noosa', 'QLD', '4567', -26.3950, 153.0883, 'independent', 'independent', 725000, 1125000, 720, 1100, 22, '[\"pool\", \"gym\", \"bowling-green\", \"library\", \"common-room\", \"restaurant\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 172, 65, '07 5447 6201', 'noosaret@stockland.com.au', 'https://stockland.com', 'Luxury Sunshine Coast. Pool, gym, bowling green, restaurant, Hastings Street.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Lendlease Retirement Living Runaway Bay', 'Lendlease', '45 Bayview Street', 'Runaway Bay', 'QLD', '4216', -27.9050, 153.3933, 'independent', 'independent', 625000, 985000, 620, 940, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"marina-access\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 152, 60, '07 5537 6201', 'runawaybay@lendlease.com', 'https://lendlease.com', 'Gold Coast waterfront. Pool, gym, cinema, marina access, Broadwater.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Ascot', 'Regis Aged Care', '88 Racecourse Road', 'Ascot', 'QLD', '4007', -27.4317, 153.0567, 'aged-care', 'aged-care', 585000, 895000, 620, 940, 26, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 126, 55, '07 3868 6201', 'ascot@regis.com.au', 'https://regis.com.au', 'Premium inner Brisbane aged care. Pool, cafe, and racing precinct.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Blue Care Paddington', 'Blue Care', '125 Given Terrace', 'Paddington', 'QLD', '4064', -27.4617, 152.9983, 'aged-care', 'aged-care', 565000, 855000, 600, 900, 26, '[\"library\", \"common-room\", \"rooftop-garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '07 3369 6201', 'paddington@bluecare.org.au', 'https://bluecare.org.au', 'Inner city aged care. Rooftop garden, cafe, and cafe culture.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Coorparoo', 'Bolton Clarke', '15 Old Cleveland Road', 'Coorparoo', 'QLD', '4151', -27.4950, 153.0600, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '07 3397 6201', 'coorparoo@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Inner east Brisbane aged care. Gardens, cafe, and village shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('TriCare Aged Care Mermaid Beach', 'TriCare', '88 Hedges Avenue', 'Mermaid Beach', 'QLD', '4218', -28.0483, 153.4383, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\", \"ocean-views\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 132, 55, '07 5572 6201', 'mermaidbeach@tricare.com.au', 'https://tricare.com.au', 'Premium beachfront aged care. Pool, cafe, ocean views, surf beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- SA Premium (5 villages)
('Resthaven Aged Care Craigburn Farm', 'Resthaven', '88 Shepherds Hill Road', 'Craigburn Farm', 'SA', '5051', -35.0233, 138.5883, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '08 8278 7001', 'craigburn@resthaven.asn.au', 'https://resthaven.asn.au', 'Hills aged care. Pool, gardens, cafe, and scenic views.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Glenelg', 'ACH Group', '125 Brighton Road', 'Glenelg', 'SA', '5045', -34.9817, 138.5100, 'aged-care', 'aged-care', 565000, 855000, 600, 900, 26, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 124, 55, '08 8295 7001', 'glenelgach@ach.org.au', 'https://ach.org.au', 'Premium beachside aged care. Pool, cafe, and Glenelg beach lifestyle.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Aged Care North Adelaide', 'Regis Aged Care', '45 Palmer Place', 'North Adelaide', 'SA', '5006', -34.9083, 138.5950, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '08 8267 7001', 'northadelaide@regis.com.au', 'https://regis.com.au', 'Premium inner city aged care. Gardens, cafe, and O\'Connell Street.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Unley', 'Estia Health', '88 Unley Road', 'Unley', 'SA', '5061', -34.9500, 138.6033, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '08 8272 7001', 'unley@estiahealth.com.au', 'https://estiahealth.com.au', 'Inner south aged care. Gardens, cafe, and shopping precinct.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Myrtle Bank', 'Southern Cross Care SA', '125 Devereux Road', 'Myrtle Bank', 'SA', '5064', -34.9633, 138.6200, 'aged-care', 'aged-care', 525000, 795000, 560, 840, 26, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '08 8379 7001', 'myrtlebank@scsa.org.au', 'https://scsa.org.au', 'Premium hills aged care. Gardens, cafe, and leafy setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- WA Premium (4 villages)
('Bethanie Retirement Living Subiaco', 'Bethanie Group', '88 Bagot Road', 'Subiaco', 'WA', '6008', -31.9483, 115.8250, 'independent', 'independent', 625000, 985000, 620, 940, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 146, 60, '08 9388 8001', 'subiaco@bethanie.com.au', 'https://bethanie.com.au', 'Premium inner west Perth. Pool, gym, cinema, cafe culture.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Retirement Living Cottesloe', 'Regis Aged Care', '125 Stirling Highway', 'Cottesloe', 'WA', '6011', -31.9967, 115.7583, 'independent', 'independent', 845000, 1385000, 840, 1360, 20, '[\"pool\", \"gym\", \"library\", \"common-room\", \"ocean-views\", \"concierge\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"concierge\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 128, 65, '08 9383 8001', 'cottesloe@regis.com.au', 'https://regis.com.au', 'Luxury beachside retirement. Pool, gym, ocean views, iconic beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Amana Living Nedlands', 'Amana Living', '45 Stirling Highway', 'Nedlands', 'WA', '6009', -31.9800, 115.8083, 'aged-care', 'aged-care', 585000, 895000, 620, 940, 26, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '08 9386 8001', 'nedlands@amana.com.au', 'https://amana.com.au', 'Premium riverside aged care. Pool, cafe, and river views.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Aged Care Applecross', 'Regis Aged Care', '88 Canning Highway', 'Applecross', 'WA', '6153', -32.0183, 115.8333, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\", \"river-views\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 134, 55, '08 9364 8001', 'applecross@regis.com.au', 'https://regis.com.au', 'Premium riverside aged care. Pool, cafe, river views, exclusive suburb.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- TAS (1 village)
('Ryman Healthcare Hobart', 'Ryman Healthcare', '125 Davey Street', 'Hobart', 'TAS', '7000', -42.8883, 147.3283, 'independent', 'aged-care', 525000, 925000, 520, 900, 28, '[\"pool\", \"gym\", \"bowling-green\", \"cinema\", \"library\", \"common-room\", \"restaurant\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\", \"dementia-care\"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 218, 60, '03 6234 9101', 'hobart@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Premium Hobart village. Pool, gym, bowling green, cinema, restaurant, waterfront.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Retirement Living Griffith', 'Goodwin', '15 Captain Cook Crescent', 'Griffith', 'ACT', '2603', -35.3267, 149.1383, 'independent', 'independent', 625000, 985000, 620, 940, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 132, 60, '02 6295 8001', 'griffith@goodwin.org.au', 'https://goodwin.org.au', 'Premium inner south Canberra. Pool, gym, gardens, and parliamentary triangle.', 'approved', 'seed_data', true, true, NOW(), NOW());
