-- Batch 14: 50 Additional Retirement Villages (FINAL BATCH)
-- Brings total to 605 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW (15 villages)
('Aveo Newmarket', 'Aveo Group', '88 King Street', 'Newtown', 'NSW', '2042', -33.8967, 151.1800, 'independent', 'independent', 605000, 965000, 600, 940, 26, '["pool", "gym", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 128, 55, '02 9519 1701', 'newmarket@aveo.com.au', 'https://aveo.com.au', 'Premium inner west retirement. Pool, gym, and King Street dining.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Forster', 'Stockland', '45 Lake Street', 'Forster', 'NSW', '2428', -32.1783, 152.5133, 'independent', 'independent', 385000, 625000, 400, 620, 30, '["pool", "library", "common-room", "bbq-area", "workshop"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 126, 55, '02 6554 1701', 'forster@stockland.com.au', 'https://stockland.com', 'Great Lakes retirement. Pool and close to beaches and lakes.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Mosman', 'Regis Aged Care', '125 Military Road', 'Mosman', 'NSW', '2088', -33.8267, 151.2417, 'aged-care', 'aged-care', 685000, 1050000, 720, 1040, 22, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 134, 55, '02 9969 1701', 'mosman@regis.com.au', 'https://regis.com.au', 'Premium harbour aged care. Pool, gardens, and village atmosphere.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Opal Aged Care Bankstown', 'Opal Aged Care', '15 Chapel Road', 'Bankstown', 'NSW', '2200', -33.9183, 151.0333, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '02 9707 1701', 'bankstown@opalcare.com.au', 'https://opalcare.com.au', 'Southwest Sydney aged care. Gardens and multicultural community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Albury', 'Estia Health', '88 Dean Street', 'Albury', 'NSW', '2640', -36.0817, 146.9167, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '02 6021 1701', 'albury@estiahealth.com.au', 'https://estiahealth.com.au', 'Border city aged care. Gardens and close to Murray River.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Maroubra', 'Arcare', '45 Anzac Parade', 'Maroubra', 'NSW', '2035', -33.9500, 151.2433, 'aged-care', 'aged-care', 605000, 945000, 640, 960, 24, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 130, 55, '02 9344 1701', 'maroubra@arcare.com.au', 'https://arcare.com.au', 'Premium beachside aged care. Pool, gym, cinema, and surf beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('BaptistCare Waratah', 'BaptistCare NSW & ACT', '88 Turramurra Avenue', 'Turramurra', 'NSW', '2074', -33.7367, 151.1283, 'aged-care', 'aged-care', 605000, 905000, 640, 920, 24, '["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '02 9449 1701', 'waratah@baptistcare.org.au', 'https://baptistcare.org.au', 'Premium Upper North Shore aged care. Pool, chapel, gardens.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Blue Care Lismore', 'Blue Care', '15 Molesworth Street', 'Lismore', 'NSW', '2480', -28.8133, 153.2783, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 80, 55, '02 6621 1701', 'lismore@bluecare.org.au', 'https://bluecare.org.au', 'North Coast aged care. Gardens and regional city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Healthcare Ryde', 'Catholic Healthcare', '125 Victoria Road', 'Ryde', 'NSW', '2112', -33.8150, 151.1017, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '02 9808 1701', 'ryde@catholichealthcare.com.au', 'https://catholichealthcare.com.au', 'Northwest Sydney aged care. Chapel, cafe, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('HammondCare Braeside Village', 'HammondCare', '45 Victoria Road', 'Burwood', 'NSW', '2134', -33.8767, 151.1033, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 124, 55, '02 9744 1701', 'braesidevillage@hammond.com.au', 'https://hammond.com.au', 'Premium inner west aged care. Pool, gardens, specialist dementia.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Uniting Mercy Place', 'Uniting NSW & ACT', '88 Oxford Street', 'Epping', 'NSW', '2121', -33.7717, 151.0800, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '02 9869 1701', 'mercyplace@uniting.org', 'https://uniting.org', 'Northwest Sydney aged care. Pool, gardens, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Glengarry', 'Japara Healthcare', '15 Pacific Highway', 'Dural', 'NSW', '2158', -33.6867, 151.0333, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '02 9651 1701', 'glengarry@japara.com.au', 'https://japara.com.au', 'Hills District aged care. Pool, gardens, and rural setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Whiddon Quirindi', 'Whiddon Group', '125 George Street', 'Quirindi', 'NSW', '2343', -31.5067, 150.6817, 'aged-care', 'aged-care', 245000, 405000, 290, 480, 34, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 70, 55, '02 6746 1701', 'quirindi@whiddon.com.au', 'https://whiddon.com.au', 'Liverpool Plains aged care. Gardens and country town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Narooma', 'Allity', '45 Princes Highway', 'Narooma', 'NSW', '2546', -36.2183, 150.1300, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '02 4476 1701', 'narooma@allity.com.au', 'https://allity.com.au', 'Sapphire Coast aged care. Gardens and close to harbour.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('RSL LifeCare Cessnock', 'RSL LifeCare', '88 Vincent Street', 'Cessnock', 'NSW', '2325', -32.8350, 151.3567, 'independent', 'independent', 325000, 545000, 340, 540, 32, '["bowling-green", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 110, 55, '02 4990 1701', 'cessnock@rsllifecare.org.au', 'https://rsllifecare.org.au', 'Hunter Valley retirement. Bowling green and wine country.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC (12 villages)
('Regis Aged Care Camberwell', 'Regis Aged Care', '125 Burke Road', 'Camberwell', 'VIC', '3124', -37.8267, 145.0583, 'aged-care', 'aged-care', 605000, 905000, 640, 920, 24, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '03 9882 3701', 'camberwell@regis.com.au', 'https://regis.com.au', 'Premium inner east aged care. Pool, gardens, and Burke Road shopping.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Colac', 'Estia Health', '45 Murray Street', 'Colac', 'VIC', '3250', -38.3383, 143.5833, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '03 5231 3701', 'colac@estiahealth.com.au', 'https://estiahealth.com.au', 'Western district aged care. Gardens and lake setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Epping', 'Arcare', '88 Cooper Street', 'Epping', 'VIC', '3076', -37.6483, 145.0217, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '03 9401 3701', 'epping@arcare.com.au', 'https://arcare.com.au', 'Northern suburbs aged care. Pool, cinema, and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bupa Aged Care Toorak', 'Bupa', '15 Malvern Road', 'Toorak', 'VIC', '3142', -37.8417, 145.0100, 'aged-care', 'aged-care', 685000, 1050000, 720, 1040, 22, '["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 136, 55, '03 9827 3701', 'toorak@bupa.com.au', 'https://bupa.com.au', 'Premium Toorak aged care. Pool, gym, gardens, and village dining.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bolton Clarke Berwick', 'Bolton Clarke', '125 High Street', 'Berwick', 'VIC', '3806', -38.0350, 145.3517, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '03 9707 3701', 'berwick@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Southeast corridor aged care. Gardens and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Benalla', 'Opal Aged Care', '45 Bridge Street', 'Benalla', 'VIC', '3672', -36.5517, 145.9817, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '03 5762 3701', 'benalla@opalcare.com.au', 'https://opalcare.com.au', 'Northeast Victoria aged care. Gardens and lake setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Kew', 'Regis Aged Care', '88 High Street', 'Kew', 'VIC', '3101', -37.8067, 145.0350, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 126, 55, '03 9853 3701', 'kew@regis.com.au', 'https://regis.com.au', 'Premium inner east aged care. Pool, gardens, and village shopping.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Wangaratta', 'Estia Health', '15 Tone Road', 'Wangaratta', 'VIC', '3677', -36.3617, 146.3167, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '03 5721 3701', 'wangaratta@estiahealth.com.au', 'https://estiahealth.com.au', 'Northeast Victoria aged care. Gardens and wine region.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas Lilydale', 'Benetas', '125 Castella Street', 'Lilydale', 'VIC', '3140', -37.7550, 145.3483, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '03 9735 3701', 'lilydale@benetas.com.au', 'https://benetas.com.au', 'Outer east aged care. Gardens and Dandenong Ranges gateway.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Carrum Downs', 'Japara Healthcare', '45 Hall Road', 'Carrum Downs', 'VIC', '3201', -38.1033, 145.1733, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '03 9782 3701', 'carrumdowns@japara.com.au', 'https://japara.com.au', 'Southeast Melbourne aged care. Gardens and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Werribee', 'Mercy Health', '88 Synnot Street', 'Werribee', 'VIC', '3030', -37.9017, 144.6633, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '03 9741 3701', 'werribee@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Southwest Melbourne aged care. Chapel, gardens, and shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ryman Healthcare Grace Joel', 'Ryman Healthcare', '15 Blackburn Road', 'Glen Waverley', 'VIC', '3150', -37.8783, 145.1650, 'aged-care', 'aged-care', 525000, 965000, 560, 940, 28, '["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 248, 55, '03 9560 3701', 'gracejoel@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Large premium retirement village. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- QLD (12 villages)
('Regis Aged Care Spring Hill', 'Regis Aged Care', '125 Wickham Terrace', 'Spring Hill', 'QLD', '4000', -27.4617, 153.0250, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 120, 55, '07 3831 4701', 'springhill@regis.com.au', 'https://regis.com.au', 'Premium inner Brisbane aged care. Pool, gardens, and CBD access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Blue Care Gympie', 'Blue Care', '45 Mary Street', 'Gympie', 'QLD', '4570', -26.1900, 152.6650, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '07 5482 4701', 'gympie@bluecare.org.au', 'https://bluecare.org.au', 'Wide Bay aged care. Gardens and gold mining heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Palm Beach', 'Opal Aged Care', '88 Fifth Avenue', 'Palm Beach', 'QLD', '4221', -28.1183, 153.4650, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 120, 55, '07 5534 4701', 'palmbeach@opalcare.com.au', 'https://opalcare.com.au', 'Premium Gold Coast beachside aged care. Pool, gardens, and surf.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('TriCare Aged Care Logan', 'TriCare', '15 Wembley Road', 'Logan Central', 'QLD', '4114', -27.6383, 153.1100, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '07 3299 4701', 'logan@tricare.com.au', 'https://tricare.com.au', 'South Brisbane region aged care. Gardens and shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Southport Park', 'Estia Health', '125 Nerang Street', 'Southport', 'QLD', '4215', -27.9683, 153.4083, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '07 5532 4701', 'southportpark@estiahealth.com.au', 'https://estiahealth.com.au', 'Central Gold Coast aged care. Pool, gardens, and light rail access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke West End', 'Bolton Clarke', '45 Vulture Street', 'West End', 'QLD', '4101', -27.4817, 153.0100, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '07 3844 4701', 'westend@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Inner Brisbane aged care. Gardens, cafe, and river access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Adventist Aged Care Warwick', 'Adventist Aged Care', '88 Palmerin Street', 'Warwick', 'QLD', '4370', -28.2150, 152.0333, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 70, 55, '07 4661 4701', 'warwick@adventistcare.org.au', 'https://adventistcare.org.au', 'Southern Downs aged care. Chapel, gardens, and rose festival.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ozcare Biloela', 'Ozcare', '15 Kariboe Street', 'Biloela', 'QLD', '4715', -24.4017, 150.5117, 'aged-care', 'aged-care', 255000, 425000, 300, 490, 34, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 64, 55, '07 4992 4701', 'biloela@ozcare.org.au', 'https://ozcare.org.au', 'Central Queensland aged care. Chapel, gardens, and mining town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Clifford House', 'Carinity', '125 Webster Road', 'Stafford', 'QLD', '4053', -27.4183, 153.0150, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '07 3357 4701', 'cliffordhouse@carinity.org.au', 'https://carinity.org.au', 'North Brisbane aged care. Chapel, gardens, and close to city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Nambour', 'Regis Aged Care', '45 Currie Street', 'Nambour', 'QLD', '4560', -26.6267, 152.9583, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '07 5441 4701', 'nambour@regis.com.au', 'https://regis.com.au', 'Sunshine Coast hinterland aged care. Pool, gardens, and mountain views.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Mount Isa', 'Allity', '88 Marian Street', 'Mount Isa', 'QLD', '4825', -20.7267, 139.4933, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 68, 55, '07 4743 4701', 'mtisa@allity.com.au', 'https://allity.com.au', 'Northwest Queensland aged care. Pool, gardens, and mining city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Carindale', 'Southern Cross Care QLD', '125 Creek Road', 'Carindale', 'QLD', '4152', -27.5000, 153.1017, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '07 3398 4701', 'carindale@scrosscc.com.au', 'https://scrosscc.com.au', 'Southeast Brisbane aged care. Pool, gardens, and shopping center.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- SA (5 villages)
('Regis Aged Care Belair', 'Regis Aged Care', '88 Main Road', 'Belair', 'SA', '5052', -35.0067, 138.6350, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '08 8370 5701', 'belair@regis.com.au', 'https://regis.com.au', 'Adelaide Hills aged care. Gardens and national park setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Gawler', 'Estia Health', '15 Cowan Street', 'Gawler', 'SA', '5118', -34.6017, 138.7433, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 90, 55, '08 8522 5701', 'gawler@estiahealth.com.au', 'https://estiahealth.com.au', 'Barossa region aged care. Gardens and historic town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Woodville', 'ACH Group', '125 Torrens Road', 'Woodville', 'SA', '5011', -34.8817, 138.5400, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '08 8445 5701', 'woodville@ach.org.au', 'https://ach.org.au', 'Northwestern Adelaide aged care. Gardens and close to city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Naracoorte', 'Southern Cross Care SA', '45 Smith Street', 'Naracoorte', 'SA', '5271', -36.9583, 140.7367, 'aged-care', 'aged-care', 245000, 405000, 290, 480, 34, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 68, 55, '08 8762 5701', 'naracoorte@scsa.org.au', 'https://scsa.org.au', 'Southeast aged care. Gardens and limestone coast region.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Burnside War Memorial', 'Japara Healthcare', '88 Portrush Road', 'Toorak Gardens', 'SA', '5065', -34.9333, 138.6300, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '08 8333 5701', 'burnsidewarmemorial@japara.com.au', 'https://japara.com.au', 'Premium inner east Adelaide aged care. Gardens, cafe, and village access.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- WA (4 villages)
('Regis Aged Care Cottesloe', 'Regis Aged Care', '125 Stirling Highway', 'Cottesloe', 'WA', '6011', -31.9933, 115.7600, 'aged-care', 'aged-care', 685000, 1050000, 720, 1040, 22, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '08 9383 6701', 'cottesloe@regis.com.au', 'https://regis.com.au', 'Premium beachside aged care. Pool, gardens, and iconic beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bethanie Esprit Coolbellup', 'Bethanie Group', '45 Coolbellup Avenue', 'Coolbellup', 'WA', '6163', -32.0800, 115.8167, 'independent', 'independent', 385000, 625000, 400, 620, 30, '["pool", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 124, 55, '08 9434 6701', 'coolbellup@bethanie.com.au', 'https://bethanie.com.au', 'Southern Perth retirement. Pool and close to Fremantle.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Kalgoorlie', 'Amana Living', '88 Hannan Street', 'Kalgoorlie', 'WA', '6430', -30.7483, 121.4650, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '08 9021 6701', 'kalgoorlie@amana.com.au', 'https://amana.com.au', 'Goldfields aged care. Gardens and mining heritage city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Busselton', 'Opal Aged Care', '15 Queen Street', 'Busselton', 'WA', '6280', -33.6500, 115.3450, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 80, 55, '08 9754 6701', 'busselton@opalcare.com.au', 'https://opalcare.com.au', 'Southwest coastal aged care. Pool, gardens, and jetty town.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Estia Health Burnie', 'Estia Health', '125 Mount Street', 'Burnie', 'TAS', '7320', -41.0517, 145.9017, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '03 6431 9701', 'burnie@estiahealth.com.au', 'https://estiahealth.com.au', 'Northwest Tasmania aged care. Gardens and close to port.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Aged Care Griffith', 'Goodwin', '45 Palmerston Lane', 'Griffith', 'ACT', '2603', -35.3267, 149.1383, 'aged-care', 'aged-care', 525000, 775000, 560, 820, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '02 6295 8701', 'griffith@goodwin.org.au', 'https://goodwin.org.au', 'Central Canberra aged care. Gardens, cafe, and close to Parliamentary Triangle.', 'approved', 'seed_data', true, true, NOW(), NOW());
