-- Batch 8: 50 Additional Retirement Villages
-- Brings total to 305 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW (15 villages)
('Lendlease Retirement Living Newtown', 'Lendlease', '125 King Street', 'Newtown', 'NSW', '2042', -33.8983, 151.1800, 'independent', 'independent', 625000, 985000, 620, 900, 26, '["gym", "library", "common-room", "rooftop-terrace"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '02 9519 1111', 'newtown@lendlease.com', 'https://lendlease.com', 'Inner Sydney urban retirement. Gym, rooftop terrace, and walk to King Street.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Willoughby', 'Stockland', '45 Penshurst Street', 'Willoughby', 'NSW', '2068', -33.8000, 151.1950, 'independent', 'independent', 585000, 925000, 580, 860, 26, '["pool", "gym", "library", "common-room"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 108, 55, '02 9958 2111', 'willoughby@stockland.com.au', 'https://stockland.com', 'Lower North Shore retirement. Pool, gym, and train access to city.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Aged Care Parramatta', 'Regis Aged Care', '88 Church Street', 'Parramatta', 'NSW', '2150', -33.8150, 151.0033, 'aged-care', 'aged-care', 495000, 745000, 530, 780, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '02 9635 3111', 'parramatta@regis.com.au', 'https://regis.com.au', 'Central Parramatta aged care. Gardens, cafe, and close to Westfield.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Penrith', 'Opal Aged Care', '15 High Street', 'Penrith', 'NSW', '2750', -33.7517, 150.6950, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '02 4721 4111', 'penrith@opalcare.com.au', 'https://opalcare.com.au', 'Western Sydney aged care. Gardens and close to Penrith Panthers.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Baulkham Hills', 'Estia Health', '125 Old Northern Road', 'Baulkham Hills', 'NSW', '2153', -33.7617, 150.9883, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '02 9686 5111', 'baulkhamhills@estiahealth.com.au', 'https://estiahealth.com.au', 'Hills District aged care. Pool, gardens, and close to Stockland Mall.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Warriewood', 'Arcare', '45 Jacksons Road', 'Warriewood', 'NSW', '2102', -33.6950, 151.2983, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '02 9979 6111', 'warriewood@arcare.com.au', 'https://arcare.com.au', 'Northern Beaches premium aged care. Pool, gym, cinema, and beaches.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('BaptistCare Dorothy Henderson Lodge', 'BaptistCare NSW & ACT', '88 Hammers Road', 'Northmead', 'NSW', '2152', -33.7900, 150.9950, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '02 9683 7111', 'dorothyhenderson@baptistcare.org.au', 'https://baptistcare.org.au', 'Parramatta area aged care. Chapel, gardens, and dementia unit.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Maitland', 'Blue Care', '15 High Street', 'Maitland', 'NSW', '2320', -32.7333, 151.5583, 'aged-care', 'aged-care', 315000, 515000, 350, 550, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '02 4933 8111', 'maitland@bluecare.org.au', 'https://bluecare.org.au', 'Hunter Valley aged care. Gardens and historic town center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Healthcare Maroubra', 'Catholic Healthcare', '125 Anzac Parade', 'Maroubra', 'NSW', '2035', -33.9500, 151.2383, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '02 9311 9111', 'maroubra@catholichealthcare.com.au', 'https://catholichealthcare.com.au', 'Eastern suburbs beachside aged care. Chapel, cafe, and beach access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('HammondCare Greenwich Hospital', 'HammondCare', '45 River Road', 'Greenwich', 'NSW', '2065', -33.8333, 151.1833, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '02 9438 1011', 'greenwich@hammond.com.au', 'https://hammond.com.au', 'Premium Lower North Shore aged care. Pool, harbour views, specialist dementia care.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Uniting Turramurra', 'Uniting NSW & ACT', '88 Eastern Road', 'Turramurra', 'NSW', '2074', -33.7367, 151.1283, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '02 9488 2011', 'turramurra@uniting.org', 'https://uniting.org', 'Upper North Shore aged care. Pool, gardens, and leafy surrounds.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Japara The Grange Goulburn', 'Japara Healthcare', '15 Clifford Street', 'Goulburn', 'NSW', '2580', -34.7550, 149.7217, 'aged-care', 'aged-care', 255000, 415000, 300, 490, 34, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '02 4822 3011', 'goulburn@japara.com.au', 'https://japara.com.au', 'Southern Tablelands aged care. Gardens and historic setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Whiddon Cessnock', 'Whiddon Group', '125 Vincent Street', 'Cessnock', 'NSW', '2325', -32.8333, 151.3500, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '02 4990 4011', 'cessnock@whiddon.com.au', 'https://whiddon.com.au', 'Hunter Valley wine country aged care. Gardens and regional charm.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Coffs Harbour', 'Allity', '45 Park Avenue', 'Coffs Harbour', 'NSW', '2450', -30.2967, 153.1183, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '02 6651 5011', 'coffsharbour@allity.com.au', 'https://allity.com.au', 'Mid North Coast aged care. Pool, gardens, and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('RSL LifeCare Forster', 'RSL LifeCare', '88 Lake Street', 'Forster', 'NSW', '2428', -32.1783, 152.5117, 'independent', 'independent', 425000, 685000, 440, 680, 28, '["pool", "bowling-green", "library", "common-room", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 114, 55, '02 6554 6011', 'forster@rsllifecare.org.au', 'https://rsllifecare.org.au', 'Coastal retirement near lakes. Pool, bowling green, and beach lifestyle.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC (12 villages)
('Regis Aged Care Hawthorn', 'Regis Aged Care', '125 Burwood Road', 'Hawthorn', 'VIC', '3122', -37.8217, 145.0317, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 122, 55, '03 9818 1111', 'hawthorn@regis.com.au', 'https://regis.com.au', 'Inner east Melbourne premium aged care. Pool, gardens, and Glenferrie Road.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Keilor Downs', 'Estia Health', '45 Taylors Road', 'Keilor Downs', 'VIC', '3038', -37.7217, 144.8017, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '03 9361 2111', 'keilordowns@estiahealth.com.au', 'https://estiahealth.com.au', 'Northwest Melbourne aged care. Gardens and close to Watergardens.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Cheltenham', 'Arcare', '88 Centre Dandenong Road', 'Cheltenham', 'VIC', '3192', -37.9617, 145.0550, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 126, 55, '03 9583 3111', 'cheltenham@arcare.com.au', 'https://arcare.com.au', 'Bayside premium aged care. Pool, gym, cinema, and close to Southland.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bupa Aged Care Box Hill', 'Bupa', '15 Elgar Road', 'Box Hill', 'VIC', '3128', -37.8167, 145.1233, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '03 9899 4111', 'boxhill@bupa.com.au', 'https://bupa.com.au', 'Eastern suburbs aged care. Gardens, cafe, and train to city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Reservoir', 'Bolton Clarke', '125 Spring Street', 'Reservoir', 'VIC', '3073', -37.7150, 145.0050, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '03 9460 5111', 'reservoir@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Northern suburbs aged care. Gardens and close to Northland.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Ballarat', 'Opal Aged Care', '45 Sturt Street', 'Ballarat', 'VIC', '3350', -37.5633, 143.8583, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '03 5332 6111', 'ballarat@opalcare.com.au', 'https://opalcare.com.au', 'Historic goldfields aged care. Gardens and heritage architecture.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Coburg', 'Regis Aged Care', '88 Sydney Road', 'Coburg', 'VIC', '3058', -37.7433, 144.9617, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '03 9354 7111', 'coburg@regis.com.au', 'https://regis.com.au', 'Inner north Melbourne aged care. Gardens, cafe, and tram access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Wangaratta', 'Estia Health', '15 Tone Road', 'Wangaratta', 'VIC', '3677', -36.3600, 146.3200, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '03 5721 8111', 'wangaratta@estiahealth.com.au', 'https://estiahealth.com.au', 'Northeast Victoria aged care. Gardens and regional city charm.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas Heidelberg Heights', 'Benetas', '125 Southern Road', 'Heidelberg Heights', 'VIC', '3081', -37.7383, 145.0517, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '03 9457 9111', 'heidelbergheights@benetas.com.au', 'https://benetas.com.au', 'Northeast Melbourne aged care. Gardens and close to Austin Hospital.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Anglesea House', 'Japara Healthcare', '45 Noble Street', 'Anglesea', 'VIC', '3230', -38.4083, 144.1850, 'aged-care', 'aged-care', 335000, 535000, 370, 570, 32, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '03 5263 1012', 'anglesea@japara.com.au', 'https://japara.com.au', 'Great Ocean Road coastal aged care. Gardens and surf town atmosphere.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Colac', 'Mercy Health', '88 Connor Street', 'Colac', 'VIC', '3250', -38.3400, 143.5850, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 68, 55, '03 5231 2012', 'colac@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Western Victoria aged care. Chapel, gardens, and lake district setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ryman Healthcare Charles Brownlow', 'Ryman Healthcare', '125 Mt Dandenong Road', 'Ringwood East', 'VIC', '3135', -37.8150, 145.2533, 'aged-care', 'aged-care', 475000, 895000, 510, 870, 28, '["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 248, 55, '03 9870 3012', 'charlesbrownlow@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Large premium retirement in Ringwood. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- QLD (12 villages)
('Regis Aged Care Indooroopilly', 'Regis Aged Care', '88 Station Road', 'Indooroopilly', 'QLD', '4068', -27.4983, 152.9717, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '07 3878 1111', 'indooroopilly@regis.com.au', 'https://regis.com.au', 'Inner west Brisbane premium aged care. Pool, gardens, and shopping.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Blue Care Sunnybank', 'Blue Care', '45 Mains Road', 'Sunnybank', 'QLD', '4109', -27.5817, 153.0617, 'aged-care', 'aged-care', 415000, 615000, 450, 650, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '07 3345 2111', 'sunnybank@bluecare.org.au', 'https://bluecare.org.au', 'Southern Brisbane aged care. Gardens and multicultural community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Currumbin', 'Opal Aged Care', '125 Currumbin Creek Road', 'Currumbin', 'QLD', '4223', -28.1367, 153.4867, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '07 5534 3111', 'currumbin@opalcare.com.au', 'https://opalcare.com.au', 'Southern Gold Coast beachside aged care. Pool, gardens, and wildlife sanctuary nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('TriCare Aged Care Aspley', 'TriCare', '15 Robinson Road', 'Aspley', 'QLD', '4034', -27.3633, 153.0217, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '07 3263 4111', 'aspley@tricare.com.au', 'https://tricare.com.au', 'North Brisbane aged care. Gardens, cafe, and close to Hypermarket.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Runaway Bay', 'Estia Health', '88 Bayview Street', 'Runaway Bay', 'QLD', '4216', -27.9050, 153.3917, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 5537 5111', 'runawaybay@estiahealth.com.au', 'https://estiahealth.com.au', 'Northern Gold Coast waterfront aged care. Pool, gardens, and marina access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Holland Park', 'Bolton Clarke', '45 Logan Road', 'Holland Park', 'QLD', '4121', -27.5183, 153.0683, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '07 3397 6111', 'hollandpark@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Inner south Brisbane aged care. Gardens, cafe, and bus routes.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Townsville', 'Adventist Aged Care', '125 Ross River Road', 'Townsville', 'QLD', '4814', -19.3200, 146.7617, 'aged-care', 'aged-care', 335000, 535000, 370, 570, 32, '["pool", "library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '07 4775 7111', 'townsville@adventistcare.org.au', 'https://adventistcare.org.au', 'Tropical North Queensland aged care. Pool, chapel, and gardens.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ozcare Ipswich', 'Ozcare', '15 Brisbane Street', 'Ipswich', 'QLD', '4305', -27.6167, 152.7617, 'aged-care', 'aged-care', 315000, 515000, 350, 550, 32, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '07 3202 8111', 'ipswich@ozcare.org.au', 'https://ozcare.org.au', 'West Brisbane aged care. Chapel, gardens, and historic Ipswich.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Karinya Place', 'Carinity', '88 Dorchester Street', 'South Brisbane', 'QLD', '4101', -27.4817, 153.0167, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '07 3844 9111', 'karinyaplace@carinity.org.au', 'https://carinity.org.au', 'Inner city Brisbane aged care. Chapel, cafe, and close to cultural precinct.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Aged Care Warwick', 'Regis Aged Care', '45 Palmerin Street', 'Warwick', 'QLD', '4370', -28.2167, 152.0333, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '07 4661 1013', 'warwick@regis.com.au', 'https://regis.com.au', 'Southern Downs aged care. Gardens and historic country town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Coolum Beach', 'Allity', '125 David Low Way', 'Coolum Beach', 'QLD', '4573', -26.5333, 153.0883, 'aged-care', 'aged-care', 415000, 625000, 450, 660, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '07 5446 2013', 'coolumbeach@allity.com.au', 'https://allity.com.au', 'Sunshine Coast beachside aged care. Pool, gardens, and surf beach.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care New Farm', 'Southern Cross Care QLD', '15 Brunswick Street', 'New Farm', 'QLD', '4005', -27.4650, 153.0500, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '07 3358 3013', 'newfarm@scrosscc.com.au', 'https://scrosscc.com.au', 'Premium inner Brisbane aged care. Pool, riverside park, and village atmosphere.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- SA (5 villages)
('Regis Aged Care Parkside', 'Regis Aged Care', '125 Glen Osmond Road', 'Parkside', 'SA', '5063', -34.9450, 138.6167, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '08 8373 1111', 'parkside@regis.com.au', 'https://regis.com.au', 'Premium inner Adelaide aged care. Pool, gardens, and parklands.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Fullarton', 'Estia Health', '45 Fullarton Road', 'Fullarton', 'SA', '5063', -34.9550, 138.6217, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '08 8338 2111', 'fullarton@estiahealth.com.au', 'https://estiahealth.com.au', 'Eastern suburbs Adelaide aged care. Gardens, cafe, and close to shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Strathalbyn', 'ACH Group', '88 Dawson Street', 'Strathalbyn', 'SA', '5255', -35.2617, 138.8950, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 68, 55, '08 8536 3111', 'strathalbyn@ach.org.au', 'https://ach.org.au', 'Fleurieu historic town aged care. Gardens and antique shops.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Westbourne Park', 'Southern Cross Care SA', '15 Marion Road', 'Westbourne Park', 'SA', '5041', -34.9900, 138.5750, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '08 8293 4111', 'westbournepark@scsa.org.au', 'https://scsa.org.au', 'Inner south Adelaide aged care. Gardens, cafe, and tram route.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Mitcham Village', 'Japara Healthcare', '125 Aberfoyle Road', 'Mitcham', 'SA', '5062', -34.9833, 138.6283, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '08 8272 5111', 'mitchamvillage@japara.com.au', 'https://japara.com.au', 'Eastern Adelaide aged care. Gardens and close to Mitcham shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- WA (4 villages)
('Regis Aged Care Cottesloe', 'Regis Aged Care', '88 Broome Street', 'Cottesloe', 'WA', '6011', -31.9983, 115.7600, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 126, 55, '08 9383 1111', 'cottesloe@regis.com.au', 'https://regis.com.au', 'Premium beachside Perth aged care. Pool, gym, and walk to Cottesloe Beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bethanie Esprit Gwelup', 'Bethanie Group', '45 Erindale Road', 'Gwelup', 'WA', '6018', -31.8683, 115.7967, 'independent', 'independent', 395000, 625000, 410, 640, 30, '["pool", "gym", "library", "common-room", "bbq-area", "workshop"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 128, 55, '08 9344 2111', 'gwelup@bethanie.com.au', 'https://bethanie.com.au', 'Northern Perth retirement. Pool, gym, and close to Karrinyup Shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Kallaroo', 'Amana Living', '125 Dampier Avenue', 'Kallaroo', 'WA', '6025', -31.7833, 115.7500, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '08 9401 3111', 'kallaroo@amana.com.au', 'https://amana.com.au', 'Northern beaches Perth aged care. Gardens and close to ocean.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Albany', 'Opal Aged Care', '15 York Street', 'Albany', 'WA', '6330', -35.0267, 117.8833, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '08 9841 4111', 'albany@opalcare.com.au', 'https://opalcare.com.au', 'Great Southern WA aged care. Gardens and historic port city.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Regis Aged Care Burnie East', 'Regis Aged Care', '125 Mount Street', 'Burnie', 'TAS', '7320', -41.0483, 145.9133, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '03 6432 1111', 'burnieeast@regis.com.au', 'https://regis.com.au', 'North coast Tasmania aged care. Gardens and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Southern Cross Care Canberra South', 'Southern Cross Care ACT & NSW', '15 Canberra Avenue', 'Fyshwick', 'ACT', '2609', -35.3350, 149.1667, 'aged-care', 'aged-care', 445000, 685000, 480, 720, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '02 6239 1111', 'canberrasouth@sccliving.org.au', 'https://sccliving.org.au', 'South Canberra aged care. Gardens, cafe, and close to shops.', 'approved', 'seed_data', true, false, NOW(), NOW());
