-- Batch 4: 30 Additional Retirement Villages - Metro & Growth Corridors
-- Brings total to 105 villages with strong metro coverage

INSERT INTO retirement_villages (
  name,
  operator,
  location,
  suburb,
  state,
  postcode,
  latitude,
  longitude,
  village_type,
  care_level,
  entry_price_min,
  entry_price_max,
  monthly_fees_min,
  monthly_fees_max,
  dmf_percentage,
  amenities,
  care_services,
  bedrooms,
  pet_friendly,
  total_units,
  age_restriction,
  contact_phone,
  contact_email,
  website,
  description,
  status,
  source,
  verified,
  featured,
  submitted_at,
  approved_at
) VALUES

-- NEW SOUTH WALES - Sydney Metro Growth (9 villages)

('Aveo Durack', 'Aveo Group', '175 Richmond Road', 'Cambridge Park', 'NSW', '2747', -33.7417, 150.7217, 'independent', 'independent', 395000, 625000, 410, 640, 30,
'["pool", "gym", "library", "common-room", "bbq-area", "workshop"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 124, 55, '02 4721 1111', 'durack@aveo.com.au', 'https://aveo.com.au',
'Western Sydney retirement living near Penrith. Modern apartments with pool, gym, and close to Nepean Hospital.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Lendlease Retirement Living Newington', 'Lendlease', '88 Australia Avenue', 'Sydney Olympic Park', 'NSW', '2127', -33.8483, 151.0650, 'independent', 'independent', 680000, 1150000, 650, 960, 26,
'["pool", "gym", "cinema", "library", "common-room", "workshop", "bbq-area", "garden"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 198, 55, '02 9764 2222', 'newington@lendlease.com', 'https://lendlease.com',
'Premium retirement at Sydney Olympic Park. Contemporary apartments with resort facilities, close to parklands and transport.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Stockland Willowdale Elara', 'Stockland', '25 Elara Boulevard', 'Marsden Park', 'NSW', '2765', -33.7017, 150.8417, 'independent', 'independent', 465000, 695000, 450, 680, 28,
'["pool", "gym", "library", "common-room", "bbq-area", "garden"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 148, 55, '02 8883 3333', 'elara@stockland.com.au', 'https://stockland.com',
'Northwest Sydney retirement in new Elara estate. Pool, gym, and modern community center.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Anglicare Newmarch House', 'Anglicare Sydney', '20 Anglicare Drive', 'Kingswood', 'NSW', '2747', -33.7650, 150.7183, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30,
'["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 104, 55, '02 4731 4444', 'newmarch@anglicare.org.au', 'https://anglicare.org.au',
'Western Sydney aged care facility. Chapel, gardens, and strong community support.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Southern Cross Care Garfield Barwick', 'Southern Cross Care NSW & ACT', '88 Hammers Road', 'Northmead', 'NSW', '2152', -33.7883, 150.9983, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 126, 55, '02 9683 5555', 'garfieldbarwick@sccliving.org.au', 'https://sccliving.org.au',
'Parramatta area aged care. Pool, gardens, dementia unit, and close to Westfield Parramatta.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('BaptistCare Gracewood', 'BaptistCare NSW & ACT', '15 Kellerman Drive', 'Green Valley', 'NSW', '2168', -33.9000, 150.8667, 'assisted', 'assisted', 375000, 575000, 390, 590, 30,
'["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb,
ARRAY['1-bed', '2-bed'], true, 92, 55, '02 9607 6666', 'gracewood@baptistcare.org.au', 'https://baptistcare.org.au',
'Southwest Sydney retirement village. Chapel, gardens, and caring community atmosphere.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('IRT Culburra Beach', 'IRT Group', '125 Weston Street', 'Culburra Beach', 'NSW', '2540', -34.9283, 150.7617, 'independent', 'independent', 325000, 545000, 350, 550, 32,
'["bowling-green", "library", "common-room", "bbq-area", "garden"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 88, 55, '02 4447 7777', 'culburra@irt.org.au', 'https://irt.org.au',
'Beachside retirement on the South Coast. Bowling green, gardens, and minutes to pristine beaches.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Uniting Lindfield Gardens', 'Uniting NSW & ACT', '45 Tryon Road', 'Lindfield', 'NSW', '2070', -33.7783, 151.1617, 'aged-care', 'aged-care', 580000, 880000, 620, 900, 26,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 114, 55, '02 9416 8888', 'lindfield@uniting.org', 'https://uniting.org',
'Upper North Shore premium aged care. Pool, gardens, and close to Lindfield village shops and trains.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Catholic Healthcare St Joseph Village', 'Catholic Healthcare', '88 Liverpool Road', 'Strathfield', 'NSW', '2135', -33.8717, 151.0883, 'assisted', 'assisted', 525000, 785000, 540, 800, 28,
'["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 86, 55, '02 9746 9999', 'stjoseph@catholichealthcare.com.au', 'https://catholichealthcare.com.au',
'Inner west Sydney retirement. Chapel, gardens, and excellent train access to the city.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- VICTORIA - Melbourne Growth Corridors (8 villages)

('Stockland Retirement Living Weir Views', 'Stockland', '45 High Street', 'Lancefield', 'VIC', '3435', -37.2733, 144.7450, 'independent', 'independent', 285000, 485000, 310, 510, 32,
'["library", "common-room", "bbq-area", "garden", "workshop"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 74, 55, '03 5429 1111', 'weirviews@stockland.com.au', 'https://stockland.com',
'Historic Macedon Ranges retirement. Country town charm with community center and gardens.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Aurrum Aged Care Eaglemont', 'Aurrum', '88 Wanalta Road', 'Eaglemont', 'VIC', '3084', -37.7617, 145.0633, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 108, 55, '03 9457 2222', 'eaglemont@aurrumagedcare.com.au', 'https://aurrumagedcare.com.au',
'Premium aged care in leafy Heidelberg area. Pool, gardens, and close to Austin Hospital.',
'approved', 'seed_data', true, true, NOW(), NOW()),

('Brightwater Care Group Taylors Lakes', 'Brightwater', '15 Calder Park Drive', 'Taylors Lakes', 'VIC', '3038', -37.7000, 144.7750, 'aged-care', 'aged-care', 395000, 595000, 430, 630, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 96, 55, '03 9390 3333', 'taylorslakes@brightwatergroup.com', 'https://brightwatergroup.com',
'Northwest Melbourne aged care. Modern facility with gardens near Watergardens Town Centre.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Estia Health Glen Waverley', 'Estia Health', '125 Blackburn Road', 'Glen Waverley', 'VIC', '3150', -37.8783, 145.1633, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 112, 55, '03 9561 4444', 'glenwaverley@estiahealth.com.au', 'https://estiahealth.com.au',
'Eastern suburbs aged care. Close to The Glen shopping, trains, and Monash Medical Centre.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Arcare Craigieburn', 'Arcare', '88 Highlander Drive', 'Craigieburn', 'VIC', '3064', -37.6000, 144.9333, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30,
'["pool", "library", "common-room", "cinema", "hairdresser", "cafe", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 124, 55, '03 8338 5555', 'craigieburn@arcare.com.au', 'https://arcare.com.au',
'Northern growth corridor aged care. Pool, cinema, dementia unit, and modern facilities.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Bupa Aged Care Parkdale', 'Bupa', '45 Como Parade West', 'Parkdale', 'VIC', '3195', -37.9933, 145.0733, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 102, 55, '03 9587 6666', 'parkdale@bupa.com.au', 'https://bupa.com.au',
'Bayside Melbourne aged care near beaches. Gardens, cafe, and close to Parkdale station.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Opal Aged Care Keilor', 'Opal Aged Care', '15 Keilor Road', 'Keilor East', 'VIC', '3033', -37.7267, 144.8517, 'aged-care', 'aged-care', 415000, 615000, 450, 650, 30,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 94, 55, '03 9331 7777', 'keilor@opalcare.com.au', 'https://opalcare.com.au',
'Northwest Melbourne aged care on Keilor Road. Gardens, cafe, and close to Essendon Airport.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Regis Aged Care Reservoir', 'Regis Aged Care', '88 Spring Street', 'Reservoir', 'VIC', '3073', -37.7183, 145.0033, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 118, 55, '03 9462 8888', 'reservoir@regis.com.au', 'https://regis.com.au',
'Northern suburbs aged care. Pool, gardens, dementia care, and close to Northland Shopping Centre.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- QUEENSLAND - Brisbane & Regional Growth (6 villages)

('Aveo Durack Shores', 'Aveo Group', '15 Durack Street', 'Durack', 'QLD', '4077', -27.5917, 152.9833, 'independent', 'independent', 395000, 625000, 410, 640, 30,
'["pool", "gym", "library", "common-room", "bbq-area", "workshop"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 132, 55, '07 3278 1111', 'duracqld@aveo.com.au', 'https://aveo.com.au',
'Southwest Brisbane retirement. Pool, gym, and close to Inala Plaza shopping.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Lendlease Retirement Living Springfield', 'Lendlease', '88 Innovation Drive', 'Springfield Lakes', 'QLD', '4300', -27.6717, 152.9217, 'independent', 'independent', 425000, 685000, 440, 680, 28,
'["pool", "gym", "library", "common-room", "bbq-area", "workshop"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 156, 55, '07 3470 2222', 'springfield@lendlease.com', 'https://lendlease.com',
'Modern retirement in growing Springfield. Pool, gym, and close to Orion Shopping Centre.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Blue Care Moreton Shores', 'Blue Care', '45 Bayview Terrace', 'Deception Bay', 'QLD', '4508', -27.1917, 153.0333, 'assisted', 'assisted', 315000, 515000, 340, 540, 32,
'["library", "common-room", "bbq-area", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb,
ARRAY['1-bed', '2-bed'], true, 78, 55, '07 3203 3333', 'moretonshores@bluecare.org.au', 'https://bluecare.org.au',
'Affordable Moreton Bay retirement. Gardens, BBQ areas, and close to waterfront.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('TriCare Aged Care Helensvale', 'TriCare', '125 Discovery Drive', 'Helensvale', 'QLD', '4212', -27.9083, 153.3283, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28,
'["pool", "gym", "library", "common-room", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 116, 55, '07 5573 4444', 'helensvale@tricare.com.au', 'https://tricare.com.au',
'Northern Gold Coast aged care. Pool, gym, cafe, and close to Westfield Helensvale.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Ozcare Logan', 'Ozcare', '88 Chambers Flat Road', 'Logan Central', 'QLD', '4114', -27.6383, 153.1083, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 30,
'["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 92, 55, '07 3808 5555', 'logan@ozcare.org.au', 'https://ozcare.org.au',
'Logan aged care with chapel and gardens. Community focus and close to Logan Hyperdome.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Bolton Clarke Hervey Bay', 'Bolton Clarke', '15 Elizabeth Street', 'Urangan', 'QLD', '4655', -25.2950, 152.9067, 'assisted', 'assisted', 295000, 495000, 330, 530, 32,
'["pool", "library", "common-room", "bbq-area", "garden"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "transport"]'::jsonb,
ARRAY['1-bed', '2-bed', '3-bed'], true, 104, 55, '07 4125 6666', 'herveybay@boltonclarke.com.au', 'https://boltonclarke.com.au',
'Fraser Coast retirement near beaches. Pool, gardens, and close to whale watching and marina.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- SOUTH AUSTRALIA - Adelaide Metro (3 villages)

('Regis Aged Care Brighton', 'Regis Aged Care', '45 Morphett Road', 'Brighton', 'SA', '5048', -35.0183, 138.5217, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 98, 55, '08 8298 1111', 'brighton@regis.com.au', 'https://regis.com.au',
'Beachside Adelaide aged care. Close to Glenelg beaches, jetty, and trams to city.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('ACH Group Colonel Light Gardens', 'ACH Group', '88 Chelmsford Avenue', 'Colonel Light Gardens', 'SA', '5041', -34.9917, 138.5783, 'independent', 'independent', 425000, 625000, 440, 640, 30,
'["pool", "library", "common-room", "bbq-area", "garden", "workshop"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 96, 55, '08 8267 2222', 'clgardens@ach.org.au', 'https://ach.org.au',
'Heritage Adelaide suburb retirement. Pool, gardens, and tree-lined streets close to city.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Estia Health Woodville', 'Estia Health', '15 Port Road', 'Woodville', 'SA', '5011', -34.8717, 138.5450, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 84, 55, '08 8445 3333', 'woodville@estiahealth.com.au', 'https://estiahealth.com.au',
'Western Adelaide aged care on Port Road. Gardens and easy access to city and port.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- WESTERN AUSTRALIA - Perth Growth (2 villages)

('Bethanie Esprit Baldivis', 'Bethanie Group', '88 Safety Bay Road', 'Baldivis', 'WA', '6171', -32.3317, 115.8267, 'independent', 'independent', 365000, 585000, 380, 580, 30,
'["pool", "gym", "bowling-green", "library", "common-room", "bbq-area", "workshop"]'::jsonb,
'["emergency-call", "on-site-manager"]'::jsonb,
ARRAY['2-bed', '3-bed'], true, 142, 55, '08 9523 1111', 'baldivis@bethanie.com.au', 'https://bethanie.com.au',
'Southern Perth growth area retirement. Pool, gym, bowling green, and modern community facilities.',
'approved', 'seed_data', true, false, NOW(), NOW()),

('Amana Living Aged Care Joondalup', 'Amana Living', '15 Shenton Avenue', 'Joondalup', 'WA', '6027', -31.7450, 115.7667, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28,
'["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 108, 55, '08 9400 2222', 'joondalup@amana.com.au', 'https://amana.com.au',
'Northern Perth aged care near Lakeside shopping. Pool, gardens, and dementia care services.',
'approved', 'seed_data', true, true, NOW(), NOW()),

-- TASMANIA (1 village)

('Embracia Aged Care Launceston', 'Embracia', '88 Elphin Road', 'Launceston', 'TAS', '7250', -41.4333, 147.1333, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32,
'["library", "common-room", "garden", "hairdresser"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 82, 55, '03 6331 1111', 'launceston@embraciacare.com.au', 'https://embraciacare.com.au',
'Northern Tasmania aged care. Gardens and close to Launceston city center and hospitals.',
'approved', 'seed_data', true, false, NOW(), NOW()),

-- AUSTRALIAN CAPITAL TERRITORY (1 village)

('Goodwin Aged Care Monash', 'Goodwin', '125 Pitman Street', 'Monash', 'ACT', '2904', -35.4150, 149.0900, 'aged-care', 'aged-care', 465000, 705000, 500, 740, 28,
'["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb,
'["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb,
ARRAY['1-bed', '2-bed'], false, 96, 55, '02 6198 1111', 'monash@goodwin.org.au', 'https://goodwin.org.au',
'Canberra south aged care in Tuggeranong. Modern facility with dementia unit and gardens.',
'approved', 'seed_data', true, false, NOW(), NOW());
