-- Batch 19: 50 Additional Retirement Villages - Growth Corridors & Aged Care
-- Brings total to 855 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW Growth Corridors (15 villages)
('Aveo Retirement Living Rouse Hill', 'Aveo Group', '88 Windsor Road', 'Rouse Hill', 'NSW', '2155', -33.6833, 150.9117, 'independent', 'independent', 565000, 895000, 560, 880, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 152, 55, '02 8884 4401', 'rousehill@aveo.com.au', 'https://aveo.com.au', 'Northwest growth corridor. Pool, gym, cinema, and Metro access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Stockland Retirement Living Marsden Park', 'Stockland', '125 Richmond Road', 'Marsden Park', 'NSW', '2765', -33.7067, 150.8417, 'independent', 'independent', 525000, 845000, 520, 840, 28, '[\"pool\", \"gym\", \"bowling-green\", \"library\", \"common-room\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 164, 55, '02 8625 4401', 'marsdenpark@stockland.com.au', 'https://stockland.com', 'Western Sydney growth. Pool, gym, bowling green, new community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Lendlease Retirement Living Oran Park', 'Lendlease', '45 Oran Park Drive', 'Oran Park', 'NSW', '2570', -34.0083, 150.7367, 'independent', 'independent', 545000, 875000, 540, 860, 26, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 158, 55, '02 4648 4401', 'oranpark@lendlease.com', 'https://lendlease.com', 'Southwest Sydney growth. Pool, gym, cinema, and modern amenities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Penrith', 'Regis Aged Care', '88 Mulgoa Road', 'Penrith', 'NSW', '2750', -33.7517, 150.6933, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '02 4722 4401', 'penrithregis@regis.com.au', 'https://regis.com.au', 'Western Sydney aged care. Gardens, cafe, and Panthers precinct.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Campbelltown', 'Estia Health', '125 Queen Street', 'Campbelltown', 'NSW', '2560', -34.0650, 150.8167, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '02 4625 4401', 'campbelltown@estiahealth.com.au', 'https://estiahealth.com.au', 'Southwest Sydney aged care. Gardens, cafe, and major hospital nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Aged Care Cabramatta', 'Arcare', '15 John Street', 'Cabramatta', 'NSW', '2166', -33.8950, 150.9367, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\", \"dementia-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '02 9724 4401', 'cabramatta@arcare.com.au', 'https://arcare.com.au', 'Multicultural aged care. Pool, gym, cinema, diverse community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bupa Aged Care Liverpool', 'Bupa', '88 Hume Highway', 'Liverpool', 'NSW', '2170', -33.9217, 150.9233, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '02 9602 4401', 'liverpool@bupa.com.au', 'https://bupa.com.au', 'Southwest Sydney aged care. Gardens, cafe, and major hospital.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Blacktown', 'Bolton Clarke', '125 Main Street', 'Blacktown', 'NSW', '2148', -33.7700, 150.9050, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '02 9621 4401', 'blacktown@boltonclarke.com.au', 'https://boltonclarke.com.au', 'West Sydney aged care. Gardens, cafe, and train hub access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Healthcare Fairfield', 'Japara Healthcare', '45 The Crescent', 'Fairfield', 'NSW', '2165', -33.8700, 150.9550, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '02 9725 4401', 'fairfield@japara.com.au', 'https://japara.com.au', 'West Sydney multicultural aged care. Gardens, cafe, diverse services.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Mount Druitt', 'Allity', '88 Luxford Road', 'Mount Druitt', 'NSW', '2770', -33.7617, 150.8167, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '02 9625 4401', 'mountdruitt@allity.com.au', 'https://allity.com.au', 'Western Sydney aged care. Gardens and Westfield shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Whiddon Group Minto', 'Whiddon Group', '125 Ben Lomond Road', 'Minto', 'NSW', '2566', -34.0317, 150.8450, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '02 4627 4401', 'minto@whiddon.com.au', 'https://whiddon.com.au', 'Southwest Sydney aged care. Gardens and growth corridor.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Parramatta', 'Southern Cross Care NSW & ACT', '15 Church Street', 'Parramatta', 'NSW', '2150', -33.8167, 151.0000, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '[\"library\", \"common-room\", \"chapel\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '02 9633 4401', 'parramatta@scrosscc.com.au', 'https://scrosscc.com.au', 'Central west Sydney aged care. Chapel, cafe, and CBD access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Westmead', 'Mercy Health', '88 Hawkesbury Road', 'Westmead', 'NSW', '2145', -33.8067, 150.9883, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '[\"library\", \"common-room\", \"chapel\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '02 9845 4401', 'westmead@mercyhealth.com.au', 'https://mercyhealth.com.au', 'West Sydney aged care. Chapel, cafe, and major hospital precinct.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('HammondCare Hurstville', 'HammondCare', '125 Forest Road', 'Hurstville', 'NSW', '2220', -33.9683, 151.1000, 'aged-care', 'aged-care', 525000, 795000, 560, 840, 26, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\", \"dementia-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '02 9580 4401', 'hurstville@hammond.com.au', 'https://hammond.com.au', 'St George aged care. Gardens, cafe, dementia care, train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Uniting Miranda', 'Uniting NSW & ACT', '45 The Kingsway', 'Miranda', 'NSW', '2228', -34.0350, 151.1000, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '02 9525 4401', 'miranda@uniting.org', 'https://uniting.org', 'Sutherland Shire aged care. Gardens, cafe, and Westfield shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC Growth Corridors (12 villages)
('Aveo Retirement Living Tarneit', 'Aveo Group', '88 Derrimut Road', 'Tarneit', 'VIC', '3029', -37.8550, 144.6717, 'independent', 'independent', 425000, 685000, 420, 680, 30, '[\"pool\", \"gym\", \"library\", \"common-room\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 148, 55, '03 9742 5401', 'tarneit@aveo.com.au', 'https://aveo.com.au', 'West growth corridor. Pool, gym, and modern community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Stockland Retirement Living Point Cook', 'Stockland', '125 Point Cook Road', 'Point Cook', 'VIC', '3030', -37.9150, 144.7483, 'independent', 'independent', 465000, 745000, 460, 740, 28, '[\"pool\", \"gym\", \"bowling-green\", \"library\", \"common-room\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 156, 55, '03 8376 5401', 'pointcook@stockland.com.au', 'https://stockland.com', 'Coastal growth area. Pool, gym, bowling green, marina access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Lendlease Retirement Living Epping', 'Lendlease', '45 High Street', 'Epping', 'VIC', '3076', -37.6500, 145.0200, 'independent', 'independent', 485000, 775000, 480, 760, 28, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 152, 55, '03 9401 5401', 'epping@lendlease.com', 'https://lendlease.com', 'North growth corridor. Pool, gym, cinema, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Pakenham', 'Regis Aged Care', '88 Main Street', 'Pakenham', 'VIC', '3810', -38.0717, 145.4850, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '03 5941 5401', 'pakenham@regis.com.au', 'https://regis.com.au', 'Southeast growth corridor aged care. Gardens and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Cranbourne', 'Estia Health', '125 South Gippsland Highway', 'Cranbourne', 'VIC', '3977', -38.0983, 145.2817, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '03 5996 5401', 'cranbourne@estiahealth.com.au', 'https://estiahealth.com.au', 'Southeast growth aged care. Gardens and shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Aged Care Sydenham', 'Arcare', '15 Sydenham Road', 'Sydenham', 'VIC', '3037', -37.6983, 144.7667, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\", \"dementia-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 120, 55, '03 9449 5401', 'sydenham@arcare.com.au', 'https://arcare.com.au', 'Northwest growth aged care. Pool, gym, cinema, modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bupa Aged Care Melton', 'Bupa', '88 High Street', 'Melton', 'VIC', '3337', -37.6833, 144.5767, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '03 9747 5401', 'melton@bupa.com.au', 'https://bupa.com.au', 'West growth corridor aged care. Gardens and regional center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Sunbury', 'Bolton Clarke', '125 Evans Street', 'Sunbury', 'VIC', '3429', -37.5783, 144.7267, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '03 9744 5401', 'sunburybolton@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Northwest growth aged care. Gardens and historic town charm.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Healthcare Werribee', 'Japara Healthcare', '45 Watton Street', 'Werribee', 'VIC', '3030', -37.9033, 144.6633, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '03 9741 5401', 'werribeejapara@japara.com.au', 'https://japara.com.au', 'Southwest growth aged care. Gardens, cafe, and zoo nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas Aged Care Broadmeadows', 'Benetas', '88 Pascoe Vale Road', 'Broadmeadows', 'VIC', '3047', -37.6817, 144.9167, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '03 9309 5401', 'broadmeadows@benetas.com.au', 'https://benetas.com.au', 'North Melbourne aged care. Gardens and train hub access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Hoppers Crossing', 'Opal Aged Care', '125 Old Geelong Road', 'Hoppers Crossing', 'VIC', '3029', -37.8800, 144.7000, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '[\"pool\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '03 9749 5401', 'hopperscrossing@opalcare.com.au', 'https://opalcare.com.au', 'West growth aged care. Pool, gardens, and Pacific Werribee.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Gisborne', 'Mercy Health', '15 Hamilton Street', 'Gisborne', 'VIC', '3437', -37.4950, 144.5917, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '[\"library\", \"common-room\", \"chapel\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '03 5428 5401', 'gisborne@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Macedon Ranges aged care. Chapel, gardens, and tree change.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- QLD Growth Corridors (12 villages)
('Aveo Retirement Living North Lakes', 'Aveo Group', '88 North Lakes Drive', 'North Lakes', 'QLD', '4509', -27.2383, 152.9617, 'independent', 'independent', 485000, 775000, 480, 760, 28, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 156, 55, '07 3482 6401', 'northlakes@aveo.com.au', 'https://aveo.com.au', 'North Brisbane growth. Pool, gym, cinema, and Westfield shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Stockland Retirement Living Pimpama', 'Stockland', '125 Yawalpah Road', 'Pimpama', 'QLD', '4209', -27.8183, 153.3083, 'independent', 'independent', 445000, 705000, 440, 700, 28, '[\"pool\", \"gym\", \"bowling-green\", \"library\", \"common-room\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 162, 55, '07 5546 6401', 'pimpama@stockland.com.au', 'https://stockland.com', 'Gold Coast growth. Pool, gym, bowling green, and new community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Lendlease Retirement Living Caboolture', 'Lendlease', '45 Morayfield Road', 'Caboolture', 'QLD', '4510', -27.0850, 152.9517, 'independent', 'independent', 425000, 685000, 420, 680, 30, '[\"pool\", \"gym\", \"library\", \"common-room\", \"cinema\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 144, 55, '07 5495 6401', 'caboolture@lendlease.com', 'https://lendlease.com', 'North Brisbane corridor. Pool, gym, cinema, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Logan', 'Regis Aged Care', '88 Wembley Road', 'Logan Central', 'QLD', '4114', -27.6383, 153.1083, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '07 3299 6401', 'logan@regis.com.au', 'https://regis.com.au', 'South Brisbane aged care. Gardens, cafe, and Hyperdome shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Morayfield', 'Blue Care', '125 Morayfield Road', 'Morayfield', 'QLD', '4506', -27.1083, 152.9467, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '07 5428 6401', 'morayfield@bluecare.org.au', 'https://bluecare.org.au', 'North Brisbane growth aged care. Gardens and shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Beenleigh', 'Bolton Clarke', '15 Main Street', 'Beenleigh', 'QLD', '4207', -27.7150, 153.2033, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '07 3287 6401', 'beenleigh@boltonclarke.com.au', 'https://boltonclarke.com.au', 'South Brisbane aged care. Gardens and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('TriCare Aged Care Narangba', 'TriCare', '88 Golden Wattle Drive', 'Narangba', 'QLD', '4504', -27.2000, 152.9617, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '[\"pool\", \"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '07 3886 6401', 'narangba@tricare.com.au', 'https://tricare.com.au', 'North Brisbane growth aged care. Pool, gardens, and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Crestmead', 'Southern Cross Care QLD', '125 Outlook Drive', 'Crestmead', 'QLD', '4132', -27.6850, 153.1000, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '07 3803 6401', 'crestmead@scrosscc.com.au', 'https://scrosscc.com.au', 'Logan aged care. Gardens and growth corridor access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Browns Plains', 'Estia Health', '45 Grand Plaza Drive', 'Browns Plains', 'QLD', '4118', -27.6617, 153.0350, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '07 3800 6401', 'brownsplains@estiahealth.com.au', 'https://estiahealth.com.au', 'South Brisbane aged care. Gardens, cafe, and Grand Plaza shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Upper Coomera', 'Opal Aged Care', '88 Reserve Road', 'Upper Coomera', 'QLD', '4209', -27.8717, 153.2900, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '[\"pool\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '07 5573 6401', 'uppercoomera@opalcare.com.au', 'https://opalcare.com.au', 'North Gold Coast aged care. Pool, gardens, and Westfield nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Colthup', 'Carinity', '125 Chambers Flat Road', 'Park Ridge', 'QLD', '4125', -27.7183, 153.0333, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"chapel\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '07 3412 6401', 'colthup@carinity.org.au', 'https://carinity.org.au', 'South Brisbane aged care. Chapel, gardens, and growth area.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Elanora', 'Adventist Aged Care', '15 KP McGrath Drive', 'Elanora', 'QLD', '4221', -28.1217, 153.4317, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '[\"pool\", \"library\", \"common-room\", \"chapel\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 5598 6401', 'elanora@adventistcare.org.au', 'https://adventistcare.org.au', 'South Gold Coast aged care. Pool, chapel, gardens, and beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- SA (5 villages)
('Resthaven Aged Care Bellevue Heights', 'Resthaven', '88 Sheoak Road', 'Bellevue Heights', 'SA', '5050', -35.0167, 138.5833, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '08 8278 9001', 'bellevueheights@resthaven.asn.au', 'https://resthaven.asn.au', 'Southern hills aged care. Gardens and scenic Adelaide views.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Parkside', 'ACH Group', '125 Fullarton Road', 'Parkside', 'SA', '5063', -34.9450, 138.6133, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '08 8272 9001', 'parkside@ach.org.au', 'https://ach.org.au', 'Inner east Adelaide aged care. Gardens, cafe, and tree-lined streets.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Tea Tree Gully', 'Regis Aged Care', '45 North East Road', 'Tea Tree Gully', 'SA', '5091', -34.8283, 138.7317, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '08 8264 9001', 'teatreegully@regis.com.au', 'https://regis.com.au', 'Northeast Adelaide aged care. Gardens and Westfield shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Burnside', 'Estia Health', '88 Glynburn Road', 'Burnside', 'SA', '5066', -34.9350, 138.6383, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '08 8338 9001', 'burnside@estiahealth.com.au', 'https://estiahealth.com.au', 'Premium eastern suburbs aged care. Gardens, cafe, and village charm.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Elizabeth', 'Southern Cross Care SA', '125 Main North Road', 'Elizabeth', 'SA', '5112', -34.7217, 138.6717, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '[\"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '08 8252 9001', 'elizabeth@scsa.org.au', 'https://scsa.org.au', 'Northern Adelaide aged care. Gardens and shopping center nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- WA (4 villages)
('Bethanie Retirement Living Ellenbrook', 'Bethanie Group', '88 Main Street', 'Ellenbrook', 'WA', '6069', -31.7817, 115.9733, 'independent', 'independent', 425000, 685000, 420, 680, 30, '[\"pool\", \"gym\", \"library\", \"common-room\", \"bbq-area\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 136, 55, '08 9296 1001', 'ellenbrook@bethanie.com.au', 'https://bethanie.com.au', 'Northeast Perth growth. Pool, gym, and modern community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Baldivis', 'Regis Aged Care', '125 Safety Bay Road', 'Baldivis', 'WA', '6171', -32.3317, 115.8283, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '08 9523 1001', 'baldivis@regis.com.au', 'https://regis.com.au', 'South Perth growth aged care. Gardens and coastal access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Butler', 'Amana Living', '45 Kingsbridge Boulevard', 'Butler', 'WA', '6036', -31.6483, 115.7117, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '[\"pool\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '08 9562 1001', 'butler@amana.com.au', 'https://amana.com.au', 'North Perth growth aged care. Pool, gardens, and beach access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Byford', 'Opal Aged Care', '88 South Western Highway', 'Byford', 'WA', '6122', -32.2217, 116.0067, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '[\"pool\", \"library\", \"common-room\", \"garden\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '08 9525 1001', 'byford@opalcare.com.au', 'https://opalcare.com.au', 'Southeast Perth growth aged care. Pool, gardens, and rural fringe.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Estia Health Kingston', 'Estia Health', '125 Channel Highway', 'Kingston', 'TAS', '7050', -42.9783, 147.3067, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '[\"library\", \"common-room\", \"garden\", \"hairdresser\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 90, 55, '03 6229 1101', 'kingston@estiahealth.com.au', 'https://estiahealth.com.au', 'South Hobart aged care. Gardens and Channel views.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Aged Care Gungahlin', 'Goodwin', '15 Hinder Street', 'Gungahlin', 'ACT', '2912', -35.1833, 149.1317, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '[\"library\", \"common-room\", \"garden\", \"hairdresser\", \"cafe\"]'::jsonb, '[\"emergency-call\", \"on-site-manager\", \"visiting-nurse\", \"meals\", \"housekeeping\", \"personal-care\", \"24hr-care\"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '02 6242 1101', 'gungahlin@goodwin.org.au', 'https://goodwin.org.au', 'North Canberra growth aged care. Gardens, cafe, and town center.', 'approved', 'seed_data', true, false, NOW(), NOW());
