-- Batch 11: 50 Additional Retirement Villages
-- Brings total to 455 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW (15 villages)
('Aveo Durack Gardens', 'Aveo Group', '88 Jersey Road', 'Woollahra', 'NSW', '2025', -33.8883, 151.2417, 'independent', 'independent', 685000, 1050000, 680, 1020, 24, '["pool", "gym", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 126, 55, '02 9327 1401', 'woollahra@aveo.com.au', 'https://aveo.com.au', 'Premium eastern suburbs retirement. Pool, gym, and village shopping.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Raymond Terrace', 'Stockland', '45 William Street', 'Raymond Terrace', 'NSW', '2324', -32.7617, 151.7450, 'independent', 'independent', 345000, 565000, 360, 560, 32, '["pool", "library", "common-room", "bbq-area", "workshop"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 116, 55, '02 4987 1401', 'raymondterrace@stockland.com.au', 'https://stockland.com', 'Hunter Valley retirement. Pool and close to river.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Dee Why', 'Regis Aged Care', '125 Pittwater Road', 'Dee Why', 'NSW', '2099', -33.7533, 151.2850, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '02 9971 1401', 'deewhy@regis.com.au', 'https://regis.com.au', 'Northern Beaches aged care. Pool, gardens, and walk to beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Opal Aged Care Liverpool', 'Opal Aged Care', '15 Macquarie Street', 'Liverpool', 'NSW', '2170', -33.9217, 150.9233, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '02 9602 1401', 'liverpool@opalcare.com.au', 'https://opalcare.com.au', 'Southwest Sydney aged care. Gardens and close to shopping district.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Forster', 'Estia Health', '88 Lake Street', 'Forster', 'NSW', '2428', -32.1800, 152.5133, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '02 6555 1401', 'forster@estiahealth.com.au', 'https://estiahealth.com.au', 'Great Lakes aged care. Pool, gardens, and close to beaches and lakes.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Glebe', 'Arcare', '45 St Johns Road', 'Glebe', 'NSW', '2037', -33.8767, 151.1867, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '02 9660 1401', 'glebe@arcare.com.au', 'https://arcare.com.au', 'Premium inner city aged care. Pool, gym, cinema, and harbour nearby.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('BaptistCare The Haynes', 'BaptistCare NSW & ACT', '88 Forest Road', 'Arncliffe', 'NSW', '2205', -33.9367, 151.1450, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '02 9567 1401', 'haynes@baptistcare.org.au', 'https://baptistcare.org.au', 'St George area aged care. Chapel, gardens, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Muswellbrook', 'Blue Care', '15 Bridge Street', 'Muswellbrook', 'NSW', '2333', -32.2650, 150.8883, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '02 6541 1401', 'muswellbrook@bluecare.org.au', 'https://bluecare.org.au', 'Upper Hunter aged care. Gardens and coal mining town heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Healthcare Bexley', 'Catholic Healthcare', '125 Forest Road', 'Bexley', 'NSW', '2207', -33.9500, 151.1183, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '02 9567 1401', 'bexley@catholichealthcare.com.au', 'https://catholichealthcare.com.au', 'St George aged care. Chapel, gardens, and close to shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('HammondCare Wahroonga Gardens', 'HammondCare', '45 Coonanbarra Road', 'Wahroonga', 'NSW', '2076', -33.7200, 151.1183, 'aged-care', 'aged-care', 595000, 895000, 620, 900, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 124, 55, '02 9489 1401', 'wahroongagardens@hammond.com.au', 'https://hammond.com.au', 'Upper North Shore premium aged care. Pool, gardens, specialist dementia care.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Uniting Dougherty Villa', 'Uniting NSW & ACT', '88 Fitzroy Street', 'Chatswood', 'NSW', '2067', -33.7967, 151.1833, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 132, 55, '02 9412 1401', 'dougherty@uniting.org', 'https://uniting.org', 'Premium North Shore aged care. Pool, gardens, and train to city.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Japara Coorabell', 'Japara Healthcare', '15 Byron Street', 'Byron Bay', 'NSW', '2481', -28.6433, 153.6117, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '02 6685 1401', 'coorabell@japara.com.au', 'https://japara.com.au', 'North Coast premium aged care. Pool, gardens, and beach lifestyle.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Whiddon Narrabri', 'Whiddon Group', '125 Maitland Street', 'Narrabri', 'NSW', '2390', -30.3283, 149.7817, 'aged-care', 'aged-care', 245000, 405000, 290, 480, 34, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '02 6792 1401', 'narrabri@whiddon.com.au', 'https://whiddon.com.au', 'Northwest NSW aged care. Gardens and cotton farming region.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Merimbula', 'Allity', '45 Sapphire Coast Drive', 'Merimbula', 'NSW', '2548', -36.8917, 149.9083, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '02 6495 1401', 'merimbula@allity.com.au', 'https://allity.com.au', 'Sapphire Coast aged care. Gardens and close to beaches and lake.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('RSL LifeCare Tamworth', 'RSL LifeCare', '88 Peel Street', 'Tamworth', 'NSW', '2340', -31.0900, 150.9350, 'independent', 'independent', 295000, 495000, 330, 530, 34, '["bowling-green", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 108, 55, '02 6767 1401', 'tamworth@rsllifecare.org.au', 'https://rsllifecare.org.au', 'New England retirement. Bowling green and country music capital.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC (12 villages)
('Regis Aged Care Balwyn', 'Regis Aged Care', '125 Whitehorse Road', 'Balwyn', 'VIC', '3103', -37.8100, 145.0833, 'aged-care', 'aged-care', 585000, 885000, 620, 900, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 126, 55, '03 9817 2401', 'balwyn@regis.com.au', 'https://regis.com.au', 'Premium inner east aged care. Pool, gardens, and village shopping.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Werribee', 'Estia Health', '45 Synnot Street', 'Werribee', 'VIC', '3030', -37.9000, 144.6617, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '03 9741 2401', 'werribee@estiahealth.com.au', 'https://estiahealth.com.au', 'Southwest Melbourne aged care. Gardens and close to Werribee Plaza.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Maidstone', 'Arcare', '88 Hampshire Road', 'Maidstone', 'VIC', '3012', -37.7767, 144.8550, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 124, 55, '03 9318 2401', 'maidstone@arcare.com.au', 'https://arcare.com.au', 'Inner west Melbourne aged care. Pool, cinema, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bupa Aged Care Blackburn', 'Bupa', '15 Whitehorse Road', 'Blackburn', 'VIC', '3130', -37.8167, 145.1500, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '03 9878 2401', 'blackburn@bupa.com.au', 'https://bupa.com.au', 'Eastern suburbs aged care. Gardens, cafe, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Pakenham', 'Bolton Clarke', '125 Main Street', 'Pakenham', 'VIC', '3810', -38.0717, 145.4833, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '03 5940 2401', 'pakenham@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Southeast growth corridor aged care. Gardens and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Bairnsdale', 'Opal Aged Care', '45 Main Street', 'Bairnsdale', 'VIC', '3875', -37.8283, 147.6183, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '03 5152 2401', 'bairnsdale@opalcare.com.au', 'https://opalcare.com.au', 'East Gippsland aged care. Gardens and close to Mitchell River.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Essendon', 'Regis Aged Care', '88 Keilor Road', 'Essendon', 'VIC', '3040', -37.7550, 144.9167, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '03 9379 2401', 'essendon@regis.com.au', 'https://regis.com.au', 'Inner northwest Melbourne aged care. Pool, gardens, and tram access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Seymour', 'Estia Health', '15 Station Street', 'Seymour', 'VIC', '3660', -37.0283, 145.1383, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '03 5792 2401', 'seymour@estiahealth.com.au', 'https://estiahealth.com.au', 'Central Victoria aged care. Gardens and close to railway heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas St Albans', 'Benetas', '125 Main Road East', 'St Albans', 'VIC', '3021', -37.7450, 144.8000, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '03 9366 2401', 'stalbans@benetas.com.au', 'https://benetas.com.au', 'Northwest Melbourne aged care. Gardens and multicultural community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Millward West', 'Japara Healthcare', '45 Thomas Mitchell Drive', 'Wodonga', 'VIC', '3690', -36.1267, 146.8850, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '02 6024 2401', 'millwardwest@japara.com.au', 'https://japara.com.au', 'Border city aged care. Gardens and close to shopping district.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Croydon', 'Mercy Health', '88 Mount Dandenong Road', 'Croydon', 'VIC', '3136', -37.7950, 145.2850, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '03 9723 2401', 'croydon@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Outer east Melbourne aged care. Chapel, gardens, and Dandenong Ranges.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ryman Healthcare Edmund Hillary', 'Ryman Healthcare', '15 Mitcham Road', 'Donvale', 'VIC', '3111', -37.7883, 145.1783, 'aged-care', 'aged-care', 485000, 915000, 520, 890, 28, '["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 242, 55, '03 9842 2401', 'edmundhillary@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Large premium retirement village. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- QLD (12 villages)
('Regis Aged Care Nundah', 'Regis Aged Care', '88 Bage Street', 'Nundah', 'QLD', '4012', -27.4017, 153.0617, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 3266 3401', 'nundah@regis.com.au', 'https://regis.com.au', 'Inner north Brisbane aged care. Gardens, cafe, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Toowoomba West', 'Blue Care', '45 Ruthven Street', 'Toowoomba', 'QLD', '4350', -27.5650, 151.9483, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '07 4632 3401', 'toowoombaw@bluecare.org.au', 'https://bluecare.org.au', 'Garden City aged care. Gardens and close to city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Sanctuary Cove', 'Opal Aged Care', '125 Santa Barbara Road', 'Hope Island', 'QLD', '4212', -27.8717, 153.3583, 'aged-care', 'aged-care', 565000, 865000, 600, 880, 26, '["pool", "gym", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 124, 55, '07 5514 3401', 'sanctuarycove@opalcare.com.au', 'https://opalcare.com.au', 'Premium Gold Coast aged care. Pool, gym, and resort lifestyle.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('TriCare Aged Care Tingalpa', 'TriCare', '15 Wynnum Road', 'Tingalpa', 'QLD', '4173', -27.4650, 153.1217, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '07 3390 3401', 'tingalpa@tricare.com.au', 'https://tricare.com.au', 'Southeast Brisbane aged care. Gardens, cafe, and bus routes.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Southport Central', 'Estia Health', '88 Scarborough Street', 'Southport', 'QLD', '4215', -27.9700, 153.4050, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '07 5532 3401', 'southportcentral@estiahealth.com.au', 'https://estiahealth.com.au', 'Central Gold Coast aged care. Pool, gardens, and close to light rail.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Sandgate', 'Bolton Clarke', '45 Flinders Parade', 'Sandgate', 'QLD', '4017', -27.3200, 153.0683, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '07 3269 3401', 'sandgate@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Bayside Brisbane aged care. Gardens, cafe, and waterfront access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Rockhampton', 'Adventist Aged Care', '125 Agnes Street', 'Rockhampton', 'QLD', '4700', -23.3800, 150.5150, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["pool", "library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '07 4927 3401', 'rocky@adventistcare.org.au', 'https://adventistcare.org.au', 'Central Queensland aged care. Pool, chapel, and tropical setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ozcare Dalby', 'Ozcare', '15 Nicholson Street', 'Dalby', 'QLD', '4405', -27.1833, 151.2667, 'aged-care', 'aged-care', 245000, 405000, 290, 480, 34, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 68, 55, '07 4662 3401', 'dalby@ozcare.org.au', 'https://ozcare.org.au', 'Darling Downs aged care. Chapel, gardens, and agricultural town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Brookfield', 'Carinity', '88 Brookfield Road', 'Kenmore Hills', 'QLD', '4069', -27.5133, 152.9300, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '07 3374 3401', 'brookfield@carinity.org.au', 'https://carinity.org.au', 'Western Brisbane aged care. Pool, chapel, gardens, and leafy setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Mudgeeraba', 'Regis Aged Care', '45 Mudgeeraba Road', 'Mudgeeraba', 'QLD', '4213', -28.0833, 153.3683, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '07 5530 3401', 'mudgeeraba@regis.com.au', 'https://regis.com.au', 'Gold Coast hinterland aged care. Pool, gardens, and mountain views.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Airlie Beach', 'Allity', '125 Shute Harbour Road', 'Airlie Beach', 'QLD', '4802', -20.2683, 148.7167, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '07 4946 3401', 'airliebeach@allity.com.au', 'https://allity.com.au', 'Whitsundays aged care. Pool, gardens, and tropical paradise.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Paradise Point', 'Southern Cross Care QLD', '15 Seabreeze Drive', 'Paradise Point', 'QLD', '4216', -27.8817, 153.3867, 'aged-care', 'aged-care', 525000, 785000, 560, 820, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '07 5577 3401', 'paradisepoint@scrosscc.com.au', 'https://scrosscc.com.au', 'Gold Coast waterfront aged care. Pool, gardens, and marina lifestyle.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- SA (5 villages)
('Regis Aged Care Prospect', 'Regis Aged Care', '88 Prospect Road', 'Prospect', 'SA', '5082', -34.8850, 138.5950, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '08 8342 4401', 'prospect@regis.com.au', 'https://regis.com.au', 'Inner north Adelaide aged care. Gardens, cafe, and close to city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Glenelg North', 'Estia Health', '15 Broadway', 'Glenelg North', 'SA', '5045', -34.9817, 138.5117, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '08 8294 4401', 'glenelgnorth@estiahealth.com.au', 'https://estiahealth.com.au', 'Beachside Adelaide aged care. Gardens, cafe, and tram to beach.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Port Lincoln', 'ACH Group', '125 Liverpool Street', 'Port Lincoln', 'SA', '5606', -34.7267, 135.8600, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '08 8682 4401', 'portlincoln@ach.org.au', 'https://ach.org.au', 'Eyre Peninsula aged care. Gardens and close to marina and seafood.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Berri', 'Southern Cross Care SA', '45 Riverview Drive', 'Berri', 'SA', '5343', -34.4767, 140.5950, 'aged-care', 'aged-care', 235000, 385000, 280, 460, 36, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 64, 55, '08 8582 4401', 'berri@scsa.org.au', 'https://scsa.org.au', 'Riverland aged care. Gardens and close to Murray River.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Brighton', 'Japara Healthcare', '45 Brighton Road', 'Brighton', 'SA', '5048', -35.0200, 138.5233, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '08 8296 4401', 'brightonsa@japara.com.au', 'https://japara.com.au', 'Beachside Adelaide aged care. Gardens, cafe, and tram to beach.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- WA (4 villages)
('Regis Aged Care Mount Lawley', 'Regis Aged Care', '125 Beaufort Street', 'Mount Lawley', 'WA', '6050', -31.9317, 115.8717, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '08 9272 5401', 'mtlawley@regis.com.au', 'https://regis.com.au', 'Premium inner Perth aged care. Pool, gardens, and Beaufort Street cafes.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bethanie Esprit Carine', 'Bethanie Group', '45 Carine Glades', 'Carine', 'WA', '6020', -31.8517, 115.7900, 'independent', 'independent', 425000, 685000, 440, 680, 28, '["pool", "gym", "library", "common-room", "bbq-area", "workshop"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 136, 55, '08 9447 5401', 'carine@bethanie.com.au', 'https://bethanie.com.au', 'Northern Perth retirement. Pool, gym, and close to Carine shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Armadale', 'Amana Living', '88 South Western Highway', 'Armadale', 'WA', '6112', -32.1500, 116.0167, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '08 9497 5401', 'armadale@amana.com.au', 'https://amana.com.au', 'Southeast Perth aged care. Gardens and close to shopping district.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Broome', 'Opal Aged Care', '15 Robinson Street', 'Broome', 'WA', '6725', -17.9617, 122.2350, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '08 9192 5401', 'broome@opalcare.com.au', 'https://opalcare.com.au', 'Tropical north WA aged care. Pool, gardens, and pearling town heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Estia Health Kingston', 'Estia Health', '125 Channel Highway', 'Kingston', 'TAS', '7050', -42.9783, 147.3067, 'aged-care', 'aged-care', 335000, 535000, 370, 570, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 90, 55, '03 6229 8401', 'kingston@estiahealth.com.au', 'https://estiahealth.com.au', 'South Hobart aged care. Gardens and close to Kingston shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Aged Care Gungahlin', 'Goodwin', '45 Hinder Street', 'Gungahlin', 'ACT', '2912', -35.1867, 149.1317, 'aged-care', 'aged-care', 485000, 735000, 520, 780, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '02 6242 9401', 'gungahlin@goodwin.org.au', 'https://goodwin.org.au', 'North Canberra aged care. Gardens, cafe, and close to town center.', 'approved', 'seed_data', true, false, NOW(), NOW());
