-- Batch 16: 50 Additional Retirement Villages (CORRECTED JSON)
-- Brings total to 705 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW (15 villages)
('Aveo Freedom Cherrybrook', 'Aveo Group', '45 Shepherds Drive', 'Cherrybrook', 'NSW', '2126', -33.7217, 151.0467, 'independent', 'independent', 625000, 985000, 620, 940, 26, '["pool", "gym", "library", "common-room", "cinema", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 148, 55, '02 9875 2101', 'cherrybrook@aveo.com.au', 'https://aveo.com.au', 'Northwest Sydney retirement. Pool, gym, cinema, Hills District lifestyle.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Laurieton', 'Stockland', '88 Bold Street', 'Laurieton', 'NSW', '2443', -31.6467, 152.8000, 'independent', 'independent', 365000, 585000, 360, 580, 32, '["pool", "bowling-green", "library", "common-room", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 116, 55, '02 6559 2101', 'laurieton@stockland.com.au', 'https://stockland.com', 'Mid North Coast retirement. Pool, bowling green, and Camden Haven.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ryman Healthcare Newmarket', 'Ryman Healthcare', '125 Station Street', 'Newmarket', 'NSW', '2088', -33.8717, 151.1917, 'independent', 'aged-care', 685000, 1185000, 680, 1120, 24, '["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser", "cafe", "art-studio"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 256, 60, '02 9476 2101', 'newmarket@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Premium North Shore village. Pool, gym, bowling green, cinema, restaurant, art studio.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Anglicare Retirement Living Armidale', 'Anglicare NSW South', '15 Rusden Street', 'Armidale', 'NSW', '2350', -30.5033, 151.6650, 'independent', 'independent', 305000, 505000, 330, 530, 32, '["library", "common-room", "chapel", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 88, 55, '02 6772 2101', 'armidale@anglicare.com.au', 'https://anglicare.com.au', 'New England retirement. Chapel, gardens, and cool climate.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('BaptistCare Retirement Living Narellan', 'BaptistCare NSW & ACT', '88 Somerset Avenue', 'Narellan', 'NSW', '2567', -34.0450, 150.7383, 'independent', 'independent', 465000, 745000, 460, 740, 28, '["pool", "gym", "library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 134, 55, '02 4647 2101', 'narellan@baptistcare.org.au', 'https://baptistcare.org.au', 'Southwest Sydney retirement. Pool, gym, chapel, growth corridor.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Uniting Retirement Living Cessnock', 'Uniting NSW & ACT', '125 Vincent Street', 'Cessnock', 'NSW', '2325', -32.8350, 151.3567, 'independent', 'independent', 325000, 525000, 340, 540, 32, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 96, 55, '02 4990 2101', 'cessnock@uniting.org', 'https://uniting.org', 'Hunter Valley retirement. Gardens and wine country lifestyle.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('IRT Retirement Villages Kiama', 'IRT Group', '45 Manning Street', 'Kiama', 'NSW', '2533', -34.6717, 150.8533, 'independent', 'independent', 525000, 845000, 520, 840, 28, '["pool", "library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 128, 55, '02 4232 2101', 'kiama@irt.org.au', 'https://irt.org.au', 'South Coast retirement. Pool, gardens, and iconic blowhole.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('RSL LifeCare Retirement Villages Raymond Terrace', 'RSL LifeCare', '88 William Street', 'Raymond Terrace', 'NSW', '2324', -32.7617, 151.7450, 'independent', 'independent', 345000, 565000, 360, 560, 32, '["bowling-green", "library", "common-room", "bbq-area", "workshop"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 104, 55, '02 4987 2101', 'raymondterrace@rsllifecare.org.au', 'https://rsllifecare.org.au', 'Hunter region retirement. Bowling green, workshop, and river access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Randwick', 'Regis Aged Care', '125 Belmore Road', 'Randwick', 'NSW', '2031', -33.9167, 151.2433, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 126, 55, '02 9398 2101', 'randwick@regis.com.au', 'https://regis.com.au', 'Premium Eastern Suburbs aged care. Pool, cafe, near beaches and UNSW.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Baulkham Hills', 'Estia Health', '15 Seven Hills Road', 'Baulkham Hills', 'NSW', '2153', -33.7617, 150.9900, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '02 9639 2101', 'baulkhamhills@estiahealth.com.au', 'https://estiahealth.com.au', 'Northwest Sydney aged care. Gardens, cafe, and Hills shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Aged Care Peakhurst', 'Arcare', '88 Belmore Road', 'Peakhurst', 'NSW', '2210', -33.9583, 151.0550, 'aged-care', 'aged-care', 525000, 795000, 560, 840, 26, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 124, 55, '02 9533 2101', 'peakhurst@arcare.com.au', 'https://arcare.com.au', 'St George aged care. Pool, gym, cinema, and Georges River nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bupa Aged Care Castle Hill', 'Bupa', '125 Windsor Road', 'Castle Hill', 'NSW', '2154', -33.7333, 151.0017, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 116, 55, '02 9899 2101', 'castlehill@bupa.com.au', 'https://bupa.com.au', 'Northwest Sydney aged care. Gardens, cafe, and shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Nowra', 'Bolton Clarke', '15 Kinghorne Street', 'Nowra', 'NSW', '2541', -34.8817, 150.5983, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 90, 55, '02 4421 2101', 'nowra@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Shoalhaven aged care. Gardens and Shoalhaven River access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Healthcare Grafton', 'Japara Healthcare', '88 Prince Street', 'Grafton', 'NSW', '2460', -29.6917, 152.9333, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '02 6642 2101', 'grafton@japara.com.au', 'https://japara.com.au', 'Clarence Valley aged care. Gardens and jacaranda city charm.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Goulburn', 'Southern Cross Care NSW & ACT', '125 Sloane Street', 'Goulburn', 'NSW', '2580', -34.7533, 149.7183, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '02 4821 2101', 'goulburn@scrosscc.com.au', 'https://scrosscc.com.au', 'Southern Tablelands aged care. Chapel, gardens, and heritage city.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC (12 villages)
('Aveo Retirement Living Craigieburn', 'Aveo Group', '88 Hume Highway', 'Craigieburn', 'VIC', '3064', -37.5983, 144.9433, 'independent', 'independent', 385000, 625000, 380, 620, 30, '["pool", "gym", "library", "common-room", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 138, 55, '03 9333 3101', 'craigieburn@aveo.com.au', 'https://aveo.com.au', 'North growth corridor retirement. Pool, gym, and modern community.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Stockland Retirement Living Traralgon', 'Stockland', '125 Franklin Street', 'Traralgon', 'VIC', '3844', -38.1950, 146.5417, 'independent', 'independent', 305000, 505000, 330, 530, 32, '["pool", "bowling-green", "library", "common-room", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 112, 55, '03 5174 3101', 'traralgon@stockland.com.au', 'https://stockland.com', 'Gippsland retirement. Pool, bowling green, and regional center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Lendlease Retirement Living Plenty Valley', 'Lendlease', '45 Plenty Road', 'Mill Park', 'VIC', '3082', -37.6650, 145.0650, 'independent', 'independent', 465000, 745000, 460, 740, 28, '["pool", "gym", "library", "common-room", "cinema", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 146, 55, '03 9407 3101', 'plentyvalley@lendlease.com', 'https://lendlease.com', 'Northeast retirement. Pool, gym, cinema, and Westfield nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ryman Healthcare Karori', 'Ryman Healthcare', '88 Mahoneys Road', 'Burwood East', 'VIC', '3151', -37.8650, 145.1617, 'aged-care', 'aged-care', 505000, 945000, 540, 920, 28, '["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 242, 55, '03 9802 3101', 'karori@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Large premium village. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Regis Aged Care Wangaratta', 'Regis Aged Care', '125 Ovens Street', 'Wangaratta', 'VIC', '3677', -36.3567, 146.3183, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '03 5721 3101', 'wangaratta@regis.com.au', 'https://regis.com.au', 'Northeast Victoria aged care. Gardens and wine region hub.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Horsham', 'Estia Health', '15 Firebrace Street', 'Horsham', 'VIC', '3400', -36.7117, 142.1983, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '03 5382 3101', 'horsham@estiahealth.com.au', 'https://estiahealth.com.au', 'Wimmera aged care. Gardens and regional grain capital.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bupa Aged Care Ferntree Gully', 'Bupa', '88 Burwood Highway', 'Ferntree Gully', 'VIC', '3156', -37.8833, 145.3000, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '03 9758 3101', 'fernttreegully@bupa.com.au', 'https://bupa.com.au', 'Foothills aged care. Gardens and Dandenong Ranges nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Frankston', 'Bolton Clarke', '125 Cranbourne Road', 'Frankston', 'VIC', '3199', -38.1450, 145.1250, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '03 9783 3101', 'frankston@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Peninsula aged care. Gardens, cafe, and beach nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Aged Care Reservoir', 'Arcare', '15 Spring Street', 'Reservoir', 'VIC', '3073', -37.7167, 145.0067, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '03 9460 3101', 'reservoir@arcare.com.au', 'https://arcare.com.au', 'North Melbourne aged care. Pool, gym, cinema, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas Aged Care Keilor', 'Benetas', '88 Buckley Street', 'Essendon', 'VIC', '3040', -37.7550, 144.9183, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '03 9379 3101', 'keilor@benetas.com.au', 'https://benetas.com.au', 'Northwest Melbourne aged care. Gardens, cafe, and airport access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Bendigo', 'Opal Aged Care', '125 Hargreaves Street', 'Bendigo', 'VIC', '3550', -36.7583, 144.2800, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '03 5443 3101', 'bendigo@opalcare.com.au', 'https://opalcare.com.au', 'Central Victoria aged care. Pool, gardens, and gold rush heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Healthcare Traralgon', 'Japara Healthcare', '45 Kay Street', 'Traralgon', 'VIC', '3844', -38.1883, 146.5383, 'aged-care', 'aged-care', 315000, 515000, 350, 550, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '03 5176 3101', 'traralgon@japara.com.au', 'https://japara.com.au', 'Latrobe Valley aged care. Gardens and Gippsland city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- QLD (12 villages)
('Aveo Retirement Living Kawana Waters', 'Aveo Group', '88 Nicklin Way', 'Kawana Waters', 'QLD', '4575', -26.7233, 153.1300, 'independent', 'independent', 485000, 775000, 480, 760, 28, '["pool", "gym", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 144, 55, '07 5444 5101', 'kawana@aveo.com.au', 'https://aveo.com.au', 'Sunshine Coast retirement. Pool, gym, and waterfront lifestyle.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Stockland Retirement Living Springfield', 'Stockland', '125 Springfield Parkway', 'Springfield', 'QLD', '4300', -27.6617, 152.9167, 'independent', 'independent', 405000, 645000, 400, 640, 30, '["pool", "gym", "bowling-green", "library", "common-room", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 152, 55, '07 3470 5101', 'springfield@stockland.com.au', 'https://stockland.com', 'Ipswich growth area retirement. Pool, gym, bowling green, modern city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Lendlease Retirement Living Redlands', 'Lendlease', '45 Cleveland-Redland Bay Road', 'Thornlands', 'QLD', '4164', -27.5400, 153.2617, 'independent', 'independent', 485000, 775000, 480, 760, 28, '["pool", "gym", "library", "common-room", "cinema", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 146, 55, '07 3488 5101', 'redlands@lendlease.com', 'https://lendlease.com', 'Bayside Brisbane retirement. Pool, gym, cinema, and island access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Ipswich', 'Regis Aged Care', '88 Brisbane Street', 'Ipswich', 'QLD', '4305', -27.6167, 152.7600, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '07 3281 5101', 'ipswich@regis.com.au', 'https://regis.com.au', 'West Brisbane aged care. Gardens and heritage city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Redcliffe', 'Blue Care', '125 Anzac Avenue', 'Redcliffe', 'QLD', '4020', -27.2283, 153.1100, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '07 3284 5101', 'redcliffe@bluecare.org.au', 'https://bluecare.org.au', 'Moreton Bay aged care. Gardens and peninsula beachside.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Mount Gravatt', 'Bolton Clarke', '15 Logan Road', 'Mount Gravatt', 'QLD', '4122', -27.5350, 153.0817, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 3349 5101', 'mountgravatt@boltonclarke.com.au', 'https://boltonclarke.com.au', 'South Brisbane aged care. Gardens, cafe, and shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('TriCare Aged Care Redland Bay', 'TriCare', '88 Weinam Street', 'Redland Bay', 'QLD', '4165', -27.6117, 153.3017, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 98, 55, '07 3829 5101', 'redlandbay@tricare.com.au', 'https://tricare.com.au', 'Bayside aged care. Pool, gardens, and Moreton Bay islands.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Noosa', 'Southern Cross Care QLD', '125 Sunshine Beach Road', 'Noosa Heads', 'QLD', '4567', -26.3917, 153.0933, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '07 5474 5101', 'noosa@scrosscc.com.au', 'https://scrosscc.com.au', 'Premium Sunshine Coast aged care. Pool, cafe, and Hastings Street.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Nambour', 'Estia Health', '45 Currie Street', 'Nambour', 'QLD', '4560', -26.6267, 152.9617, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '07 5441 5101', 'nambour@estiahealth.com.au', 'https://estiahealth.com.au', 'Sunshine Coast hinterland aged care. Gardens and Big Pineapple.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Caloundra', 'Opal Aged Care', '88 Omrah Avenue', 'Caloundra', 'QLD', '4551', -26.8000, 153.1333, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '07 5491 5101', 'caloundra@opalcare.com.au', 'https://opalcare.com.au', 'Sunshine Coast aged care. Pool, gardens, and multiple beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Wishart', 'Carinity', '125 Warrigal Road', 'Eight Mile Plains', 'QLD', '4113', -27.5800, 153.1000, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '07 3341 5101', 'wishart@carinity.org.au', 'https://carinity.org.au', 'South Brisbane aged care. Chapel, gardens, and Gateway shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Adventist Aged Care Warwick', 'Adventist Aged Care', '15 Palmerin Street', 'Warwick', 'QLD', '4370', -28.2167, 152.0333, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '07 4661 5101', 'warwick@adventistcare.org.au', 'https://adventistcare.org.au', 'Darling Downs aged care. Chapel, gardens, and rodeo capital.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- SA (5 villages)
('Resthaven Aged Care Paradise', 'Resthaven', '125 Darley Road', 'Paradise', 'SA', '5075', -34.8717, 138.6717, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '08 8337 6001', 'paradise@resthaven.asn.au', 'https://resthaven.asn.au', 'Northeast Adelaide aged care. Gardens, cafe, and Tea Tree shopping.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Westbourne Park', 'ACH Group', '45 Goodwood Road', 'Westbourne Park', 'SA', '5041', -34.9450, 138.5933, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '08 8272 6001', 'westbournepark@ach.org.au', 'https://ach.org.au', 'Inner south Adelaide aged care. Gardens, cafe, and tram access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Whyalla', 'Estia Health', '88 Nicolson Avenue', 'Whyalla', 'SA', '5600', -33.0333, 137.5667, 'aged-care', 'aged-care', 235000, 395000, 280, 460, 36, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 70, 55, '08 8645 6001', 'whyalla@estiahealth.com.au', 'https://estiahealth.com.au', 'Upper Spencer Gulf aged care. Gardens and iron city heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Salisbury', 'Regis Aged Care', '125 John Street', 'Salisbury', 'SA', '5108', -34.7617, 138.6417, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '08 8250 6001', 'salisbury@regis.com.au', 'https://regis.com.au', 'Northern Adelaide aged care. Gardens and shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Port Lincoln', 'Southern Cross Care SA', '15 Liverpool Street', 'Port Lincoln', 'SA', '5606', -34.7267, 135.8567, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '08 8682 6001', 'portlincoln@scsa.org.au', 'https://scsa.org.au', 'Eyre Peninsula aged care. Pool, gardens, and seafood capital.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- WA (4 villages)
('Bethanie Retirement Living Kwinana', 'Bethanie Group', '88 Gilmore Avenue', 'Kwinana', 'WA', '6167', -32.2350, 115.7750, 'independent', 'independent', 325000, 525000, 340, 540, 32, '["pool", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 106, 55, '08 9419 7001', 'kwinana@bethanie.com.au', 'https://bethanie.com.au', 'South Perth retirement. Pool, gardens, and beach access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Midland', 'Regis Aged Care', '125 Great Eastern Highway', 'Midland', 'WA', '6056', -31.8883, 116.0117, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '08 9274 7001', 'midland@regis.com.au', 'https://regis.com.au', 'East Perth aged care. Gardens and train hub access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Rockingham', 'Amana Living', '45 Kent Street', 'Rockingham', 'WA', '6168', -32.2783, 115.7300, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '08 9592 7001', 'rockingham@amana.com.au', 'https://amana.com.au', 'Coastal aged care. Pool, gardens, and safe swimming beach.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Kalgoorlie', 'Opal Aged Care', '88 Hannan Street', 'Kalgoorlie', 'WA', '6430', -30.7483, 121.4683, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '08 9021 7001', 'kalgoorlie@opalcare.com.au', 'https://opalcare.com.au', 'Goldfields aged care. Pool, gardens, and mining heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Estia Health Burnie', 'Estia Health', '125 Mount Street', 'Burnie', 'TAS', '7320', -41.0517, 145.9033, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '03 6431 8101', 'burnie@estiahealth.com.au', 'https://estiahealth.com.au', 'Northwest Tasmania aged care. Gardens and coastal city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Aged Care Monash', 'Goodwin', '45 Bugden Avenue', 'Tuggeranong', 'ACT', '2900', -35.4133, 149.0917, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '02 6293 7101', 'monash@goodwin.org.au', 'https://goodwin.org.au', 'South Canberra aged care. Gardens, cafe, and Hyperdome shopping.', 'approved', 'seed_data', true, false, NOW(), NOW());
