-- Batch 13: 50 Additional Retirement Villages
-- Brings total to 555 villages

INSERT INTO retirement_villages (
  name, operator, location, suburb, state, postcode, latitude, longitude,
  village_type, care_level, entry_price_min, entry_price_max,
  monthly_fees_min, monthly_fees_max, dmf_percentage,
  amenities, care_services, bedrooms, pet_friendly, total_units, age_restriction,
  contact_phone, contact_email, website, description,
  status, source, verified, featured, submitted_at, approved_at
) VALUES

-- NSW (15 villages)
('Aveo Freedom Narrabeen', 'Aveo Group', '88 Ocean Street', 'Narrabeen', 'NSW', '2101', -33.7133, 151.2967, 'independent', 'independent', 625000, 985000, 620, 940, 26, '["pool", "gym", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 132, 55, '02 9913 1601', 'narrabeen@aveo.com.au', 'https://aveo.com.au', 'Premium Northern Beaches retirement. Pool, gym, and beach access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Stockland Retirement Living Maitland', 'Stockland', '45 High Street', 'Maitland', 'NSW', '2320', -32.7317, 151.5550, 'independent', 'independent', 365000, 585000, 380, 580, 32, '["pool", "library", "common-room", "bbq-area", "workshop"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 124, 55, '02 4933 1601', 'maitland@stockland.com.au', 'https://stockland.com', 'Hunter Valley retirement. Pool and heritage city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Cronulla', 'Regis Aged Care', '125 Kingsway', 'Cronulla', 'NSW', '2230', -34.0567, 151.1517, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 126, 55, '02 9523 1601', 'cronulla@regis.com.au', 'https://regis.com.au', 'Premium beachside aged care. Pool, gardens, and beach lifestyle.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Opal Aged Care Penrith', 'Opal Aged Care', '15 High Street', 'Penrith', 'NSW', '2750', -33.7500, 150.6950, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 104, 55, '02 4721 1601', 'penrith@opalcare.com.au', 'https://opalcare.com.au', 'Western Sydney aged care. Gardens and close to Panthers.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Wagga Wagga', 'Estia Health', '88 Tarcutta Street', 'Wagga Wagga', 'NSW', '2650', -35.1167, 147.3683, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 86, 55, '02 6921 1601', 'waggawagga@estiahealth.com.au', 'https://estiahealth.com.au', 'Riverina aged care. Gardens and regional city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Harbord', 'Arcare', '45 Moore Road', 'Freshwater', 'NSW', '2096', -33.7800, 151.2850, 'aged-care', 'aged-care', 645000, 1005000, 680, 1000, 24, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 134, 55, '02 9938 1601', 'harbord@arcare.com.au', 'https://arcare.com.au', 'Premium beachside aged care. Pool, gym, cinema, and surf beaches.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('BaptistCare Cooinda Village', 'BaptistCare NSW & ACT', '88 Hammers Road', 'Northmead', 'NSW', '2152', -33.7833, 150.9983, 'aged-care', 'aged-care', 465000, 685000, 500, 720, 28, '["pool", "library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '02 9683 1601', 'cooinda@baptistcare.org.au', 'https://baptistcare.org.au', 'Western Sydney aged care. Pool, chapel, and gardens.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Blue Care Bathurst', 'Blue Care', '15 Howick Street', 'Bathurst', 'NSW', '2795', -33.4200, 149.5783, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '02 6331 1601', 'bathurst@bluecare.org.au', 'https://bluecare.org.au', 'Central Tablelands aged care. Gardens and heritage city.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Catholic Healthcare Eastwood', 'Catholic Healthcare', '125 Blaxland Road', 'Eastwood', 'NSW', '2122', -33.7917, 151.0817, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["library", "common-room", "chapel", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '02 9858 1601', 'eastwood@catholichealthcare.com.au', 'https://catholichealthcare.com.au', 'Northwest Sydney aged care. Chapel, cafe, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('HammondCare Greenwich Hospital', 'HammondCare', '45 River Road', 'Greenwich', 'NSW', '2065', -33.8317, 151.1833, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '02 9437 1601', 'greenwich@hammond.com.au', 'https://hammond.com.au', 'Premium Lower North Shore aged care. Pool, gardens, harbour views.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Uniting Lindfield Gardens', 'Uniting NSW & ACT', '88 Tryon Road', 'Lindfield', 'NSW', '2070', -33.7783, 151.1633, 'aged-care', 'aged-care', 605000, 905000, 640, 920, 24, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 130, 55, '02 9416 1601', 'lindfieldgardens@uniting.org', 'https://uniting.org', 'Premium Upper North Shore aged care. Pool, gardens, train access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Japara Scotts Head', 'Japara Healthcare', '15 Pacific Street', 'Scotts Head', 'NSW', '2447', -30.7533, 153.0417, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '02 6569 1601', 'scottshead@japara.com.au', 'https://japara.com.au', 'Mid North Coast beachside aged care. Pool, gardens, and surf beach.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Whiddon Inverell', 'Whiddon Group', '125 Byron Street', 'Inverell', 'NSW', '2360', -29.7767, 151.1117, 'aged-care', 'aged-care', 255000, 425000, 300, 490, 34, '["library", "common-room", "garden", "bbq-area"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '02 6721 1601', 'inverell@whiddon.com.au', 'https://whiddon.com.au', 'New England aged care. Gardens and sapphire mining heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Moruya', 'Allity', '45 Vulcan Street', 'Moruya', 'NSW', '2537', -35.9100, 150.0850, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '02 4474 1601', 'moruya@allity.com.au', 'https://allity.com.au', 'South Coast aged care. Gardens and close to river and beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('RSL LifeCare Gwandalan', 'RSL LifeCare', '88 Gwynneville Avenue', 'Gwandalan', 'NSW', '2259', -33.1400, 151.5817, 'independent', 'independent', 345000, 565000, 360, 560, 32, '["bowling-green", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 112, 55, '02 4976 1601', 'gwandalan@rsllifecare.org.au', 'https://rsllifecare.org.au', 'Central Coast lakeside retirement. Bowling green and water access.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- VIC (12 villages)
('Regis Aged Care Brighton', 'Regis Aged Care', '125 Bay Street', 'Brighton', 'VIC', '3186', -37.9267, 145.0000, 'aged-care', 'aged-care', 625000, 975000, 660, 980, 24, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 132, 55, '03 9596 2601', 'brighton@regis.com.au', 'https://regis.com.au', 'Premium bayside aged care. Pool, gardens, and beach access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Sale', 'Estia Health', '45 Raymond Street', 'Sale', 'VIC', '3850', -38.1067, 147.0683, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '03 5144 2601', 'sale@estiahealth.com.au', 'https://estiahealth.com.au', 'East Gippsland aged care. Gardens and regional city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Arcare Templestowe', 'Arcare', '88 Church Road', 'Templestowe', 'VIC', '3106', -37.7617, 145.1450, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '["pool", "gym", "library", "common-room", "cinema", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 128, 55, '03 9846 2601', 'templestowe@arcare.com.au', 'https://arcare.com.au', 'Premium eastern suburbs aged care. Pool, gym, cinema, leafy setting.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Bupa Aged Care Cheltenham', 'Bupa', '15 Charman Road', 'Cheltenham', 'VIC', '3192', -37.9633, 145.0550, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '03 9583 2601', 'cheltenham@bupa.com.au', 'https://bupa.com.au', 'Bayside aged care. Gardens, cafe, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Sunbury Gardens', 'Bolton Clarke', '125 Evans Street', 'Sunbury', 'VIC', '3429', -37.5767, 144.7283, 'aged-care', 'aged-care', 385000, 585000, 420, 620, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '03 9740 2601', 'sunburygardens@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Northwest growth corridor aged care. Gardens and historic town.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Swan Hill', 'Opal Aged Care', '45 Campbell Street', 'Swan Hill', 'VIC', '3585', -35.3383, 143.5550, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34, '["pool", "library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 76, 55, '03 5032 2601', 'swanhill@opalcare.com.au', 'https://opalcare.com.au', 'Mallee region aged care. Pool, gardens, and Murray River setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Ivanhoe', 'Regis Aged Care', '88 Upper Heidelberg Road', 'Ivanhoe', 'VIC', '3079', -37.7667, 145.0450, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 120, 55, '03 9497 2601', 'ivanhoe@regis.com.au', 'https://regis.com.au', 'Premium northeast aged care. Pool, gardens, and train access.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Estia Health Echuca', 'Estia Health', '15 Ogilvie Avenue', 'Echuca', 'VIC', '3564', -36.1383, 144.7550, 'aged-care', 'aged-care', 295000, 475000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 84, 55, '03 5482 2601', 'echuca@estiahealth.com.au', 'https://estiahealth.com.au', 'Murray River aged care. Gardens and paddle steamer heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Benetas Greensborough', 'Benetas', '125 Main Street', 'Greensborough', 'VIC', '3088', -37.7033, 145.1033, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '03 9435 2601', 'greensborough@benetas.com.au', 'https://benetas.com.au', 'Northeast Melbourne aged care. Gardens and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Millward', 'Japara Healthcare', '45 York Street', 'Ballarat', 'VIC', '3350', -37.5617, 143.8583, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 92, 55, '03 5331 2601', 'millward@japara.com.au', 'https://japara.com.au', 'Central Highlands aged care. Gardens and gold rush heritage.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Mercy Health Colac', 'Mercy Health', '88 Queen Street', 'Colac', 'VIC', '3250', -38.3400, 143.5850, 'aged-care', 'aged-care', 275000, 455000, 320, 520, 32, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '03 5231 2601', 'colac@mercyhealth.com.au', 'https://mercyhealth.com.au', 'Western district aged care. Chapel, gardens, and lake setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ryman Healthcare Weary Dunlop', 'Ryman Healthcare', '15 Boronia Road', 'Wheelers Hill', 'VIC', '3150', -37.9100, 145.1850, 'aged-care', 'aged-care', 505000, 945000, 540, 920, 28, '["pool", "gym", "bowling-green", "cinema", "library", "common-room", "restaurant", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care", "dementia-care"]'::jsonb, ARRAY['1-bed', '2-bed', '3-bed'], true, 244, 55, '03 9562 2601', 'wearydunlop@rymanhealthcare.com', 'https://rymanhealthcare.com', 'Large premium retirement village. Pool, gym, bowling green, cinema, restaurant.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- QLD (12 villages)
('Regis Aged Care New Farm', 'Regis Aged Care', '125 Brunswick Street', 'New Farm', 'QLD', '4005', -27.4650, 153.0483, 'aged-care', 'aged-care', 545000, 825000, 580, 860, 26, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 118, 55, '07 3358 3601', 'newfarm@regis.com.au', 'https://regis.com.au', 'Premium inner Brisbane aged care. Pool, gardens, and river lifestyle.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Blue Care Cairns', 'Blue Care', '45 McLeod Street', 'Cairns', 'QLD', '4870', -16.9200, 145.7717, 'aged-care', 'aged-care', 365000, 565000, 400, 600, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 96, 55, '07 4031 3601', 'cairns@bluecare.org.au', 'https://bluecare.org.au', 'Tropical north aged care. Pool, gardens, and reef gateway.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Tweed Heads', 'Opal Aged Care', '88 Wharf Street', 'Tweed Heads', 'QLD', '4485', -28.1783, 153.5450, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 114, 55, '07 5536 3601', 'tweedheads@opalcare.com.au', 'https://opalcare.com.au', 'Border coastal aged care. Pool, gardens, and river access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('TriCare Aged Care Cleveland', 'TriCare', '15 Shore Street', 'Cleveland', 'QLD', '4163', -27.5283, 153.2650, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '07 3286 3601', 'cleveland@tricare.com.au', 'https://tricare.com.au', 'Bayside Brisbane aged care. Gardens and ferry to islands.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Ashmore', 'Estia Health', '125 Currumburra Road', 'Ashmore', 'QLD', '4214', -27.9950, 153.3833, 'aged-care', 'aged-care', 465000, 695000, 500, 740, 28, '["pool", "library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 110, 55, '07 5527 3601', 'ashmore@estiahealth.com.au', 'https://estiahealth.com.au', 'Central Gold Coast aged care. Pool, gardens, and shopping nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bolton Clarke Hamilton', 'Bolton Clarke', '45 Racecourse Road', 'Hamilton', 'QLD', '4007', -27.4400, 153.0650, 'aged-care', 'aged-care', 505000, 755000, 540, 800, 26, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 112, 55, '07 3868 3601', 'hamilton@boltonclarke.com.au', 'https://boltonclarke.com.au', 'Inner Brisbane aged care. Gardens, cafe, and Portside dining.', 'approved', 'seed_data', true, true, NOW(), NOW()),
('Adventist Aged Care Atherton', 'Adventist Aged Care', '88 Jack Street', 'Atherton', 'QLD', '4883', -17.2650, 145.4783, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 72, 55, '07 4091 3601', 'atherton@adventistcare.org.au', 'https://adventistcare.org.au', 'Tablelands aged care. Chapel, gardens, and cool climate.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Ozcare Stanthorpe', 'Ozcare', '15 High Street', 'Stanthorpe', 'QLD', '4380', -28.6550, 151.9317, 'aged-care', 'aged-care', 255000, 425000, 300, 490, 34, '["library", "common-room", "chapel", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 66, 55, '07 4681 3601', 'stanthorpe@ozcare.org.au', 'https://ozcare.org.au', 'Granite Belt aged care. Chapel, gardens, and wine region.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Carinity Aged Care Shalom', 'Carinity', '125 Prospect Road', 'Gaythorne', 'QLD', '4051', -27.4167, 152.9817, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "chapel", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '07 3354 3601', 'shalom@carinity.org.au', 'https://carinity.org.au', 'Northwest Brisbane aged care. Chapel, gardens, and train access.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Regis Aged Care Coomera', 'Regis Aged Care', '45 Foxwell Road', 'Coomera', 'QLD', '4209', -27.8650, 153.3217, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '07 5580 3601', 'coomera@regis.com.au', 'https://regis.com.au', 'North Gold Coast aged care. Pool, gardens, and growth area.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Allity Aged Care Maryborough', 'Allity', '88 Kent Street', 'Maryborough', 'QLD', '4650', -25.5383, 152.7017, 'aged-care', 'aged-care', 285000, 465000, 330, 530, 32, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 78, 55, '07 4123 3601', 'maryborough@allity.com.au', 'https://allity.com.au', 'Fraser Coast aged care. Gardens and heritage city center.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Ormiston', 'Southern Cross Care QLD', '125 Wellington Street', 'Ormiston', 'QLD', '4160', -27.5200, 153.2550, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '07 3390 3601', 'ormiston@scrosscc.com.au', 'https://scrosscc.com.au', 'Bayside Brisbane aged care. Pool, gardens, and waterfront access.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- SA (5 villages)
('Regis Aged Care Oaklands Park', 'Regis Aged Care', '88 Morphett Road', 'Oaklands Park', 'SA', '5046', -35.0150, 138.5467, 'aged-care', 'aged-care', 425000, 625000, 460, 660, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 102, 55, '08 8277 4601', 'oaklandspark@regis.com.au', 'https://regis.com.au', 'Southern Adelaide aged care. Gardens and close to beaches.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Estia Health Murray Bridge', 'Estia Health', '15 Adelaide Road', 'Murray Bridge', 'SA', '5253', -35.1183, 139.2750, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '08 8532 4601', 'murraybridge@estiahealth.com.au', 'https://estiahealth.com.au', 'Murraylands aged care. Gardens and close to Murray River.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('ACH Group Edwardstown', 'ACH Group', '125 Shepherds Hill Road', 'Edwardstown', 'SA', '5039', -34.9850, 138.5717, 'aged-care', 'aged-care', 405000, 605000, 440, 640, 30, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 100, 55, '08 8276 4601', 'edwardstown@ach.org.au', 'https://ach.org.au', 'Southern Adelaide aged care. Gardens and modern facilities.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Southern Cross Care Mount Gambier', 'Southern Cross Care SA', '45 Helen Street', 'Mount Gambier', 'SA', '5290', -37.8317, 140.7833, 'aged-care', 'aged-care', 265000, 435000, 310, 500, 34, '["library", "common-room", "garden"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 74, 55, '08 8723 4601', 'mtgambier@scsa.org.au', 'https://scsa.org.au', 'Southeast aged care. Gardens and close to Blue Lake.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Japara Bairnsdale Park', 'Japara Healthcare', '88 Henley Beach Road', 'Henley Beach', 'SA', '5022', -34.9167, 138.4933, 'aged-care', 'aged-care', 485000, 725000, 520, 760, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '08 8353 4601', 'bairnsdale@japara.com.au', 'https://japara.com.au', 'Beachside Adelaide aged care. Gardens, cafe, and beach access.', 'approved', 'seed_data', true, true, NOW(), NOW()),

-- WA (4 villages)
('Regis Aged Care Belmont', 'Regis Aged Care', '125 Great Eastern Highway', 'Belmont', 'WA', '6104', -31.9467, 115.9233, 'aged-care', 'aged-care', 445000, 665000, 480, 700, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 108, 55, '08 9277 5601', 'belmont@regis.com.au', 'https://regis.com.au', 'Eastern Perth aged care. Gardens, cafe, and close to airport.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Bethanie Esprit Joondalup', 'Bethanie Group', '45 Shenton Avenue', 'Joondalup', 'WA', '6027', -31.7450, 115.7650, 'independent', 'independent', 465000, 745000, 480, 740, 28, '["pool", "gym", "library", "common-room", "bbq-area", "garden"]'::jsonb, '["emergency-call", "on-site-manager"]'::jsonb, ARRAY['2-bed', '3-bed'], true, 138, 55, '08 9400 5601', 'joondalup@bethanie.com.au', 'https://bethanie.com.au', 'Northern Perth retirement. Pool, gym, and shopping center nearby.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Amana Living Mandurah', 'Amana Living', '88 Old Coast Road', 'Mandurah', 'WA', '6210', -32.5267, 115.7200, 'aged-care', 'aged-care', 345000, 545000, 380, 580, 30, '["pool", "library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 94, 55, '08 9535 5601', 'mandurah@amana.com.au', 'https://amana.com.au', 'Peel region aged care. Pool, gardens, and waterways lifestyle.', 'approved', 'seed_data', true, false, NOW(), NOW()),
('Opal Aged Care Albany', 'Opal Aged Care', '15 York Street', 'Albany', 'WA', '6330', -35.0267, 117.8833, 'aged-care', 'aged-care', 305000, 505000, 340, 540, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 82, 55, '08 9841 5601', 'albany@opalcare.com.au', 'https://opalcare.com.au', 'Great Southern coastal aged care. Gardens and harbour setting.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- TAS (1 village)
('Estia Health Devonport', 'Estia Health', '125 William Street', 'Devonport', 'TAS', '7310', -41.1800, 146.3617, 'aged-care', 'aged-care', 325000, 525000, 360, 560, 32, '["library", "common-room", "garden", "hairdresser"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 88, 55, '03 6424 8601', 'devonport@estiahealth.com.au', 'https://estiahealth.com.au', 'North Tasmania aged care. Gardens and close to ferry terminal.', 'approved', 'seed_data', true, false, NOW(), NOW()),

-- ACT (1 village)
('Goodwin Aged Care Bruce', 'Goodwin', '45 Telita Street', 'Bruce', 'ACT', '2617', -35.2450, 149.0933, 'aged-care', 'aged-care', 485000, 735000, 520, 780, 28, '["library", "common-room", "garden", "hairdresser", "cafe"]'::jsonb, '["emergency-call", "on-site-manager", "visiting-nurse", "meals", "housekeeping", "personal-care", "24hr-care"]'::jsonb, ARRAY['1-bed', '2-bed'], false, 106, 55, '02 6253 7601', 'bruce@goodwin.org.au', 'https://goodwin.org.au', 'North Canberra aged care. Gardens, cafe, and close to AIS.', 'approved', 'seed_data', true, false, NOW(), NOW());